{
 "title": "logging: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8245226639 at Fri Nov  1 04:32:10 UTC 2024",
 "tags": [
  "managed",
  "logging",
  "gitlab",
  "type:logging",
  "logging",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "logging Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "logging error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"logging\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"logging\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "logging error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"logging\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"logging\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"logging\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"logging\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"logging\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "logging Service | Errors"
    }
   ]
  },
  {
   "title": "logging Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n",
     "legendFormat": "logging RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"logging\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "elasticsearch_indexing_cluster SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"elasticsearch_indexing_cluster\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n",
     "legendFormat": "elasticsearch_indexing_cluster RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"elasticsearch_indexing_cluster\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "content": "### Description\n\nThis cluster SLI monitors log index operations to GitLab's logging ELK instance.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Monitoring Cluster logs](https://00a4ef3362214c44a044feaa539b4686.us-central1.gcp.cloud.es.io:9243/app/kibana#/discover?_a=(columns:!(log.level,message,elasticsearch.component),filters:!((meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:json.type,params:logging,type:phrase),query:(match:(json.type:(query:logging,type:phrase))))),index:'3fdde960-1f73-11eb-9ead-c594f004ece2')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Monitoring Cluster failed request logs](https://00a4ef3362214c44a044feaa539b4686.us-central1.gcp.cloud.es.io:9243/app/kibana#/discover?_a=(columns:!(log.level,message,elasticsearch.component),filters:!((meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:json.type,params:logging,type:phrase),query:(match:(json.type:(query:logging,type:phrase)))),(meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:log.level,params:!(CRITICAL,ERROR),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(log.level:CRITICAL)),(match_phrase:(log.level:ERROR))))))),index:'3fdde960-1f73-11eb-9ead-c594f004ece2')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Monitoring Cluster requests](https://00a4ef3362214c44a044feaa539b4686.us-central1.gcp.cloud.es.io:9243/app/kibana#/visualize/create?type=line&indexPattern=3fdde960-1f73-11eb-9ead-c594f004ece2&_a=(filters:!((meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:json.type,params:logging,type:phrase),query:(match:(json.type:(query:logging,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Monitoring Cluster failed requests](https://00a4ef3362214c44a044feaa539b4686.us-central1.gcp.cloud.es.io:9243/app/kibana#/visualize/create?type=line&indexPattern=3fdde960-1f73-11eb-9ead-c594f004ece2&_a=(filters:!((meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:json.type,params:logging,type:phrase),query:(match:(json.type:(query:logging,type:phrase)))),(meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:log.level,params:!(CRITICAL,ERROR),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(log.level:CRITICAL)),(match_phrase:(log.level:ERROR))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "elasticsearch_indexing_index SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"elasticsearch_indexing_index\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n",
     "legendFormat": "elasticsearch_indexing_index RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"elasticsearch_indexing_index\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "content": "### Description\n\nThis index SLI monitors log index operations to GitLab's logging ELK instance.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Monitoring Cluster logs](https://00a4ef3362214c44a044feaa539b4686.us-central1.gcp.cloud.es.io:9243/app/kibana#/discover?_a=(columns:!(log.level,message,elasticsearch.component),filters:!((meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:json.type,params:logging,type:phrase),query:(match:(json.type:(query:logging,type:phrase))))),index:'3fdde960-1f73-11eb-9ead-c594f004ece2')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Monitoring Cluster failed request logs](https://00a4ef3362214c44a044feaa539b4686.us-central1.gcp.cloud.es.io:9243/app/kibana#/discover?_a=(columns:!(log.level,message,elasticsearch.component),filters:!((meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:json.type,params:logging,type:phrase),query:(match:(json.type:(query:logging,type:phrase)))),(meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:log.level,params:!(CRITICAL,ERROR),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(log.level:CRITICAL)),(match_phrase:(log.level:ERROR))))))),index:'3fdde960-1f73-11eb-9ead-c594f004ece2')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Monitoring Cluster requests](https://00a4ef3362214c44a044feaa539b4686.us-central1.gcp.cloud.es.io:9243/app/kibana#/visualize/create?type=line&indexPattern=3fdde960-1f73-11eb-9ead-c594f004ece2&_a=(filters:!((meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:json.type,params:logging,type:phrase),query:(match:(json.type:(query:logging,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Monitoring Cluster failed requests](https://00a4ef3362214c44a044feaa539b4686.us-central1.gcp.cloud.es.io:9243/app/kibana#/visualize/create?type=line&indexPattern=3fdde960-1f73-11eb-9ead-c594f004ece2&_a=(filters:!((meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:json.type,params:logging,type:phrase),query:(match:(json.type:(query:logging,type:phrase)))),(meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:log.level,params:!(CRITICAL,ERROR),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(log.level:CRITICAL)),(match_phrase:(log.level:ERROR))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "elasticsearch_searching_cluster SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"elasticsearch_searching_cluster\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n",
     "legendFormat": "elasticsearch_searching_cluster RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"elasticsearch_searching_cluster\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "content": "### Description\n\nThis cluster SLI monitors searches issued to GitLab's logging ELK instance.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Monitoring Cluster logs](https://00a4ef3362214c44a044feaa539b4686.us-central1.gcp.cloud.es.io:9243/app/kibana#/discover?_a=(columns:!(log.level,message,elasticsearch.component),filters:!((meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:json.type,params:logging,type:phrase),query:(match:(json.type:(query:logging,type:phrase))))),index:'3fdde960-1f73-11eb-9ead-c594f004ece2')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Monitoring Cluster failed request logs](https://00a4ef3362214c44a044feaa539b4686.us-central1.gcp.cloud.es.io:9243/app/kibana#/discover?_a=(columns:!(log.level,message,elasticsearch.component),filters:!((meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:json.type,params:logging,type:phrase),query:(match:(json.type:(query:logging,type:phrase)))),(meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:log.level,params:!(CRITICAL,ERROR),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(log.level:CRITICAL)),(match_phrase:(log.level:ERROR))))))),index:'3fdde960-1f73-11eb-9ead-c594f004ece2')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Monitoring Cluster requests](https://00a4ef3362214c44a044feaa539b4686.us-central1.gcp.cloud.es.io:9243/app/kibana#/visualize/create?type=line&indexPattern=3fdde960-1f73-11eb-9ead-c594f004ece2&_a=(filters:!((meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:json.type,params:logging,type:phrase),query:(match:(json.type:(query:logging,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Monitoring Cluster failed requests](https://00a4ef3362214c44a044feaa539b4686.us-central1.gcp.cloud.es.io:9243/app/kibana#/visualize/create?type=line&indexPattern=3fdde960-1f73-11eb-9ead-c594f004ece2&_a=(filters:!((meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:json.type,params:logging,type:phrase),query:(match:(json.type:(query:logging,type:phrase)))),(meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:log.level,params:!(CRITICAL,ERROR),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(log.level:CRITICAL)),(match_phrase:(log.level:ERROR))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "elasticsearch_searching_index SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"elasticsearch_searching_index\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n",
     "legendFormat": "elasticsearch_searching_index RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"elasticsearch_searching_index\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "content": "### Description\n\nThis index SLI monitors searches issued to GitLab's logging ELK instance.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Monitoring Cluster logs](https://00a4ef3362214c44a044feaa539b4686.us-central1.gcp.cloud.es.io:9243/app/kibana#/discover?_a=(columns:!(log.level,message,elasticsearch.component),filters:!((meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:json.type,params:logging,type:phrase),query:(match:(json.type:(query:logging,type:phrase))))),index:'3fdde960-1f73-11eb-9ead-c594f004ece2')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Monitoring Cluster failed request logs](https://00a4ef3362214c44a044feaa539b4686.us-central1.gcp.cloud.es.io:9243/app/kibana#/discover?_a=(columns:!(log.level,message,elasticsearch.component),filters:!((meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:json.type,params:logging,type:phrase),query:(match:(json.type:(query:logging,type:phrase)))),(meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:log.level,params:!(CRITICAL,ERROR),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(log.level:CRITICAL)),(match_phrase:(log.level:ERROR))))))),index:'3fdde960-1f73-11eb-9ead-c594f004ece2')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Monitoring Cluster requests](https://00a4ef3362214c44a044feaa539b4686.us-central1.gcp.cloud.es.io:9243/app/kibana#/visualize/create?type=line&indexPattern=3fdde960-1f73-11eb-9ead-c594f004ece2&_a=(filters:!((meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:json.type,params:logging,type:phrase),query:(match:(json.type:(query:logging,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Monitoring Cluster failed requests](https://00a4ef3362214c44a044feaa539b4686.us-central1.gcp.cloud.es.io:9243/app/kibana#/visualize/create?type=line&indexPattern=3fdde960-1f73-11eb-9ead-c594f004ece2&_a=(filters:!((meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:json.type,params:logging,type:phrase),query:(match:(json.type:(query:logging,type:phrase)))),(meta:(index:'3fdde960-1f73-11eb-9ead-c594f004ece2',key:log.level,params:!(CRITICAL,ERROR),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(log.level:CRITICAL)),(match_phrase:(log.level:ERROR))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "fluentd_log_output SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"fluentd_log_output\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "fluentd_log_output error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"fluentd_log_output\",monitor=\"global\",type=\"logging\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"fluentd_log_output\",monitor=\"global\",type=\"logging\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"fluentd_log_output\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "fluentd_log_output error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"fluentd_log_output\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"fluentd_log_output\",monitor=\"global\",type=\"logging\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"fluentd_log_output\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"fluentd_log_output\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"fluentd_log_output\",monitor=\"global\",type=\"logging\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"fluentd_log_output\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"fluentd_log_output\",monitor=\"global\",type=\"logging\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"fluentd_log_output\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"fluentd_log_output\",monitor=\"global\",type=\"logging\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"fluentd_log_output\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"fluentd_log_output\",monitor=\"global\",type=\"logging\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "fluentd_log_output SLI | Errors"
    }
   ]
  },
  {
   "title": "fluentd_log_output SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"fluentd_log_output\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n",
     "legendFormat": "fluentd_log_output RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"fluentd_log_output\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "content": "### Description\n\nThis SLI monitors fluentd log output and the number of output errors in fluentd.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Fluentd logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.message,json.type),filters:!((meta:(index:'6f3fe550-4317-11ec-8c8e-ed83b5469915',key:type,params:fluentd,type:phrase),query:(match:(type:(query:fluentd,type:phrase))))),index:'6f3fe550-4317-11ec-8c8e-ed83b5469915')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "kibana_googlelb SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"kibana_googlelb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "kibana_googlelb error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"kibana_googlelb\",monitor=\"global\",type=\"logging\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"kibana_googlelb\",monitor=\"global\",type=\"logging\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"kibana_googlelb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "kibana_googlelb error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"kibana_googlelb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"kibana_googlelb\",monitor=\"global\",type=\"logging\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"kibana_googlelb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"kibana_googlelb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"kibana_googlelb\",monitor=\"global\",type=\"logging\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"kibana_googlelb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"kibana_googlelb\",monitor=\"global\",type=\"logging\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"kibana_googlelb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"kibana_googlelb\",monitor=\"global\",type=\"logging\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"kibana_googlelb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"kibana_googlelb\",monitor=\"global\",type=\"logging\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "kibana_googlelb SLI | Errors"
    }
   ]
  },
  {
   "title": "kibana_googlelb SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"kibana_googlelb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n",
     "legendFormat": "kibana_googlelb RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"kibana_googlelb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
   "content": "### Observability Tools\n\n* [Google Load Balancer](https://console.cloud.google.com/net-services/loadbalancing/details/http/ops-prod-proxy?project=gitlab-ops)\n* [Stackdriver Logs: Loadbalancer Access Logs](https://console.cloud.google.com/logs/query;query=resource%2Elabels%2Eurl%5Fmap%5Fname%3D%22ops%2Dprod%2Dproxy%22%0Aresource%2Etype%3D%22http%5Fload%5Fbalancer%22;timeRange=PT30M?project=gitlab-ops)\n* [Stackdriver Logs: Loadbalancer Access 5xx Logs](https://console.cloud.google.com/logs/query;query=httpRequest%2Estatus%3E%3D500%0Aresource%2Elabels%2Eurl%5Fmap%5Fname%3D%22ops%2Dprod%2Dproxy%22%0Aresource%2Etype%3D%22http%5Fload%5Fbalancer%22;timeRange=PT30M?project=gitlab-ops)\n\n"
  },
  {
   "title": "pubsub_subscriptions SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"pubsub_subscriptions\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n",
     "legendFormat": "pubsub_subscriptions RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"pubsub_subscriptions\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "content": "### Description\n\nThis SLI monitors pubsub subscriptions.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Pubsubbeat logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(kubernetes.host,json.message),filters:!((meta:(index:'c1ee6e20-fbf1-11ea-af41-ad80f197fa45',key:json.type,params:pubsubbeat,type:phrase),query:(match:(json.type:(query:pubsubbeat,type:phrase))))),index:'c1ee6e20-fbf1-11ea-af41-ad80f197fa45')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Pubsubbeat requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=c1ee6e20-fbf1-11ea-af41-ad80f197fa45&_a=(filters:!((meta:(index:'c1ee6e20-fbf1-11ea-af41-ad80f197fa45',key:json.type,params:pubsubbeat,type:phrase),query:(match:(json.type:(query:pubsubbeat,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "pubsub_topics SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"pubsub_topics\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n",
     "legendFormat": "pubsub_topics RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"pubsub_topics\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "content": "### Description\n\nThis SLI monitors pubsub topics.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Pubsubbeat logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(kubernetes.host,json.message),filters:!((meta:(index:'c1ee6e20-fbf1-11ea-af41-ad80f197fa45',key:json.type,params:pubsubbeat,type:phrase),query:(match:(json.type:(query:pubsubbeat,type:phrase))))),index:'c1ee6e20-fbf1-11ea-af41-ad80f197fa45')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Pubsubbeat requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=c1ee6e20-fbf1-11ea-af41-ad80f197fa45&_a=(filters:!((meta:(index:'c1ee6e20-fbf1-11ea-af41-ad80f197fa45',key:json.type,params:pubsubbeat,type:phrase),query:(match:(json.type:(query:pubsubbeat,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "pubsubbeat SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "pubsubbeat error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"pubsubbeat\",monitor=\"global\",type=\"logging\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"pubsubbeat\",monitor=\"global\",type=\"logging\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "pubsubbeat error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"pubsubbeat\",monitor=\"global\",type=\"logging\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"pubsubbeat\",monitor=\"global\",type=\"logging\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"pubsubbeat\",monitor=\"global\",type=\"logging\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"pubsubbeat\",monitor=\"global\",type=\"logging\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"pubsubbeat\",monitor=\"global\",type=\"logging\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "pubsubbeat SLI | Errors"
    }
   ]
  },
  {
   "title": "pubsubbeat SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n",
     "legendFormat": "pubsubbeat RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 101 },
   "content": "### Description\n\nThis SLI monitors pubsubbeat errors.\n\n"
  },
  {
   "title": "stackdriver SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"stackdriver\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"}[$__interval])\n",
     "legendFormat": "stackdriver RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"stackdriver\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"logging\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "content": "### Description\n\nThis SLI monitors the total number of logs sent to GCP StackDriver logging.\n\n"
  },
  {
   "title": "🔬 SLI Detail: elasticsearch_indexing_cluster",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "elasticsearch_indexing_cluster RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  clamp_min(deriv(elasticsearch_indices_indexing_index_total{env=\"$environment\",environment=\"$environment\",type=\"logging\"}[$__interval]), 0)\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "elasticsearch_indexing_cluster RPS - per name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (\n  clamp_min(deriv(elasticsearch_indices_indexing_index_total{env=\"$environment\",environment=\"$environment\",name!=\"\",type=\"logging\"}[$__interval]), 0)\n)\n > 0",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: elasticsearch_indexing_index",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "elasticsearch_indexing_index RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  clamp_min(deriv(elasticsearch_index_stats_indexing_index_total{env=\"$environment\",environment=\"$environment\",type=\"logging\"}[$__interval]), 0)\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "elasticsearch_indexing_index RPS - per index",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (index) (\n  clamp_min(deriv(elasticsearch_index_stats_indexing_index_total{env=\"$environment\",environment=\"$environment\",index!=\"\",type=\"logging\"}[$__interval]), 0)\n)\n > 0",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: elasticsearch_searching_cluster",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 220 },
   "collapsed": true,
   "panels": [
    {
     "title": "elasticsearch_searching_cluster RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  clamp_min(deriv(elasticsearch_indices_search_query_total{env=\"$environment\",environment=\"$environment\",type=\"logging\"}[$__interval]), 0)\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "elasticsearch_searching_cluster RPS - per name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (\n  clamp_min(deriv(elasticsearch_indices_search_query_total{env=\"$environment\",environment=\"$environment\",name!=\"\",type=\"logging\"}[$__interval]), 0)\n)\n > 0",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: elasticsearch_searching_index",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 230 },
   "collapsed": true,
   "panels": [
    {
     "title": "elasticsearch_searching_index RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  clamp_min(deriv(elasticsearch_index_stats_search_query_total{env=\"$environment\",environment=\"$environment\",type=\"logging\"}[$__interval]), 0)\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "elasticsearch_searching_index RPS - per index",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (index) (\n  clamp_min(deriv(elasticsearch_index_stats_search_query_total{env=\"$environment\",environment=\"$environment\",index!=\"\",type=\"logging\"}[$__interval]), 0)\n)\n > 0",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: fluentd_log_output",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 240 },
   "collapsed": true,
   "panels": [
    {
     "title": "fluentd_log_output Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:fluentd_output_status_num_errors:rate_5m{env=\"$environment\",environment=\"$environment\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "fluentd_log_output RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:fluentd_output_status_write_count:rate_5m{env=\"$environment\",environment=\"$environment\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "fluentd_log_output Errors - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  sli_aggregations:fluentd_output_status_num_errors:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\"}\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "fluentd_log_output RPS - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  sli_aggregations:fluentd_output_status_write_count:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\"}\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "fluentd_log_output Errors - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:fluentd_output_status_num_errors:rate_5m{env=\"$environment\",environment=\"$environment\",pod!=\"\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "fluentd_log_output RPS - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:fluentd_output_status_write_count:rate_5m{env=\"$environment\",environment=\"$environment\",pod!=\"\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "fluentd_log_output Errors - per type",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (\n  sli_aggregations:fluentd_output_status_num_errors:rate_5m{env=\"$environment\",environment=\"$environment\",type!=\"\"}\n)\n > 0",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "fluentd_log_output RPS - per type",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (\n  sli_aggregations:fluentd_output_status_write_count:rate_5m{env=\"$environment\",environment=\"$environment\",type!=\"\"}\n)\n > 0",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: kibana_googlelb",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 250 },
   "collapsed": true,
   "panels": [
    {
     "title": "kibana_googlelb Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-ops\",response_code_class=\"500\",url_map_name=\"ops-prod-proxy\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "kibana_googlelb RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-ops\",url_map_name=\"ops-prod-proxy\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "kibana_googlelb Errors - per proxy_continent",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy_continent) (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-ops\",proxy_continent!=\"\",response_code_class=\"500\",url_map_name=\"ops-prod-proxy\"}\n)\n > 0",
       "legendFormat": "{{proxy_continent}}"
      }
     ]
    },
    {
     "title": "kibana_googlelb RPS - per proxy_continent",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy_continent) (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-ops\",proxy_continent!=\"\",url_map_name=\"ops-prod-proxy\"}\n)\n > 0",
       "legendFormat": "{{proxy_continent}}"
      }
     ]
    },
    {
     "title": "kibana_googlelb Errors - per response_code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (response_code) (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-ops\",response_code!=\"\",response_code_class=\"500\",url_map_name=\"ops-prod-proxy\"}\n)\n > 0",
       "legendFormat": "{{response_code}}"
      }
     ]
    },
    {
     "title": "kibana_googlelb RPS - per response_code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (response_code) (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-ops\",response_code!=\"\",url_map_name=\"ops-prod-proxy\"}\n)\n > 0",
       "legendFormat": "{{response_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: pubsub_subscriptions",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 260 },
   "collapsed": true,
   "panels": [
    {
     "title": "pubsub_subscriptions RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:stackdriver_pubsub_subscription_pubsub_googleapis_com_subscription_byte_cost:rate_5m{env=\"$environment\",environment=\"$environment\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "pubsub_subscriptions RPS - per subscription_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (subscription_id) (\n  sli_aggregations:stackdriver_pubsub_subscription_pubsub_googleapis_com_subscription_byte_cost:rate_5m{env=\"$environment\",environment=\"$environment\",subscription_id!=\"\"}\n)\n > 0",
       "legendFormat": "{{subscription_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: pubsub_topics",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 270 },
   "collapsed": true,
   "panels": [
    {
     "title": "pubsub_topics RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:stackdriver_pubsub_topic_pubsub_googleapis_com_topic_byte_cost:rate_5m{env=\"$environment\",environment=\"$environment\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "pubsub_topics RPS - per topic_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (topic_id) (\n  sli_aggregations:stackdriver_pubsub_topic_pubsub_googleapis_com_topic_byte_cost:rate_5m{env=\"$environment\",environment=\"$environment\",topic_id!=\"\"}\n)\n > 0",
       "legendFormat": "{{topic_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: pubsubbeat",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 280 },
   "collapsed": true,
   "panels": [
    {
     "title": "pubsubbeat Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:pubsubbeat_errors_total:rate_5m{env=\"$environment\",environment=\"$environment\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "pubsubbeat RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:pubsubbeat_libbeat_output_events:rate_5m{env=\"$environment\",environment=\"$environment\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "pubsubbeat Errors - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:pubsubbeat_errors_total:rate_5m{env=\"$environment\",environment=\"$environment\",pod!=\"\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "pubsubbeat RPS - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:pubsubbeat_libbeat_output_events:rate_5m{env=\"$environment\",environment=\"$environment\",pod!=\"\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: stackdriver",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 290 },
   "collapsed": true,
   "panels": [
    {
     "title": "stackdriver RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:stackdriver_gce_instance_logging_googleapis_com_log_entry_count:rate_5m{env=\"$environment\",environment=\"$environment\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "stackdriver RPS - per log",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (log) (\n  sli_aggregations:stackdriver_gce_instance_logging_googleapis_com_log_entry_count:rate_5m{env=\"$environment\",environment=\"$environment\",log!=\"\"}\n)\n > 0",
       "legendFormat": "{{log}}"
      }
     ]
    },
    {
     "title": "stackdriver RPS - per severity",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (severity) (\n  sli_aggregations:stackdriver_gce_instance_logging_googleapis_com_log_entry_count:rate_5m{env=\"$environment\",environment=\"$environment\",severity!=\"\"}\n)\n > 0",
       "legendFormat": "{{severity}}"
      }
     ]
    }
   ]
  },
  {
   "title": "☸️ Kubernetes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 },
   "collapsed": true,
   "panels": [
    {
     "title": "fluentd-archiver Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "fluentd-archiver Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "fluentd-archiver Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "fluentd-elasticsearch Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "fluentd-elasticsearch Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "fluentd-elasticsearch Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "pubsubbeat Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "pubsubbeat Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "pubsubbeat Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "elastic_cpu component saturation: Average CPU Utilization per Node",
     "type": "graph",
     "description": "Average CPU utilization per Node.\n\nThis resource measures all CPU across a fleet. If it is becoming saturated, it may indicate that the fleet needs horizontal or\nvertical scaling. The metrics are coming from elasticsearch_exporter.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      avg by (environment, tier, type, stage, shard) (\n        avg_over_time(elasticsearch_process_cpu_percent{env=\"$environment\",environment=\"$environment\",type=\"logging\"}[1m]) / 100\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"elastic_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"elastic_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "elastic_disk_space component saturation: Disk Utilization Overall",
     "type": "graph",
     "description": "Disk utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, host) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard, host) (\n        (elasticsearch_filesystem_data_size_bytes{env=\"$environment\",environment=\"$environment\",type=\"logging\"} - elasticsearch_filesystem_data_free_bytes{env=\"$environment\",environment=\"$environment\",type=\"logging\"})\n      )\n      /\n      sum by (environment, tier, type, stage, shard, host) (\n        elasticsearch_filesystem_data_size_bytes{env=\"$environment\",environment=\"$environment\",type=\"logging\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ host }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_disk_space\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_disk_space\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_disk_space\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"elastic_disk_space\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"elastic_disk_space\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "elastic_jvm_heap_memory component saturation: JVM Heap Utilization per Node",
     "type": "graph",
     "description": "JVM heap memory utilization per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, name) (\n  clamp_min(\n    clamp_max(\n      elasticsearch_jvm_memory_used_bytes{area=\"heap\", env=\"$environment\",environment=\"$environment\",type=\"logging\"}\n      /\n      elasticsearch_jvm_memory_max_bytes{area=\"heap\", env=\"$environment\",environment=\"$environment\",type=\"logging\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_jvm_heap_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_jvm_heap_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_jvm_heap_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"elastic_jvm_heap_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"elastic_jvm_heap_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "elastic_single_node_cpu component saturation: Average CPU Utilization per Node",
     "type": "graph",
     "description": "Average CPU per Node.\n\nThis resource measures all CPU across a fleet. If it is becoming saturated, it may indicate that the fleet needs horizontal or\nvertical scaling. The metrics are coming from elasticsearch_exporter.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, name) (\n  clamp_min(\n    clamp_max(\n      avg_over_time(elasticsearch_process_cpu_percent{env=\"$environment\",environment=\"$environment\",type=\"logging\"}[5m]) / 100\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_single_node_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_single_node_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_single_node_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"elastic_single_node_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"elastic_single_node_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "elastic_single_node_disk_space component saturation: Disk Utilization per Device per Node",
     "type": "graph",
     "description": "Disk utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, name) (\n  clamp_min(\n    clamp_max(\n      (\n        (\n          elasticsearch_filesystem_data_size_bytes{env=\"$environment\",environment=\"$environment\",type=\"logging\"}\n          -\n          elasticsearch_filesystem_data_free_bytes{env=\"$environment\",environment=\"$environment\",type=\"logging\"}\n        )\n        /\n        elasticsearch_filesystem_data_size_bytes{env=\"$environment\",environment=\"$environment\",type=\"logging\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_single_node_disk_space\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_single_node_disk_space\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_single_node_disk_space\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"elastic_single_node_disk_space\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"elastic_single_node_disk_space\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "elastic_thread_pools component saturation: Thread pool utilization",
     "type": "graph",
     "description": "Utilization of each thread pool on each node.\n\nDescriptions of the threadpool types can be found at\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, name, exported_type) (\n  clamp_min(\n    clamp_max(\n      (\n        avg_over_time(elasticsearch_thread_pool_active_count{exported_type!=\"snapshot\", env=\"$environment\",environment=\"$environment\",type=\"logging\"}[5m])\n        /\n        (avg_over_time(elasticsearch_thread_pool_threads_count{exported_type!=\"snapshot\", env=\"$environment\",environment=\"$environment\",type=\"logging\"}[5m]) > 0)\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ name }} {{ exported_type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_thread_pools\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_thread_pools\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"elastic_thread_pools\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"elastic_thread_pools\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"elastic_thread_pools\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_cpu component saturation: Kube Container CPU Utilization",
     "type": "graph",
     "description": "Kubernetes containers are allocated a share of CPU. Configured using resource requests.\n\nThis is the amount of CPU that a container should always have available,\nthough it can briefly utilize more. However, if a lot of pods on the same\nhost exceed their requested CPU the container could be throttled earlier.\n\nThis monitors utilization/allocated requests over a 1 hour period, and takes\nthe 99th quantile of that utilization percentage in that period.\nWe want the worst case to be around 80%-90% utilization,\nmeaning we've sized the container correctly. If utilization is much higher than that\nthe container could already be throttled because the host is overused, if it\nis much lower, then we could be underutilizing a host.\n\nThis saturation point is only used for capacity planning.\nContainers that have a quota specified are excluded here and can be monitored using\nthe `kube_container_throttling` saturation component.\nThe burst utilization of a CPU is monitored and alerted upon using the\n`kube_container_cpu_limit` saturation point.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, pod, container) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      (\n        sum by (environment, tier, type, stage, shard, pod, container) (\n          rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"logging\"}[1h])\n        )\n        unless on(environment, tier, type, stage, shard, pod, container) (\n          last_over_time(container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"logging\"}[1h])\n        )\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        kube_pod_container_resource_requests:labeled{container!=\"\", container!=\"POD\", resource=\"cpu\", env=\"$environment\",environment=\"$environment\",type=\"logging\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"kube_container_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_cpu_limit component saturation: Kube Container CPU over-utilization",
     "type": "graph",
     "description": "Kubernetes containers can have a limit configured on how much CPU they can consume in\na burst. If we are at this limit, exceeding the allocated requested resources, we\nshould consider revisting the container's HPA configuration.\n\nWhen a container is utilizing CPU resources up-to it's configured limit for\nextended periods of time, this could cause it and other running containers to be\nthrottled.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, pod, container) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard, pod, container) (\n        rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"logging\"}[5m])\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"logging\"}\n        /\n        container_spec_cpu_period:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"logging\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"kube_container_cpu_limit\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_memory component saturation: Kube Container Memory Utilization",
     "type": "graph",
     "description": "This uses the working set size from cAdvisor for the cgroup's memory usage. That may\nnot be a good measure as it includes filesystem cache pages that are not necessarily\nattributable to the application inside the cgroup, and are permitted to be evicted\ninstead of being OOM killed.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, deployment) (\n  clamp_min(\n    clamp_max(\n      container_memory_working_set_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"logging\"}\n      /\n      (container_spec_memory_limit_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"logging\"} > 0)\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ deployment }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"kube_container_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"kube_container_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"kube_container_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_throttling component saturation: Kube container throttling",
     "type": "graph",
     "description": "Kube container throttling\n\nA container will be throttled if it reaches the configured cpu limit for the\nhorizontal pod autoscaler. Or when other containers on the node are overutilizing\nthe the CPU.\n\nTo get around this, consider increasing the limit for this workload, taking\ninto consideration the requested resources.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, pod, container) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      avg by (environment, tier, type, stage, shard, pod, container)(\n        rate(container_cpu_cfs_throttled_periods_total:labeled{container!=\"\", env=\"$environment\",environment=\"$environment\",type=\"logging\"}[5m])\n        /\n        rate(container_cpu_cfs_periods_total:labeled{container!=\"\", env=\"$environment\",environment=\"$environment\",type=\"logging\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"kube_container_throttling\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"kube_container_throttling\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"kube_container_throttling\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_throttling\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_throttling\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_horizontalpodautoscaler_desired_replicas component saturation: Horizontal Pod Autoscaler Desired Replicas",
     "type": "graph",
     "description": "The [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)\nautomatically scales the number of Pods in a deployment based on metrics.\n\nThe Horizontal Pod Autoscaler has a configured upper maximum. When this\nlimit is reached, the HPA will not increase the number of pods and other\nresource saturation (eg, CPU, memory) may occur.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, horizontalpodautoscaler, shard) (\n  clamp_min(\n    clamp_max(\n      kube_horizontalpodautoscaler_status_desired_replicas:labeled{env=\"$environment\",environment=\"$environment\",type=\"logging\", shard!~\"ai-abstraction-layer|database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects\", namespace!~\"pubsubbeat\"}\n      /\n      kube_horizontalpodautoscaler_spec_max_replicas:labeled{env=\"$environment\",environment=\"$environment\",type=\"logging\", shard!~\"ai-abstraction-layer|database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects\", namespace!~\"pubsubbeat\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ horizontalpodautoscaler }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",type=\"logging\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"logging\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",type=\"logging\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"logging\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"logging\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph inf\n  logging\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph inf\n  logging\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph inf\n  logging[\"logging (Level 1)\"]\nend\n\n\n  \n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  },
  {
   "title": "PubSub Subscriptions Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 },
   "collapsed": true,
   "panels": [
    {
     "title": "PubSub subscriptions Undelivered Messages",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1000 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(stackdriver_pubsub_subscription_pubsub_googleapis_com_subscription_num_undelivered_messages{environment=\"$environment\"}[$__interval])) by (subscription_id)\n",
       "legendFormat": "{{ subscription_id }}"
      }
     ]
    },
    {
     "title": "PubSub subscriptions Oldest Unacked Messages",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1000 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(stackdriver_pubsub_subscription_pubsub_googleapis_com_subscription_oldest_unacked_message_age{environment=\"$environment\"}[$__interval])) by (subscription_id)\n",
       "legendFormat": "{{ subscription_id }}"
      }
     ]
    },
    {
     "title": "PubSub subscriptions Oldest Retained Acked Messages",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1000 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(stackdriver_pubsub_subscription_pubsub_googleapis_com_subscription_oldest_retained_acked_message_age{environment=\"$environment\"}[$__interval])) by (subscription_id)\n",
       "legendFormat": "{{ subscription_id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "👀 fluentd process activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 },
   "collapsed": true,
   "panels": [
    {
     "title": "fluentd processes: CPU Time",
     "type": "graph",
     "description": "Seconds of CPU time for the named process group, per second. Note that this metric is sampled periodically, and thus will greatly under-sample short-lived processes.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  rate(\n    namedprocess_namegroup_cpu_seconds_total{env=\"$environment\",groupname=\"fluentd\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "fluentd processes: Open File Descriptors",
     "type": "graph",
     "description": "Maximum number of open file descriptors per host",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by(fqdn) (\n    namedprocess_namegroup_open_filedesc{env=\"$environment\",groupname=\"fluentd\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "fluentd processes: Number of Processes",
     "type": "graph",
     "description": "Number of processes in the process group",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  avg_over_time(namedprocess_namegroup_num_procs{env=\"$environment\",groupname=\"fluentd\"}[$__interval])\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "fluentd processes: Number of Threads",
     "type": "graph",
     "description": "Number of threads in the process group",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  namedprocess_namegroup_num_threads{env=\"$environment\",groupname=\"fluentd\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "fluentd processes: RSS Memory Usage",
     "type": "graph",
     "description": "Resident Memory usage for named process group",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  namedprocess_namegroup_memory_bytes{memtype=\"resident\", env=\"$environment\",groupname=\"fluentd\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    }
   ]
  }
 ]
}