{
 "title": "logging: Kube Containers Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8245226639 at Fri Nov  1 04:32:10 UTC 2024",
 "tags": [
  "managed",
  "logging",
  "logging",
  "type:logging",
  "kube",
  "kube detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   }
  ]
 },
 "panels": [
  { "title": "fluentd-archiver deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "fluentd container/fluentd-archiver deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"fluentd\",deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 fluentd Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"fluentd\",deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 fluentd Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"fluentd\",deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 fluentd Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"fluentd\",deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 fluentd Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"fluentd\",deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 fluentd Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"fluentd\",deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 fluentd Container CPU"
    }
   ]
  },
  {
   "title": "fluentd container/fluentd-archiver deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"fluentd\",deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p99 fluentd Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"fluentd\",deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p95 fluentd Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"fluentd\",deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p75 fluentd Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"fluentd\",deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p50 fluentd Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"fluentd\",deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p25 fluentd Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"fluentd\",deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p10 fluentd Container Memory"
    }
   ]
  },
  {
   "title": "fluentd container/fluentd-archiver deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"fluentd\",deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "fluentd container/fluentd-archiver deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"fluentd\",deployment=\"fluentd-archiver\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "fluentd-elasticsearch deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "fluentd-elasticsearch container/fluentd-elasticsearch deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"fluentd-elasticsearch\",deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 fluentd-elasticsearch Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"fluentd-elasticsearch\",deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 fluentd-elasticsearch Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"fluentd-elasticsearch\",deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 fluentd-elasticsearch Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"fluentd-elasticsearch\",deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 fluentd-elasticsearch Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"fluentd-elasticsearch\",deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 fluentd-elasticsearch Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"fluentd-elasticsearch\",deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 fluentd-elasticsearch Container CPU"
    }
   ]
  },
  {
   "title": "fluentd-elasticsearch container/fluentd-elasticsearch deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"fluentd-elasticsearch\",deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p99 fluentd-elasticsearch Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"fluentd-elasticsearch\",deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p95 fluentd-elasticsearch Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"fluentd-elasticsearch\",deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p75 fluentd-elasticsearch Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"fluentd-elasticsearch\",deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p50 fluentd-elasticsearch Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"fluentd-elasticsearch\",deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p25 fluentd-elasticsearch Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"fluentd-elasticsearch\",deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p10 fluentd-elasticsearch Container Memory"
    }
   ]
  },
  {
   "title": "fluentd-elasticsearch container/fluentd-elasticsearch deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"fluentd-elasticsearch\",deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "fluentd-elasticsearch container/fluentd-elasticsearch deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"fluentd-elasticsearch\",deployment=\"fluentd-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "pubsubbeat deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "pubsubbeat container/pubsubbeat deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"pubsubbeat\",deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 pubsubbeat Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"pubsubbeat\",deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 pubsubbeat Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"pubsubbeat\",deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 pubsubbeat Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"pubsubbeat\",deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 pubsubbeat Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"pubsubbeat\",deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 pubsubbeat Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"pubsubbeat\",deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 pubsubbeat Container CPU"
    }
   ]
  },
  {
   "title": "pubsubbeat container/pubsubbeat deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"pubsubbeat\",deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p99 pubsubbeat Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"pubsubbeat\",deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p95 pubsubbeat Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"pubsubbeat\",deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p75 pubsubbeat Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"pubsubbeat\",deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p50 pubsubbeat Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"pubsubbeat\",deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p25 pubsubbeat Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"pubsubbeat\",deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n }\n)\n",
     "legendFormat": "p10 pubsubbeat Container Memory"
    }
   ]
  },
  {
   "title": "pubsubbeat container/pubsubbeat deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"pubsubbeat\",deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "pubsubbeat container/pubsubbeat deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"pubsubbeat\",deployment=\"pubsubbeat\",env=\"$environment\",environment=\"$environment\",type=\"logging\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}