{
 "title": "patroni-registry: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8245226639 at Fri Nov  1 04:32:20 UTC 2024",
 "tags": [
  "managed",
  "patroni-registry",
  "gitlab",
  "type:patroni-registry",
  "patroni-registry",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "patroni-registry Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "patroni-registry error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"patroni-registry\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"patroni-registry\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "patroni-registry error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"patroni-registry\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"patroni-registry\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"patroni-registry\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"patroni-registry\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"patroni-registry\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "patroni-registry Service | Errors"
    }
   ]
  },
  {
   "title": "patroni-registry Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}[$__interval])\n",
     "legendFormat": "patroni-registry RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "pgbouncer SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"pgbouncer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "pgbouncer error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"pgbouncer\",monitor=\"global\",type=\"patroni-registry\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"pgbouncer\",monitor=\"global\",type=\"patroni-registry\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"pgbouncer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "pgbouncer error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"pgbouncer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"pgbouncer\",monitor=\"global\",type=\"patroni-registry\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"pgbouncer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"pgbouncer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"pgbouncer\",monitor=\"global\",type=\"patroni-registry\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"pgbouncer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"pgbouncer\",monitor=\"global\",type=\"patroni-registry\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"pgbouncer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"pgbouncer\",monitor=\"global\",type=\"patroni-registry\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"pgbouncer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"pgbouncer\",monitor=\"global\",type=\"patroni-registry\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "pgbouncer SLI | Errors"
    }
   ]
  },
  {
   "title": "pgbouncer SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"pgbouncer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}[$__interval])\n",
     "legendFormat": "pgbouncer RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"pgbouncer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "content": "### Description\n\nAll transactions destined for the Postgres secondary instances are routed through the pgbouncer instances\nrunning on the patroni nodes themselves. This SLI models those transactions in aggregate.\n\nError rate uses mtail metrics from pgbouncer logs.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: pgbouncer logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.pg_message),filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.pgbouncer,type:phrase),query:(match:(json.tag.keyword:(query:postgres.pgbouncer,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase))))),index:'97f04200-024b-11eb-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: pgbouncer requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97f04200-024b-11eb-81e5-155ba78758d4&_a=(filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.pgbouncer,type:phrase),query:(match:(json.tag.keyword:(query:postgres.pgbouncer,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "transactions_primary SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"transactions_primary\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "transactions_primary error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"transactions_primary\",monitor=\"global\",type=\"patroni-registry\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"transactions_primary\",monitor=\"global\",type=\"patroni-registry\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"transactions_primary\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "transactions_primary error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"transactions_primary\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"transactions_primary\",monitor=\"global\",type=\"patroni-registry\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"transactions_primary\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"transactions_primary\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"transactions_primary\",monitor=\"global\",type=\"patroni-registry\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"transactions_primary\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"transactions_primary\",monitor=\"global\",type=\"patroni-registry\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"transactions_primary\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"transactions_primary\",monitor=\"global\",type=\"patroni-registry\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"transactions_primary\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"transactions_primary\",monitor=\"global\",type=\"patroni-registry\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "transactions_primary SLI | Errors"
    }
   ]
  },
  {
   "title": "transactions_primary SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"transactions_primary\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}[$__interval])\n",
     "legendFormat": "transactions_primary RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"transactions_primary\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "content": "### Description\n\nRepresents all SQL transactions issued to the primary Postgres instance.\nErrors represent transaction rollbacks.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Postgres logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.endpoint_id,json.error_severity,json.message,json.session_start_time,json.sql_state_code,json.duration_s,json.sql),filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.postgres_csv,type:phrase),query:(match:(json.tag.keyword:(query:postgres.postgres_csv,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase))))),index:'97f04200-024b-11eb-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Postgres failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.endpoint_id,json.error_severity,json.message,json.session_start_time,json.sql_state_code,json.duration_s,json.sql),filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.postgres_csv,type:phrase),query:(match:(json.tag.keyword:(query:postgres.postgres_csv,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.sql_state_code,negate:!t,params:'00000',type:phrase),query:(match:(json.sql_state_code:(query:'00000',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:exists,type:json.sql_state_code,value:exists),query:(exists:(field:json.sql_state_code)))),index:'97f04200-024b-11eb-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Postgres requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97f04200-024b-11eb-81e5-155ba78758d4&_a=(filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.postgres_csv,type:phrase),query:(match:(json.tag.keyword:(query:postgres.postgres_csv,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Postgres failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97f04200-024b-11eb-81e5-155ba78758d4&_a=(filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.postgres_csv,type:phrase),query:(match:(json.tag.keyword:(query:postgres.postgres_csv,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.sql_state_code,negate:!t,params:'00000',type:phrase),query:(match:(json.sql_state_code:(query:'00000',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:exists,type:json.sql_state_code,value:exists),query:(exists:(field:json.sql_state_code)))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Postgres sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97f04200-024b-11eb-81e5-155ba78758d4&_a=(filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.postgres_csv,type:phrase),query:(match:(json.tag.keyword:(query:postgres.postgres_csv,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Postgres sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97f04200-024b-11eb-81e5-155ba78758d4&_a=(filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.postgres_csv,type:phrase),query:(match:(json.tag.keyword:(query:postgres.postgres_csv,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.fingerprint.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Postgres percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97f04200-024b-11eb-81e5-155ba78758d4&_a=(filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.postgres_csv,type:phrase),query:(match:(json.tag.keyword:(query:postgres.postgres_csv,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Postgres percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97f04200-024b-11eb-81e5-155ba78758d4&_a=(filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.postgres_csv,type:phrase),query:(match:(json.tag.keyword:(query:postgres.postgres_csv,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.fingerprint.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "transactions_replica SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"transactions_replica\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "transactions_replica error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"transactions_replica\",monitor=\"global\",type=\"patroni-registry\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"transactions_replica\",monitor=\"global\",type=\"patroni-registry\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"transactions_replica\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "transactions_replica error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"transactions_replica\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"transactions_replica\",monitor=\"global\",type=\"patroni-registry\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"transactions_replica\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"transactions_replica\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"transactions_replica\",monitor=\"global\",type=\"patroni-registry\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"transactions_replica\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"transactions_replica\",monitor=\"global\",type=\"patroni-registry\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"transactions_replica\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"transactions_replica\",monitor=\"global\",type=\"patroni-registry\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"transactions_replica\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"transactions_replica\",monitor=\"global\",type=\"patroni-registry\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "transactions_replica SLI | Errors"
    }
   ]
  },
  {
   "title": "transactions_replica SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"transactions_replica\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"}[$__interval])\n",
     "legendFormat": "transactions_replica RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"transactions_replica\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"patroni-registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "content": "### Description\n\nRepresents all SQL transactions issued to replica Postgres instances, in aggregate.\nErrors represent transaction rollbacks.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Postgres logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.endpoint_id,json.error_severity,json.message,json.session_start_time,json.sql_state_code,json.duration_s,json.sql),filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.postgres_csv,type:phrase),query:(match:(json.tag.keyword:(query:postgres.postgres_csv,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase))))),index:'97f04200-024b-11eb-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Postgres failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.endpoint_id,json.error_severity,json.message,json.session_start_time,json.sql_state_code,json.duration_s,json.sql),filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.postgres_csv,type:phrase),query:(match:(json.tag.keyword:(query:postgres.postgres_csv,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.sql_state_code,negate:!t,params:'00000',type:phrase),query:(match:(json.sql_state_code:(query:'00000',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:exists,type:json.sql_state_code,value:exists),query:(exists:(field:json.sql_state_code)))),index:'97f04200-024b-11eb-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Postgres requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97f04200-024b-11eb-81e5-155ba78758d4&_a=(filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.postgres_csv,type:phrase),query:(match:(json.tag.keyword:(query:postgres.postgres_csv,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Postgres failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97f04200-024b-11eb-81e5-155ba78758d4&_a=(filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.postgres_csv,type:phrase),query:(match:(json.tag.keyword:(query:postgres.postgres_csv,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.sql_state_code,negate:!t,params:'00000',type:phrase),query:(match:(json.sql_state_code:(query:'00000',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:exists,type:json.sql_state_code,value:exists),query:(exists:(field:json.sql_state_code)))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Postgres sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97f04200-024b-11eb-81e5-155ba78758d4&_a=(filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.postgres_csv,type:phrase),query:(match:(json.tag.keyword:(query:postgres.postgres_csv,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Postgres sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97f04200-024b-11eb-81e5-155ba78758d4&_a=(filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.postgres_csv,type:phrase),query:(match:(json.tag.keyword:(query:postgres.postgres_csv,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.fingerprint.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Postgres percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97f04200-024b-11eb-81e5-155ba78758d4&_a=(filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.postgres_csv,type:phrase),query:(match:(json.tag.keyword:(query:postgres.postgres_csv,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Postgres percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97f04200-024b-11eb-81e5-155ba78758d4&_a=(filters:!((meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type.keyword,params:'patroni-registry',type:phrase),query:(match:(json.type.keyword:(query:'patroni-registry',type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.tag.keyword,params:postgres.postgres_csv,type:phrase),query:(match:(json.tag.keyword:(query:postgres.postgres_csv,type:phrase)))),(meta:(index:'97f04200-024b-11eb-81e5-155ba78758d4',key:json.type,params:'patroni-registry',type:phrase),query:(match:(json.type:(query:'patroni-registry',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.fingerprint.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "🔬 SLI Detail: pgbouncer",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "pgbouncer Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:pgbouncer_pooler_errors_total:rate_5m{env=\"$environment\",environment=\"$environment\",tier=\"db\",type=\"patroni-registry\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "pgbouncer RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  label_replace(rate(pgbouncer_stats_sql_transactions_pooled_total{env=\"$environment\",environment=\"$environment\",tier=\"db\",type=\"patroni-registry\"}[$__interval]), \"_c\", \"0\", \"\", \"\")\n  or\n  label_replace(rate(pgbouncer_stats_queries_pooled_total{env=\"$environment\",environment=\"$environment\",tier=\"db\",type=\"patroni-registry\"}[$__interval]), \"_c\", \"1\", \"\", \"\")\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "pgbouncer Errors - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  sli_aggregations:pgbouncer_pooler_errors_total:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",tier=\"db\",type=\"patroni-registry\"}\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "pgbouncer RPS - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  label_replace(rate(pgbouncer_stats_sql_transactions_pooled_total{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",tier=\"db\",type=\"patroni-registry\"}[$__interval]), \"_c\", \"0\", \"\", \"\")\n  or\n  label_replace(rate(pgbouncer_stats_queries_pooled_total{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",tier=\"db\",type=\"patroni-registry\"}[$__interval]), \"_c\", \"1\", \"\", \"\")\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "pgbouncer Errors - per error",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (error) (\n  sli_aggregations:pgbouncer_pooler_errors_total:rate_5m{env=\"$environment\",environment=\"$environment\",error!=\"\",tier=\"db\",type=\"patroni-registry\"}\n)\n > 0",
       "legendFormat": "{{error}}"
      }
     ]
    },
    {
     "title": "pgbouncer RPS - per error",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (error) (\n  label_replace(rate(pgbouncer_stats_sql_transactions_pooled_total{env=\"$environment\",environment=\"$environment\",error!=\"\",tier=\"db\",type=\"patroni-registry\"}[$__interval]), \"_c\", \"0\", \"\", \"\")\n  or\n  label_replace(rate(pgbouncer_stats_queries_pooled_total{env=\"$environment\",environment=\"$environment\",error!=\"\",tier=\"db\",type=\"patroni-registry\"}[$__interval]), \"_c\", \"1\", \"\", \"\")\n)\n > 0",
       "legendFormat": "{{error}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: transactions_primary",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "transactions_primary Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:pg_stat_database_xact_rollback:rate_5m{env=\"$environment\",environment=\"$environment\",tier=\"db\",type=\"patroni-registry\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "transactions_primary RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  label_replace(rate(pg_stat_database_xact_commit{env=\"$environment\",environment=\"$environment\",tier=\"db\",type=\"patroni-registry\"}[$__interval]) and on (instance) (pg_replication_is_replica == 0), \"_c\", \"0\", \"\", \"\")\n  or\n  label_replace(rate(pg_stat_database_xact_rollback{env=\"$environment\",environment=\"$environment\",tier=\"db\",type=\"patroni-registry\"}[$__interval]) and on (instance) (pg_replication_is_replica == 0), \"_c\", \"1\", \"\", \"\")\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "transactions_primary Errors - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  sli_aggregations:pg_stat_database_xact_rollback:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",tier=\"db\",type=\"patroni-registry\"}\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "transactions_primary RPS - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  label_replace(rate(pg_stat_database_xact_commit{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",tier=\"db\",type=\"patroni-registry\"}[$__interval]) and on (instance) (pg_replication_is_replica == 0), \"_c\", \"0\", \"\", \"\")\n  or\n  label_replace(rate(pg_stat_database_xact_rollback{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",tier=\"db\",type=\"patroni-registry\"}[$__interval]) and on (instance) (pg_replication_is_replica == 0), \"_c\", \"1\", \"\", \"\")\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: transactions_replica",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 220 },
   "collapsed": true,
   "panels": [
    {
     "title": "transactions_replica Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:pg_stat_database_xact_rollback:rate_5m{env=\"$environment\",environment=\"$environment\",tier=\"db\",type=\"patroni-registry\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "transactions_replica RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  label_replace(rate(pg_stat_database_xact_commit{env=\"$environment\",environment=\"$environment\",tier=\"db\",type=\"patroni-registry\"}[$__interval]) and on (instance) (pg_replication_is_replica == 1), \"_c\", \"0\", \"\", \"\")\n  or\n  label_replace(rate(pg_stat_database_xact_rollback{env=\"$environment\",environment=\"$environment\",tier=\"db\",type=\"patroni-registry\"}[$__interval]) and on (instance) (pg_replication_is_replica == 1), \"_c\", \"1\", \"\", \"\")\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "transactions_replica Errors - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  sli_aggregations:pg_stat_database_xact_rollback:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",tier=\"db\",type=\"patroni-registry\"}\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "transactions_replica RPS - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  label_replace(rate(pg_stat_database_xact_commit{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",tier=\"db\",type=\"patroni-registry\"}[$__interval]) and on (instance) (pg_replication_is_replica == 1), \"_c\", \"0\", \"\", \"\")\n  or\n  label_replace(rate(pg_stat_database_xact_rollback{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",tier=\"db\",type=\"patroni-registry\"}[$__interval]) and on (instance) (pg_replication_is_replica == 1), \"_c\", \"1\", \"\", \"\")\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🖥️ Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU",
     "type": "graph",
     "description": "The amount of non-idle time consumed by nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Average CPU Utilization" }
     ],
     "targets": [
      {
       "expr": "avg(instance:node_cpu_utilization:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Maximum Single Core Utilization",
     "type": "graph",
     "description": "The maximum utilization of a single core on each node. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(max(1 - rate(node_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", mode=\"idle\"}[$__interval])) by (fqdn)\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Network Utilization",
     "type": "graph",
     "description": "Network utilization for nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "send {{ fqdn }}"
      },
      {
       "expr": "sum(rate(node_network_receive_bytes_total{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "receive {{ fqdn }}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "description": "Memory utilization. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(instance:node_memory_utilization:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read IOPs",
     "type": "graph",
     "description": "Disk Read IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_reads_completed_total{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write IOPs",
     "type": "graph",
     "description": "Disk Write IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_writes_completed_total{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Throughput",
     "type": "graph",
     "description": "Disk Read throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_read_bytes_total{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Throughput",
     "type": "graph",
     "description": "Disk Write throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_written_bytes_total{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Total Time",
     "type": "graph",
     "description": "Total time spent in read operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_read_time_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Total Time",
     "type": "graph",
     "description": "Total time spent in write operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_write_time_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "CPU Scheduling Waiting",
     "type": "graph",
     "description": "CPU scheduling waiting on the run queue, as a percentage of time. Aggregated to worst CPU per node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "max by (fqdn) (\n  rate(node_schedstat_waiting_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[5m])\n)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg1 per core",
     "type": "graph",
     "description": "Loadavg (1 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "loadavg1" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load1{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg5 per core",
     "type": "graph",
     "description": "Loadavg (5 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg5" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load5{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg15 per core",
     "type": "graph",
     "description": "Loadavg (15 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg15" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load15{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu component saturation: Average Service CPU Utilization",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in a service fleet.\nIf it is becoming saturated, it may indicate that the fleet needs\nhorizontal or vertical scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage, shard) (\n        rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_inodes component saturation: Disk inode Utilization per Device per Node",
     "type": "graph",
     "description": "Disk inode utilization per device per node.\n\nIf this is too high, its possible that a directory is filling up with\nfiles. Consider logging in an checking temp directories for large numbers\nof files\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      1 - (\n        node_filesystem_files_free{fstype=~\"(ext.|xfs)\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}\n        /\n        node_filesystem_files{fstype=~\"(ext.|xfs)\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"disk_inodes\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"disk_inodes\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"disk_inodes\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_inodes\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_inodes\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_maximum_capacity component saturation: Maximum per-disk capacity",
     "type": "graph",
     "description": "The maximum capacity for a single disk can be limited by the cloud provider.\nThis tracks the saturation as a ratio of the storage utilization to the maximum size limit enforced per disk.\n\nIn order to resolve a saturation alert, storage needed on a single disk needs to be reduced.\nPossible ways of doing this include reducing utilization overall or partitioning data across multiple disks.\n\n(64*2^40) = 64TiB is the maximum value for many types of GCP disks, see https://cloud.google.com/compute/docs/disks#introduction.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      max by (environment, tier, type, stage, shard, fqdn, device) (\n        node_filesystem_size_bytes{fstype=~\"ext.|xfs\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"} - node_filesystem_avail_bytes{fstype=~\"ext.|xfs\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}\n      ) / (64*2^40)\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"disk_maximum_capacity\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"disk_maximum_capacity\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"disk_maximum_capacity\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_maximum_capacity\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_maximum_capacity\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_space component saturation: Disk Space Utilization per Device per Node",
     "type": "graph",
     "description": "Disk space utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      (\n        1 - node_filesystem_avail_bytes{fstype=~\"ext.|xfs\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"} / node_filesystem_size_bytes{fstype=~\"ext.|xfs\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"disk_space\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"disk_space\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"disk_space\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "memory component saturation: Memory Utilization per Node",
     "type": "graph",
     "description": "Memory utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      instance:node_memory_utilization:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"} or instance:node_memory_utilisation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "nf_conntrack_entries component saturation: conntrack Entries per Node",
     "type": "graph",
     "description": "Netfilter connection tracking table utilization per node.\n\nWhen saturated, new connection attempts (incoming SYN packets) are dropped with no reply, leaving clients to slowly retry (and typically fail again) over the next several seconds.  When packets are being dropped due to this condition, kernel will log the event as: \"nf_conntrack: table full, dropping packet\".\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, instance) (\n  clamp_min(\n    clamp_max(\n      max_over_time(node_nf_conntrack_entries{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[1m])\n      /\n      node_nf_conntrack_entries_limit{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"nf_conntrack_entries\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"nf_conntrack_entries\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"nf_conntrack_entries\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"nf_conntrack_entries\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"nf_conntrack_entries\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "node_schedstat_waiting component saturation: Node Scheduler Waiting Time",
     "type": "graph",
     "description": "Measures the amount of scheduler waiting time that processes are waiting\nto be scheduled, according to [`CPU Scheduling Metrics`](https://www.robustperception.io/cpu-scheduling-metrics-from-the-node-exporter).\n\nA high value indicates that a node has more processes to be run than CPU time available\nto handle them, and may lead to degraded responsiveness and performance from the application.\n\nAdditionally, it may indicate that the fleet is under-provisioned.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, shard) (\n  clamp_min(\n    clamp_max(\n      avg without (cpu) (rate(node_schedstat_waiting_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[1h]))\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"node_schedstat_waiting\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"node_schedstat_waiting\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"node_schedstat_waiting\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"node_schedstat_waiting\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"node_schedstat_waiting\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "pg_active_db_connections_primary component saturation: Active Primary DB Connection Utilization",
     "type": "graph",
     "description": "Active db connection utilization on the primary node.\n\nPostgres is configured to use a maximum number of connections.\nWhen this resource is saturated, connections may queue.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      sum without (state) (\n        pg_stat_activity_count{datname=~\"gitlabhq_production|gitlabhq_registry\", state!=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"} unless on(instance) (pg_replication_is_replica == 1)\n      )\n      / on (environment, tier, type, stage, shard, fqdn)\n      pg_settings_max_connections{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_active_db_connections_primary\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_active_db_connections_primary\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_active_db_connections_primary\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"pg_active_db_connections_primary\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"pg_active_db_connections_primary\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "pg_active_db_connections_replica component saturation: Active Secondary DB Connection Utilization",
     "type": "graph",
     "description": "Active db connection utilization per replica node\n\nPostgres is configured to use a maximum number of connections.\nWhen this resource is saturated, connections may queue.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      sum without (state) (\n        pg_stat_activity_count{datname=~\"gitlabhq_production|gitlabhq_registry\", state!=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"} and on(instance) (pg_replication_is_replica == 1)\n      )\n      / on (environment, tier, type, stage, shard, fqdn)\n      pg_settings_max_connections{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_active_db_connections_replica\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_active_db_connections_replica\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_active_db_connections_replica\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"pg_active_db_connections_replica\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"pg_active_db_connections_replica\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "pg_btree_bloat component saturation: Postgres btree bloat",
     "type": "graph",
     "description": "This estimates the total bloat in Postgres Btree indexes, as a percentage of total index size.\n\nIMPORTANT: bloat estimates are rough and depending on table/index structure, can be off for individual indexes,\nin some cases significantly (10-50%).\n\nThe larger this measure, the more pages will unnecessarily be retrieved during index scans.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard, fqdn) (last_over_time(gitlab_database_bloat_btree_bloat_size{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[1h]))\n      /\n      sum by (environment, tier, type, stage, shard, fqdn) (last_over_time(gitlab_database_bloat_btree_real_size{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[1h]))\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_btree_bloat\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_btree_bloat\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_btree_bloat\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"pg_btree_bloat\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"pg_btree_bloat\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "pg_primary_cpu component saturation: Average CPU Utilization on Postgres Primary Instance",
     "type": "graph",
     "description": "Average CPU utilization across all cores on the Postgres primary instance.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(env, environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      avg without(cpu, mode) (\n        1\n        -\n        (\n          rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[5m])\n          and on(fqdn)\n          pg_replication_is_replica{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"} == 0\n        )\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_primary_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_primary_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_primary_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"pg_primary_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"pg_primary_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "pg_table_bloat component saturation: Postgres Table Bloat",
     "type": "graph",
     "description": "This measures the total bloat in Postgres Table pages, as a percentage of total size. This includes bloat in TOAST tables,\nand excludes extra space reserved due to fillfactor.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard, fqdn) (avg_over_time(gitlab_database_bloat_table_bloat_size{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[58m]))\n      /\n      sum by (environment, tier, type, stage, shard, fqdn) (avg_over_time(gitlab_database_bloat_table_real_size{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[58m]))\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_table_bloat\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_table_bloat\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_table_bloat\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"pg_table_bloat\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"pg_table_bloat\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "pg_txid_vacuum_to_wraparound component saturation: Total autovacuum time to TXID wraparound horizon",
     "type": "graph",
     "description": "This saturation metric measures the capacity of the Postgres primary instance to perform autovacuum operations\non all tables.\n\nIt measures the total time spent in vacuum operations, over a 24 hour period divided the maximum number of autovacuum processes\nto give the total vacuum activity, in seconds. This value is divided by the TXID wraparound horizon for the database to\nproduce a percentage.\n\nThis value will approach 100% as two situation occur:\n\n1. The amount of time spent performing autovacuum operations goes up, due to high dead-tuple generation in the database.\n1. The write transaction volume goes up, decreasing the wraparound horizon.\n\nIf the total time spent vacuuming approached the wraparound time horizon, this would mean that the database would be at risk\nof being unable to complete a vacuum of all tables within the wraparound time horizon. This would put the database at risk of XID\nwraparound and immediate shutdown.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      (\n        sum by (environment, tier, type, stage, shard) (\n          increase(fluentd_pg_auto_vacuum_elapsed_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[1d])\n        )\n        / on(environment, type) group_left() (\n          pg_settings_autovacuum_max_workers and\n          on (instance) pg_replication_is_replica == 0\n        )\n      )\n      /\n      (\n        (2^31 - 10^6)\n        /\n        (\n          avg by (environment, tier, type, stage, shard) (\n            deriv(pg_txid_current{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[1d]) and\n            on (instance) pg_replication_is_replica == 0\n          )\n        )\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_txid_vacuum_to_wraparound\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_txid_vacuum_to_wraparound\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_txid_vacuum_to_wraparound\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"pg_txid_vacuum_to_wraparound\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"pg_txid_vacuum_to_wraparound\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "pg_vacuum_activity_v2 component saturation: Postgres Autovacuum Activity (non-sampled)",
     "type": "graph",
     "description": "This measures the total amount of time spent each day by autovacuum workers, as a percentage of total autovacuum capacity.\n\nThis resource uses the `auto_vacuum_elapsed_seconds` value logged by the autovacuum worker, and aggregates this across all\nautovacuum jobs. In the case that there are 10 autovacuum workers, the total capacity is 10-days worth of autovacuum time per day.\n\nOnce the system is performing 10 days worth of autovacuum per day, the capacity will be saturated.\n\nThis resource is primarily intended to be used for long-term capacity planning.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(env, environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      sum by (env, environment, tier, type, stage, shard) (\n        rate(fluentd_pg_auto_vacuum_elapsed_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[1d])\n        and on (fqdn) (pg_replication_is_replica{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"} == 0)\n      )\n      /\n      avg by (env, environment, tier, type, stage, shard) (\n        pg_settings_autovacuum_max_workers{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}\n        and on (instance, job) (pg_replication_is_replica{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"} == 0)\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_vacuum_activity_v2\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_vacuum_activity_v2\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_vacuum_activity_v2\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"pg_vacuum_activity_v2\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"pg_vacuum_activity_v2\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "pg_walsender_cpu component saturation: Walsender CPU Saturation",
     "type": "graph",
     "description": "This saturation metric measures the total amount of time that the primary postgres instance is spending sending WAL segments\nto replicas. It is expressed as a percentage of all CPU available on the primary postgres instance.\n\nThe more replicas connected, the higher this metric will be.\n\nSince it's expressed as a percentage of all CPU, this should always remain low, since the CPU primarily needs to be available for\nhandling SQL statements.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(env, environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      sum by (env, environment, tier, type, stage, shard) (\n        sum by(env, environment, tier, type, stage, shard, fqdn) (\n          rate(namedprocess_namegroup_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", groupname=~\"pg.worker.walsender|pg.worker.walwriter|wal-g\"}[5m])\n          and on (fqdn) (pg_replication_is_replica{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"} == 0)\n        )\n        /\n        count by (env, environment, tier, type, stage, shard, fqdn) (\n          node_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", mode=\"idle\"} and on(fqdn) (pg_replication_is_replica{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"} == 0)\n        )\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_walsender_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_walsender_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_walsender_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"pg_walsender_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"pg_walsender_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "pg_xid_wraparound component saturation: Transaction ID Wraparound",
     "type": "graph",
     "description": "Risk of DB shutdown in the near future, approaching transaction ID wraparound.\n\nThis is a critical situation.\n\nThis saturation metric measures how close the database is to Transaction ID wraparound.\n\nWhen wraparound occurs, the database will automatically shutdown to prevent data loss, causing a full outage.\n\nRecovery would require entering single-user mode to run vacuum, taking the site down for a potentially multi-hour maintenance session.\n\nTo avoid reaching the db shutdown threshold, consider the following short-term actions:\n\n1. Escalate to the SRE Datastores team, and then,\n\n2. Find and terminate any very old transactions. The runbook for this alert has details.  Do this first.  It is the most critical step and may be all that is necessary to let autovacuum do its job.\n\n3. Run a manual vacuum on tables with oldest relfrozenxid.  Manual vacuums run faster than autovacuum.\n\n4. Add autovacuum workers or reduce autovacuum cost delay, if autovacuum is chronically unable to keep up with the transaction rate.\n\nLong running transaction dashboard: https://dashboards.gitlab.net/d/alerts-long_running_transactions/alerts-long-running-transactions?orgId=1\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, datname) (\n  clamp_min(\n    clamp_max(\n      (\n        max without (series) (\n          label_replace(pg_database_wraparound_age_datfrozenxid{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}, \"series\", \"datfrozenxid\", \"\", \"\")\n          or\n          label_replace(pg_database_wraparound_age_datminmxid{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}, \"series\", \"datminmxid\", \"\", \"\")\n        )\n        and on (instance, job) (pg_replication_is_replica{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"} == 0)\n      )\n      /\n      (2^31 - 3000000)\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ datname }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_xid_wraparound\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_xid_wraparound\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pg_xid_wraparound\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"pg_xid_wraparound\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"pg_xid_wraparound\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "pgbouncer_client_conn_replicas component saturation: PGBouncer Client Connections per Process (Replicas)",
     "type": "graph",
     "description": "Client connections per pgbouncer process for Replicas connections.\n\npgbouncer is configured to use a `max_client_conn` setting. This limits the total number of client connections per pgbouncer.\n\nWhen this limit is reached, client connections may be refused, and `max_client_conn` errors may appear in the pgbouncer logs.\n\nThis could affect users as Rails clients are left unable to connect to the database. Another potential knock-on effect\nis that Rails clients could fail their readiness checks for extended periods during a deployment, leading to saturation of\nthe older nodes.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      max_over_time(pgbouncer_used_clients{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[5m])\n      /\n      30000\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pgbouncer_client_conn_replicas\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pgbouncer_client_conn_replicas\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pgbouncer_client_conn_replicas\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"pgbouncer_client_conn_replicas\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"pgbouncer_client_conn_replicas\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "pgbouncer_sync_replica_pool component saturation: Postgres Sync (Web/API/Git) replica Connection Pool Utilization per Node",
     "type": "graph",
     "description": "pgbouncer sync connection pool Saturation per database node, for replica database connections.\n\nWeb/api/git applications use a separate connection pool to sidekiq.\n\nWhen this resource is saturated, web/api database operations may queue, leading to rails worker\nsaturation and 503 errors in the web.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        avg_over_time(pgbouncer_pools_server_active_connections{user=~\"gitlab|gitlab-registry\", database=~\"gitlabhq_registry|gitlabhq_production\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[5m]) +\n        avg_over_time(pgbouncer_pools_server_testing_connections{user=~\"gitlab|gitlab-registry\", database=~\"gitlabhq_registry|gitlabhq_production\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[5m]) +\n        avg_over_time(pgbouncer_pools_server_used_connections{user=~\"gitlab|gitlab-registry\", database=~\"gitlabhq_registry|gitlabhq_production\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[5m]) +\n        avg_over_time(pgbouncer_pools_server_login_connections{user=~\"gitlab|gitlab-registry\", database=~\"gitlabhq_registry|gitlabhq_production\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[5m])\n      )\n      / on(environment, tier, type, stage, shard, fqdn, instance) group_left()\n      sum by (environment, tier, type, stage, shard, fqdn, instance) (\n        avg_over_time(pgbouncer_databases_pool_size{name=~\"gitlabhq_registry|gitlabhq_production\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pgbouncer_sync_replica_pool\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pgbouncer_sync_replica_pool\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"pgbouncer_sync_replica_pool\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"pgbouncer_sync_replica_pool\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"pgbouncer_sync_replica_pool\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "shard_cpu component saturation: Average CPU Utilization per Shard",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in a shard of a\nservice fleet. If it is becoming saturated, it may indicate that the\nshard needs horizontal or vertical scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, shard) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage, shard, shard) (\n        rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"shard_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"shard_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"shard_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"shard_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"shard_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "single_node_cpu component saturation: Average CPU Utilization per Node",
     "type": "graph",
     "description": "Average CPU utilization per Node.\n\nIf average CPU is saturated, it may indicate that a fleet is in need to horizontal or vertical scaling. It may also indicate\nimbalances in load in a fleet.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      avg without(cpu, mode) (1 - rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\"}[5m]))\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"single_node_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"single_node_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"patroni-registry\", component=\"single_node_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  { "title": "pgbouncer Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Queries Pooled per Node",
   "type": "graph",
   "description": "Total number of SQL queries pooled - stats_total_query_count",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_queries_pooled_total{type=\"patroni-registry\", environment=\"$environment\"}[$__interval])) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Total Time in Queries per Node",
   "type": "graph",
   "description": "Total number of seconds spent by pgbouncer when actively connected to PostgreSQL, executing queries - stats.total_query_time",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_queries_duration_seconds_total{type=\"patroni-registry\", environment=\"$environment\"}[$__interval])) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "SQL Transactions Pooled per Node",
   "type": "graph",
   "description": "Total number of SQL transactions pooled - stats.total_xact_count",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1011 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_sql_transactions_pooled_total{type=\"patroni-registry\", environment=\"$environment\"}[$__interval])) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Time in Transaction per Server",
   "type": "graph",
   "description": "Total number of seconds spent by pgbouncer when connected to PostgreSQL in a transaction, either idle in transaction or executing queries - stats.total_xact_time",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1011 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_server_in_transaction_seconds_total{type=\"patroni-registry\", environment=\"$environment\"}[$__interval])) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  { "title": "pgbouncer Connection Pooling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Server Connection Pool Active Connections per Node",
   "type": "graph",
   "description": "Number of active connections per node",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(pgbouncer_pools_server_active_connections{type=\"patroni-registry\", environment=\"$environment\", user=\"gitlab-registry\", database!=\"pgbouncer\"}[$__interval])) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Connection Saturation per Pool",
   "type": "graph",
   "description": "Shows connection saturation per pgbouncer pool. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2001 },
   "yaxes": [
    { "format": "percentunit", "label": "Server Pool Utilization" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by (database, env, environment, shard, stage, type) (\n  pgbouncer_pools_server_active_connections{type=\"patroni-registry\", environment=\"$environment\", user=\"gitlab-registry\", database!=\"pgbouncer\"} +\n  pgbouncer_pools_server_testing_connections{type=\"patroni-registry\", environment=\"$environment\", user=\"gitlab-registry\", database!=\"pgbouncer\"} +\n  pgbouncer_pools_server_used_connections{type=\"patroni-registry\", environment=\"$environment\", user=\"gitlab-registry\", database!=\"pgbouncer\"} +\n  pgbouncer_pools_server_login_connections{type=\"patroni-registry\", environment=\"$environment\", user=\"gitlab-registry\", database!=\"pgbouncer\"}\n)\n/\nsum by (database, env, environment, shard, stage, type) (\n  label_replace(\n    pgbouncer_databases_pool_size{type=\"patroni-registry\", environment=\"$environment\"},\n    \"database\", \"$1\", \"name\", \"(.*)\"\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ database }} pool"
    }
   ]
  },
  {
   "title": "Connection Saturation per Pool per Node",
   "type": "graph",
   "description": "Shows connection saturation per pgbouncer pool, per pgbouncer node. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2011 },
   "yaxes": [
    { "format": "percentunit", "label": "Server Pool Utilization" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by (database, env, environment, fqdn, job, shard, stage, type) (\n  pgbouncer_pools_server_active_connections{type=\"patroni-registry\", environment=\"$environment\", user=\"gitlab-registry\", database!=\"pgbouncer\"} +\n  pgbouncer_pools_server_testing_connections{type=\"patroni-registry\", environment=\"$environment\", user=\"gitlab-registry\", database!=\"pgbouncer\"} +\n  pgbouncer_pools_server_used_connections{type=\"patroni-registry\", environment=\"$environment\", user=\"gitlab-registry\", database!=\"pgbouncer\"} +\n  pgbouncer_pools_server_login_connections{type=\"patroni-registry\", environment=\"$environment\", user=\"gitlab-registry\", database!=\"pgbouncer\"}\n)\n/\nsum by (database, env, environment, fqdn, job, shard, stage, type) (\n  label_replace(\n    pgbouncer_databases_pool_size{type=\"patroni-registry\", environment=\"$environment\"},\n    \"database\", \"$1\", \"name\", \"(.*)\"\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ fqdn }} {{ database }} pool"
    }
   ]
  },
  {
   "title": "Total Connection Wait Time",
   "type": "graph",
   "description": "Total aggregated time spend waiting for a backend connection. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2011 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "sum by (database, environment, type) (rate(pgbouncer_stats_client_wait_seconds_total{type=\"patroni-registry\", environment=\"$environment\", database!=\"pgbouncer\"}[$__interval]) / on() group_left() (vector((time() < bool 1588233600) * 1000000) == 1000000 or vector(1)))\n",
     "legendFormat": "{{ database }}"
    }
   ]
  },
  {
   "title": "Average Wait Time per SQL Transaction",
   "type": "graph",
   "description": "Average time spent waiting for a backend connection from the pool. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2021 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "sum by (database, environment, type, fqdn, job) (rate(pgbouncer_stats_client_wait_seconds_total{type=\"patroni-registry\", environment=\"$environment\", database!=\"pgbouncer\"}[$__interval]) / on() group_left() (vector((time() < bool 1588233600) * 1000000) == 1000000 or vector(1)))\n/\nsum by (database, environment, type, fqdn, job) (rate(pgbouncer_stats_sql_transactions_pooled_total{type=\"patroni-registry\", environment=\"$environment\", database!=\"pgbouncer\"}[$__interval]))\n",
     "legendFormat": "{{ fqdn }} {{ job }} {{ database }}"
    }
   ]
  },
  {
   "title": "Waiting Client Connections per Pool (⚠️ possibly inaccurate, occassionally polled value, do not make assumptions based on this)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2021 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(pgbouncer_pools_client_waiting_connections{type=\"patroni-registry\", environment=\"$environment\", user=\"gitlab-registry\", database!=\"pgbouncer\"}[$__interval])) by (database)\n",
     "legendFormat": "{{ database }} pool"
    }
   ]
  },
  {
   "title": "Active Backend Server Connections per Database",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2031 },
   "yaxes": [
    { "format": "short", "label": "Active Connections" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(pgbouncer_pools_server_active_connections{type=\"patroni-registry\", environment=\"$environment\", user=\"gitlab-registry\", database!=\"pgbouncer\"}[$__interval])) by (database)\n",
     "legendFormat": "{{ database }} database"
    }
   ]
  },
  {
   "title": "Active Backend Server Connections per User",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2031 },
   "yaxes": [
    { "format": "short", "label": "Active Connections" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(pgbouncer_pools_server_active_connections{type=\"patroni-registry\", environment=\"$environment\", user=\"gitlab-registry\", database!=\"pgbouncer\"}[$__interval])) by (user)\n",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "pgbouncer Single Threaded CPU Saturation per Node",
   "type": "graph",
   "description": "pgbouncer is single-threaded. This graph shows maximum utilization across all cores on each host. Lower is better.\n\nMissing data? [https://gitlab.com/gitlab-com/gl-infra/reliability/-/issues/9980](https://gitlab.com/gitlab-com/gl-infra/reliability/-/issues/9980)\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2041 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum(\n  rate(\n    namedprocess_namegroup_cpu_seconds_total{groupname=~\"pgbouncer.*\", type=\"patroni-registry\", environment=\"$environment\"}[5m]\n  )\n) by (groupname, fqdn, type, stage, environment)\n,1),0)\n",
     "legendFormat": "{{ groupname }} {{ fqdn }}"
    }
   ]
  },
  { "title": "pgbouncer Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 } },
  {
   "title": "Sent Bytes",
   "type": "graph",
   "description": "Total volume in bytes of network traffic sent by pgbouncer, shown as bytes - stats.total_sent",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3001 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_sent_bytes_total{type=\"patroni-registry\", environment=\"$environment\"}[$__interval])) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "graph",
   "description": "Total volume in bytes of network traffic received by pgbouncer, shown as bytes - stats.total_received",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3001 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_received_bytes_total{type=\"patroni-registry\", environment=\"$environment\"}[$__interval])) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "postgres process stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4000 },
   "collapsed": true,
   "panels": [
    {
     "title": "postgres: CPU Time",
     "type": "graph",
     "description": "Seconds of CPU time for the named process group, per second. Note that this metric is sampled periodically, and thus will greatly under-sample short-lived processes.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  rate(\n    namedprocess_namegroup_cpu_seconds_total{environment=\"$environment\",groupname=\"postgres\",stage=\"main\",type=\"patroni-registry\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "postgres: Open File Descriptors",
     "type": "graph",
     "description": "Maximum number of open file descriptors per host",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by(fqdn) (\n    namedprocess_namegroup_open_filedesc{environment=\"$environment\",groupname=\"postgres\",stage=\"main\",type=\"patroni-registry\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "postgres: Number of Processes",
     "type": "graph",
     "description": "Number of processes in the process group",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  avg_over_time(namedprocess_namegroup_num_procs{environment=\"$environment\",groupname=\"postgres\",stage=\"main\",type=\"patroni-registry\"}[$__interval])\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "postgres: Number of Threads",
     "type": "graph",
     "description": "Number of threads in the process group",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  namedprocess_namegroup_num_threads{environment=\"$environment\",groupname=\"postgres\",stage=\"main\",type=\"patroni-registry\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "postgres: RSS Memory Usage",
     "type": "graph",
     "description": "Resident Memory usage for named process group",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  namedprocess_namegroup_memory_bytes{memtype=\"resident\", environment=\"$environment\",groupname=\"postgres\",stage=\"main\",type=\"patroni-registry\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    }
   ]
  },
  {
   "title": "wal-g process stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4010 },
   "collapsed": true,
   "panels": [
    {
     "title": "wal-g: CPU Time",
     "type": "graph",
     "description": "Seconds of CPU time for the named process group, per second. Note that this metric is sampled periodically, and thus will greatly under-sample short-lived processes.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  rate(\n    namedprocess_namegroup_cpu_seconds_total{environment=\"$environment\",groupname=\"wal-g\",stage=\"main\",type=\"patroni-registry\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "wal-g: Open File Descriptors",
     "type": "graph",
     "description": "Maximum number of open file descriptors per host",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by(fqdn) (\n    namedprocess_namegroup_open_filedesc{environment=\"$environment\",groupname=\"wal-g\",stage=\"main\",type=\"patroni-registry\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "wal-g: Number of Processes",
     "type": "graph",
     "description": "Number of processes in the process group",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  avg_over_time(namedprocess_namegroup_num_procs{environment=\"$environment\",groupname=\"wal-g\",stage=\"main\",type=\"patroni-registry\"}[$__interval])\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "wal-g: Number of Threads",
     "type": "graph",
     "description": "Number of threads in the process group",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  namedprocess_namegroup_num_threads{environment=\"$environment\",groupname=\"wal-g\",stage=\"main\",type=\"patroni-registry\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "wal-g: RSS Memory Usage",
     "type": "graph",
     "description": "Resident Memory usage for named process group",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  namedprocess_namegroup_memory_bytes{memtype=\"resident\", environment=\"$environment\",groupname=\"wal-g\",stage=\"main\",type=\"patroni-registry\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    }
   ]
  },
  {
   "title": "patroni process stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4020 },
   "collapsed": true,
   "panels": [
    {
     "title": "patroni-registry: CPU Time",
     "type": "graph",
     "description": "Seconds of CPU time for the named process group, per second. Note that this metric is sampled periodically, and thus will greatly under-sample short-lived processes.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  rate(\n    namedprocess_namegroup_cpu_seconds_total{environment=\"$environment\",groupname=\"patroni-registry\",stage=\"main\",type=\"patroni-registry\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "patroni-registry: Open File Descriptors",
     "type": "graph",
     "description": "Maximum number of open file descriptors per host",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by(fqdn) (\n    namedprocess_namegroup_open_filedesc{environment=\"$environment\",groupname=\"patroni-registry\",stage=\"main\",type=\"patroni-registry\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "patroni-registry: Number of Processes",
     "type": "graph",
     "description": "Number of processes in the process group",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  avg_over_time(namedprocess_namegroup_num_procs{environment=\"$environment\",groupname=\"patroni-registry\",stage=\"main\",type=\"patroni-registry\"}[$__interval])\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "patroni-registry: Number of Threads",
     "type": "graph",
     "description": "Number of threads in the process group",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  namedprocess_namegroup_num_threads{environment=\"$environment\",groupname=\"patroni-registry\",stage=\"main\",type=\"patroni-registry\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "patroni-registry: RSS Memory Usage",
     "type": "graph",
     "description": "Resident Memory usage for named process group",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  namedprocess_namegroup_memory_bytes{memtype=\"resident\", environment=\"$environment\",groupname=\"patroni-registry\",stage=\"main\",type=\"patroni-registry\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni\n  patroni-registry\nend\n\n\n  patroni-registry --> patroni\n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni\n  patroni-registry\nend\n\n\n  patroni-registry --> patroni\n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni-registry[\"patroni-registry (Level 1)\"]\n  patroni[\"patroni (Level 2)\"]\nend\n\n\n  patroni-registry[\"patroni-registry (Level 1)\"] --> patroni\n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}