groups:
  - name: cloudflare.rules
    rules:
      - alert: CloudflareExporterStaleData
        expr: sum without (pod, instance)  (time() - cloudflare_graphql_last_success_timestamp_seconds) > 600
        labels:
          severity: s4
          alert_type: cause
        annotations:
          title: Scrape errors in Cloudflare exporter
          description: >
            The cloudflare exporter has failed to scrape Cloudflare for 10
            minutes. Note that this refers to a background scrape loop in the
            exporter itself, and that prometheus may be successfully scraping
            the exporter.
      - alert: CloudflareCloudConnectorRateLimitEvents
        for: 10m
        expr: >
          rate(cloudflare_zone_firewall_events_count{zone="cloud.gitlab.com", source="ratelimit", action="block"}[5m]) > 0
        labels:
          severity: s4
          alert_type: cause
          team: cloud_connector
        annotations:
          title: Client was rate limited while dialing cloud.gitlab.com
          description: >
            One or more clients consuming features delivered through Cloud Connector was blocked by
            our rate limit rules in Cloudflare for 10 minutes or more. This could be OK but should
            be investigated for false positives.
