{
 "title": "observability: Clickhouse",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8397766929 at Mon Nov 18 09:15:18 UTC 2024",
 "tags": [
  "managed",
  "observability",
  "gitlab-observability"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   {
    "name": "Node",
    "query": "query_result(count(count_over_time(kube_node_labels{environment=\"$environment\", cluster=\"$cluster\"}[1w])) by (label_kubernetes_io_hostname))"
   },
   { "name": "environment", "label": "Environment", "query": "gstg,gprd" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_container_info{env=\"$environment\", cluster=~\"opstrace-.*\"}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_statefulset_status_replicas{env=\"gprd\", cluster=~\"opstrace-.*\", statefulset=~\"cluster-.*\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "ClickHouse - Deployed Version(s)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Active Version - clickhouse-server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(\n    kube_pod_container_info{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", container=\"clickhouse-server\"}\n) by (image)\n",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "Active Version - clickhouse-keeper",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(\n    kube_pod_container_info{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", container=\"clickhouse-keeper\"}\n) by (image)\n",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  { "title": "ClickHouse - CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "CPU (cores) - Server",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "sum(\n    rate(container_cpu_usage_seconds_total{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", container=\"clickhouse-server\"}[2m])\n) by (pod)\n",
     "legendFormat": "usage: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", resource=\"cpu\", container=\"clickhouse-server\"}\n",
     "legendFormat": "limit: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", resource=\"cpu\", container=\"clickhouse-server\"}\n",
     "legendFormat": "request: {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU (cores) - Keeper",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 101 },
   "targets": [
    {
     "expr": "sum(\n    rate(container_cpu_usage_seconds_total{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", container=\"clickhouse-keeper\"}[2m])\n) by (pod)\n",
     "legendFormat": "usage: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", resource=\"cpu\", container=\"clickhouse-keeper\"}\n",
     "legendFormat": "limit: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", resource=\"cpu\", container=\"clickhouse-keeper\"}\n",
     "legendFormat": "request: {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU (cores) - ZK Exporter",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 101 },
   "targets": [
    {
     "expr": "sum(\n    rate(container_cpu_usage_seconds_total{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", container=\"zookeeper-exporter\"}[2m])\n) by (pod)\n",
     "legendFormat": "usage: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", resource=\"cpu\", container=\"zookeeper-exporter\"}\n",
     "legendFormat": "limit: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", resource=\"cpu\", container=\"zookeeper-exporter\"}\n",
     "legendFormat": "request: {{ pod }}"
    }
   ]
  },
  {
   "title": "Throttled % - Server",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 113 },
   "targets": [
    {
     "expr": "100*(\n    sum(\n        rate(container_cpu_cfs_throttled_periods_total{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", container=\"clickhouse-server\"}[2m])\n    ) by (pod)\n    /\n    sum(\n        rate(container_cpu_cfs_periods_total{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", container=\"clickhouse-server\"}[2m])\n    ) by (pod)\n)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Throttled % - Keeper",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 113 },
   "targets": [
    {
     "expr": "100*(\n    sum(\n        rate(container_cpu_cfs_throttled_periods_total{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", container=\"clickhouse-keeper\"}[2m])\n    ) by (pod)\n    /\n    sum(\n        rate(container_cpu_cfs_periods_total{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", container=\"clickhouse-keeper\"}[2m])\n    ) by (pod)\n)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Throttled % - ZK Exporter",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 113 },
   "targets": [
    {
     "expr": "100*(\n    sum(\n        rate(container_cpu_cfs_throttled_periods_total{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", container=\"zookeeper-exporter\"}[2m])\n    ) by (pod)\n    /\n    sum(\n        rate(container_cpu_cfs_periods_total{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", container=\"zookeeper-exporter\"}[2m])\n    ) by (pod)\n)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "ClickHouse - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "Memory (GB) - Server",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 201 },
   "targets": [
    {
     "expr": "sum(\n    rate(container_memory_working_set_bytes{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", container=\"clickhouse-server\"}[2m])\n) by (pod) / (1024*1024*1024)\n",
     "legendFormat": "usage: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", resource=\"memory\", container=\"clickhouse-server\"} / (1024*1024*1024)\n",
     "legendFormat": "limit: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", resource=\"memory\", container=\"clickhouse-server\"} / (1024*1024*1024)\n",
     "legendFormat": "request: {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory (GB) - Keeper",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 201 },
   "targets": [
    {
     "expr": "sum(\n    rate(container_memory_working_set_bytes{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", container=\"clickhouse-keeper\"}[2m])\n) by (pod) / (1024*1024*1024)\n",
     "legendFormat": "usage: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", resource=\"memory\", container=\"clickhouse-keeper\"} / (1024*1024*1024)\n",
     "legendFormat": "limit: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", resource=\"memory\", container=\"clickhouse-keeper\"} / (1024*1024*1024)\n",
     "legendFormat": "request: {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory (GB) - ZK Exporter",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 201 },
   "targets": [
    {
     "expr": "sum(\n    rate(container_memory_working_set_bytes{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", container=\"zookeeper-exporter\"}[2m])\n) by (pod) / (1024*1024*1024)\n",
     "legendFormat": "usage: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", resource=\"memory\", container=\"zookeeper-exporter\"} / (1024*1024*1024)\n",
     "legendFormat": "limit: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"cluster-.*\", resource=\"memory\", container=\"zookeeper-exporter\"} / (1024*1024*1024)\n",
     "legendFormat": "request: {{ pod }}"
    }
   ]
  },
  { "title": "ClickHouse - Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 } },
  {
   "title": "Volume Size (GB) - Data",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 301 },
   "yaxes": [
    { "format": "GB" }
   ],
   "targets": [
    {
     "expr": "sum(\n    kubelet_volume_stats_used_bytes{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\"data-cluster-.*\"}\n) by (persistentvolumeclaim) / (1024*1024*1024)\n",
     "legendFormat": "used: {{ persistentvolumeclaim }}"
    },
    {
     "expr": "sum(\n    kubelet_volume_stats_capacity_bytes{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\"data-cluster-.*\"}\n) by (persistentvolumeclaim) / (1024*1024*1024)\n",
     "legendFormat": "capacity: {{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Volume Size (GB) - Logs",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 301 },
   "yaxes": [
    { "format": "GB" }
   ],
   "targets": [
    {
     "expr": "sum(\n    kubelet_volume_stats_used_bytes{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\"logs-cluster-.*\"}\n) by (persistentvolumeclaim) / (1024*1024*1024)\n",
     "legendFormat": "used: {{ persistentvolumeclaim }}"
    },
    {
     "expr": "sum(\n    kubelet_volume_stats_capacity_bytes{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\"logs-cluster-.*\"}\n) by (persistentvolumeclaim) / (1024*1024*1024)\n",
     "legendFormat": "capacity: {{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Volume Size (GB) - Keeper Logs",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 301 },
   "yaxes": [
    { "format": "GB" }
   ],
   "targets": [
    {
     "expr": "sum(\n    kubelet_volume_stats_used_bytes{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\"keeper-logs-cluster-.*\"}\n) by (persistentvolumeclaim) / (1024*1024*1024)\n",
     "legendFormat": "used: {{ persistentvolumeclaim }}"
    },
    {
     "expr": "sum(\n    kubelet_volume_stats_capacity_bytes{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\"keeper-logs-cluster-.*\"}\n) by (persistentvolumeclaim) / (1024*1024*1024)\n",
     "legendFormat": "capacity: {{ persistentvolumeclaim }}"
    }
   ]
  },
  { "title": "ClickHouse - Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 } },
  {
   "title": "Number of read-only replicas",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 401 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_ReadonlyReplica{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\"}\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Number of detached parts",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 401 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_NumberOfDetachedParts{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\"}\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}