{
 "title": "observability: Data Ingestion",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7867191950 at Thu Sep 19 12:03:55 UTC 2024",
 "tags": [
  "managed",
  "observability",
  "gitlab-observability"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "environment", "label": "Environment", "query": "gstg,gprd" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(analytics_events_total_count{env=\"$environment\", cluster=~\"opstrace-.*\"}, namespace_id)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(analytics_events_total_count{env=\"$environment\", cluster=~\"opstrace-.*\"}, project_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of events ingested per environment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(analytics_events_total_count{env=\"$environment\"}) by (env)\n",
     "legendFormat": "{{feature_name}}"
    }
   ]
  },
  {
   "title": "Number of events ingested per feature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }
  },
  {
   "title": "Metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(analytics_events_total_count{feature_name=\"metrics\", env=\"$environment\"}) by (feature_name)\n",
     "legendFormat": "{{feature_name}}"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(analytics_events_total_count{feature_name=\"tracing\", env=\"$environment\"}) by (feature_name)\n",
     "legendFormat": "{{feature_name}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(analytics_events_total_count{feature_name=\"logging\", env=\"$environment\"}) by (feature_name)\n",
     "legendFormat": "{{feature_name}}"
    }
   ]
  },
  {
   "title": "Error Tracking",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(analytics_events_total_count{feature_name=\"errortracking\", env=\"$environment\"}) by (feature_name)\n",
     "legendFormat": "{{feature_name}}"
    }
   ]
  },
  { "title": "Top event producers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "Top 10 by namespace",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(analytics_events_total_count{env=\"$environment\"}) by (feature_name, namespace_id))\n",
     "legendFormat": "{{feature_name}} - {{namespace_id}}"
    }
   ]
  },
  {
   "title": "Top 10 by project",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 201 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(analytics_events_total_count{env=\"$environment\"}) by (feature_name, project_id))\n",
     "legendFormat": "{{feature_name}} - {{project_id}}"
    }
   ]
  },
  {
   "title": "Number of events ingested by project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 }
  },
  {
   "title": "Metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 301 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(analytics_events_total_count{feature_name=\"metrics\", env=\"$environment\", project_id=\"$project\"}) by (feature_name, project_id)\n",
     "legendFormat": "{{project_id}}"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 301 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(analytics_events_total_count{feature_name=\"tracing\", env=\"$environment\", project_id=\"$project\"}) by (feature_name, project_id)\n",
     "legendFormat": "{{project_id}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 301 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(analytics_events_total_count{feature_name=\"logging\", env=\"$environment\", project_id=\"$project\"}) by (feature_name, project_id)\n",
     "legendFormat": "{{project_id}}"
    }
   ]
  },
  {
   "title": "Error Tracking",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 301 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(analytics_events_total_count{feature_name=\"errortracking\", env=\"$environment\", project_id=\"$project\"}) by (feature_name, project_id)\n",
     "legendFormat": "{{project_id}}"
    }
   ]
  }
 ]
}