{
 "title": "observability: Errortracking API",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7867191950 at Thu Sep 19 12:03:55 UTC 2024",
 "tags": [
  "managed",
  "observability",
  "gitlab-observability"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "environment", "label": "Environment", "query": "gstg,gprd" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_container_info{env=\"$environment\", cluster=~\"opstrace-.*\"}, cluster)"
   },
   { "name": "namespace", "label": "Environment", "query": "default" },
   { "name": "Node", "label": "Node", "query": "gke-" },
   { "name": "Deployment", "query": "errortracking" }
  ]
 },
 "panels": [
  { "title": "Deployed version(s)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active version",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(\n    kube_pod_container_info{cluster=\"$cluster\",env=\"$environment\",namespace=\"default\", pod=~\"errortracking-api.*\"}\n) by (image)\n",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "Up",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\",env=\"$environment\",namespace=\"default\", job=\"errortracking-api\", endpoint=\"metrics\"}\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Ready replicas",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{cluster=\"$cluster\",env=\"$environment\",namespace=\"default\", statefulset=\"errortracking-api\"}\n",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  { "title": "Deployment Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Deployment CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(\n  rate(\n    container_cpu_usage_seconds_total{cluster=\"$cluster\",env=\"$environment\", pod=~\"errortracking-api.*\"}[2m]\n  )\n)\n/\nsum(machine_cpu_cores{cluster=\"$cluster\",env=\"$environment\", node=~\"gke-.*\"})\n"
    }
   ]
  },
  {
   "title": "Deployment Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(container_memory_working_set_bytes{cluster=\"$cluster\",env=\"$environment\",namespace=\"default\", pod=~\"errortracking-api.*\"})\n/\nsum(kube_node_status_allocatable{resource=\"memory\", unit= \"byte\", env=~\"$environment\", node=~\"gke-.*\"})\n"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    container_cpu_usage_seconds_total{cluster=\"$cluster\",env=\"$environment\",namespace=\"default\", pod=~\"errortracking-api.*\"}[1m]\n  )\n) by (pod,node)\n",
     "legendFormat": "real: {{ pod }}"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{cluster=\"$cluster\",env=\"$environment\",namespace=\"default\", resource=\"cpu\", unit=\"core\", pod=~\"errortracking-api.*\"}\n) by (pod,node)\n",
     "legendFormat": "rqst: {{ pod }}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 } },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 301 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{cluster=\"$cluster\",env=\"$environment\",namespace=\"default\", pod=~\"errortracking-api.*\", container=\"errortracking-api\"}\n) by (pod)\n",
     "legendFormat": "real: {{ pod }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 } },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 401 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", id!=\"/\",pod=~\"^$Deployment.*$\"}[1m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum( rate (container_network_transmit_bytes_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", id!=\"/\",pod=~\"^$Deployment.*$\"}[1m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 401 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", id!=\"/\",pod=~\"^$Deployment.*$\"}[1m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum( rate (container_network_transmit_bytes_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", id!=\"/\",pod=~\"^$Deployment.*$\"}[1m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 } },
  {
   "title": "Requests per second by HTTP status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 601 },
   "yaxes": [
    { "format": "short", "label": "req/sec" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    http_requests_duration_seconds_count{cluster=\"$cluster\",env=\"$environment\",namespace=\"default\", pod=~\"errortracking-api.*\"}[$__rate_interval]\n  )\n) by (code) > 0\n",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Requests duration by HTTP status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 601 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (code, le) (\n  rate(http_requests_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"errortracking-api.*\"}[$__interval])\n))\n",
     "legendFormat": "HTTP {{code}} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (code, le) (\n  rate(http_requests_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"errortracking-api.*\"}[$__interval])\n))\n",
     "legendFormat": "HTTP {{code}} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (code, le) (\n  rate(http_requests_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"errortracking-api.*\"}[$__interval])\n))\n",
     "legendFormat": "HTTP {{code}} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (code, le) (\n  rate(http_requests_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"errortracking-api.*\"}[$__interval])\n))\n",
     "legendFormat": "HTTP {{code}} p99"
    }
   ]
  },
  {
   "title": "Requests per second by path",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 611 },
   "yaxes": [
    { "format": "short", "label": "req/sec" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    http_requests_duration_seconds_count{cluster=\"$cluster\",env=\"$environment\",namespace=\"default\", pod=~\"errortracking-api.*\"}[$__rate_interval]\n  )\n) by (path) > 0\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests duration by path",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 611 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (path, le) (\n  rate(http_requests_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"errortracking-api.*\"}[$__interval])\n))\n",
     "legendFormat": "{{path}} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (path, le) (\n  rate(http_requests_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"errortracking-api.*\"}[$__interval])\n))\n",
     "legendFormat": "{{path}} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (path, le) (\n  rate(http_requests_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"errortracking-api.*\"}[$__interval])\n))\n",
     "legendFormat": "{{path}} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (path, le) (\n  rate(http_requests_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"errortracking-api.*\"}[$__interval])\n))\n",
     "legendFormat": "{{path}} p99"
    }
   ]
  },
  {
   "title": "Response Error Rate by Method and Path",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 621 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, path) (\n  rate(\n    http_requests_duration_seconds_count{cluster=\"$cluster\",env=\"$environment\",namespace=\"default\", pod=~\"errortracking-api.*\", code =~ \"[4-5].*\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ method }} {{ path }}"
    }
   ]
  },
  { "title": "Project-specific telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 700 } },
  {
   "title": "Envelope requests by project ID",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 701 },
   "yaxes": [
    { "format": "short", "label": "req/sec" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    project_envelope_total{cluster=\"$cluster\",env=\"$environment\",namespace=\"default\", pod=~\"errortracking-api.*\"}[$__rate_interval]\n  )\n) by (projectID)\n",
     "legendFormat": "{{projectID}}"
    }
   ]
  },
  {
   "title": "Get error requests by project ID",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 701 },
   "yaxes": [
    { "format": "short", "label": "req/sec" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    project_get_error_total{cluster=\"$cluster\",env=\"$environment\",namespace=\"default\", pod=~\"errortracking-api.*\"}[$__rate_interval]\n  )\n) by (projectID)\n",
     "legendFormat": "{{projectID}}"
    }
   ]
  },
  {
   "title": "List errors requests by project ID",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 701 },
   "yaxes": [
    { "format": "short", "label": "req/sec" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    project_list_errors_total{cluster=\"$cluster\",env=\"$environment\",namespace=\"default\", pod=~\"errortracking-api.*\"}[$__rate_interval]\n  )\n) by (projectID)\n",
     "legendFormat": "{{projectID}}"
    }
   ]
  },
  {
   "title": "List events requests by project ID",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 711 },
   "yaxes": [
    { "format": "short", "label": "req/sec" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    project_list_events_total{cluster=\"$cluster\",env=\"$environment\",namespace=\"default\", pod=~\"errortracking-api.*\"}[$__rate_interval]\n  )\n) by (projectID)\n",
     "legendFormat": "{{projectID}}"
    }
   ]
  },
  {
   "title": "Store requests by project ID",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 711 },
   "yaxes": [
    { "format": "short", "label": "req/sec" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    project_store_total{cluster=\"$cluster\",env=\"$environment\",namespace=\"default\", pod=~\"errortracking-api.*\"}[$__rate_interval]\n  )\n) by (projectID)\n",
     "legendFormat": "{{projectID}}"
    }
   ]
  }
 ]
}