{
 "title": "ci-partitioning: CI data partitions tracking",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8397766929 at Mon Nov 18 09:15:12 UTC 2024",
 "tags": [
  "managed",
  "ci-partitioning",
  "type:ci-runners",
  "managed"
 ],
 "time": { "from": "now-3h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "type",
    "query": "label_values(gitlab_runner_version_info{job=~\"runners-manager|scrapeConfig/monitoring/prometheus-agent-runner\", environment=\"$environment\"}, type)\n"
   },
   {
    "name": "shard",
    "query": "label_values(gitlab_runner_version_info{environment=~\"$environment\",stage=~\"$stage\",type=~\"$type\",shard!=\"default\"}, shard)\n"
   },
   {
    "name": "runner_manager",
    "query": "query_result(label_replace(gitlab_runner_version_info{environment=~\"$environment\",stage=~\"$stage\",shard=~\"$shard\"}, \"fqdn\", \"$1.*\", \"instance\", \"([^:]*)(:[0-9]+)?$\"))\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  },
  { "title": "Current partition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Pipeline creation",
   "type": "graph",
   "description": "Number of pipelines created per partition",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pipelines_created_total{environment=\"$environment\"}[$__interval])) by (partition_id) != 0\n",
     "legendFormat": "{{ partition_id }}"
    }
   ]
  },
  { "title": "Table size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Table size for each partition",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(pg_total_relation_size_bytes{type=\"patroni-ci\", environment=\"$environment\", relname=~\"ci_build_names|ci_build_names_\\\\d+|ci_builds|ci_builds_\\\\d+|ci_builds_execution_configs|ci_builds_execution_configs_\\\\d+|ci_builds_metadata|ci_builds_metadata_\\\\d+|ci_job_annotations|ci_job_annotations_\\\\d+|ci_job_artifacts|ci_job_artifacts_\\\\d+|ci_pipeline_variables|ci_pipeline_variables_\\\\d+|ci_pipelines|ci_pipelines_\\\\d+|ci_runner_machine_builds|ci_runner_machine_builds_\\\\d+|ci_stages|ci_stages_\\\\d+\"}) by (relname)\n",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Partition growth rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2001 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "max(rate(pg_total_relation_size_bytes{type=\"patroni-ci\", environment=\"$environment\", relname=~\"ci_build_names|ci_build_names_\\\\d+|ci_builds|ci_builds_\\\\d+|ci_builds_execution_configs|ci_builds_execution_configs_\\\\d+|ci_builds_metadata|ci_builds_metadata_\\\\d+|ci_job_annotations|ci_job_annotations_\\\\d+|ci_job_artifacts|ci_job_artifacts_\\\\d+|ci_pipeline_variables|ci_pipeline_variables_\\\\d+|ci_pipelines|ci_pipelines_\\\\d+|ci_runner_machine_builds|ci_runner_machine_builds_\\\\d+|ci_stages|ci_stages_\\\\d+\"}[$__interval])) by (relname)\n",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Database nodes query stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 } },
  {
   "title": "Total Time in Queries per Node",
   "type": "graph",
   "description": "Total number of seconds spent by pgbouncer when actively connected to PostgreSQL, executing queries - stats.total_query_time",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_queries_duration_seconds_total{type=\"patroni-ci\", environment=\"$environment\"}[$__interval])) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Time in Transaction per Server",
   "type": "graph",
   "description": "Total number of seconds spent by pgbouncer when connected to PostgreSQL in a transaction, either idle in transaction or executing queries - stats.total_xact_time",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3001 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_server_in_transaction_seconds_total{type=\"patroni-ci\", environment=\"$environment\"}[$__interval])) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  { "title": "Database nodes CPU stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4000 } },
  {
   "title": "Node CPU",
   "type": "graph",
   "description": "The amount of non-idle time consumed by nodes for this service",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4001 },
   "yaxes": [
    { "format": "percentunit", "label": "Average CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "avg(instance:node_cpu_utilization:ratio{type=\"patroni-ci\", environment=\"$environment\"}) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Node Maximum Single Core Utilization",
   "type": "graph",
   "description": "The maximum utilization of a single core on each node. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4001 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(max(1 - rate(node_cpu_seconds_total{type=\"patroni-ci\", environment=\"$environment\", mode=\"idle\"}[$__interval])) by (fqdn)\n,1),0)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  { "title": "Autovacuum stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5000 } },
  {
   "title": "Autovacuum age",
   "type": "graph",
   "description": "Total number of seconds spent vacuuming the tables",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5001 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_activity_autovacuum_age_in_seconds{type=\"patroni-ci\", environment=\"$environment\", relname!~\".*\\\\(to prevent wraparound\\\\)\"} / 3600) by(relname)\n",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Wraparound autovacuum age",
   "type": "graph",
   "description": "Total number of seconds spent vacuuming the tables in transaction wraparound prevention mode",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5001 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_activity_autovacuum_age_in_seconds{type=\"patroni-ci\", environment=\"$environment\", relname=~\".*\\\\(to prevent wraparound\\\\)\"} / 3600) by(relname)\n",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Tuple stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6000 } },
  {
   "title": "Dead tuples",
   "type": "graph",
   "description": "Total number of dead tuples per table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_user_tables_n_dead_tup{type=\"patroni-ci\", environment=\"$environment\", relname=~\"ci_build_names|ci_build_names_\\\\d+|ci_builds|ci_builds_\\\\d+|ci_builds_execution_configs|ci_builds_execution_configs_\\\\d+|ci_builds_metadata|ci_builds_metadata_\\\\d+|ci_job_annotations|ci_job_annotations_\\\\d+|ci_job_artifacts|ci_job_artifacts_\\\\d+|ci_pipeline_variables|ci_pipeline_variables_\\\\d+|ci_pipelines|ci_pipelines_\\\\d+|ci_runner_machine_builds|ci_runner_machine_builds_\\\\d+|ci_stages|ci_stages_\\\\d+\"}[$__interval])) by(relname) != 0\n",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Live tuples",
   "type": "graph",
   "description": "Total number of live tuples per table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_user_tables_n_live_tup{type=\"patroni-ci\", environment=\"$environment\", relname=~\"ci_build_names|ci_build_names_\\\\d+|ci_builds|ci_builds_\\\\d+|ci_builds_execution_configs|ci_builds_execution_configs_\\\\d+|ci_builds_metadata|ci_builds_metadata_\\\\d+|ci_job_annotations|ci_job_annotations_\\\\d+|ci_job_artifacts|ci_job_artifacts_\\\\d+|ci_pipeline_variables|ci_pipeline_variables_\\\\d+|ci_pipelines|ci_pipelines_\\\\d+|ci_runner_machine_builds|ci_runner_machine_builds_\\\\d+|ci_stages|ci_stages_\\\\d+\"}[$__interval])) by(relname) != 0\n",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Tuple ops rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7000 } },
  {
   "title": "Tuple inserts",
   "type": "graph",
   "description": "Number of records inserted for each table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_user_tables_n_tup_ins{type=\"patroni-ci\", environment=\"$environment\", relname=~\"ci_build_names|ci_build_names_\\\\d+|ci_builds|ci_builds_\\\\d+|ci_builds_execution_configs|ci_builds_execution_configs_\\\\d+|ci_builds_metadata|ci_builds_metadata_\\\\d+|ci_job_annotations|ci_job_annotations_\\\\d+|ci_job_artifacts|ci_job_artifacts_\\\\d+|ci_pipeline_variables|ci_pipeline_variables_\\\\d+|ci_pipelines|ci_pipelines_\\\\d+|ci_runner_machine_builds|ci_runner_machine_builds_\\\\d+|ci_stages|ci_stages_\\\\d+\"}[$__interval])) by (relname) != 0\n",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Tuple updates",
   "type": "graph",
   "description": "Number of records updated for each table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_user_tables_n_tup_upd{type=\"patroni-ci\", environment=\"$environment\", relname=~\"ci_build_names|ci_build_names_\\\\d+|ci_builds|ci_builds_\\\\d+|ci_builds_execution_configs|ci_builds_execution_configs_\\\\d+|ci_builds_metadata|ci_builds_metadata_\\\\d+|ci_job_annotations|ci_job_annotations_\\\\d+|ci_job_artifacts|ci_job_artifacts_\\\\d+|ci_pipeline_variables|ci_pipeline_variables_\\\\d+|ci_pipelines|ci_pipelines_\\\\d+|ci_runner_machine_builds|ci_runner_machine_builds_\\\\d+|ci_stages|ci_stages_\\\\d+\"}[$__interval])) by (relname) != 0\n",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Tuple deletes",
   "type": "graph",
   "description": "Number of records deleted for each table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_user_tables_n_tup_del{type=\"patroni-ci\", environment=\"$environment\", relname=~\"ci_build_names|ci_build_names_\\\\d+|ci_builds|ci_builds_\\\\d+|ci_builds_execution_configs|ci_builds_execution_configs_\\\\d+|ci_builds_metadata|ci_builds_metadata_\\\\d+|ci_job_annotations|ci_job_annotations_\\\\d+|ci_job_artifacts|ci_job_artifacts_\\\\d+|ci_pipeline_variables|ci_pipeline_variables_\\\\d+|ci_pipelines|ci_pipelines_\\\\d+|ci_runner_machine_builds|ci_runner_machine_builds_\\\\d+|ci_stages|ci_stages_\\\\d+\"}[$__interval])) by (relname) != 0\n",
     "legendFormat": "{{ relname }}"
    }
   ]
  }
 ]
}