{
 "title": "git: Rails Controller",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8245226639 at Fri Nov  1 04:32:43 UTC 2024",
 "tags": [
  "managed",
  "git",
  "type:git",
  "detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "type", "query": "git" },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "controller",
    "query": "label_values(controller_action:gitlab_transaction_duration_seconds_count:rate1m{environment=\"$environment\", type=\"$type\"}, controller)"
   },
   {
    "name": "action",
    "query": "label_values(controller_action:gitlab_transaction_duration_seconds_count:rate1m{environment=\"$environment\", type=\"$type\", controller=\"$controller\"}, action)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (avg_over_time(controller_action:gitlab_transaction_duration_seconds_count:rate1m{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval]))",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (controller, action) (avg_over_time(controller_action:gitlab_transaction_duration_seconds:p99{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval]))",
     "legendFormat": "{{ action }} - p99"
    },
    {
     "expr": "avg by (controller, action) (avg_over_time(controller_action:gitlab_transaction_duration_seconds:p95{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval]))",
     "legendFormat": "{{ action }} - p95"
    },
    {
     "expr": "sum by (controller, action) (avg_over_time(controller_action:gitlab_transaction_duration_seconds_sum:rate1m{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval]))\n/\nsum by (controller, action) (avg_over_time(controller_action:gitlab_transaction_duration_seconds_count:rate1m{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval]))\n",
     "legendFormat": "{{ action }} - mean"
    }
   ]
  },
  { "title": "SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 201 } },
  {
   "title": "Total SQL Queries Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (action) (\n  rate(\n    gitlab_transaction_db_count_total{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval]\n  )\n)\n",
     "legendFormat": "Total - {{ action }}"
    },
    {
     "expr": "sum by (action) (\n  rate(\n    gitlab_transaction_db_primary_count_total{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval]\n  )\n)\n",
     "legendFormat": "Primary - {{ action }}"
    },
    {
     "expr": "sum by (action) (\n  rate(\n    gitlab_transaction_db_replica_count_total{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval]\n  )\n)\n",
     "legendFormat": "Replica - {{ action }}"
    }
   ]
  },
  {
   "title": "SQL Requests per Controller Request",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (action) (\n  rate(gitlab_sql_duration_seconds_count{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval])\n)\n/\nsum by (action) (\n  avg_over_time(\n    controller_action:gitlab_transaction_duration_seconds_count:rate1m{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval]\n  )\n)\n",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "SQL Latency per Controller Request",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 202 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (avg_over_time(controller_action:gitlab_sql_duration_seconds_sum:rate1m{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval]))\n/\nsum by (controller, action) (avg_over_time(controller_action:gitlab_transaction_duration_seconds_count:rate1m{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval]))\n",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "SQL Latency per SQL Request",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 202 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (action) (\n  rate(gitlab_sql_duration_seconds_sum{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval])\n)\n/\nsum by (action) (\n  rate(gitlab_sql_duration_seconds_count{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval])\n)\n",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  { "title": "SQL Transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 301 } },
  {
   "title": "SQL Transactions per Controller Request",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 302 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (action) (\n  rate(gitlab_database_transaction_seconds_count{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval])\n)\n",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Average Duration per SQL Transaction",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 302 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_database_transaction_seconds_sum{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval])) by (action)\n/\nsum(rate(gitlab_database_transaction_seconds_count{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval])) by (action)\n",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 401 } },
  {
   "title": "Cache Operations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 402 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (action, operation) (\n  rate(gitlab_cache_operations_total{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval])\n)\n",
     "legendFormat": "{{ action }} - {{ operation }}"
    }
   ]
  },
  { "title": "Elasticsearch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 501 } },
  {
   "title": "Elasticsearch Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 502 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (controller, action, le) (\n  rate(http_elasticsearch_requests_duration_seconds_bucket{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval])\n))\n",
     "legendFormat": "{{ action }} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (controller, action, le) (\n  rate(http_elasticsearch_requests_duration_seconds_bucket{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval])\n))\n",
     "legendFormat": "{{ action }} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (controller, action, le) (\n  rate(http_elasticsearch_requests_duration_seconds_bucket{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval])\n))\n",
     "legendFormat": "{{ action }} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (controller, action, le) (\n  rate(http_elasticsearch_requests_duration_seconds_bucket{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval])\n))\n",
     "legendFormat": "{{ action }} p99"
    }
   ]
  },
  { "title": "External HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 601 } },
  {
   "title": "External HTTP calls",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 602 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action, code) (\nrate(gitlab_external_http_total{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[$__interval])\n)\n",
     "legendFormat": "{{ action }} - {{ code }}"
    }
   ]
  },
  {
   "title": "External HTTP Latency per call",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 602 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum(\n    rate(\n      gitlab_external_http_duration_seconds_bucket{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[5m]\n    )\n  ) by (action, le)\n)\n",
     "legendFormat": "{{ action }} - p50"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum(\n    rate(\n      gitlab_external_http_duration_seconds_bucket{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[5m]\n    )\n  ) by (action, le)\n)\n",
     "legendFormat": "{{ action }} - p90"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(\n    rate(\n      gitlab_external_http_duration_seconds_bucket{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"git\"}[5m]\n    )\n  ) by (action, le)\n)\n",
     "legendFormat": "{{ action }} - p99"
    }
   ]
  },
  {
   "title": "Extra links",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 602 },
   "content": "The metrics displayed in this row indicate all the network requests made inside a Rails process via the HTTP protocol. The requests may be triggered by Gitlab::HTTP utility inside the application code base or by any 3rd-party gems. We don't differentiate the destinations. So, the metrics include both internal/external dependencies.\n* [📖 Kibana: External HTTP logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:exists,type:json.external_http_count,value:exists),query:(exists:(field:json.external_http_count)))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n"
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}