{
 "title": "git: Regional Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7927277014 at Thu Sep 26 12:04:13 UTC 2024",
 "tags": [
  "managed",
  "git",
  "type:git",
  "regional"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "Regional Service Aggregated  Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_regional_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"git\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"git\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "Regional Service Aggregated  Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_regional_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"git\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"git\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "Regional Service Aggregated  RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_regional_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  { "title": "🔬 Regional SLIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "gitlab_shell SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"gitlab_shell\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1001 },
   "content": "### Description\n\nWe monitor GitLab shell, using HAProxy 2 SSH connection information.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: GitLab Shell logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.command,json.msg,json.level,json.gl_project_path,json.error),filters:!((meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),index:'AWORyp9K1NBBQZg_dXA9')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: GitLab Shell failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.command,json.msg,json.level,json.gl_project_path,json.error),filters:!((meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase)))),(meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.level,params:error,type:phrase),query:(match:(json.level:(query:error,type:phrase))))),index:'AWORyp9K1NBBQZg_dXA9')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: GitLab Shell requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWORyp9K1NBBQZg_dXA9&_a=(filters:!((meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: GitLab Shell failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWORyp9K1NBBQZg_dXA9&_a=(filters:!((meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase)))),(meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.level,params:error,type:phrase),query:(match:(json.level:(query:error,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "gitlab_sshd SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1011 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"gitlab_sshd\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"gitlab_sshd\",monitor=\"global\",type=\"git\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"gitlab_sshd\",monitor=\"global\",type=\"git\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "gitlab_sshd SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1011 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"gitlab_sshd\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_sshd\",monitor=\"global\",type=\"git\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_sshd\",monitor=\"global\",type=\"git\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "gitlab_sshd SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1011 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"gitlab_sshd\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1011 },
   "content": "### Description\n\nMonitors Gitlab-sshd, using the connections bucket, and http requests bucket.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: GitLab Shell logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.command,json.msg,json.level,json.gl_project_path,json.error),filters:!((meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),index:'AWORyp9K1NBBQZg_dXA9')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: GitLab Shell failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.command,json.msg,json.level,json.gl_project_path,json.error),filters:!((meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase)))),(meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.level,params:error,type:phrase),query:(match:(json.level:(query:error,type:phrase))))),index:'AWORyp9K1NBBQZg_dXA9')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: GitLab Shell requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWORyp9K1NBBQZg_dXA9&_a=(filters:!((meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: GitLab Shell failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWORyp9K1NBBQZg_dXA9&_a=(filters:!((meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase)))),(meta:(index:'AWORyp9K1NBBQZg_dXA9',key:json.level,params:error,type:phrase),query:(match:(json.level:(query:error,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "loadbalancer SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1021 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"git\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"git\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "loadbalancer SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1021 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1021 },
   "content": "### Description\n\nMeasures aggregated HTTP request traffic through the HAProxy.\n5xx responses are considered to be failures.\n\n\n\n### Observability Tools\n\n* [BigQuery: Top http clients by number of requests, cny stage, 10m](https://console.cloud.google.com/bigquery?project=gitlab-production&sq=805818759045:dea839bd669e41b5bc264c510294bb9f)\n* [BigQuery: Top http clients by number of requests, main stage, 10m](https://console.cloud.google.com/bigquery?project=gitlab-production&sq=805818759045:704c6bdf00a743d195d344306bf207ee)\n\n"
  },
  {
   "title": "loadbalancer_ssh SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1031 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"loadbalancer_ssh\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer_ssh\",monitor=\"global\",type=\"git\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer_ssh\",monitor=\"global\",type=\"git\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "loadbalancer_ssh SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1031 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"loadbalancer_ssh\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1031 },
   "content": "### Description\n\nMeasures aggregated L4 traffic through the HAProxy. Traffic is measured in TCP connections,\nwith upstream TCP connection failures being treated as service-level failures.\n\n\n\n### Observability Tools\n\n* [BigQuery: Top ssh clients by number of requests, 10m](https://console.cloud.google.com/bigquery?project=gitlab-production&sq=805818759045:8a185b18fafe4081bf9fbdb5354844f9)\n\n"
  },
  {
   "title": "rails_request SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1041 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"git\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"git\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "rails_request SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1041 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"git\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"git\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "rails_request SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1041 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1041 },
   "content": "### Description\n\nThe number of requests meeting their duration target based on the urgency\nof the endpoint. By default, a request should take no more than 1s. But\nthis can be adjusted by endpoint.\n\nRead more about this in the [documentation](https://docs.gitlab.com/ee/development/application_slis/rails_request_apdex.html).\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:exists,type:json.target_duration_s,value:exists),query:(exists:(field:json.target_duration_s))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:exists,type:json.duration_s,value:exists),query:(exists:(field:json.duration_s))),!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"script\":+{\"script\":+{\"source\":+\"doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value\"}}}]}}'),query:(bool:(minimum_should_match:1,should:!((script:(script:(source:'doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value'))))))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase)))),(meta:(field:json.status,index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase)))),(meta:(field:json.status,index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "workhorse SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1051 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse\",monitor=\"global\",type=\"git\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse\",monitor=\"global\",type=\"git\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "workhorse SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1051 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"workhorse\",monitor=\"global\",type=\"git\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"workhorse\",monitor=\"global\",type=\"git\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "workhorse SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1051 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1051 },
   "content": "### Description\n\nMonitors the Workhorse instance running in the Git fleet, via the HTTP interface. This SLI\nexcludes API requests, which have their own SLI with tigher latency thresholds.\nWebsocket connections are excluded from the apdex score.\n\n\n\n### Observability Tools\n\n* [Google Stackdriver Continuous Profiling](https://console.cloud.google.com/profiler;timespan=4h/workhorse-git;type=CPU/cpu?project=gitlab-production)\n* [🐞 Sentry Releases](https://new-sentry.gitlab.net/organizations/gitlab/releases/?project=15&environment=${environment})\n* [🐞 Sentry issues](https://new-sentry.gitlab.net/organizations/gitlab/issues/?project=15&environment=${environment})\n* [📖 Kibana: Workhorse logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.remote_ip,json.status,json.uri,json.duration_ms),filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Workhorse slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.remote_ip,json.status,json.uri,json.duration_ms),filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase)))),(meta:(field:json.duration_ms,index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.duration_ms,params:(gte:10000,lte:!n),type:range),query:(range:(json.duration_ms:(gte:10000,lte:!n))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4',sort:!(!(json.duration_ms,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Workhorse failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.remote_ip,json.status,json.uri,json.duration_ms),filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase)))),(meta:(field:json.status,index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase)))),(meta:(field:json.status,index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_ms),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "workhorse_auth_api SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1061 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"workhorse_auth_api\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse_auth_api\",monitor=\"global\",type=\"git\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse_auth_api\",monitor=\"global\",type=\"git\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "workhorse_auth_api SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1061 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"workhorse_auth_api\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"workhorse_auth_api\",monitor=\"global\",type=\"git\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"workhorse_auth_api\",monitor=\"global\",type=\"git\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "workhorse_auth_api SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1061 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"workhorse_auth_api\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1061 },
   "content": "### Description\n\nMonitors Workhorse API endpoints, running in the Git fleet, via the HTTP interface.\nWorkhorse API requests have much tigher latency requirements, as these requests originate in GitLab-Shell\nand are on the critical path for authentication of Git SSH commands.\n\n\n\n### Observability Tools\n\n* [Google Stackdriver Continuous Profiling](https://console.cloud.google.com/profiler;timespan=4h/workhorse-git;type=CPU/cpu?project=gitlab-production)\n* [🐞 Sentry Releases](https://new-sentry.gitlab.net/organizations/gitlab/releases/?project=15&environment=${environment})\n* [🐞 Sentry issues](https://new-sentry.gitlab.net/organizations/gitlab/issues/?project=15&environment=${environment})\n* [📖 Kibana: Workhorse logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.remote_ip,json.status,json.uri,json.duration_ms),filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Workhorse slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.remote_ip,json.status,json.uri,json.duration_ms),filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase)))),(meta:(field:json.duration_ms,index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.duration_ms,params:(gte:10000,lte:!n),type:range),query:(range:(json.duration_ms:(gte:10000,lte:!n))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4',sort:!(!(json.duration_ms,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Workhorse failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.remote_ip,json.status,json.uri,json.duration_ms),filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase)))),(meta:(field:json.status,index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase)))),(meta:(field:json.status,index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:git,type:phrase),query:(match:(json.type.keyword:(query:git,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:git,type:phrase),query:(match:(json.type:(query:git,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_ms),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}