{
 "title": "api: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8245226639 at Fri Nov  1 04:32:32 UTC 2024",
 "tags": [
  "managed",
  "api",
  "gitlab",
  "type:api",
  "api",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "api Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "api apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"api\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"api\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "api apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"api\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "api Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "api Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "api error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"api\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"api\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "api error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"api\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "api Service | Errors"
    }
   ]
  },
  {
   "title": "api Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "api RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "global_search SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"global_search\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "global_search apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"global_search\",monitor=\"global\",type=\"api\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"global_search\",monitor=\"global\",type=\"api\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"global_search\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "global_search apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"global_search\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"global_search\",monitor=\"global\",type=\"api\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"global_search\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"global_search\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"global_search\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"global_search\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"global_search\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"global_search\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"global_search\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"global_search\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"global_search\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "global_search SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "global_search SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"global_search\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "global_search RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"global_search\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "content": "### Description\n\nThe number of Global Search search requests meeting their duration target based on the 99.95th percentile of\nthe search with the same parameters.\n\n"
  },
  {
   "title": "graphql_query SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"graphql_query\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "graphql_query apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"graphql_query\",monitor=\"global\",type=\"api\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"graphql_query\",monitor=\"global\",type=\"api\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"graphql_query\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "graphql_query apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"graphql_query\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"graphql_query\",monitor=\"global\",type=\"api\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:confidence:ratio_5m{component=\"graphql_query\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "Apdex SLI (upper 98% confidence boundary)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:confidence:ratio_1h{component=\"graphql_query\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:confidence:ratio_5m{component=\"graphql_query\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"graphql_query\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:confidence:ratio_1h{component=\"graphql_query\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"graphql_query\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:confidence:ratio_30m{component=\"graphql_query\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"graphql_query\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:confidence:ratio_6h{component=\"graphql_query\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"graphql_query\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "graphql_query SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "graphql_query SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"graphql_query\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "graphql_query error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"graphql_query\",monitor=\"global\",type=\"api\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"graphql_query\",monitor=\"global\",type=\"api\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"graphql_query\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "graphql_query error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"graphql_query\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"graphql_query\",monitor=\"global\",type=\"api\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:confidence:ratio_5m{component=\"graphql_query\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "Error SLI (lower 98% confidence boundary)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:confidence:ratio_1h{component=\"graphql_query\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:confidence:ratio_5m{component=\"graphql_query\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"graphql_query\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:confidence:ratio_1h{component=\"graphql_query\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"graphql_query\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:confidence:ratio_30m{component=\"graphql_query\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"graphql_query\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:confidence:ratio_6h{component=\"graphql_query\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"graphql_query\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "graphql_query SLI | Errors"
    }
   ]
  },
  {
   "title": "graphql_query SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"graphql_query\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "graphql_query RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"graphql_query\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "content": "### Description\n\nA GraphQL query is executed in the context of a request. An error does not\nalways result in a 5xx error. But could contain errors in the response.\nMutliple queries could be batched inside a single request.\n\nThis SLI counts all operations, a succeeded operation does not contain errors in\nit's response or return a 500 error.\n\nThe number of GraphQL queries meeting their duration target based on the urgency\nof the endpoint. By default, a query should take no more than 1s. We're working\non making the urgency customizable in [this epic](https://gitlab.com/groups/gitlab-org/-/epics/5841).\n\nWe're only taking known operations into account. Known operations are queries\ndefined in our codebase and originating from our frontend.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.meta.caller_id,json.operation_name,json.meta.feature_category,json.operation_fingerprint,json.duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.meta.caller_id,json.operation_name,json.meta.feature_category,json.operation_fingerprint,json.duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:exists,type:json.target_duration_s,value:exists),query:(exists:(field:json.target_duration_s))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:exists,type:json.duration_s,value:exists),query:(exists:(field:json.duration_s))),!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"script\":+{\"script\":+{\"source\":+\"doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value\"}}}]}}'),query:(bool:(minimum_should_match:1,should:!((script:(script:(source:'doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value'))))))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.meta.caller_id,json.operation_name,json.meta.feature_category,json.operation_fingerprint,json.duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase)))),(meta:(field:json.status,index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase)))),(meta:(field:json.status,index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "group_management SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"group_management\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "group_management error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"group_management\",monitor=\"global\",type=\"api\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"group_management\",monitor=\"global\",type=\"api\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"group_management\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "group_management error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"group_management\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"group_management\",monitor=\"global\",type=\"api\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:confidence:ratio_5m{component=\"group_management\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "Error SLI (lower 98% confidence boundary)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:confidence:ratio_1h{component=\"group_management\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:confidence:ratio_5m{component=\"group_management\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"group_management\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:confidence:ratio_1h{component=\"group_management\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"group_management\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:confidence:ratio_30m{component=\"group_management\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"group_management\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:confidence:ratio_6h{component=\"group_management\",confidence=\"98%\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"group_management\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "group_management SLI | Errors"
    }
   ]
  },
  {
   "title": "group_management SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"group_management\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "group_management RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"group_management\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "content": "### Description\n\nMeasures calls to the Groups API resource as the number of unsuccessful calls vs the number of total calls.\n\nAn alert on this SLI may indicate that users are unable to modify or create groups via the API.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.caller_id,params:!('PUT+/api/:version/groups/:id','POST+/api/:version/groups'),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.caller_id:'PUT+/api/:version/groups/:id')),(match_phrase:(json.meta.caller_id:'POST+/api/:version/groups')))))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.caller_id,params:!('PUT+/api/:version/groups/:id','POST+/api/:version/groups'),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.caller_id:'PUT+/api/:version/groups/:id')),(match_phrase:(json.meta.caller_id:'POST+/api/:version/groups')))))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:exists,type:json.target_duration_s,value:exists),query:(exists:(field:json.target_duration_s))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:exists,type:json.duration_s,value:exists),query:(exists:(field:json.duration_s))),!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"script\":+{\"script\":+{\"source\":+\"doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value\"}}}]}}'),query:(bool:(minimum_should_match:1,should:!((script:(script:(source:'doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value'))))))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.caller_id,params:!('PUT+/api/:version/groups/:id','POST+/api/:version/groups'),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.caller_id:'PUT+/api/:version/groups/:id')),(match_phrase:(json.meta.caller_id:'POST+/api/:version/groups')))))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase)))),(meta:(field:json.status,index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.caller_id,params:!('PUT+/api/:version/groups/:id','POST+/api/:version/groups'),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.caller_id:'PUT+/api/:version/groups/:id')),(match_phrase:(json.meta.caller_id:'POST+/api/:version/groups')))))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.caller_id,params:!('PUT+/api/:version/groups/:id','POST+/api/:version/groups'),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.caller_id:'PUT+/api/:version/groups/:id')),(match_phrase:(json.meta.caller_id:'POST+/api/:version/groups')))))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase)))),(meta:(field:json.status,index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.caller_id,params:!('PUT+/api/:version/groups/:id','POST+/api/:version/groups'),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.caller_id:'PUT+/api/:version/groups/:id')),(match_phrase:(json.meta.caller_id:'POST+/api/:version/groups')))))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.caller_id,params:!('PUT+/api/:version/groups/:id','POST+/api/:version/groups'),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.caller_id:'PUT+/api/:version/groups/:id')),(match_phrase:(json.meta.caller_id:'POST+/api/:version/groups')))))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.caller_id,params:!('PUT+/api/:version/groups/:id','POST+/api/:version/groups'),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.caller_id:'PUT+/api/:version/groups/:id')),(match_phrase:(json.meta.caller_id:'POST+/api/:version/groups')))))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.caller_id,params:!('PUT+/api/:version/groups/:id','POST+/api/:version/groups'),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.caller_id:'PUT+/api/:version/groups/:id')),(match_phrase:(json.meta.caller_id:'POST+/api/:version/groups')))))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "loadbalancer SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "loadbalancer error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"api\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"api\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "loadbalancer error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"api\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "loadbalancer SLI | Errors"
    }
   ]
  },
  {
   "title": "loadbalancer SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "loadbalancer RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "content": "### Description\n\nMeasures aggregated HTTP request traffic through the HAProxy.\n5xx responses are considered to be failures.\n\n\n\n### Observability Tools\n\n* [BigQuery: Main-stage: top paths for 5xx errors](https://console.cloud.google.com/bigquery?project=gitlab-production&sq=805818759045:342973e81d4a481d8055b43564d09728)\n\n"
  },
  {
   "title": "nginx_ingress SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"nginx_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "nginx_ingress error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"nginx_ingress\",monitor=\"global\",type=\"api\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"nginx_ingress\",monitor=\"global\",type=\"api\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"nginx_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "nginx_ingress error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"nginx_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"nginx_ingress\",monitor=\"global\",type=\"api\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"nginx_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"nginx_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"nginx_ingress\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"nginx_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"nginx_ingress\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"nginx_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"nginx_ingress\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"nginx_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"nginx_ingress\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "nginx_ingress SLI | Errors"
    }
   ]
  },
  {
   "title": "nginx_ingress SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"nginx_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "nginx_ingress RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"nginx_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "content": "### Description\n\nnginx for api\n\n\n\n### Observability Tools\n\n\n"
  },
  {
   "title": "rails_request SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "rails_request apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"api\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"api\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "rails_request apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"api\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "rails_request SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "rails_request SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 71 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "rails_request error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"api\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"api\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "rails_request error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"api\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "rails_request SLI | Errors"
    }
   ]
  },
  {
   "title": "rails_request SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "rails_request RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 71 },
   "content": "### Description\n\nThe number of requests meeting their duration target based on the urgency\nof the endpoint. By default, a request should take no more than 1s. But\nthis can be adjusted by endpoint.\n\nRead more about this in the [documentation](https://docs.gitlab.com/ee/development/application_slis/rails_request_apdex.html).\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:exists,type:json.target_duration_s,value:exists),query:(exists:(field:json.target_duration_s))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:exists,type:json.duration_s,value:exists),query:(exists:(field:json.duration_s))),!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"script\":+{\"script\":+{\"source\":+\"doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value\"}}}]}}'),query:(bool:(minimum_should_match:1,should:!((script:(script:(source:'doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value'))))))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase)))),(meta:(field:json.status,index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase)))),(meta:(field:json.status,index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "workhorse SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "workhorse apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse\",monitor=\"global\",type=\"api\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse\",monitor=\"global\",type=\"api\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "workhorse apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse\",monitor=\"global\",type=\"api\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse\",monitor=\"global\",type=\"api\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "workhorse SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "workhorse SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 81 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "workhorse error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"workhorse\",monitor=\"global\",type=\"api\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"workhorse\",monitor=\"global\",type=\"api\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "workhorse error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"workhorse\",monitor=\"global\",type=\"api\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"workhorse\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"workhorse\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"workhorse\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"workhorse\",monitor=\"global\",type=\"api\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "workhorse SLI | Errors"
    }
   ]
  },
  {
   "title": "workhorse SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "workhorse RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 81 },
   "content": "### Description\n\nAggregation of most web requests that pass through workhorse, monitored via the HTTP interface.\nExcludes health, readiness and liveness requests. Some known slow requests, such as HTTP uploads,\nare excluded from the apdex score.\n\n\n\n### Observability Tools\n\n* [Google Stackdriver Continuous Profiling](https://console.cloud.google.com/profiler;timespan=4h/workhorse-api;type=CPU/cpu?project=gitlab-production)\n* [🐞 Sentry Releases](https://new-sentry.gitlab.net/organizations/gitlab/releases/?project=15&environment=${environment})\n* [🐞 Sentry issues](https://new-sentry.gitlab.net/organizations/gitlab/issues/?project=15&environment=${environment})\n* [📖 Kibana: Workhorse logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.remote_ip,json.status,json.uri,json.duration_ms),filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:api,type:phrase),query:(match:(json.type.keyword:(query:api,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Workhorse slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.remote_ip,json.status,json.uri,json.duration_ms),filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:api,type:phrase),query:(match:(json.type.keyword:(query:api,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase)))),(meta:(field:json.duration_ms,index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.duration_ms,params:(gte:10000,lte:!n),type:range),query:(range:(json.duration_ms:(gte:10000,lte:!n))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4',sort:!(!(json.duration_ms,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Workhorse failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.remote_ip,json.status,json.uri,json.duration_ms),filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:api,type:phrase),query:(match:(json.type.keyword:(query:api,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase)))),(meta:(field:json.status,index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:api,type:phrase),query:(match:(json.type.keyword:(query:api,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:api,type:phrase),query:(match:(json.type.keyword:(query:api,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase)))),(meta:(field:json.status,index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:api,type:phrase),query:(match:(json.type.keyword:(query:api,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:api,type:phrase),query:(match:(json.type.keyword:(query:api,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:api,type:phrase),query:(match:(json.type.keyword:(query:api,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:api,type:phrase),query:(match:(json.type.keyword:(query:api,type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:api,type:phrase),query:(match:(json.type:(query:api,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_ms),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "🔬 SLI Detail: global_search",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "global_search RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_global_search_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for global_search Latency - per endpoint_id",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli_global_search_apdex_total:rate_5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n    )\n    -\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli_global_search_apdex_success_total:rate_5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n  / ignoring (endpoint_id) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_global_search_apdex_total:rate_5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "global_search RPS - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli_global_search_apdex_total:rate_5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for global_search Latency - per search_level",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (search_level) (\n      sli_aggregations:gitlab_sli_global_search_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",search_level!=\"\",stage=\"$stage\",type=\"api\"}\n    )\n    -\n    sum by (search_level) (\n      sli_aggregations:gitlab_sli_global_search_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",search_level!=\"\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n  / ignoring (search_level) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_global_search_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",search_level!=\"\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{search_level}}"
      }
     ]
    },
    {
     "title": "global_search RPS - per search_level",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (search_level) (\n  sli_aggregations:gitlab_sli_global_search_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",search_level!=\"\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{search_level}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for global_search Latency - per search_scope",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (search_scope) (\n      sli_aggregations:gitlab_sli_global_search_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",search_scope!=\"\",stage=\"$stage\",type=\"api\"}\n    )\n    -\n    sum by (search_scope) (\n      sli_aggregations:gitlab_sli_global_search_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",search_scope!=\"\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n  / ignoring (search_scope) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_global_search_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",search_scope!=\"\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{search_scope}}"
      }
     ]
    },
    {
     "title": "global_search RPS - per search_scope",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (search_scope) (\n  sli_aggregations:gitlab_sli_global_search_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",search_scope!=\"\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{search_scope}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for global_search Latency - per search_type",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (search_type) (\n      sli_aggregations:gitlab_sli_global_search_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",search_type!=\"\",stage=\"$stage\",type=\"api\"}\n    )\n    -\n    sum by (search_type) (\n      sli_aggregations:gitlab_sli_global_search_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",search_type!=\"\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n  / ignoring (search_type) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_global_search_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",search_type!=\"\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{search_type}}"
      }
     ]
    },
    {
     "title": "global_search RPS - per search_type",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (search_type) (\n  sli_aggregations:gitlab_sli_global_search_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",search_type!=\"\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{search_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: graphql_query",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "graphql_query Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_graphql_query_error_total:rate_5m{endpoint_id!=\"graphql:unknown\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "graphql_query RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_graphql_query_total:rate_5m{endpoint_id!=\"graphql:unknown\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for graphql_query Latency - per endpoint_id",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_total:rate_5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n    )\n    -\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_success_total:rate_5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n  / ignoring (endpoint_id) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_total:rate_5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "graphql_query Errors - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli_graphql_query_error_total:rate_5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "graphql_query RPS - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli_graphql_query_total:rate_5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for graphql_query Latency - per feature_category",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_total:rate_5m{endpoint_id!=\"graphql:unknown\",env=\"$environment\",environment=\"$environment\",feature_category!=\"\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n    )\n    -\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_success_total:rate_5m{endpoint_id!=\"graphql:unknown\",env=\"$environment\",environment=\"$environment\",feature_category!=\"\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_total:rate_5m{endpoint_id!=\"graphql:unknown\",env=\"$environment\",environment=\"$environment\",feature_category!=\"\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "graphql_query Errors - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli_graphql_query_error_total:rate_5m{endpoint_id!=\"graphql:unknown\",env=\"$environment\",environment=\"$environment\",feature_category!=\"\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "graphql_query RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli_graphql_query_total:rate_5m{endpoint_id!=\"graphql:unknown\",env=\"$environment\",environment=\"$environment\",feature_category!=\"\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for graphql_query Latency - per query_urgency",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (query_urgency) (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_total:rate_5m{endpoint_id!=\"graphql:unknown\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\",type=\"api\"}\n    )\n    -\n    sum by (query_urgency) (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_success_total:rate_5m{endpoint_id!=\"graphql:unknown\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n  / ignoring (query_urgency) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_total:rate_5m{endpoint_id!=\"graphql:unknown\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{query_urgency}}"
      }
     ]
    },
    {
     "title": "graphql_query Errors - per query_urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (query_urgency) (\n  sli_aggregations:gitlab_sli_graphql_query_error_total:rate_5m{endpoint_id!=\"graphql:unknown\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{query_urgency}}"
      }
     ]
    },
    {
     "title": "graphql_query RPS - per query_urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (query_urgency) (\n  sli_aggregations:gitlab_sli_graphql_query_total:rate_5m{endpoint_id!=\"graphql:unknown\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{query_urgency}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: group_management",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 220 },
   "collapsed": true,
   "panels": [
    {
     "title": "group_management Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_rails_request_error_total:rate_5m{endpoint_id=~\"POST /api/:version/groups|PUT /api/:version/groups/:id\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "group_management RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_rails_request_total:rate_5m{endpoint_id=~\"POST /api/:version/groups|PUT /api/:version/groups/:id\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "group_management Errors - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli_rails_request_error_total:rate_5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "group_management RPS - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli_rails_request_total:rate_5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: nginx_ingress",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 230 },
   "collapsed": true,
   "panels": [
    {
     "title": "nginx_ingress Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:nginx_ingress_controller_requests:labeled:rate_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",status=~\"^5.*\",type=\"api\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "nginx_ingress RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:nginx_ingress_controller_requests:labeled:rate_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "nginx_ingress Errors - per path",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (path) (\n  sli_aggregations:nginx_ingress_controller_requests:labeled:rate_5m{env=\"$environment\",environment=\"$environment\",path!=\"\",stage=\"$stage\",status=~\"^5.*\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "nginx_ingress RPS - per path",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (path) (\n  sli_aggregations:nginx_ingress_controller_requests:labeled:rate_5m{env=\"$environment\",environment=\"$environment\",path!=\"\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "nginx_ingress Errors - per status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (\n  sli_aggregations:nginx_ingress_controller_requests:labeled:rate_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",status!=\"\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "nginx_ingress RPS - per status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (\n  sli_aggregations:nginx_ingress_controller_requests:labeled:rate_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",status!=\"\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: rails_request",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 240 },
   "collapsed": true,
   "panels": [
    {
     "title": "rails_request Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_rails_request_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "rails_request RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_rails_request_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_request Latency - per endpoint_id",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total:rate_5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n    )\n    -\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_success_total:rate_5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n  / ignoring (endpoint_id) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total:rate_5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "rails_request Errors - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli_rails_request_error_total:rate_5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "rails_request RPS - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli_rails_request_total:rate_5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_request Latency - per feature_category",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",feature_category!=\"\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n    )\n    -\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",feature_category!=\"\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",feature_category!=\"\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "rails_request Errors - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli_rails_request_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",feature_category!=\"\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "rails_request RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli_rails_request_total:rate_5m{env=\"$environment\",environment=\"$environment\",feature_category!=\"\",job=\"gitlab-rails\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_request Latency - per request_urgency",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (request_urgency) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\",type=\"api\"}\n    )\n    -\n    sum by (request_urgency) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n  / ignoring (request_urgency) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\",type=\"api\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{request_urgency}}"
      }
     ]
    },
    {
     "title": "rails_request Errors - per request_urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (request_urgency) (\n  sli_aggregations:gitlab_sli_rails_request_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{request_urgency}}"
      }
     ]
    },
    {
     "title": "rails_request RPS - per request_urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (request_urgency) (\n  sli_aggregations:gitlab_sli_rails_request_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{request_urgency}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: workhorse",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 250 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p90 workhorse Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    sli_aggregations:gitlab_workhorse_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",route!=\"\\\\A/api/v4/jobs/request\\\\z\",route!=\"^/api/v4/jobs/request\\\\z\",route!=\"^/-/health$\",route!=\"^/-/(readiness|liveness)$\",stage=\"$stage\",type=\"api\"}\n  )\n)\n > 0",
       "legendFormat": "p90 overall"
      }
     ]
    },
    {
     "title": "workhorse Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_workhorse_http_requests_total:rate_5m{code=~\"^5.*\",env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",route!=\"^/-/health$\",route!=\"^/-/(readiness|liveness)$\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "workhorse RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_workhorse_http_requests_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p90 workhorse Latency - per region",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le,region) (\n    sli_aggregations:gitlab_workhorse_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",region!=\"\",route!=\"\\\\A/api/v4/jobs/request\\\\z\",route!=\"^/api/v4/jobs/request\\\\z\",route!=\"^/-/health$\",route!=\"^/-/(readiness|liveness)$\",stage=\"$stage\",type=\"api\"}\n  )\n)\n > 0",
       "legendFormat": "p90 {{region}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for workhorse Latency - per region",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (region) (\n  sli_aggregations:gitlab_workhorse_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",le=\"+Inf\",region!=\"\",route!=\"\\\\A/api/v4/jobs/request\\\\z\",route!=\"^/api/v4/jobs/request\\\\z\",route!=\"^/-/health$\",route!=\"^/-/(readiness|liveness)$\",stage=\"$stage\",type=\"api\"}\n)\n\n    -\n    (\n      (\n  sum by (region) (\n    sli_aggregations:gitlab_workhorse_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",le=\"1\",region!=\"\",route!=\"\\\\A/api/v4/jobs/request\\\\z\",route!=\"^/api/v4/jobs/request\\\\z\",route!=\"^/-/health$\",route!=\"^/-/(readiness|liveness)$\",stage=\"$stage\",type=\"api\"}\n  )\n  +\n  sum by (region) (\n    sli_aggregations:gitlab_workhorse_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",le=\"10\",region!=\"\",route!=\"\\\\A/api/v4/jobs/request\\\\z\",route!=\"^/api/v4/jobs/request\\\\z\",route!=\"^/-/health$\",route!=\"^/-/(readiness|liveness)$\",stage=\"$stage\",type=\"api\"}\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(region) group_left()\n  (\n    sum by () (\n  sli_aggregations:gitlab_workhorse_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",le=\"+Inf\",region!=\"\",route!=\"\\\\A/api/v4/jobs/request\\\\z\",route!=\"^/api/v4/jobs/request\\\\z\",route!=\"^/-/health$\",route!=\"^/-/(readiness|liveness)$\",stage=\"$stage\",type=\"api\"}\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "workhorse Errors - per region",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (region) (\n  sli_aggregations:gitlab_workhorse_http_requests_total:rate_5m{code=~\"^5.*\",env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",region!=\"\",route!=\"^/-/health$\",route!=\"^/-/(readiness|liveness)$\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "workhorse RPS - per region",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (region) (\n  sli_aggregations:gitlab_workhorse_http_requests_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",region!=\"\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "Estimated p90 workhorse Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le,method) (\n    sli_aggregations:gitlab_workhorse_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",method!=\"\",route!=\"\\\\A/api/v4/jobs/request\\\\z\",route!=\"^/api/v4/jobs/request\\\\z\",route!=\"^/-/health$\",route!=\"^/-/(readiness|liveness)$\",stage=\"$stage\",type=\"api\"}\n  )\n)\n > 0",
       "legendFormat": "p90 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for workhorse Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (method) (\n  sli_aggregations:gitlab_workhorse_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",le=\"+Inf\",method!=\"\",route!=\"\\\\A/api/v4/jobs/request\\\\z\",route!=\"^/api/v4/jobs/request\\\\z\",route!=\"^/-/health$\",route!=\"^/-/(readiness|liveness)$\",stage=\"$stage\",type=\"api\"}\n)\n\n    -\n    (\n      (\n  sum by (method) (\n    sli_aggregations:gitlab_workhorse_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",le=\"1\",method!=\"\",route!=\"\\\\A/api/v4/jobs/request\\\\z\",route!=\"^/api/v4/jobs/request\\\\z\",route!=\"^/-/health$\",route!=\"^/-/(readiness|liveness)$\",stage=\"$stage\",type=\"api\"}\n  )\n  +\n  sum by (method) (\n    sli_aggregations:gitlab_workhorse_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",le=\"10\",method!=\"\",route!=\"\\\\A/api/v4/jobs/request\\\\z\",route!=\"^/api/v4/jobs/request\\\\z\",route!=\"^/-/health$\",route!=\"^/-/(readiness|liveness)$\",stage=\"$stage\",type=\"api\"}\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(method) group_left()\n  (\n    sum by () (\n  sli_aggregations:gitlab_workhorse_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",le=\"+Inf\",method!=\"\",route!=\"\\\\A/api/v4/jobs/request\\\\z\",route!=\"^/api/v4/jobs/request\\\\z\",route!=\"^/-/health$\",route!=\"^/-/(readiness|liveness)$\",stage=\"$stage\",type=\"api\"}\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "workhorse Errors - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  sli_aggregations:gitlab_workhorse_http_requests_total:rate_5m{code=~\"^5.*\",env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",method!=\"\",route!=\"^/-/health$\",route!=\"^/-/(readiness|liveness)$\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "workhorse RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  sli_aggregations:gitlab_workhorse_http_requests_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",method!=\"\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Estimated p90 workhorse Latency - per route",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le,route) (\n    sli_aggregations:gitlab_workhorse_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",route!=\"\",stage=\"$stage\",type=\"api\"}\n  )\n)\n > 0",
       "legendFormat": "p90 {{route}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for workhorse Latency - per route",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (route) (\n  sli_aggregations:gitlab_workhorse_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",le=\"+Inf\",route!=\"\",stage=\"$stage\",type=\"api\"}\n)\n\n    -\n    (\n      (\n  sum by (route) (\n    sli_aggregations:gitlab_workhorse_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",le=\"1\",route!=\"\",stage=\"$stage\",type=\"api\"}\n  )\n  +\n  sum by (route) (\n    sli_aggregations:gitlab_workhorse_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",le=\"10\",route!=\"\",stage=\"$stage\",type=\"api\"}\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(route) group_left()\n  (\n    sum by () (\n  sli_aggregations:gitlab_workhorse_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",le=\"+Inf\",route!=\"\",stage=\"$stage\",type=\"api\"}\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "workhorse Errors - per route",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (route) (\n  sli_aggregations:gitlab_workhorse_http_requests_total:rate_5m{code=~\"^5.*\",env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",route!=\"\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "workhorse RPS - per route",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (route) (\n  sli_aggregations:gitlab_workhorse_http_requests_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-api\",route!=\"\",stage=\"$stage\",type=\"api\"}\n)\n > 0",
       "legendFormat": "{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "☸️ Kubernetes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 },
   "collapsed": true,
   "panels": [
    {
     "title": "api Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"api\",env=\"$environment\",environment=\"$environment\",type=\"api\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "api Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"api\",env=\"$environment\",environment=\"$environment\",type=\"api\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "api Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"api\",env=\"$environment\",environment=\"$environment\",type=\"api\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"api\",env=\"$environment\",environment=\"$environment\",type=\"api\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "kube_container_cpu component saturation: Kube Container CPU Utilization",
     "type": "graph",
     "description": "Kubernetes containers are allocated a share of CPU. Configured using resource requests.\n\nThis is the amount of CPU that a container should always have available,\nthough it can briefly utilize more. However, if a lot of pods on the same\nhost exceed their requested CPU the container could be throttled earlier.\n\nThis monitors utilization/allocated requests over a 1 hour period, and takes\nthe 99th quantile of that utilization percentage in that period.\nWe want the worst case to be around 80%-90% utilization,\nmeaning we've sized the container correctly. If utilization is much higher than that\nthe container could already be throttled because the host is overused, if it\nis much lower, then we could be underutilizing a host.\n\nThis saturation point is only used for capacity planning.\nContainers that have a quota specified are excluded here and can be monitored using\nthe `kube_container_throttling` saturation component.\nThe burst utilization of a CPU is monitored and alerted upon using the\n`kube_container_cpu_limit` saturation point.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, pod, container) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      (\n        sum by (environment, tier, type, stage, shard, pod, container) (\n          rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[1h])\n        )\n        unless on(environment, tier, type, stage, shard, pod, container) (\n          last_over_time(container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[1h])\n        )\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        kube_pod_container_resource_requests:labeled{container!=\"\", container!=\"POD\", resource=\"cpu\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_container_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_cpu_limit component saturation: Kube Container CPU over-utilization",
     "type": "graph",
     "description": "Kubernetes containers can have a limit configured on how much CPU they can consume in\na burst. If we are at this limit, exceeding the allocated requested resources, we\nshould consider revisting the container's HPA configuration.\n\nWhen a container is utilizing CPU resources up-to it's configured limit for\nextended periods of time, this could cause it and other running containers to be\nthrottled.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, pod, container) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard, pod, container) (\n        rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[5m])\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}\n        /\n        container_spec_cpu_period:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_container_cpu_limit\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_rss component saturation: Kube Container Memory Utilization (RSS)",
     "type": "graph",
     "description": "Records the total anonymous (unevictable) memory utilization for containers for this\nservice, as a percentage of the memory limit as configured through Kubernetes.\n\nThis is computed using the container's resident set size (RSS), as opposed to\nkube_container_memory which uses the working set size. For our purposes, RSS is the\nbetter metric as cAdvisor's working set calculation includes pages from the\nfilesystem cache that can (and will) be evicted before the OOM killer kills the\ncgroup.\n\nA container's RSS (anonymous memory usage) is still not precisely what the OOM\nkiller will use, but it's a better approximation of what the container's workload is\nactually using. RSS metrics can, however, be dramatically inflated if a process in\nthe container uses MADV_FREE (lazy-free) memory. RSS will include the memory that is\navailable to be reclaimed without a page fault, but not currently in use.\n\nThe most common case of OOM kills is for anonymous memory demand to overwhelm the\ncontainer's memory limit. On swapless hosts, anonymous memory cannot be evicted from\nthe page cache, so when a container's memory usage is mostly anonymous pages, the\nonly remaining option to relieve memory pressure may be the OOM killer.\n\nAs container RSS approaches container memory limit, OOM kills become much more\nlikely. Consequently, this ratio is a good leading indicator of memory saturation\nand OOM risk.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      container_memory_rss:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}\n      /\n      (container_spec_memory_limit_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"} > 0)\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_container_rss\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_container_rss\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_container_rss\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_rss\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_rss\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_throttling component saturation: Kube container throttling",
     "type": "graph",
     "description": "Kube container throttling\n\nA container will be throttled if it reaches the configured cpu limit for the\nhorizontal pod autoscaler. Or when other containers on the node are overutilizing\nthe the CPU.\n\nTo get around this, consider increasing the limit for this workload, taking\ninto consideration the requested resources.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, pod, container) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      avg by (environment, tier, type, stage, shard, pod, container)(\n        rate(container_cpu_cfs_throttled_periods_total:labeled{container!=\"\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[5m])\n        /\n        rate(container_cpu_cfs_periods_total:labeled{container!=\"\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_container_throttling\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_container_throttling\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_container_throttling\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_throttling\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_throttling\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_go_memory component saturation: Go Memory Utilization per Node",
     "type": "graph",
     "description": "Measures Go memory usage as a percentage of container memory limit\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(env, environment, tier, type, stage, shard, cluster, pod) (\n  clamp_min(\n    clamp_max(\n      go_memstats_alloc_bytes{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}\n      / on(env, environment, tier, type, stage, shard, cluster, pod) group_left()\n      topk by(env, environment, tier, type, stage, shard, cluster, pod) (1,\n        container_spec_memory_limit_bytes:labeled{container=~\"gitlab-pages|gitlab-workhorse|kas|registry|thanos-store\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ cluster }} {{ pod }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_go_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_go_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_go_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_go_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_go_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_horizontalpodautoscaler_desired_replicas component saturation: Horizontal Pod Autoscaler Desired Replicas",
     "type": "graph",
     "description": "The [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)\nautomatically scales the number of Pods in a deployment based on metrics.\n\nThe Horizontal Pod Autoscaler has a configured upper maximum. When this\nlimit is reached, the HPA will not increase the number of pods and other\nresource saturation (eg, CPU, memory) may occur.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, horizontalpodautoscaler, shard) (\n  clamp_min(\n    clamp_max(\n      kube_horizontalpodautoscaler_status_desired_replicas:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", shard!~\"ai-abstraction-layer|database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects\", namespace!~\"pubsubbeat\"}\n      /\n      kube_horizontalpodautoscaler_spec_max_replicas:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", shard!~\"ai-abstraction-layer|database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects\", namespace!~\"pubsubbeat\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ horizontalpodautoscaler }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "puma_workers component saturation: Puma Worker Saturation",
     "type": "graph",
     "description": "Puma thread utilization.\n\nPuma uses a fixed size thread pool to handle HTTP requests. This metric shows how many threads are busy handling requests. When this resource is saturated,\nwe will see puma queuing taking place. Leading to slowdowns across the application.\n\nPuma saturation is usually caused by latency problems in downstream services: usually Gitaly or Postgres, but possibly also Redis.\nPuma saturation can also be caused by traffic spikes.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      sum by(environment, tier, type, stage, shard) (avg_over_time(sum without (pid,worker) (puma_active_connections{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"})[1m:]))\n      /\n      sum by(environment, tier, type, stage, shard) (sum without (pid,worker) (puma_max_threads{pid=\"puma_master\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}))\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"puma_workers\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"puma_workers\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"puma_workers\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"puma_workers\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"puma_workers\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "rails_db_connection_pool component saturation: Rails DB Connection Pool Utilization",
     "type": "graph",
     "description": "Rails uses connection pools for its database connections. As each\nnode may have multiple connection pools, this is by node and by\ndatabase host.\n\nRead more about this resource in our [documentation](https://docs.gitlab.com/ee/development/database/client_side_connection_pool.html#client-side-connection-pool).\n\nIf this resource is saturated, it may indicate that our connection\npools are not correctly sized, perhaps because an unexpected\napplication thread is using a database connection.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, instance, host, port) (\n  clamp_min(\n    clamp_max(\n      (\n        avg_over_time(gitlab_database_connection_pool_busy{class=\"ActiveRecord::Base\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[5m])\n        +\n        avg_over_time(gitlab_database_connection_pool_dead{class=\"ActiveRecord::Base\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[5m])\n      )\n      /\n      gitlab_database_connection_pool_size{class=\"ActiveRecord::Base\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ instance }} {{ host }} {{ port }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"rails_db_connection_pool\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"rails_db_connection_pool\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"rails_db_connection_pool\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"rails_db_connection_pool\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"rails_db_connection_pool\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "ruby_thread_contention component saturation: Ruby Thread Contention",
     "type": "graph",
     "description": "Ruby (technically Ruby MRI), like some other scripting languages, uses a Global VM lock (GVL) also known as a\nGlobal Interpreter Lock (GIL) to ensure that multiple threads can execute safely. Ruby code is only allowed to\nexecute in one thread in a process at a time. When calling out to c extensions, the thread can cede the lock to\nother thread while it continues to execute.\n\nThis means that when CPU-bound workloads run in a multithreaded environment such as Puma or Sidekiq, contention\nwith other Ruby worker threads running in the same process can occur, effectively slowing thoses threads down as\nthey await GVL entry.\n\nOften the best fix for this situation is to add more workers by scaling up the fleet.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, fqdn, pod) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      rate(ruby_process_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[1h])\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ pod }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"ruby_thread_contention\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"ruby_thread_contention\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"api\", component=\"ruby_thread_contention\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"ruby_thread_contention\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"ruby_thread_contention\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  { "title": "Workhorse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "p50 Overall Latency Estimate",
   "type": "graph",
   "description": "p50 Latency. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum(\n    job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n      environment=\"$environment\",\n      type=\"api\",\n      stage=\"$stage\"}\n  ) by (le))\n",
     "legendFormat": "{{ method }} {{ route }}"
    }
   ]
  },
  {
   "title": "p90 Latency Estimate per Route",
   "type": "graph",
   "description": "90th percentile Latency. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  histogram_quantile(\n    0.9,\n    sum(\n      job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n        environment=\"$environment\",\n        type=\"api\",\n        stage=\"$stage\"}\n    ) by (route, le)),\n\"route\", \"none\", \"route\", \"\")\n",
     "legendFormat": "{{ method }} {{ route }}"
    }
   ]
  },
  {
   "title": "p50 Latency Estimate per Route",
   "type": "graph",
   "description": "Median Latency. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1011 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  histogram_quantile(\n    0.5,\n    sum(\n      job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n        environment=\"$environment\",\n        type=\"api\",\n        stage=\"$stage\"}\n    ) by (route, le)),\n\"route\", \"none\", \"route\", \"\")\n",
     "legendFormat": "{{ method }} {{ route }}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "description": "Total Requests",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1011 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n      environment=\"$environment\",\n      type=\"api\",\n      stage=\"$stage\",\n      le=\"+Inf\"}\n)\n",
     "legendFormat": "{{ code_class }}"
    }
   ]
  },
  {
   "title": "Requests by Status Class",
   "type": "graph",
   "description": "Requests by Status Class",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1021 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    sum(\n      job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n          environment=\"$environment\",\n          type=\"api\",\n          stage=\"$stage\",\n          le=\"+Inf\"}\n    ) by (code),\n  \"code_class\", \"${1}XX\", \"code\", \"(.).*\")\n) by (code_class)\n",
     "legendFormat": "{{ code_class }}"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "graph",
   "description": "Requests by Status Code",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1021 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n      environment=\"$environment\",\n      type=\"api\",\n      stage=\"$stage\",\n      le=\"+Inf\"}\n) by (code)\n",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Requests by Route",
   "type": "graph",
   "description": "Requests by Route",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1031 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    sum(\n      job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n          environment=\"$environment\",\n          type=\"api\",\n          stage=\"$stage\",\n          le=\"+Inf\"}\n    ) by (route),\n  \"route\", \"none\", \"route\", \"\")\n) by (route)\n",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  { "title": "Rails", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 } },
  {
   "title": "p95 Latency Estimate",
   "type": "graph",
   "description": "95th percentile Latency. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3001 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum(job_environment:gitlab_transaction_duration_seconds_bucket:rate5m{\n    environment=\"$environment\",\n    type=\"api\",\n    stage=\"$stage\"\n  }) by (le, job)\n)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Rails Total Time",
   "type": "graph",
   "description": "Seconds of Rails processing, per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3001 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  job_environment:gitlab_transaction_duration_seconds_sum:rate1m{\n    environment=\"$environment\",\n    type=\"api\",\n    stage=\"$stage\"}\n) by (job)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Rails Queue Time",
   "type": "graph",
   "description": "Time spend waiting for a rails worker",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3011 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    gitlab_transaction_rails_queue_duration_total{\n      environment=\"$environment\",\n      type=\"api\",\n      stage=\"$stage\"}\n      [$__interval]\n  )\n) by (job)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Cache Operations",
   "type": "graph",
   "description": "Cache Operations per Second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3011 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    gitlab_cache_operations_total{\n      environment=\"$environment\",\n      type=\"api\",\n      stage=\"$stage\"}[$__interval]\n  )\n) by (job)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "gitlab-rails Process restarts",
   "type": "graph",
   "description": "The number of times this process restarted in a given period, including children workers. Restarts are associated with poor client experience, so lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3021 },
   "yaxes": [
    { "format": "short", "label": "Process restarts" }
   ],
   "targets": [
    {
     "expr": "sum(\n  changes(\n    ruby_process_start_time_seconds{\n      environment=\"$environment\",\n      type=\"api\",\n      stage=\"$stage\",\n      job=\"gitlab-rails\"\n    }[$__interval]\n  )\n)\n",
     "legendFormat": "process restarts"
    }
   ]
  },
  {
   "title": "Database load balancer: average secondary connections per client",
   "type": "graph",
   "description": "This graph shows the average number of secondary database connections\n        per process. A value of zero indicates that the secondary replicas are unreachable.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3021 },
   "yaxes": [
    { "format": "short", "label": "Average connections" }
   ],
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(\n    db_load_balancing_hosts{\n      environment=\"$environment\",\n      type=\"api\",\n      stage=\"$stage\"}[$__interval]\n  )\n) by (job)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni\n  pgbouncer\n  redis\n  redis-cluster-cache\n  redis-cluster-chat-cache\n  redis-cluster-feature-flag\n  redis-cluster-queues-meta\n  redis-cluster-ratelimiting\n  redis-cluster-repo-cache\n  redis-cluster-shared-state\n  redis-pubsub\n  redis-sessions\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph inf\n  search\n  zoekt\nend\n\nsubgraph stor\n  gitaly\n  google-cloud-storage\nend\n\nsubgraph sv\n  api\n  consul\n  ext-pvs\n  kas\nend\n\n\n  api --> consul\napi --> ext-pvs\napi --> gitaly\napi --> google-cloud-storage\napi --> kas\napi --> patroni\napi --> pgbouncer\napi --> redis\napi --> redis-cluster-cache\napi --> redis-cluster-chat-cache\napi --> redis-cluster-feature-flag\napi --> redis-cluster-queues-meta\napi --> redis-cluster-ratelimiting\napi --> redis-cluster-repo-cache\napi --> redis-cluster-shared-state\napi --> redis-pubsub\napi --> redis-sessions\napi --> redis-sidekiq\napi --> redis-tracechunks\napi --> search\napi --> zoekt\ngitaly --> gitaly\nkas --> api\nkas --> gitaly\nkas --> kas\nkas --> redis\npgbouncer --> patroni\n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni\n  pgbouncer\n  redis\n  redis-cluster-cache\n  redis-cluster-chat-cache\n  redis-cluster-feature-flag\n  redis-cluster-queues-meta\n  redis-cluster-ratelimiting\n  redis-cluster-repo-cache\n  redis-cluster-shared-state\n  redis-pubsub\n  redis-sessions\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph inf\n  search\n  zoekt\nend\n\nsubgraph stor\n  gitaly\n  google-cloud-storage\nend\n\nsubgraph sv\n  api\n  consul\n  ext-pvs\n  kas\nend\n\n\n  api --> consul\napi --> ext-pvs\napi --> gitaly\napi --> google-cloud-storage\napi --> kas\napi --> patroni\napi --> pgbouncer\napi --> redis\napi --> redis-cluster-cache\napi --> redis-cluster-chat-cache\napi --> redis-cluster-feature-flag\napi --> redis-cluster-queues-meta\napi --> redis-cluster-ratelimiting\napi --> redis-cluster-repo-cache\napi --> redis-cluster-shared-state\napi --> redis-pubsub\napi --> redis-sessions\napi --> redis-sidekiq\napi --> redis-tracechunks\napi --> search\napi --> zoekt\ngitaly --> gitaly\nkas --> api\nkas --> gitaly\nkas --> kas\nkas --> redis\npgbouncer --> patroni\n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni[\"patroni (Level 2)\"]\n  pgbouncer[\"pgbouncer (Level 1)\"]\n  redis-cluster-cache[\"redis-cluster-cache (Level 2)\"]\n  redis-cluster-chat-cache[\"redis-cluster-chat-cache (Level 2)\"]\n  redis-cluster-feature-flag[\"redis-cluster-feature-flag (Level 2)\"]\n  redis-cluster-queues-meta[\"redis-cluster-queues-meta (Level 2)\"]\n  redis-cluster-ratelimiting[\"redis-cluster-ratelimiting (Level 2)\"]\n  redis-cluster-repo-cache[\"redis-cluster-repo-cache (Level 2)\"]\n  redis-cluster-shared-state[\"redis-cluster-shared-state (Level 2)\"]\n  redis-pubsub[\"redis-pubsub (Level 2)\"]\n  redis-sessions[\"redis-sessions (Level 3)\"]\n  redis-sidekiq[\"redis-sidekiq (Level 3)\"]\n  redis-tracechunks[\"redis-tracechunks (Level 3)\"]\n  redis[\"redis (Level 3)\"]\nend\n\nsubgraph inf\n  search[\"search (Level 1)\"]\n  zoekt[\"zoekt (Level 1)\"]\nend\n\nsubgraph stor\n  gitaly[\"gitaly (Level 3)\"]\n  google-cloud-storage[\"google-cloud-storage (Level 2)\"]\nend\n\nsubgraph sv\n  api[\"api (Level 2)\"]\n  consul[\"consul (Level 1)\"]\n  ext-pvs[\"ext-pvs (Level 2)\"]\n  kas[\"kas (Level 3)\"]\nend\n\n\n  api[\"api (Level 2)\"] --> consul\napi[\"api (Level 2)\"] --> ext-pvs\napi[\"api (Level 2)\"] --> gitaly\napi[\"api (Level 2)\"] --> google-cloud-storage\napi[\"api (Level 2)\"] --> kas\napi[\"api (Level 2)\"] --> patroni\napi[\"api (Level 2)\"] --> pgbouncer\napi[\"api (Level 2)\"] --> redis\napi[\"api (Level 2)\"] --> redis-cluster-cache\napi[\"api (Level 2)\"] --> redis-cluster-chat-cache\napi[\"api (Level 2)\"] --> redis-cluster-feature-flag\napi[\"api (Level 2)\"] --> redis-cluster-queues-meta\napi[\"api (Level 2)\"] --> redis-cluster-ratelimiting\napi[\"api (Level 2)\"] --> redis-cluster-repo-cache\napi[\"api (Level 2)\"] --> redis-cluster-shared-state\napi[\"api (Level 2)\"] --> redis-pubsub\napi[\"api (Level 2)\"] --> redis-sessions\napi[\"api (Level 2)\"] --> redis-sidekiq\napi[\"api (Level 2)\"] --> redis-tracechunks\napi[\"api (Level 2)\"] --> search\napi[\"api (Level 2)\"] --> zoekt\ngitaly[\"gitaly (Level 3)\"] --> gitaly\nkas[\"kas (Level 3)\"] --> api\nkas[\"kas (Level 3)\"] --> gitaly\nkas[\"kas (Level 3)\"] --> kas\nkas[\"kas (Level 3)\"] --> redis\npgbouncer[\"pgbouncer (Level 1)\"] --> patroni\n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}