{
 "title": "sidekiq: Kube Containers Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8245226639 at Fri Nov  1 04:32:13 UTC 2024",
 "tags": [
  "managed",
  "sidekiq",
  "sidekiq",
  "type:sidekiq",
  "kube",
  "kube detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "sidekiq-ai-abstraction-layer deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "sidekiq container/sidekiq-ai-abstraction-layer deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 sidekiq Container CPU"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-ai-abstraction-layer deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p99 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p95 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p75 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p50 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p25 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p10 sidekiq Container Memory"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-ai-abstraction-layer deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-ai-abstraction-layer deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "sidekiq-catchall deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "sidekiq container/sidekiq-catchall deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 sidekiq Container CPU"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-catchall deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p99 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p95 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p75 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p50 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p25 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p10 sidekiq Container Memory"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-catchall deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-catchall deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq-database-throttled deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 }
  },
  {
   "title": "sidekiq container/sidekiq-database-throttled deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 sidekiq Container CPU"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-database-throttled deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p99 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p95 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p75 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p50 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p25 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p10 sidekiq Container Memory"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-database-throttled deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-database-throttled deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq-elasticsearch deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 }
  },
  {
   "title": "sidekiq container/sidekiq-elasticsearch deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 sidekiq Container CPU"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-elasticsearch deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p99 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p95 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p75 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p50 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p25 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p10 sidekiq Container Memory"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-elasticsearch deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-elasticsearch deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq-gitaly-throttled deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 }
  },
  {
   "title": "sidekiq container/sidekiq-gitaly-throttled deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 sidekiq Container CPU"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-gitaly-throttled deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p99 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p95 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p75 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p50 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p25 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p10 sidekiq Container Memory"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-gitaly-throttled deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-gitaly-throttled deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq-low-urgency-cpu-bound deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 }
  },
  {
   "title": "sidekiq container/sidekiq-low-urgency-cpu-bound deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 sidekiq Container CPU"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-low-urgency-cpu-bound deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p99 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p95 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p75 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p50 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p25 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p10 sidekiq Container Memory"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-low-urgency-cpu-bound deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-low-urgency-cpu-bound deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq-memory-bound deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 144 }
  },
  {
   "title": "sidekiq container/sidekiq-memory-bound deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 sidekiq Container CPU"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-memory-bound deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p99 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p95 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p75 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p50 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p25 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p10 sidekiq Container Memory"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-memory-bound deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-memory-bound deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "sidekiq-quarantine deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 168 } },
  {
   "title": "sidekiq container/sidekiq-quarantine deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 sidekiq Container CPU"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-quarantine deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p99 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p95 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p75 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p50 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p25 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p10 sidekiq Container Memory"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-quarantine deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-quarantine deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-authorized-projects deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 192 }
  },
  {
   "title": "sidekiq container/sidekiq-urgent-authorized-projects deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 sidekiq Container CPU"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-urgent-authorized-projects deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p99 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p95 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p75 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p50 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p25 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p10 sidekiq Container Memory"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-urgent-authorized-projects deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-urgent-authorized-projects deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-cpu-bound deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 216 }
  },
  {
   "title": "sidekiq container/sidekiq-urgent-cpu-bound deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 224 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 sidekiq Container CPU"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-urgent-cpu-bound deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 224 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p99 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p95 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p75 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p50 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p25 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p10 sidekiq Container Memory"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-urgent-cpu-bound deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 232 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-urgent-cpu-bound deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 232 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-other deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 240 }
  },
  {
   "title": "sidekiq container/sidekiq-urgent-other deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 248 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 sidekiq Container CPU"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-urgent-other deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 248 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p99 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p95 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p75 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p50 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p25 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n }\n)\n",
     "legendFormat": "p10 sidekiq Container Memory"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-urgent-other deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 256 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq-urgent-other deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 256 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}