{
 "title": "sidekiq: Worker Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8397766929 at Mon Nov 18 09:15:16 UTC 2024",
 "tags": [
  "managed",
  "sidekiq",
  "type:sidekiq",
  "detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "worker",
    "query": "label_values(application_sli_aggregation:sidekiq_execution:ops:rate_1h{environment=\"$environment\", type=\"sidekiq\"}, worker)"
   }
  ]
 },
 "panels": [
  {
   "title": "Worker Attribute: Urgency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  topk by (worker) (1, sum(rate(sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", worker=~\"$worker\"}[$__range])) by (worker, urgency)),\n  \"urgency\", \"unknown\", \"urgency\", \"\"\n)\n",
     "legendFormat": "{{ urgency }} ({{ worker }})"
    }
   ]
  },
  {
   "title": "Worker Attribute: Feature Category",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  topk by (worker) (1, sum(rate(sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", worker=~\"$worker\"}[$__range])) by (worker, feature_category)),\n  \"feature_category\", \"unknown\", \"feature_category\", \"\"\n)\n",
     "legendFormat": "{{ feature_category }} ({{ worker }})"
    }
   ]
  },
  {
   "title": "Worker Attribute: Shard",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  topk by (worker) (1, sum(rate(sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", worker=~\"$worker\"}[$__range])) by (worker, shard)),\n  \"shard\", \"unknown\", \"shard\", \"\"\n)\n",
     "legendFormat": "{{ shard }} ({{ worker }})"
    }
   ]
  },
  {
   "title": "Worker Attribute: External Dependencies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  topk by (worker) (1, sum(rate(sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", worker=~\"$worker\"}[$__range])) by (worker, external_dependencies)),\n  \"external_dependencies\", \"none\", \"external_dependencies\", \"\"\n)\n",
     "legendFormat": "{{ external_dependencies }} ({{ worker }})"
    }
   ]
  },
  {
   "title": "Worker Attribute: Resource Boundary",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  topk by (worker) (1, sum(rate(sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", worker=~\"$worker\"}[$__range])) by (worker, boundary)),\n  \"boundary\", \"none\", \"boundary\", \"\"\n)\n",
     "legendFormat": "{{ boundary }} ({{ worker }})"
    }
   ]
  },
  {
   "title": "Max Queuing Duration SLO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(NaN) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", worker=~\"$worker\", urgency=\"throttled\"}\nor\nvector(60.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", worker=~\"$worker\", urgency=\"low\"}\nor\nvector(10.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", worker=~\"$worker\", urgency=\"high\"}\n"
    }
   ]
  },
  {
   "title": "Max Execution Duration SLO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(300.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", worker=~\"$worker\", urgency=\"throttled\"}\nor\nvector(300.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", worker=~\"$worker\", urgency=\"low\"}\nor\nvector(10.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", worker=~\"$worker\", urgency=\"high\"}\n"
    }
   ]
  },
  { "title": "🌡 Worker Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Queue Apdex",
   "type": "graph",
   "description": "Queue apdex monitors the percentage of jobs that are dequeued within their queue threshold. Higher is better. Different jobs have different thresholds.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 101 },
   "yaxes": [
    {
     "format": "percentunit",
     "label": "% Jobs within Max Queuing Duration SLO"
    }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by (worker) (\n  clamp_max(\n    (application_sli_aggregation:sidekiq_queueing:apdex:success:rate_5m{environment=\"$environment\", worker=~\"$worker\"} >= 0)\n    /\n    (application_sli_aggregation:sidekiq_queueing:apdex:weight:score_5m{environment=\"$environment\", worker=~\"$worker\"} >= 0)\n  , 1)\n)\n,1),0)\n",
     "legendFormat": "{{ worker }} queue apdex"
    }
   ]
  },
  {
   "title": "Execution Apdex",
   "type": "graph",
   "description": "Execution apdex monitors the percentage of jobs that run within their execution (run-time) threshold. Higher is better. Different jobs have different thresholds.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 101 },
   "yaxes": [
    {
     "format": "percentunit",
     "label": "% Jobs within Max Execution Duration SLO"
    }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by (worker) (\n  clamp_max(\n    (application_sli_aggregation:sidekiq_execution:apdex:success:rate_5m{environment=\"$environment\", worker=~\"$worker\"} >= 0)\n    /\n    (application_sli_aggregation:sidekiq_execution:apdex:weight:score_5m{environment=\"$environment\", worker=~\"$worker\"} >= 0)\n  , 1)\n)\n,1),0)\n",
     "legendFormat": "{{ worker }} execution apdex"
    }
   ]
  },
  {
   "title": "Execution Rate (RPS)",
   "type": "graph",
   "description": "Jobs executed per second",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "ops", "label": "Jobs per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (application_sli_aggregation:sidekiq_execution:ops:rate_5m{environment=\"$environment\", worker=~\"$worker\"})\n",
     "legendFormat": "{{ worker }} rps"
    }
   ]
  },
  {
   "title": "Error Ratio",
   "type": "graph",
   "description": "Percentage of jobs that fail with an error. Lower is better.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 101 },
   "yaxes": [
    { "format": "percentunit", "label": "Error Percentage" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by (worker) (\n  (application_sli_aggregation:sidekiq_execution:error:rate_5m{environment=\"$environment\", worker=~\"$worker\"} >= 0)\n)\n/\nsum by (worker) (\n  (application_sli_aggregation:sidekiq_execution:ops:rate_5m{environment=\"$environment\", worker=~\"$worker\"} >= 0)\n)\n,1),0)\n",
     "legendFormat": "{{ worker }} error ratio"
    }
   ]
  },
  {
   "title": "Enqueuing (rate of jobs enqueuing)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 201 }
  },
  {
   "title": "Jobs Enqueued",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (\n  sli_aggregations:sidekiq_enqueued_jobs_total:rate_5m{environment=\"$environment\", worker=~\"$worker\"}\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Jobs Enqueued per Service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type, worker) (\n  sli_aggregations:sidekiq_enqueued_jobs_total:rate_5m{environment=\"$environment\", worker=~\"$worker\"}\n)\n",
     "legendFormat": "{{ worker }} - {{ type }}"
    }
   ]
  },
  {
   "title": "Jobs Enqueued by Schedule",
   "type": "graph",
   "description": "Enqueue events separated by immediate (destined for execution) vs delayed (destined for ScheduledSet) scheduling.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (queue, scheduling) (\n  rate(sidekiq_enqueued_jobs_total{environment=\"$environment\", stage=\"$stage\", worker=~\"$worker\"}[$__interval])\n  )\n",
     "legendFormat": "{{ queue }} - {{ scheduling }}"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "graph",
   "description": "The number of unstarted jobs in a queue (capped at 1000 at scrape time for performance reasons)",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (name) (max_over_time(sidekiq_enqueued_jobs{environment=\"$environment\", name=~\"$worker\"}[$__interval]) and on(fqdn) (redis_connected_slaves != 0)) or on () label_replace(vector(0), \"name\", \"$worker\", \"name\", \"\")\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Queue Time & Execution Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 301 } },
  {
   "title": "Queue Time - time spend queueing",
   "type": "text",
   "description": "Estimated queue time, between when the job is enqueued and executed. Lower is better.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 302 },
   "content": "* [📈 Kibana: Sidekiq queue time p95 percentile latency aggregated (split by worker)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.class.keyword,params:'${worker:regex}',type:custom),query:(regexp:(json.class.keyword:'${worker:regex}')))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.queueing_duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.class.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.queueing_duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.queueing_duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n"
  },
  {
   "title": "Individual Execution Time - time taken for individual jobs to complete",
   "type": "text",
   "description": "The duration, once a job starts executing, that it runs for, by shard. Lower is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 302 },
   "content": "* [📈 Kibana: Sidekiq execution time p95 percentile latency aggregated (split by worker)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.class.keyword,params:'${worker:regex}',type:custom),query:(regexp:(json.class.keyword:'${worker:regex}')))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.class.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n"
  },
  {
   "title": "Execution RPS (the rate at which jobs are completed after dequeue)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 501 }
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 502 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (\n  application_sli_aggregation:sidekiq_execution:ops:rate_5m{environment=\"$environment\", worker=~\"$worker\"}\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Error Rate (the rate at which jobs fail)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 601 }
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 602 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (\n  application_sli_aggregation:sidekiq_execution:error:rate_5m{environment=\"$environment\", worker=~\"$worker\"}\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Dead Jobs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 602 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (\n  increase(sidekiq_jobs_dead_total{environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\",worker=~\"$worker\"}[5m])\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 700 } },
  {
   "title": "Average CPU Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 702 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (rate(sidekiq_jobs_cpu_seconds_sum{environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\",worker=~\"$worker\"}[$__interval]))\n/\nsum by (worker) (\n  rate(sidekiq_jobs_completion_count{environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\",worker=~\"$worker\"}[$__interval])\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Average Gitaly Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 702 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (rate(sidekiq_jobs_gitaly_seconds_sum{environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\",worker=~\"$worker\"}[$__interval]))\n/\nsum by (worker) (\n  rate(sidekiq_jobs_completion_count{environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\",worker=~\"$worker\"}[$__interval])\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Average Database Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 702 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (rate(sidekiq_jobs_db_seconds_sum{environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\",worker=~\"$worker\"}[$__interval]))\n/\nsum by (worker) (\n  rate(sidekiq_jobs_completion_count{environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\",worker=~\"$worker\"}[$__interval])\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Average Redis Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 703 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (rate(sidekiq_redis_requests_duration_seconds_sum{environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\",worker=~\"$worker\"}[$__interval]))\n/\nsum by (worker) (\n  rate(sidekiq_jobs_completion_count{environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\",worker=~\"$worker\"}[$__interval])\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Average Elasticsearch Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 703 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (rate(sidekiq_elasticsearch_requests_duration_seconds_sum{environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\",worker=~\"$worker\"}[$__interval]))\n/\nsum by (worker) (\n  rate(sidekiq_jobs_completion_count{environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\",worker=~\"$worker\"}[$__interval])\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  { "title": "SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 750 } },
  {
   "title": "Total SQL Queries Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 751 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (endpoint_id) (\n  rate(\n    gitlab_transaction_db_count_total{endpoint_id=~\"$worker\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}[$__interval]\n  )\n)\n",
     "legendFormat": "{{ endpoint_id }} - total"
    },
    {
     "expr": "sum by (endpoint_id) (\n  rate(\n    gitlab_transaction_db_primary_count_total{endpoint_id=~\"$worker\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}[$__interval]\n  )\n)\n",
     "legendFormat": "{{ endpoint_id }} - primary"
    },
    {
     "expr": "sum by (endpoint_id) (\n  rate(\n    gitlab_transaction_db_replica_count_total{endpoint_id=~\"$worker\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}[$__interval]\n  )\n)\n",
     "legendFormat": "{{ endpoint_id }} - replica"
    }
   ]
  },
  {
   "title": "SQL Transactions Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 751 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (endpoint_id) (\n  rate(gitlab_database_transaction_seconds_count{endpoint_id=~\"$worker\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n)\n",
     "legendFormat": "{{ endpoint_id }}"
    }
   ]
  },
  {
   "title": "SQL Transaction Holding Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 751 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_database_transaction_seconds_sum{endpoint_id=~\"$worker\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])) by (endpoint_id)\n/\nsum(rate(gitlab_database_transaction_seconds_count{endpoint_id=~\"$worker\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])) by (endpoint_id)\n",
     "legendFormat": "{{ endpoint_id }} - p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitlab_database_transaction_seconds_bucket{endpoint_id=~\"$worker\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])) by (endpoint_id, le))\n",
     "legendFormat": "{{ endpoint_id }} - p95"
    }
   ]
  },
  { "title": "Skipped Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 801 } },
  {
   "title": "Jobs Skipped",
   "type": "graph",
   "description": "Jobs skipped (dropped/deferred) intentionally via feature flag `drop_sidekiq_jobs_<worker_name>` or `run_sidekiq_jobs_<worker_name>`",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 802 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (environment, worker, action)  (\n  rate(\n    sidekiq_jobs_skipped_total{environment=\"$environment\", worker=~\"$worker\"}[$__interval]\n    )\n  )\n  > 0\n",
     "legendFormat": "{{ worker }} - {{ action }}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}