{
 "title": "sidekiq: Worker Concurency Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8397766929 at Mon Nov 18 09:15:16 UTC 2024",
 "tags": [
  "managed",
  "sidekiq",
  "type:sidekiq",
  "detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "worker",
    "query": "label_values(sidekiq_concurrency_limit_current_concurrent_jobs_total{environment=\"$environment\", type=\"sidekiq\"}, worker)"
   }
  ]
 },
 "panels": [
  {
   "title": "Concurrency limit queue sizes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (worker) (\n  idelta(\n    sidekiq_concurrency_limit_queue_jobs_total{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", worker=~\"$worker\"}[$__interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Worker concurrency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (worker) (\n  idelta(\n    sidekiq_concurrency_limit_current_concurrent_jobs_total{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", worker=~\"$worker\"}[$__interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Worker deferment rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (\n  rate(\n    sidekiq_concurrency_limit_deferred_jobs_total{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", worker=~\"$worker\"}[$__interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Concurrency limits",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (worker) (\n  sidekiq_concurrency_limit_max_concurrent_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", worker=~\"$worker\"}\n)\n"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}