{
 "title": "sidekiq: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8397766929 at Mon Nov 18 09:15:15 UTC 2024",
 "tags": [
  "managed",
  "sidekiq",
  "gitlab",
  "type:sidekiq",
  "sidekiq",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "shard",
    "query": "label_values(up{environment=\"$environment\", type=\"sidekiq\"}, shard)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "sidekiq Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"sidekiq\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"sidekiq\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"sidekiq\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"sidekiq\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"sidekiq\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"sidekiq\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"sidekiq\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "sidekiq Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "sidekiq Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "sidekiq error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"sidekiq\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"sidekiq\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "sidekiq error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"sidekiq\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"sidekiq\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"sidekiq\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"sidekiq\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"sidekiq\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "sidekiq Service | Errors"
    }
   ]
  },
  {
   "title": "sidekiq Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[$__interval]\n  )\n) by (component, shard)\n",
     "legendFormat": "{{ component }} component - {{ shard }} shard"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "enqueued_jobs SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"enqueued_jobs\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "enqueued_jobs RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "content": "### Description\n\nThe number of jobs enqueued by Sidekiq clients (api, web, sidekiq, etc).\n\n"
  },
  {
   "title": "llm_completion SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"llm_completion\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "llm_completion apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"llm_completion\",monitor=\"global\",type=\"sidekiq\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"llm_completion\",monitor=\"global\",type=\"sidekiq\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "llm_completion SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"llm_completion\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "llm_completion error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"llm_completion\",monitor=\"global\",type=\"sidekiq\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"llm_completion\",monitor=\"global\",type=\"sidekiq\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "llm_completion SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"llm_completion\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "llm_completion RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "content": "### Description\n\nThese signifies operations that reach out to a language model with a prompt. These interactions\nwith an AI provider are executed within `Llm::CompletionWorker`-jobs. The worker could execute multiple\nrequests to an AI provider for a single operation.\n\nA success means that we were able to present the user with a response that is delivered to a client that is\nsubscribed to a websocket. An error could be that the AI-provider is not responding, or is erroring.\n\nFor the apdex, we consider an operation fast enough if we were able to get a complete response from the AI provider within\n20 seconds. This not include the time it took for the Sidekiq job to get picked up, or the time it took to deliver\nthe response to the client.\n\nThe `service_class` label on the source metrics tells us which AI related features the operation is for.\n\nThese operations do not go through the API gateway yet, but will in the future.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Sidekiq CompletionWorker logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.class,json.queue,json.meta.project,json.job_status,json.queueing_duration_s,json.duration_s),filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.class.keyword,params:'Llm::CompletionWorker',type:phrase),query:(match:(json.class.keyword:(query:'Llm::CompletionWorker',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),index:'AWNABDRwNDuQHTm2tH6l')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Sidekiq CompletionWorker failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.class,json.queue,json.meta.project,json.job_status,json.queueing_duration_s,json.duration_s),filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.class.keyword,params:'Llm::CompletionWorker',type:phrase),query:(match:(json.class.keyword:(query:'Llm::CompletionWorker',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.job_status,params:fail,type:phrase),query:(match:(json.job_status:(query:fail,type:phrase))))),index:'AWNABDRwNDuQHTm2tH6l')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq CompletionWorker requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.class.keyword,params:'Llm::CompletionWorker',type:phrase),query:(match:(json.class.keyword:(query:'Llm::CompletionWorker',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq CompletionWorker failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.class.keyword,params:'Llm::CompletionWorker',type:phrase),query:(match:(json.class.keyword:(query:'Llm::CompletionWorker',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.job_status,params:fail,type:phrase),query:(match:(json.job_status:(query:fail,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq CompletionWorker sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.class.keyword,params:'Llm::CompletionWorker',type:phrase),query:(match:(json.class.keyword:(query:'Llm::CompletionWorker',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq CompletionWorker sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.class.keyword,params:'Llm::CompletionWorker',type:phrase),query:(match:(json.class.keyword:(query:'Llm::CompletionWorker',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.project.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq CompletionWorker percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.class.keyword,params:'Llm::CompletionWorker',type:phrase),query:(match:(json.class.keyword:(query:'Llm::CompletionWorker',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq CompletionWorker percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.class.keyword,params:'Llm::CompletionWorker',type:phrase),query:(match:(json.class.keyword:(query:'Llm::CompletionWorker',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.project.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "sidekiq_execution SLI (By Shard) Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_shard_apdex:ratio_5m{component=\"sidekiq_execution\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq_execution - {{ shard }} shard apdex"
    },
    {
     "expr": "(1 - 6 * (1 - (\navg by (shard) (slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_execution\",monitor=\"global\",shard=~\"$shard\",type=\"sidekiq\"})\nor\navg by (shard) (slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_execution\",monitor=\"global\",shard=\"\",type=\"sidekiq\"})\n)\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget) - {{ shard }} shard"
    },
    {
     "expr": "(1 - 14.4 * (1 - (\navg by (shard) (slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_execution\",monitor=\"global\",shard=~\"$shard\",type=\"sidekiq\"})\nor\navg by (shard) (slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_execution\",monitor=\"global\",shard=\"\",type=\"sidekiq\"})\n)\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget) - {{ shard }} shard"
    }
   ]
  },
  {
   "title": "sidekiq_execution SLI (By Shard) Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_shard_errors:ratio_5m{component=\"sidekiq_execution\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "sidekiq_execution - {{ shard }} shard error ratio"
    },
    {
     "expr": "(6 * (\navg by (shard) (slo:max:events:gitlab_service_errors:ratio{component=\"sidekiq_execution\",monitor=\"global\",shard=~\"$shard\",type=\"sidekiq\"})\nor\navg by (shard) (slo:max:events:gitlab_service_errors:ratio{component=\"sidekiq_execution\",monitor=\"global\",shard=\"\",type=\"sidekiq\"})\n)\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget) - {{ shard }} shard"
    },
    {
     "expr": "(14.4 * (\navg by (shard) (slo:max:events:gitlab_service_errors:ratio{component=\"sidekiq_execution\",monitor=\"global\",shard=~\"$shard\",type=\"sidekiq\"})\nor\navg by (shard) (slo:max:events:gitlab_service_errors:ratio{component=\"sidekiq_execution\",monitor=\"global\",shard=\"\",type=\"sidekiq\"})\n)\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget) - {{ shard }} shard"
    }
   ]
  },
  {
   "title": "sidekiq_execution SLI (By Shard) RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_shard_ops:rate_5m{component=\"sidekiq_execution\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq_execution - {{ shard }} shard RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "content": "### Description\n\nThe number of Sidekiq jobs meeting their execution duration target based on the urgency of the worker.\nBy default, execution of a job should take no more than 300 seconds. But this can be adjusted by the\nurgency of the worker.\n\nRead more about this in the [runbooks doc](https://gitlab.com/gitlab-com/runbooks/-/blob/master/docs/sidekiq/sidekiq-slis.md).\n\n\n\n### Observability Tools\n\n* [🐞 Sentry Releases](https://new-sentry.gitlab.net/organizations/gitlab/releases/?project=3&environment=${environment})\n* [🐞 Sentry sidekiq issues](https://new-sentry.gitlab.net/organizations/gitlab/issues/?project=3&environment=${environment}&query=stage%3A${stage}+type%3Asidekiq)\n* [📖 Kibana: Sidekiq execution logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.class,json.queue,json.meta.project,json.meta.feature_category,json.job_status,json.queueing_duration_s,json.urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),index:'AWNABDRwNDuQHTm2tH6l')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Sidekiq execution slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.class,json.queue,json.meta.project,json.meta.feature_category,json.job_status,json.queueing_duration_s,json.urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:exists,type:json.target_duration_s,value:exists),query:(exists:(field:json.target_duration_s))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:exists,type:json.duration_s,value:exists),query:(exists:(field:json.duration_s))),!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"script\":+{\"script\":+{\"source\":+\"doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value\"}}}]}}'),query:(bool:(minimum_should_match:1,should:!((script:(script:(source:'doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value'))))))))),index:'AWNABDRwNDuQHTm2tH6l',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Sidekiq execution failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.class,json.queue,json.meta.project,json.meta.feature_category,json.job_status,json.queueing_duration_s,json.urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.job_status,params:fail,type:phrase),query:(match:(json.job_status:(query:fail,type:phrase))))),index:'AWNABDRwNDuQHTm2tH6l')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq execution requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq execution failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.job_status,params:fail,type:phrase),query:(match:(json.job_status:(query:fail,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq execution sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq execution sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.project.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq execution percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq execution percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.project.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "sidekiq_execution_with_external_dependency SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"sidekiq_execution_with_external_dependency\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq_execution_with_external_dependency apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_execution_with_external_dependency\",monitor=\"global\",type=\"sidekiq\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_execution_with_external_dependency\",monitor=\"global\",type=\"sidekiq\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "sidekiq_execution_with_external_dependency SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"sidekiq_execution_with_external_dependency\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "sidekiq_execution_with_external_dependency error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"sidekiq_execution_with_external_dependency\",monitor=\"global\",type=\"sidekiq\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"sidekiq_execution_with_external_dependency\",monitor=\"global\",type=\"sidekiq\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "sidekiq_execution_with_external_dependency SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"sidekiq_execution_with_external_dependency\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq_execution_with_external_dependency RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
   "content": "### Description\n\nThe number of Sidekiq jobs with external dependencies across all shards meeting their execution duration target based on the urgency of the worker.\nBy default, execution of a job should take no more than 300 seconds. But this can be adjusted by the\nurgency of the worker.\n\nRead more about this in the [runbooks doc](https://gitlab.com/gitlab-com/runbooks/-/blob/master/docs/sidekiq/sidekiq-slis.md).\n\n"
  },
  {
   "title": "sidekiq_queueing SLI (By Shard) Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_shard_apdex:ratio_5m{component=\"sidekiq_queueing\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq_queueing - {{ shard }} shard apdex"
    },
    {
     "expr": "(1 - 6 * (1 - (\navg by (shard) (slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_queueing\",monitor=\"global\",shard=~\"$shard\",type=\"sidekiq\"})\nor\navg by (shard) (slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_queueing\",monitor=\"global\",shard=\"\",type=\"sidekiq\"})\n)\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget) - {{ shard }} shard"
    },
    {
     "expr": "(1 - 14.4 * (1 - (\navg by (shard) (slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_queueing\",monitor=\"global\",shard=~\"$shard\",type=\"sidekiq\"})\nor\navg by (shard) (slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_queueing\",monitor=\"global\",shard=\"\",type=\"sidekiq\"})\n)\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget) - {{ shard }} shard"
    }
   ]
  },
  {
   "title": "sidekiq_queueing SLI (By Shard) RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_shard_ops:rate_5m{component=\"sidekiq_queueing\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq_queueing - {{ shard }} shard RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "content": "### Description\n\nThe number of Sidekiq jobs meeting their queueing duration target based on the urgency of the worker.\nBy default, queueing of a job should take no more than 60 seconds. But this can be adjusted by the\nurgency of the worker.\n\nRead more about this in the [runbooks doc](https://gitlab.com/gitlab-com/runbooks/-/blob/master/docs/sidekiq/sidekiq-slis.md).\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Sidekiq queueing logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.class,json.queue,json.meta.project,json.job_status,json.urgency,json.queueing_duration_s,json.target_scheduling_latency_s,json.duration_s),filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),index:'AWNABDRwNDuQHTm2tH6l')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Sidekiq queueing slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.class,json.queue,json.meta.project,json.job_status,json.urgency,json.queueing_duration_s,json.target_scheduling_latency_s,json.duration_s),filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:exists,type:json.target_scheduling_latency_s,value:exists),query:(exists:(field:json.target_scheduling_latency_s))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:exists,type:json.queueing_duration_s,value:exists),query:(exists:(field:json.queueing_duration_s))),!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"script\":+{\"script\":+{\"source\":+\"doc[!'json.queueing_duration_s!'].value+>+doc[!'json.target_scheduling_latency_s!'].value\"}}}]}}'),query:(bool:(minimum_should_match:1,should:!((script:(script:(source:'doc[!'json.queueing_duration_s!'].value+>+doc[!'json.target_scheduling_latency_s!'].value'))))))))),index:'AWNABDRwNDuQHTm2tH6l',sort:!(!(json.queueing_duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq queueing requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq queueing sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.queueing_duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.queueing_duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq queueing sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.queueing_duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.project.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.queueing_duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq queueing percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.queueing_duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.queueing_duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq queueing percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type,params:sidekiq,type:phrase),query:(match:(json.type:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.queueing_duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.project.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.queueing_duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.queueing_duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "sidekiq_queueing_with_external_dependency SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"sidekiq_queueing_with_external_dependency\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq_queueing_with_external_dependency apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_queueing_with_external_dependency\",monitor=\"global\",type=\"sidekiq\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_queueing_with_external_dependency\",monitor=\"global\",type=\"sidekiq\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "sidekiq_queueing_with_external_dependency SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"sidekiq_queueing_with_external_dependency\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq_queueing_with_external_dependency RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
   "content": "### Description\n\nThe number of Sidekiq jobs with external dependencies across all shards meeting their queueing duration target based on the urgency of the worker.\nBy default, queueing of a job should take no more than 60 seconds. But this can be adjusted by the\nurgency of the worker.\n\nRead more about this in the [runbooks doc](https://gitlab.com/gitlab-com/runbooks/-/blob/master/docs/sidekiq/sidekiq-slis.md).\n\n"
  },
  {
   "title": "🔬 SLI Detail: enqueued_jobs",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "enqueued_jobs RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:sidekiq_enqueued_jobs_total:rate_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "enqueued_jobs RPS - per queue",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (queue) (\n  sli_aggregations:sidekiq_enqueued_jobs_total:rate_5m{env=\"$environment\",environment=\"$environment\",queue!=\"\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "enqueued_jobs RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:sidekiq_enqueued_jobs_total:rate_5m{env=\"$environment\",environment=\"$environment\",feature_category!=\"\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "enqueued_jobs RPS - per urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (urgency) (\n  sli_aggregations:sidekiq_enqueued_jobs_total:rate_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",urgency!=\"\"}\n)\n > 0",
       "legendFormat": "{{urgency}}"
      }
     ]
    },
    {
     "title": "enqueued_jobs RPS - per worker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (worker) (\n  sli_aggregations:sidekiq_enqueued_jobs_total:rate_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",worker!=\"\"}\n)\n > 0",
       "legendFormat": "{{worker}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: llm_completion",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "llm_completion Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_llm_completion_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "llm_completion RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_llm_completion_total:rate_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for llm_completion Latency - per feature_category",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_llm_completion_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",feature_category!=\"\",stage=\"$stage\"}\n    )\n    -\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_llm_completion_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",feature_category!=\"\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_llm_completion_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",feature_category!=\"\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "llm_completion Errors - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli_llm_completion_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",feature_category!=\"\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "llm_completion RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli_llm_completion_total:rate_5m{env=\"$environment\",environment=\"$environment\",feature_category!=\"\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for llm_completion Latency - per service_class",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (service_class) (\n      sli_aggregations:gitlab_sli_llm_completion_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",service_class!=\"\",stage=\"$stage\"}\n    )\n    -\n    sum by (service_class) (\n      sli_aggregations:gitlab_sli_llm_completion_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",service_class!=\"\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (service_class) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_llm_completion_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",service_class!=\"\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{service_class}}"
      }
     ]
    },
    {
     "title": "llm_completion Errors - per service_class",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (service_class) (\n  sli_aggregations:gitlab_sli_llm_completion_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",service_class!=\"\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{service_class}}"
      }
     ]
    },
    {
     "title": "llm_completion RPS - per service_class",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (service_class) (\n  sli_aggregations:gitlab_sli_llm_completion_total:rate_5m{env=\"$environment\",environment=\"$environment\",service_class!=\"\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{service_class}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: sidekiq_execution",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 220 },
   "collapsed": true,
   "panels": [
    {
     "title": "sidekiq_execution Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_sidekiq_execution_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "sidekiq_execution RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_sidekiq_execution_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_execution Latency - per worker",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (worker) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n    )\n    -\n    sum by (worker) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n    )\n  )\n  / ignoring (worker) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution Errors - per worker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (worker) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n)\n > 0",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution RPS - per worker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (worker) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n)\n > 0",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_execution Latency - per feature_category",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n    -\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution Errors - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_execution Latency - per urgency",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (urgency) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n    )\n    -\n    sum by (urgency) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n  / ignoring (urgency) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{urgency}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution Errors - per urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (urgency) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{urgency}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution RPS - per urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (urgency) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{urgency}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_execution Latency - per external_dependencies",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (external_dependencies) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n    -\n    sum by (external_dependencies) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n  / ignoring (external_dependencies) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{external_dependencies}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution Errors - per external_dependencies",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (external_dependencies) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{external_dependencies}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution RPS - per external_dependencies",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (external_dependencies) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{external_dependencies}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_execution Latency - per queue",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (queue) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",queue!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n    -\n    sum by (queue) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",queue!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n  / ignoring (queue) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",queue!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution Errors - per queue",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (queue) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",queue!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution RPS - per queue",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (queue) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",queue!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{queue}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: sidekiq_execution_with_external_dependency",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 230 },
   "collapsed": true,
   "panels": [
    {
     "title": "sidekiq_execution_with_external_dependency Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_sidekiq_execution_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "sidekiq_execution_with_external_dependency RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_sidekiq_execution_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_execution_with_external_dependency Latency - per worker",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (worker) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n    )\n    -\n    sum by (worker) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n    )\n  )\n  / ignoring (worker) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution_with_external_dependency Errors - per worker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (worker) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n)\n > 0",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution_with_external_dependency RPS - per worker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (worker) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n)\n > 0",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_execution_with_external_dependency Latency - per feature_category",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n    -\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution_with_external_dependency Errors - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution_with_external_dependency RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_execution_with_external_dependency Latency - per urgency",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (urgency) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n    )\n    -\n    sum by (urgency) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n  / ignoring (urgency) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{urgency}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution_with_external_dependency Errors - per urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (urgency) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{urgency}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution_with_external_dependency RPS - per urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (urgency) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{urgency}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_execution_with_external_dependency Latency - per external_dependencies",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (external_dependencies) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n    -\n    sum by (external_dependencies) (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n  / ignoring (external_dependencies) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_execution_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{external_dependencies}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution_with_external_dependency Errors - per external_dependencies",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (external_dependencies) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_error_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{external_dependencies}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution_with_external_dependency RPS - per external_dependencies",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (external_dependencies) (\n  sli_aggregations:gitlab_sli_sidekiq_execution_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{external_dependencies}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: sidekiq_queueing",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 240 },
   "collapsed": true,
   "panels": [
    {
     "title": "sidekiq_queueing RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_queueing Latency - per worker",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (worker) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n    )\n    -\n    sum by (worker) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n    )\n  )\n  / ignoring (worker) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "sidekiq_queueing RPS - per worker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (worker) (\n  sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n)\n > 0",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_queueing Latency - per feature_category",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n    -\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "sidekiq_queueing RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_queueing Latency - per urgency",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (urgency) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n    )\n    -\n    sum by (urgency) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n  / ignoring (urgency) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{urgency}}"
      }
     ]
    },
    {
     "title": "sidekiq_queueing RPS - per urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (urgency) (\n  sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{urgency}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_queueing Latency - per external_dependencies",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (external_dependencies) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n    -\n    sum by (external_dependencies) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n  / ignoring (external_dependencies) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{external_dependencies}}"
      }
     ]
    },
    {
     "title": "sidekiq_queueing RPS - per external_dependencies",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (external_dependencies) (\n  sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{external_dependencies}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_queueing Latency - per queue",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (queue) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",queue!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n    -\n    sum by (queue) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",queue!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n  / ignoring (queue) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",queue!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "sidekiq_queueing RPS - per queue",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (queue) (\n  sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"yes\",queue!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{queue}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: sidekiq_queueing_with_external_dependency",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 250 },
   "collapsed": true,
   "panels": [
    {
     "title": "sidekiq_queueing_with_external_dependency RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_queueing_with_external_dependency Latency - per worker",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (worker) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n    )\n    -\n    sum by (worker) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n    )\n  )\n  / ignoring (worker) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "sidekiq_queueing_with_external_dependency RPS - per worker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (worker) (\n  sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",worker!=\"\"}\n)\n > 0",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_queueing_with_external_dependency Latency - per feature_category",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n    -\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "sidekiq_queueing_with_external_dependency RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",feature_category!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_queueing_with_external_dependency Latency - per urgency",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (urgency) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n    )\n    -\n    sum by (urgency) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n  / ignoring (urgency) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{urgency}}"
      }
     ]
    },
    {
     "title": "sidekiq_queueing_with_external_dependency RPS - per urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (urgency) (\n  sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies=\"yes\",stage=\"$stage\",type=\"sidekiq\",urgency!=\"\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{urgency}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_queueing_with_external_dependency Latency - per external_dependencies",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (external_dependencies) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n    -\n    sum by (external_dependencies) (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_success_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n  / ignoring (external_dependencies) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{external_dependencies}}"
      }
     ]
    },
    {
     "title": "sidekiq_queueing_with_external_dependency RPS - per external_dependencies",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (external_dependencies) (\n  sli_aggregations:gitlab_sli_sidekiq_queueing_apdex_total:rate_5m{env=\"$environment\",environment=\"$environment\",external_dependencies!=\"\",stage=\"$stage\",type=\"sidekiq\",worker!=\"ProjectExportWorker\"}\n)\n > 0",
       "legendFormat": "{{external_dependencies}}"
      }
     ]
    }
   ]
  },
  {
   "title": "☸️ Kubernetes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 },
   "collapsed": true,
   "panels": [
    {
     "title": "sidekiq-ai-abstraction-layer Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-ai-abstraction-layer Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-ai-abstraction-layer Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-ai-abstraction-layer\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-catchall Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-catchall Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-catchall Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-database-throttled Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-database-throttled Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-database-throttled Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-elasticsearch Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-elasticsearch Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-elasticsearch Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-gitaly-throttled Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-gitaly-throttled Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-gitaly-throttled Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-low-urgency-cpu-bound Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-low-urgency-cpu-bound Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-low-urgency-cpu-bound Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-memory-bound Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-memory-bound Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-memory-bound Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-quarantine Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-quarantine Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-quarantine Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-urgent-authorized-projects Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-urgent-authorized-projects Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 65 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-urgent-authorized-projects Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 65 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-urgent-cpu-bound Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-urgent-cpu-bound Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-urgent-cpu-bound Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-urgent-other Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-urgent-other Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 81 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "sidekiq-urgent-other Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 81 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "excluded_sidekiq_thread_contention component saturation: Excluded Shards Sidekiq Ruby Thread Contention",
     "type": "graph",
     "description": "Ruby (technically Ruby MRI), like some other scripting languages, uses a Global VM lock (GVL) also known as a\nGlobal Interpreter Lock (GIL) to ensure that multiple threads can execute safely. Ruby code is only allowed to\nexecute in one thread in a process at a time. When calling out to c extensions, the thread can cede the lock to\nother thread while it continues to execute.\n\nThis means that when CPU-bound workloads run in a multithreaded environment such as Puma or Sidekiq, contention\nwith other Ruby worker threads running in the same process can occur, effectively slowing thoses threads down as\nthey await GVL entry.\n\nOften the best fix for this situation is to add more workers by scaling up the fleet.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, fqdn, pod) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      rate(ruby_process_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", shard=\"memory-bound\"}[1h])\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ pod }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"excluded_sidekiq_thread_contention\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"excluded_sidekiq_thread_contention\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"excluded_sidekiq_thread_contention\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"excluded_sidekiq_thread_contention\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"excluded_sidekiq_thread_contention\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_cpu component saturation: Kube Container CPU Utilization",
     "type": "graph",
     "description": "Kubernetes containers are allocated a share of CPU. Configured using resource requests.\n\nThis is the amount of CPU that a container should always have available,\nthough it can briefly utilize more. However, if a lot of pods on the same\nhost exceed their requested CPU the container could be throttled earlier.\n\nThis monitors utilization/allocated requests over a 1 hour period, and takes\nthe 99th quantile of that utilization percentage in that period.\nWe want the worst case to be around 80%-90% utilization,\nmeaning we've sized the container correctly. If utilization is much higher than that\nthe container could already be throttled because the host is overused, if it\nis much lower, then we could be underutilizing a host.\n\nThis saturation point is only used for capacity planning.\nContainers that have a quota specified are excluded here and can be monitored using\nthe `kube_container_throttling` saturation component.\nThe burst utilization of a CPU is monitored and alerted upon using the\n`kube_container_cpu_limit` saturation point.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, pod, container) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      (\n        sum by (environment, tier, type, stage, shard, pod, container) (\n          rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}[1h])\n        )\n        unless on(environment, tier, type, stage, shard, pod, container) (\n          last_over_time(container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}[1h])\n        )\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        kube_pod_container_resource_requests:labeled{container!=\"\", container!=\"POD\", resource=\"cpu\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"kube_container_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_cpu_limit component saturation: Kube Container CPU over-utilization",
     "type": "graph",
     "description": "Kubernetes containers can have a limit configured on how much CPU they can consume in\na burst. If we are at this limit, exceeding the allocated requested resources, we\nshould consider revisting the container's HPA configuration.\n\nWhen a container is utilizing CPU resources up-to it's configured limit for\nextended periods of time, this could cause it and other running containers to be\nthrottled.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, pod, container) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard, pod, container) (\n        rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}[5m])\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}\n        /\n        container_spec_cpu_period:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"kube_container_cpu_limit\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_rss component saturation: Kube Container Memory Utilization (RSS)",
     "type": "graph",
     "description": "Records the total anonymous (unevictable) memory utilization for containers for this\nservice, as a percentage of the memory limit as configured through Kubernetes.\n\nThis is computed using the container's resident set size (RSS), as opposed to\nkube_container_memory which uses the working set size. For our purposes, RSS is the\nbetter metric as cAdvisor's working set calculation includes pages from the\nfilesystem cache that can (and will) be evicted before the OOM killer kills the\ncgroup.\n\nA container's RSS (anonymous memory usage) is still not precisely what the OOM\nkiller will use, but it's a better approximation of what the container's workload is\nactually using. RSS metrics can, however, be dramatically inflated if a process in\nthe container uses MADV_FREE (lazy-free) memory. RSS will include the memory that is\navailable to be reclaimed without a page fault, but not currently in use.\n\nThe most common case of OOM kills is for anonymous memory demand to overwhelm the\ncontainer's memory limit. On swapless hosts, anonymous memory cannot be evicted from\nthe page cache, so when a container's memory usage is mostly anonymous pages, the\nonly remaining option to relieve memory pressure may be the OOM killer.\n\nAs container RSS approaches container memory limit, OOM kills become much more\nlikely. Consequently, this ratio is a good leading indicator of memory saturation\nand OOM risk.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      container_memory_rss:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}\n      /\n      (container_spec_memory_limit_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"} > 0)\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"kube_container_rss\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"kube_container_rss\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"kube_container_rss\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_rss\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_rss\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_throttling component saturation: Kube container throttling",
     "type": "graph",
     "description": "Kube container throttling\n\nA container will be throttled if it reaches the configured cpu limit for the\nhorizontal pod autoscaler. Or when other containers on the node are overutilizing\nthe the CPU.\n\nTo get around this, consider increasing the limit for this workload, taking\ninto consideration the requested resources.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, pod, container) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      avg by (environment, tier, type, stage, shard, pod, container)(\n        rate(container_cpu_cfs_throttled_periods_total:labeled{container!=\"\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}[5m])\n        /\n        rate(container_cpu_cfs_periods_total:labeled{container!=\"\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"kube_container_throttling\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"kube_container_throttling\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"kube_container_throttling\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_throttling\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_throttling\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_horizontalpodautoscaler_desired_replicas component saturation: Horizontal Pod Autoscaler Desired Replicas",
     "type": "graph",
     "description": "The [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)\nautomatically scales the number of Pods in a deployment based on metrics.\n\nThe Horizontal Pod Autoscaler has a configured upper maximum. When this\nlimit is reached, the HPA will not increase the number of pods and other\nresource saturation (eg, CPU, memory) may occur.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, horizontalpodautoscaler, shard) (\n  clamp_min(\n    clamp_max(\n      kube_horizontalpodautoscaler_status_desired_replicas:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", shard!~\"ai-abstraction-layer|database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects\", namespace!~\"pubsubbeat\"}\n      /\n      kube_horizontalpodautoscaler_spec_max_replicas:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", shard!~\"ai-abstraction-layer|database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects\", namespace!~\"pubsubbeat\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ horizontalpodautoscaler }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "rails_db_connection_pool component saturation: Rails DB Connection Pool Utilization",
     "type": "graph",
     "description": "Rails uses connection pools for its database connections. As each\nnode may have multiple connection pools, this is by node and by\ndatabase host.\n\nRead more about this resource in our [documentation](https://docs.gitlab.com/ee/development/database/client_side_connection_pool.html#client-side-connection-pool).\n\nIf this resource is saturated, it may indicate that our connection\npools are not correctly sized, perhaps because an unexpected\napplication thread is using a database connection.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, instance, host, port) (\n  clamp_min(\n    clamp_max(\n      (\n        avg_over_time(gitlab_database_connection_pool_busy{class=\"ActiveRecord::Base\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}[5m])\n        +\n        avg_over_time(gitlab_database_connection_pool_dead{class=\"ActiveRecord::Base\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}[5m])\n      )\n      /\n      gitlab_database_connection_pool_size{class=\"ActiveRecord::Base\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ instance }} {{ host }} {{ port }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"rails_db_connection_pool\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"rails_db_connection_pool\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"rails_db_connection_pool\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"rails_db_connection_pool\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"rails_db_connection_pool\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "sidekiq_shard_workers component saturation: Sidekiq Worker Utilization per shard",
     "type": "graph",
     "description": "Sidekiq worker utilization per shard.\n\nThis metric represents the percentage of available threads*workers that are actively processing jobs.\n\nWhen this metric is saturated, new Sidekiq jobs will queue. Depending on whether or not the jobs are latency sensitive,\nthis could impact user experience.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, shard) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard, shard) (\n        avg_over_time(sidekiq_running_jobs{shard!~\"ai-abstraction-layer|database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}[5m])\n      )\n      /\n      sum by (environment, tier, type, stage, shard, shard) (\n        avg_over_time(sidekiq_concurrency{shard!~\"ai-abstraction-layer|database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"sidekiq_shard_workers\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"sidekiq_shard_workers\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"sidekiq_shard_workers\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"sidekiq_shard_workers\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"sidekiq_shard_workers\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "sidekiq_thread_contention component saturation: Sidekiq Ruby Thread Contention",
     "type": "graph",
     "description": "Ruby (technically Ruby MRI), like some other scripting languages, uses a Global VM lock (GVL) also known as a\nGlobal Interpreter Lock (GIL) to ensure that multiple threads can execute safely. Ruby code is only allowed to\nexecute in one thread in a process at a time. When calling out to c extensions, the thread can cede the lock to\nother thread while it continues to execute.\n\nThis means that when CPU-bound workloads run in a multithreaded environment such as Puma or Sidekiq, contention\nwith other Ruby worker threads running in the same process can occur, effectively slowing thoses threads down as\nthey await GVL entry.\n\nOften the best fix for this situation is to add more workers by scaling up the fleet.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, fqdn, pod) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      rate(ruby_process_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", shard!~\"memory-bound\"}[1h])\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ pod }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"sidekiq_thread_contention\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"sidekiq_thread_contention\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\", component=\"sidekiq_thread_contention\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"sidekiq_thread_contention\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"sidekiq_thread_contention\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  { "title": "Sidekiq Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Sidekiq Aggregated Queue Length",
   "type": "graph",
   "description": "The total number of jobs in the system queued up to be executed. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "expr": "sum(sidekiq_queue_size{environment=\"$environment\"} and on(fqdn) (redis_connected_slaves != 0))\n",
     "legendFormat": "Total Jobs"
    }
   ]
  },
  {
   "title": "Sidekiq Queue Lengths per Queue",
   "type": "graph",
   "description": "The number of jobs queued up to be executed. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "expr": "max_over_time(sidekiq_queue_size{environment=\"$environment\"}[$__interval]) and on(fqdn) (redis_connected_slaves != 0)\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Sidekiq Queue Lengths per Worker",
   "type": "graph",
   "description": "The number of jobs queued up to be executed. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1011 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "expr": "max_over_time(sidekiq_enqueued_jobs{environment=\"$environment\"}[$__interval]) and on(fqdn) (redis_connected_slaves != 0)\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Sidekiq Queuing Latency per Queue",
   "type": "graph",
   "description": "How long the oldest job has been waiting in the queue to execute. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1011 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(sidekiq_queue_latency_seconds{environment=\"$environment\"}[$__interval]) and on (fqdn) (redis_connected_slaves != 0)\nor\navg_over_time(sidekiq_queue_latency{environment=\"$environment\"}[$__interval]) and on (fqdn) (redis_connected_slaves != 0)\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Sidekiq Queues (Global Search)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1500 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global search incremental indexing queue length",
     "type": "graph",
     "description": "The number of records waiting to be synced to Elasticsearch for Global Search. These are picked up in batches every minute. Lower is better but the batching every minute means it will not usually stay at 0. Steady growth over a sustained period of time indicates that ElasticIndexBulkCronWorker is not keeping up.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1501 },
     "yaxes": [
      { "format": "short", "label": "Queue Length" }
     ],
     "targets": [
      {
       "expr": "quantile(0.10, global_search_bulk_cron_queue_size{environment=\"$environment\"})\n",
       "legendFormat": "p10"
      },
      {
       "expr": "quantile(0.50, global_search_bulk_cron_queue_size{environment=\"$environment\"})\n",
       "legendFormat": "p50"
      },
      {
       "expr": "quantile(0.90, global_search_bulk_cron_queue_size{environment=\"$environment\"})\n",
       "legendFormat": "p90"
      }
     ]
    },
    {
     "title": "Global search initial indexing queue length",
     "type": "graph",
     "description": "The number of records waiting to be synced to Elasticsearch for Global Search during initial project backfill. These jobs are created when projects are imported or when Elasticsearch is enabled for a group in order to backfill all project data to the index. These are picked up in batches every minute. Lower is better but the batching every minute means it will not usually stay at 0. Sudden spikes are expected if a large group is enabled for Elasticsearch but sustained steady growth over a long period of time may indicate that ElasticIndexInitialBulkCronWorker is not keeping up.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1501 },
     "yaxes": [
      { "format": "short", "label": "Queue Length" }
     ],
     "targets": [
      {
       "expr": "quantile(0.10, global_search_bulk_cron_initial_queue_size{environment=\"$environment\"})\n",
       "legendFormat": "p10"
      },
      {
       "expr": "quantile(0.50, global_search_bulk_cron_initial_queue_size{environment=\"$environment\"})\n",
       "legendFormat": "p50"
      },
      {
       "expr": "quantile(0.90, global_search_bulk_cron_initial_queue_size{environment=\"$environment\"})\n",
       "legendFormat": "p90"
      }
     ]
    },
    {
     "title": "Global search awaiting indexing queue length",
     "type": "graph",
     "description": "The number of records waiting to be synced to Elasticsearch for Global Search while indexing is paused.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1511 },
     "yaxes": [
      { "format": "short", "label": "Queue Length" }
     ],
     "targets": [
      {
       "expr": "quantile(0.10, global_search_awaiting_indexing_queue_size{environment=\"$environment\"})\n",
       "legendFormat": "p10"
      },
      {
       "expr": "quantile(0.50, global_search_awaiting_indexing_queue_size{environment=\"$environment\"})\n",
       "legendFormat": "p50"
      },
      {
       "expr": "quantile(0.90, global_search_awaiting_indexing_queue_size{environment=\"$environment\"})\n",
       "legendFormat": "p90"
      }
     ]
    }
   ]
  },
  { "title": "Sidekiq Future Sets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Sidekiq Scheduled Set Delay",
   "type": "graph",
   "description": "How late is scheduled job that is next to execute. Lower is better; up to 20 seconds is normal",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sidekiq_schedule_set_processing_delay_seconds{environment=\"$environment\"} and on(fqdn) (redis_connected_slaves != 0)\n",
     "legendFormat": "Delay"
    }
   ]
  },
  {
   "title": "Sidekiq Scheduled Set Backlog",
   "type": "graph",
   "description": "How many scheduled jobs are overdue. Lower is better; periodic processing means some backlog is normal",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2001 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sidekiq_schedule_set_backlog_count{environment=\"$environment\"} and on(fqdn) (redis_connected_slaves != 0)\n",
     "legendFormat": "Backlog"
    }
   ]
  },
  {
   "title": "Sidekiq Retry Set Delay",
   "type": "graph",
   "description": "How late is retry job that is next to execute. Lower is better; up to 20 seconds is normal",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2011 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sidekiq_retry_set_processing_delay_seconds{environment=\"$environment\"} and on(fqdn) (redis_connected_slaves != 0)\n",
     "legendFormat": "Delay"
    }
   ]
  },
  {
   "title": "Sidekiq Retry Set Backlog",
   "type": "graph",
   "description": "How many retry jobs are overdue. Lower is better; periodic processing means some backlog is normal",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2011 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sidekiq_retry_set_backlog_count{environment=\"$environment\"} and on(fqdn) (redis_connected_slaves != 0)\n",
     "legendFormat": "Backlog"
    }
   ]
  },
  { "title": "Sidekiq Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2500 } },
  {
   "title": "Sidekiq Total Execution Time",
   "type": "graph",
   "description": "The sum of job execution times",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2501 },
   "yaxes": [
    { "format": "s", "label": "Job time completed per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_completion_seconds_sum{environment=\"$environment\"}[$__interval]))\n",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Sidekiq Total Execution Time Per Shard",
   "type": "graph",
   "description": "The sum of job execution times",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2501 },
   "yaxes": [
    { "format": "s", "label": "Job time completed per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_completion_seconds_sum{environment=\"$environment\"}[$__interval])) by (shard)\n",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Sidekiq Aggregated Throughput",
   "type": "graph",
   "description": "The total number of jobs being completed",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2511 },
   "yaxes": [
    { "format": "short", "label": "Jobs Completed per Second" }
   ],
   "targets": [
    {
     "expr": "sum(application_sli_aggregation:sidekiq_execution:ops:rate_5m{monitor=\"global\", environment=\"$environment\"})\n",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Sidekiq Throughput per Shard",
   "type": "graph",
   "description": "The total number of jobs being completed per shard",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2511 },
   "yaxes": [
    { "format": "short", "label": "Jobs Completed per Second" }
   ],
   "targets": [
    {
     "expr": "gitlab_component_shard_ops:rate_5m{monitor=\"global\", environment=\"$environment\", component=\"sidekiq_execution\"}\n",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Sidekiq Throughput per Job",
   "type": "graph",
   "description": "The total number of jobs being completed per worker",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2521 },
   "yaxes": [
    { "format": "short", "label": "Jobs Completed per Second" }
   ],
   "targets": [
    {
     "expr": "sum(application_sli_aggregation:sidekiq_execution:ops:rate_5m{monitor=\"global\", environment=\"$environment\"}) by (worker)\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Sidekiq Aggregated Inflight Operations",
   "type": "graph",
   "description": "The total number of jobs being executed at a single moment",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2521 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sidekiq_running_jobs{environment=\"$environment\"})\n",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Sidekiq Inflight Operations by Shard",
   "type": "graph",
   "description": "The total number of jobs being executed at a single moment, for each queue",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2531 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sidekiq_running_jobs{environment=\"$environment\"}) by (shard)\n",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Sidekiq Job Latency per shard",
   "type": "text",
   "description": "The duration, once a job starts executing, that it runs for, by shard. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2531 },
   "content": "* [📈 Kibana: Sidekiq execution time median latency (aggregated by shard)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(50)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.shard.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Sidekiq execution time p95 percentile latency (aggregated by shard)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.type.keyword,params:sidekiq,type:phrase),query:(match:(json.type.keyword:(query:sidekiq,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.shard.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n"
  },
  { "title": "Shard Workloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 } },
  {
   "title": "Sidekiq Worker Saturation by Shard",
   "type": "graph",
   "description": "Shows sidekiq worker saturation. Once saturated, all sidekiq workers will be busy processing jobs, and any new jobs that arrive will queue. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3001 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(max by(shard, environment, type, stage) (\n  sum by (fqdn, instance, shard, environment, type, stage) (sidekiq_running_jobs{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\"})\n  /\n  sum by (fqdn, instance, shard, environment, type, stage) (sidekiq_concurrency{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\"})\n)\n,1),0)\n",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Node Average CPU Utilization per Shard",
   "type": "graph",
   "description": "The maximum utilization of a single core on each node. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3001 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(1 - rate(node_cpu_seconds_total{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", mode=\"idle\"}[$__interval])) by (shard)\n,1),0)\n",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Node Maximum Single Core Utilization per Shard",
   "type": "graph",
   "description": "The maximum utilization of a single core on each node. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3011 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(max(1 - rate(node_cpu_seconds_total{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", mode=\"idle\"}[$__interval])) by (shard)\n,1),0)\n",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Maximum Memory Utilization per Shard",
   "type": "graph",
   "description": "Memory utilization. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3011 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(max by (shard) (\n  instance:node_memory_utilization:ratio{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\"}\n)\n,1),0)\n",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Rails Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5000 },
   "collapsed": true,
   "panels": [
    {
     "title": "p95 Latency Estimate",
     "type": "graph",
     "description": "95th percentile Latency. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95,\n  sum(job_environment:gitlab_transaction_duration_seconds_bucket:rate5m{\n    environment=\"$environment\",\n    type=\"sidekiq\",\n    stage=\"$stage\"\n  }) by (le, job)\n)\n",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Rails Total Time",
     "type": "graph",
     "description": "Seconds of Rails processing, per second",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  job_environment:gitlab_transaction_duration_seconds_sum:rate1m{\n    environment=\"$environment\",\n    type=\"sidekiq\",\n    stage=\"$stage\"}\n) by (job)\n",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Rails Queue Time",
     "type": "graph",
     "description": "Time spend waiting for a rails worker",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(\n    gitlab_transaction_rails_queue_duration_total{\n      environment=\"$environment\",\n      type=\"sidekiq\",\n      stage=\"$stage\"}\n      [$__interval]\n  )\n) by (job)\n",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Cache Operations",
     "type": "graph",
     "description": "Cache Operations per Second",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(\n    gitlab_cache_operations_total{\n      environment=\"$environment\",\n      type=\"sidekiq\",\n      stage=\"$stage\"}[$__interval]\n  )\n) by (job)\n",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "gitlab-rails Process restarts",
     "type": "graph",
     "description": "The number of times this process restarted in a given period, including children workers. Restarts are associated with poor client experience, so lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Process restarts" }
     ],
     "targets": [
      {
       "expr": "sum(\n  changes(\n    ruby_process_start_time_seconds{\n      environment=\"$environment\",\n      type=\"sidekiq\",\n      stage=\"$stage\",\n      job=\"gitlab-rails\"\n    }[$__interval]\n  )\n)\n",
       "legendFormat": "process restarts"
      }
     ]
    },
    {
     "title": "Database load balancer: average secondary connections per client",
     "type": "graph",
     "description": "This graph shows the average number of secondary database connections\n        per process. A value of zero indicates that the secondary replicas are unreachable.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Average connections" }
     ],
     "targets": [
      {
       "expr": "avg(\n  avg_over_time(\n    db_load_balancing_hosts{\n      environment=\"$environment\",\n      type=\"sidekiq\",\n      stage=\"$stage\"}[$__interval]\n  )\n) by (job)\n",
       "legendFormat": "{{ job }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni\n  pgbouncer\n  redis\n  redis-cluster-cache\n  redis-cluster-queues-meta\n  redis-cluster-repo-cache\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph inf\n  search\n  zoekt\nend\n\nsubgraph stor\n  gitaly\n  google-cloud-storage\nend\n\nsubgraph sv\n  consul\n  ext-pvs\n  sidekiq\nend\n\n\n  gitaly --> gitaly\npgbouncer --> patroni\nsidekiq --> consul\nsidekiq --> ext-pvs\nsidekiq --> gitaly\nsidekiq --> google-cloud-storage\nsidekiq --> patroni\nsidekiq --> pgbouncer\nsidekiq --> redis\nsidekiq --> redis-cluster-cache\nsidekiq --> redis-cluster-queues-meta\nsidekiq --> redis-cluster-repo-cache\nsidekiq --> redis-sidekiq\nsidekiq --> redis-tracechunks\nsidekiq --> search\nsidekiq --> zoekt\n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni\n  pgbouncer\n  redis\n  redis-cluster-cache\n  redis-cluster-queues-meta\n  redis-cluster-repo-cache\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph inf\n  search\n  zoekt\nend\n\nsubgraph stor\n  gitaly\n  google-cloud-storage\nend\n\nsubgraph sv\n  consul\n  ext-pvs\n  sidekiq\nend\n\n\n  gitaly --> gitaly\npgbouncer --> patroni\nsidekiq --> consul\nsidekiq --> ext-pvs\nsidekiq --> gitaly\nsidekiq --> google-cloud-storage\nsidekiq --> patroni\nsidekiq --> pgbouncer\nsidekiq --> redis\nsidekiq --> redis-cluster-cache\nsidekiq --> redis-cluster-queues-meta\nsidekiq --> redis-cluster-repo-cache\nsidekiq --> redis-sidekiq\nsidekiq --> redis-tracechunks\nsidekiq --> search\nsidekiq --> zoekt\n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni[\"patroni (Level 2)\"]\n  pgbouncer[\"pgbouncer (Level 1)\"]\n  redis-cluster-cache[\"redis-cluster-cache (Level 2)\"]\n  redis-cluster-queues-meta[\"redis-cluster-queues-meta (Level 2)\"]\n  redis-cluster-repo-cache[\"redis-cluster-repo-cache (Level 2)\"]\n  redis-sidekiq[\"redis-sidekiq (Level 3)\"]\n  redis-tracechunks[\"redis-tracechunks (Level 3)\"]\n  redis[\"redis (Level 3)\"]\nend\n\nsubgraph inf\n  search[\"search (Level 1)\"]\n  zoekt[\"zoekt (Level 1)\"]\nend\n\nsubgraph stor\n  gitaly[\"gitaly (Level 3)\"]\n  google-cloud-storage[\"google-cloud-storage (Level 2)\"]\nend\n\nsubgraph sv\n  consul[\"consul (Level 1)\"]\n  ext-pvs[\"ext-pvs (Level 2)\"]\n  sidekiq[\"sidekiq (Level 2)\"]\nend\n\n\n  gitaly[\"gitaly (Level 3)\"] --> gitaly\npgbouncer[\"pgbouncer (Level 1)\"] --> patroni\nsidekiq[\"sidekiq (Level 2)\"] --> consul\nsidekiq[\"sidekiq (Level 2)\"] --> ext-pvs\nsidekiq[\"sidekiq (Level 2)\"] --> gitaly\nsidekiq[\"sidekiq (Level 2)\"] --> google-cloud-storage\nsidekiq[\"sidekiq (Level 2)\"] --> patroni\nsidekiq[\"sidekiq (Level 2)\"] --> pgbouncer\nsidekiq[\"sidekiq (Level 2)\"] --> redis\nsidekiq[\"sidekiq (Level 2)\"] --> redis-cluster-cache\nsidekiq[\"sidekiq (Level 2)\"] --> redis-cluster-queues-meta\nsidekiq[\"sidekiq (Level 2)\"] --> redis-cluster-repo-cache\nsidekiq[\"sidekiq (Level 2)\"] --> redis-sidekiq\nsidekiq[\"sidekiq (Level 2)\"] --> redis-tracechunks\nsidekiq[\"sidekiq (Level 2)\"] --> search\nsidekiq[\"sidekiq (Level 2)\"] --> zoekt\n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}