# DO NOT MANUALLY EDIT; Run ./scripts/update-asdf-version-variables.sh to update this
variables:
    GL_ASDF_GO_JSONNET_VERSION: 0.18.0
    GL_ASDF_GOLANG_VERSION: 1.17.6
    GL_ASDF_JB_VERSION: 0.4.0
    GL_ASDF_JSONNET_TOOL_VERSION: 1.7.0
    GL_ASDF_PROMTOOL_VERSION: 2.34.0
    GL_ASDF_RUBY_VERSION: 3.0.1
    GL_ASDF_SHELLCHECK_VERSION: 0.7.0
    GL_ASDF_SHFMT_VERSION: 3.0.2
    GL_ASDF_THANOS_VERSION: 0.20.1
