---
# From https://gitlab.com/gitlab-org/gitlab/-/blob/master/.markdownlint.yml
header-style:
  style: "atx"
line-length: false
no-inline-html: false
first-line-h1: false
emphasis-style: false

# TODO:
code-block-style: false
fenced-code-language: false
no-blanks-blockquote: false
no-space-in-code: false
ol-prefix: false
no-empty-links: false
no-alt-text: false
no-emphasis-as-header: false
single-h1: false
no-duplicate-header: false
header-increment: false
