---
exclude: ^spec/fixtures/|\.svg$|\.svg$|\.excalidraw$|\.drawio$|reference-architectures/get-hybrid/config|test/lib/shunit2
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
<<<<<<< before updating
        args: [--branch, master]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/google/go-jsonnet
    rev: v0.20.0
    hooks:
      - id: jsonnet-format
        args: [-i, --string-style, s, -n, "2"]
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck -e SC1090,SC1091,SC2002
        language: system
        files: '^(.*\.sh|bin/[^\.]*)$'
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.6.0-2  # Note: keep this in sync with .tool-versions
    hooks:
      - id: shfmt
        args: ["-i", "2", "-ci"]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1  # renovate:managed
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yaml]
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4  # renovate:managed
    hooks:
      - id: gitleaks
=======
        args: [--branch, main]
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]

  # pre-commit tasks from common-ci-tasks
  # Documentation available at
  # https://gitlab.com/gitlab-com/gl-infra/common-ci-tasks/-/blob/main/docs/pre-commit.md
  - repo: https://gitlab.com/gitlab-com/gl-infra/common-ci-tasks
    rev: v2.25  # renovate:managed

    hooks:
      - id: shellcheck  # Run shellcheck for changed Shell files
      - id: shfmt  # Run shellcheck for changed Shell files
      - id: update-asdf-version-variables  # Update .gitlab-ci-asdf-versions.yml if .tool-versions has changed

      # - id: gitlint  # Checks your git commit messages for style
      - id: gitleaks  #  Detect hardcoded secrets using Gitleaks
      - id: editorconfig  # Validate text files against .editorconfig
      - id: yamllint  # Validate YAML files using yamllint
      - id: go-fmt  # Run gofmt for changed Go files
      - id: go-imports  # Run go-imports for changed Go files
      - id: go-mod-tidy  # Run go mod tidy for changed Go files
      - id: go-test  # Run go test for the project if any go files have changed
      - id: golangci-lint  # Run golangci-lint for changed Go files
>>>>>>> after updating
