---
extends: default

ignore: |
<<<<<<< before updating
  vendor/
  mimir-rules/
=======
  .copier-*.yml
>>>>>>> after updating

rules:
  document-start: disable
  indentation:
    indent-sequences: consistent
    spaces: 2
  line-length: disable
