---
extends: default
rules:
  line-length: disable
  document-start: disable
  colons:
    level: warning
  empty-lines:
    level: warning
  indentation:
    level: warning
    spaces: 2
    indent-sequences: whatever
  new-line-at-end-of-file:
    level: warning
  trailing-spaces:
    level: warning
