{
 "title": "general: Pagespeed",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7927277014 at Thu Sep 26 12:03:45 UTC 2024",
 "tags": [
  "managed",
  "general"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values(pagespeed_lighthouse_category_score,host)"
   },
   {
    "name": "path",
    "label": "path",
    "query": "label_values(pagespeed_lighthouse_category_score{env=\"ops\", host=\"$host\"},path)"
   },
   {
    "name": "strategy",
    "label": "strategy",
    "query": "label_values(pagespeed_lighthouse_category_score,strategy)"
   },
   { "name": "diff", "label": "Diff", "query": "1d,2d,1w, 2w, 1m" }
  ]
 },
 "panels": [
  { "title": "Overview ($strategy)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "strategy" },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "content": "#### Lighthouse scores for $strategy\n* 0 to 49 (slow): Red\n* 50 to 89 (average): Orange\n* 90 to 100 (fast): Green\n"
  },
  {
   "title": "Performance Score",
   "type": "singlestat",
   "description": "Performance Score",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pagespeed_lighthouse_category_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\",category=\"performance\"} * 100)"
    }
   ]
  },
  {
   "title": "Accessibility Score",
   "type": "singlestat",
   "description": "The Accessibility score is a weighted average of all the accessibility audits. See Scoring Details for a full list of how each audit is weighted. The heavier-weighted audits have a bigger impact on your score.\n\nEach accessibility audit is pass or fail. Unlike the Performance audits, a page doesn't get points for partially passing an accessibility audit. For example, if some elements have screenreader-friendly names, but others don't, that page gets a 0 for the screenreader-friendly-names audit.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pagespeed_lighthouse_category_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\",category=\"accessibility\"} * 100)"
    }
   ]
  },
  {
   "title": "PWA Score",
   "type": "singlestat",
   "description": "Lighthouse returns a Progressive Web App (PWA) score between 0 and 100. 0 is the worst possible score, and 100 is the best.\n\nThe PWA audits are based on the Baseline PWA Checklist, which lists 14 requirements. Lighthouse has automated audits for 11 of the 14 requirements. The remaining 3 can only be tested manually. Each of the 11 automated PWA audits are weighted equally, so each one contributes approximately 9 points to your PWA score.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pagespeed_lighthouse_category_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\",category=\"pwa\"} * 100)"
    }
   ]
  },
  {
   "title": "SEO Score",
   "type": "singlestat",
   "description": "Search Engine Optimization Score",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pagespeed_lighthouse_category_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\",category=\"seo\"} * 100)"
    }
   ]
  },
  {
   "title": "Best Practices Score",
   "type": "singlestat",
   "description": "Lighthouse returns a Best Practices score between 0 and 100. 0 is the worst possible score, and 100 is the best.\n\nThe Best Practices audits are equally weighted. To calculate how much each audit contributes to your overall Best Practices score, count the number of Best Practices audits, then divide 100 by that number.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pagespeed_lighthouse_category_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\",category=\"best-practices\"} * 100)"
    }
   ]
  },
  { "title": "Overview ($strategy)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "content": "#### Lighthouse scores for $strategy\n* 0 to 49 (slow): Red\n* 50 to 89 (average): Orange\n* 90 to 100 (fast): Green\n"
  },
  {
   "title": "Performance Score",
   "type": "singlestat",
   "description": "Performance Score",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pagespeed_lighthouse_category_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\",category=\"performance\"} * 100)"
    }
   ]
  },
  {
   "title": "Accessibility Score",
   "type": "singlestat",
   "description": "The Accessibility score is a weighted average of all the accessibility audits. See Scoring Details for a full list of how each audit is weighted. The heavier-weighted audits have a bigger impact on your score.\n\nEach accessibility audit is pass or fail. Unlike the Performance audits, a page doesn't get points for partially passing an accessibility audit. For example, if some elements have screenreader-friendly names, but others don't, that page gets a 0 for the screenreader-friendly-names audit.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pagespeed_lighthouse_category_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\",category=\"accessibility\"} * 100)"
    }
   ]
  },
  {
   "title": "PWA Score",
   "type": "singlestat",
   "description": "Lighthouse returns a Progressive Web App (PWA) score between 0 and 100. 0 is the worst possible score, and 100 is the best.\n\nThe PWA audits are based on the Baseline PWA Checklist, which lists 14 requirements. Lighthouse has automated audits for 11 of the 14 requirements. The remaining 3 can only be tested manually. Each of the 11 automated PWA audits are weighted equally, so each one contributes approximately 9 points to your PWA score.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pagespeed_lighthouse_category_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\",category=\"pwa\"} * 100)"
    }
   ]
  },
  {
   "title": "SEO Score",
   "type": "singlestat",
   "description": "Search Engine Optimization Score",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pagespeed_lighthouse_category_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\",category=\"seo\"} * 100)"
    }
   ]
  },
  {
   "title": "Best Practices Score",
   "type": "singlestat",
   "description": "Lighthouse returns a Best Practices score between 0 and 100. 0 is the worst possible score, and 100 is the best.\n\nThe Best Practices audits are equally weighted. To calculate how much each audit contributes to your overall Best Practices score, count the number of Best Practices audits, then divide 100 by that number.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pagespeed_lighthouse_category_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\",category=\"best-practices\"} * 100)"
    }
   ]
  },
  {
   "title": "Timings / Scores / Audits ($strategy)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "strategy",
   "collapsed": true,
   "panels": [
    {
     "title": "Timings",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pagespeed_lighthouse_total_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
       "legendFormat": "Total Time"
      },
      {
       "expr": "pagespeed_lighthouse_first_contentful_paint_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
       "legendFormat": "First Contentful Paint"
      },
      {
       "expr": "pagespeed_lighthouse_first_cpu_idle_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
       "legendFormat": "First CPU Idle"
      },
      {
       "expr": "pagespeed_lighthouse_first_meaningful_paint_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
       "legendFormat": "First Meaningful Paint"
      },
      {
       "expr": "pagespeed_lighthouse_interactive_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
       "legendFormat": "Interactive"
      },
      {
       "expr": "pagespeed_lighthouse_speed_index_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
       "legendFormat": "Content Speed Index "
      },
      {
       "expr": "pagespeed_lighthouse_bootup_time_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
       "legendFormat": "JS Bootup Time"
      }
     ]
    },
    {
     "title": "Timing Diff $diff",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "delta(pagespeed_lighthouse_total_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
       "legendFormat": "Total Time"
      },
      {
       "expr": "delta(pagespeed_lighthouse_first_contentful_paint_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
       "legendFormat": "First Contentful Paint"
      },
      {
       "expr": "delta(pagespeed_lighthouse_first_cpu_idle_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
       "legendFormat": "First CPU Idle"
      },
      {
       "expr": "delta(pagespeed_lighthouse_first_meaningful_paint_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
       "legendFormat": "First Meaningful Paint"
      },
      {
       "expr": "delta(pagespeed_lighthouse_interactive_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
       "legendFormat": "Interactive"
      },
      {
       "expr": "delta(pagespeed_lighthouse_speed_index_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
       "legendFormat": "Content Speed Index "
      },
      {
       "expr": "delta(pagespeed_lighthouse_bootup_time_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
       "legendFormat": "JS Bootup Time"
      }
     ]
    },
    {
     "title": "Audit Scores",
     "type": "graph",
     "description": "https://developers.google.com/web/tools/lighthouse/v3/scoring",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pagespeed_lighthouse_audit_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
       "legendFormat": "{{audit}}"
      }
     ]
    },
    {
     "title": "Audit Diff $diff",
     "type": "graph",
     "description": "https://developers.google.com/web/tools/lighthouse/v3/scoring",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(pagespeed_lighthouse_audit_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
       "legendFormat": "{{audit}}"
      }
     ]
    },
    {
     "title": "Score History",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "pagespeed_lighthouse_category_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}*100 ",
       "legendFormat": "{{category}}"
      }
     ]
    },
    {
     "title": "Score History Diff $diff",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "delta(pagespeed_lighthouse_category_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])*100",
       "legendFormat": "{{category}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Timings / Scores / Audits ($strategy)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timings",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pagespeed_lighthouse_total_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
       "legendFormat": "Total Time"
      },
      {
       "expr": "pagespeed_lighthouse_first_contentful_paint_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
       "legendFormat": "First Contentful Paint"
      },
      {
       "expr": "pagespeed_lighthouse_first_cpu_idle_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
       "legendFormat": "First CPU Idle"
      },
      {
       "expr": "pagespeed_lighthouse_first_meaningful_paint_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
       "legendFormat": "First Meaningful Paint"
      },
      {
       "expr": "pagespeed_lighthouse_interactive_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
       "legendFormat": "Interactive"
      },
      {
       "expr": "pagespeed_lighthouse_speed_index_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
       "legendFormat": "Content Speed Index "
      },
      {
       "expr": "pagespeed_lighthouse_bootup_time_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
       "legendFormat": "JS Bootup Time"
      }
     ]
    },
    {
     "title": "Timing Diff $diff",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "delta(pagespeed_lighthouse_total_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
       "legendFormat": "Total Time"
      },
      {
       "expr": "delta(pagespeed_lighthouse_first_contentful_paint_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
       "legendFormat": "First Contentful Paint"
      },
      {
       "expr": "delta(pagespeed_lighthouse_first_cpu_idle_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
       "legendFormat": "First CPU Idle"
      },
      {
       "expr": "delta(pagespeed_lighthouse_first_meaningful_paint_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
       "legendFormat": "First Meaningful Paint"
      },
      {
       "expr": "delta(pagespeed_lighthouse_interactive_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
       "legendFormat": "Interactive"
      },
      {
       "expr": "delta(pagespeed_lighthouse_speed_index_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
       "legendFormat": "Content Speed Index "
      },
      {
       "expr": "delta(pagespeed_lighthouse_bootup_time_duration_seconds{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
       "legendFormat": "JS Bootup Time"
      }
     ]
    },
    {
     "title": "Audit Scores",
     "type": "graph",
     "description": "https://developers.google.com/web/tools/lighthouse/v3/scoring",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pagespeed_lighthouse_audit_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
       "legendFormat": "{{audit}}"
      }
     ]
    },
    {
     "title": "Audit Diff $diff",
     "type": "graph",
     "description": "https://developers.google.com/web/tools/lighthouse/v3/scoring",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(pagespeed_lighthouse_audit_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
       "legendFormat": "{{audit}}"
      }
     ]
    },
    {
     "title": "Score History",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "pagespeed_lighthouse_category_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}*100 ",
       "legendFormat": "{{category}}"
      }
     ]
    },
    {
     "title": "Score History Diff $diff",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "delta(pagespeed_lighthouse_category_score{env=\"ops\", host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])*100",
       "legendFormat": "{{category}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pagespeed Exporter Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pagespeed Scrape Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pagespeed_scrape_duration_seconds",
       "legendFormat": "scrape duration"
      }
     ]
    }
   ]
  }
 ]
}