{
 "title": "general: Mean Time Between Failure",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7927277014 at Thu Sep 26 12:03:45 UTC 2024",
 "tags": [
  "managed",
  "general",
  "general"
 ],
 "time": { "from": "now-7d", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  { "title": "Overall GitLab.com", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Time since last failure (GitLab.com)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1101 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(\n  time() -\n  gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\".*\"}\n)\n"
    }
   ]
  },
  {
   "title": "Mean time between failures (GitLab.com)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 8, "y": 1101 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "$__range_s / changes(\n  max(\n    gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\".*\"}\n  )[$__range:]\n)\n"
    }
   ]
  },
  {
   "title": "Disclaimer",
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 1101 },
   "content": "### Disclaimer\n\nThis rolls up the Mean Time Between Failures from all primary services into\nan overall number. This means this shows the mean time between any failure across\nall of these primary services.\n\nA failure in this context does not mean an outage on GitLab.com. A failure is\nany moment in time where a service does not meet SLO for error rates or apdex.\nMost often these failures won't be noticed by all users.\n\nRead more about MTBF as a PI in [the handbook][mtbf-pi].\n\n[mtbf-pi]: https://about.gitlab.com/handbook/engineering/infrastructure/performance-indicators/#mean-time-between-failure-mtbf\n"
  },
  { "title": "Primary Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Time since last failure (GitLab.com Web)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2101 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(\n  time() -\n  gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\"web\"}\n)\n"
    }
   ]
  },
  {
   "title": "Mean time between failures (GitLab.com Web)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 2101 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "$__range_s / changes(\n  max(\n    gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\"web\"}\n  )[$__range:]\n)\n"
    }
   ]
  },
  {
   "title": "Time since last failure (Git Access)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2109 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(\n  time() -\n  gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\"git\"}\n)\n"
    }
   ]
  },
  {
   "title": "Mean time between failures (Git Access)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 2109 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "$__range_s / changes(\n  max(\n    gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\"git\"}\n  )[$__range:]\n)\n"
    }
   ]
  },
  {
   "title": "Time since last failure (GitLab API)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2117 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(\n  time() -\n  gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\"api\"}\n)\n"
    }
   ]
  },
  {
   "title": "Mean time between failures (GitLab API)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 2117 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "$__range_s / changes(\n  max(\n    gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\"api\"}\n  )[$__range:]\n)\n"
    }
   ]
  },
  {
   "title": "Time since last failure (CI Runners)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2125 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(\n  time() -\n  gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\"ci-runners\"}\n)\n"
    }
   ]
  },
  {
   "title": "Mean time between failures (CI Runners)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 2125 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "$__range_s / changes(\n  max(\n    gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\"ci-runners\"}\n  )[$__range:]\n)\n"
    }
   ]
  },
  {
   "title": "Time since last failure (Container Registry)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2133 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(\n  time() -\n  gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\"registry\"}\n)\n"
    }
   ]
  },
  {
   "title": "Mean time between failures (Container Registry)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 2133 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "$__range_s / changes(\n  max(\n    gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\"registry\"}\n  )[$__range:]\n)\n"
    }
   ]
  },
  {
   "title": "Time since last failure (GitLab Pages)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2141 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(\n  time() -\n  gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\"web-pages\"}\n)\n"
    }
   ]
  },
  {
   "title": "Mean time between failures (GitLab Pages)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 2141 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "$__range_s / changes(\n  max(\n    gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\"web-pages\"}\n  )[$__range:]\n)\n"
    }
   ]
  },
  {
   "title": "Time since last failure (Sidekiq Background Jobs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2149 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(\n  time() -\n  gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\"sidekiq\"}\n)\n"
    }
   ]
  },
  {
   "title": "Mean time between failures (Sidekiq Background Jobs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 2149 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "$__range_s / changes(\n  max(\n    gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\"sidekiq\"}\n  )[$__range:]\n)\n"
    }
   ]
  },
  {
   "title": "Time since last failure (GitLab Internal API)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2157 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(\n  time() -\n  gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\"internal-api\"}\n)\n"
    }
   ]
  },
  {
   "title": "Mean time between failures (GitLab Internal API)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 2157 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "$__range_s / changes(\n  max(\n    gitlab_slo:last_violation_leading_timestamp{stage='$stage', env=\"$environment\", environment=\"$environment\", type=~\"internal-api\"}\n  )[$__range:]\n)\n"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}