{
 "title": "general: Application SLI Violations",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8245226639 at Fri Nov  1 04:32:15 UTC 2024",
 "tags": [
  "managed",
  "general"
 ],
 "time": { "from": "now-7d/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "product_stage",
    "query": "label_values(gitlab:feature_category:stage_group:mapping{monitor=\"global\"}, product_stage)"
   },
   {
    "name": "stage_group",
    "query": "label_values(gitlab:feature_category:stage_group:mapping{monitor=\"global\", product_stage=~\"$product_stage\"}, stage_group)"
   },
   {
    "name": "component",
    "query": "label_values(gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\", monitor=\"global\", component=~\"rails_request|graphql_query|customers_dot_sidekiq_jobs|customers_dot_requests|global_search|global_search_indexing|sidekiq_execution|sidekiq_queueing|sidekiq_execution_with_external_dependency|sidekiq_queueing_with_external_dependency|llm_completion|client_database_transaction\"}, component)"
   }
  ]
 },
 "panels": [
  {
   "title": "$component availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{component=~\"$component\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{component=~\"$component\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{component=~\"$component\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{component=~\"$component\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{component=~\"$component\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{component=~\"$component\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "title": "$component apdex",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      sum_over_time(\n        gitlab:component:stage_group:execution:apdex:success:rate_1h{component=~\"$component\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      sum_over_time(\n        gitlab:component:stage_group:execution:apdex:weight:score_1h{component=~\"$component\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "title": "$component errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{component=~\"$component\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{component=~\"$component\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "title": "$component by significant labels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 201 },
     "targets": [
      {
       "expr": "ceil(\n  (\n    sum by(db_config_name,document_type,endpoint_id,external_dependencies,feature_category,query_urgency,queue,request_urgency,search_level,search_scope,search_type,service_class,type,urgency,worker) (\n      sum_over_time({__name__=~\"application_sli_aggregation:($component):ops:rate_1h\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n    )\n    * on (feature_category) group_left(stage_group) gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}\n    or on () (sum by(db_config_name,document_type,endpoint_id,external_dependencies,feature_category,query_urgency,queue,request_urgency,search_level,search_scope,search_type,service_class,type,urgency,worker) (\n      sum_over_time({__name__=~\"application_sli_aggregation:($component):ops:rate_1h\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n    )\n    )\n  ) * 60\n)\n"
      },
      {
       "expr": "clamp_max(\n  sum by(db_config_name,document_type,endpoint_id,external_dependencies,feature_category,query_urgency,queue,request_urgency,search_level,search_scope,search_type,service_class,type,urgency,worker) (\n    sum_over_time({__name__=~\"application_sli_aggregation:($component):apdex:success:rate_1h\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range]) > 0\n  )\n  /\n  sum by(db_config_name,document_type,endpoint_id,external_dependencies,feature_category,query_urgency,queue,request_urgency,search_level,search_scope,search_type,service_class,type,urgency,worker) (\n    sum_over_time({__name__=~\"application_sli_aggregation:($component):apdex:weight:score_1h\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range]) > 0\n  )\n, 1\n)\n\n* on (feature_category) group_left(stage_group) gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}\nor on () (clamp_max(\n  sum by(db_config_name,document_type,endpoint_id,external_dependencies,feature_category,query_urgency,queue,request_urgency,search_level,search_scope,search_type,service_class,type,urgency,worker) (\n    sum_over_time({__name__=~\"application_sli_aggregation:($component):apdex:success:rate_1h\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range]) > 0\n  )\n  /\n  sum by(db_config_name,document_type,endpoint_id,external_dependencies,feature_category,query_urgency,queue,request_urgency,search_level,search_scope,search_type,service_class,type,urgency,worker) (\n    sum_over_time({__name__=~\"application_sli_aggregation:($component):apdex:weight:score_1h\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range]) > 0\n  )\n, 1\n)\n)\n"
      },
      {
       "expr": "clamp_max(\n  sum by(db_config_name,document_type,endpoint_id,external_dependencies,feature_category,query_urgency,queue,request_urgency,search_level,search_scope,search_type,service_class,type,urgency,worker) (\n    sum_over_time({__name__=~\"application_sli_aggregation:($component):error:rate_1h\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n  )\n  /\n  sum by(db_config_name,document_type,endpoint_id,external_dependencies,feature_category,query_urgency,queue,request_urgency,search_level,search_scope,search_type,service_class,type,urgency,worker) (\n    sum_over_time({__name__=~\"application_sli_aggregation:($component):ops:rate_1h\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n  )\n, 1\n)\n\n* on (feature_category) group_left(stage_group) gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}\nor on () (clamp_max(\n  sum by(db_config_name,document_type,endpoint_id,external_dependencies,feature_category,query_urgency,queue,request_urgency,search_level,search_scope,search_type,service_class,type,urgency,worker) (\n    sum_over_time({__name__=~\"application_sli_aggregation:($component):error:rate_1h\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n  )\n  /\n  sum by(db_config_name,document_type,endpoint_id,external_dependencies,feature_category,query_urgency,queue,request_urgency,search_level,search_scope,search_type,service_class,type,urgency,worker) (\n    sum_over_time({__name__=~\"application_sli_aggregation:($component):ops:rate_1h\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n  )\n, 1\n)\n)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}