{
 "title": "general: Availability indicator",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8245226639 at Fri Nov  1 04:32:16 UTC 2024",
 "tags": [
  "managed",
  "general"
 ],
 "time": { "from": "now-7d/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "product_stage",
    "query": "label_values(gitlab:feature_category:stage_group:mapping{monitor=\"global\"}, product_stage)"
   },
   {
    "name": "stage_group",
    "query": "label_values(gitlab:feature_category:stage_group:mapping{monitor=\"global\", product_stage=~\"$product_stage\"}, stage_group)"
   }
  ]
 },
 "panels": [
  {
   "title": "Error budget for all groups",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}[$__range]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}[$__range]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}[$__range]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}[$__range]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}[$__range]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}[$__range]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "title": "Teams over budget target",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "3", "legendFormat": "Target" },
    {
     "expr": "count(\n  last_over_time(gitlab:stage_group:availability:ratio_28d{environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}[$__range]) < 0.9995\n  and\n  last_over_time(gitlab:stage_group:traffic_share:ratio_28d{environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}[$__range]) > 0.0001\n)\n",
     "legendFormat": "Teams Over Budget"
    }
   ]
  },
  { "title": "Error budget by groups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "Availabilities",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 201 },
   "targets": [
    {
     "expr": "sum by (product_stage, stage_group) (\n  last_over_time(gitlab:stage_group:availability:ratio_28d{environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}[$__range])\n)\n"
    },
    {
     "expr": "sum by (product_stage, stage_group) (\n  last_over_time(gitlab:stage_group:traffic_share:ratio_28d{environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}[$__range])\n)\n"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}