{
 "title": "general: Platform Triage",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7927277014 at Thu Sep 26 12:03:45 UTC 2024",
 "tags": [
  "managed",
  "general",
  "general"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__interval])\n",
     "legendFormat": "{{ type }} service"
    }
   ]
  },
  {
   "title": "Error Ratios",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__interval])\n,\n  0.14999999999999999\n)\n",
     "legendFormat": "{{ type }} service"
    }
   ]
  },
  {
   "title": "Service Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__interval])\n",
     "legendFormat": "{{ type }} service"
    }
   ]
  },
  {
   "title": "Anomaly detection: Requests per second",
   "type": "graph",
   "description": "Each timeseries represents the distance, in standard deviations, that each service is away from its normal range. The further from zero, the more anomalous",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Sigma σ" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    avg((\n  gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}\n  -\n  gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}\n)\n/\ngitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}\n) by (type),\n    6.000000),\n  -3.000000)\n",
     "legendFormat": "{{ type }} service"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of the most saturated component of the service. Lower is better.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percentunit", "label": "Availability %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\", stage=\"$stage\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    }
   ]
  }
 ]
}