{
 "title": "ci-runners: Incident Support: runner-manager",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7867191950 at Thu Sep 19 12:04:23 UTC 2024",
 "tags": [
  "managed",
  "ci-runners",
  "type:ci-runners",
  "managed",
  "ci-runners:incident-support",
  "ci-runners:incident-rm"
 ],
 "time": { "from": "now-3h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "type",
    "query": "label_values(gitlab_runner_version_info{job=~\"runners-manager|scrapeConfig/monitoring/prometheus-agent-runner\", environment=\"$environment\"}, type)\n"
   },
   {
    "name": "shard",
    "query": "label_values(gitlab_runner_version_info{environment=~\"$environment\",stage=~\"$stage\",type=~\"$type\",shard!=\"default\"}, shard)\n"
   },
   {
    "name": "runner_manager",
    "query": "query_result(label_replace(gitlab_runner_version_info{environment=~\"$environment\",stage=~\"$stage\",shard=~\"$shard\"}, \"fqdn\", \"$1.*\", \"instance\", \"([^:]*)(:[0-9]+)?$\"))\n"
   },
   {
    "name": "project_jobs_running",
    "query": "label_values(gitlab_runner_job_queue_duration_seconds_sum{environment=~\"$environment\",stage=~\"$stage\"}, project_jobs_running)\n"
   },
   {
    "name": "runner_job_failure_reason",
    "query": "label_values(gitlab_runner_failed_jobs_total{environment=~\"$environment\",stage=~\"$stage\"}, failure_reason)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  },
  {
   "title": "ci-runners Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n",
     "legendFormat": "ci-runners apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n",
     "legendFormat": "ci-runners apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "ci-runners Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "ci-runners Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "ci-runners error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "ci-runners error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "ci-runners Service | Errors"
    }
   ]
  },
  {
   "title": "ci-runners Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n",
     "legendFormat": "ci-runners RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  {
   "title": "Jobs running on GitLab Inc. runners (by shard)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 0, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  gitlab_runner_jobs{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Jobs started on runners (by shard)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 4.8, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  increase(gitlab_runner_jobs_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{ shard }}"
    },
    {
     "expr": "avg (\n  increase(gitlab_runner_jobs_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Pending job queue duration histogram",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 4.8, "x": 9.6, "y": 1000 },
   "targets": [
    {
     "expr": "sum by (le) (\n  increase(gitlab_runner_job_queue_duration_seconds_bucket{environment=~\"$environment\", stage=~\"$stage\", project_jobs_running=~\"$project_jobs_running\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pending jobs queue size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 14.399999999999999, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(runner_type) (\n  gitlab_ci_current_queue_size{environment=~\"$environment\", stage=~\"$stage\"}\n)\n",
     "legendFormat": "{{runner_type}}"
    }
   ]
  },
  {
   "title": "runner-manager caused incident notes",
   "type": "text",
   "gridPos": { "h": 7, "w": 4.8, "x": 19.2, "y": 1000 },
   "content": "Runner Manager is the central point of job execution. It's responsible for asking GitLab for\nnew jobs, executing them with the configured executor, collecting and sending back the job log\nand finally detecting the result of the job and reporting it back as well.\n\nRunner Manager orchestrates job's execution **for the whole lifetime of the running job**. Therefore\nproblems on the Runner Manager side (usually related to resources usage or errors in configuration)\naffects the whole GitLab CI/CD experience.\n\nKnown problem indicators:\n- high usage of Runner Manager VM resources,\n- high saturation of jobs (approaching defined limits),\n- highly increased number of job failures (especially the `runner_system_failure` type),\n- highly reduced number of jobs that are started by the Runner Manager.\n\nRunner Manager problems are usually caused by two possible reasons:\n- Not enough jobs capacity or resources capacity to the load being handled. For that concider\n  adjusting the concurrency settings or resizing the Runner Manager VM to a more powerful one.\n- Bugs in Runner Manager configuration. For that double check if there were any changes made\n  in Runner Manager's `config.toml` file.\n"
  },
  {
   "title": "Runner saturation of concurrent by shard",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3000 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (shard) (\n  gitlab_runner_jobs{environment=\"$environment\", stage=\"$stage\", job=~\"runners-manager|scrapeConfig/monitoring/prometheus-agent-runner\", instance=~\"${runner_manager:pipe}\"}\n)\n/\nsum by (shard) (\n  gitlab_runner_concurrent{environment=\"$environment\", stage=\"$stage\", job=~\"runners-manager|scrapeConfig/monitoring/prometheus-agent-runner\", instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{ shard }}"
    },
    { "expr": "0.85", "legendFormat": "Soft SLO" },
    { "expr": "0.9", "legendFormat": "Hard SLO" }
   ]
  },
  {
   "title": "Runner saturation of concurrent by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3000 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (\n  gitlab_runner_jobs{environment=\"$environment\", stage=\"$stage\", job=~\"runners-manager|scrapeConfig/monitoring/prometheus-agent-runner\", instance=~\"${runner_manager:pipe}\"}\n)\n/\nsum by (instance) (\n  gitlab_runner_concurrent{environment=\"$environment\", stage=\"$stage\", job=~\"runners-manager|scrapeConfig/monitoring/prometheus-agent-runner\", instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{ instance }}"
    },
    { "expr": "0.85", "legendFormat": "Soft SLO" },
    { "expr": "0.9", "legendFormat": "Hard SLO" }
   ]
  },
  {
   "title": "Runner saturation of limit by instance,runner",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3000 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,runner) (\n  gitlab_runner_jobs{environment=\"$environment\", stage=\"$stage\", job=~\"runners-manager|scrapeConfig/monitoring/prometheus-agent-runner\", instance=~\"${runner_manager:pipe}\"}\n)\n/\nsum by (instance,runner) (\n  gitlab_runner_limit{environment=\"$environment\", stage=\"$stage\", job=~\"runners-manager|scrapeConfig/monitoring/prometheus-agent-runner\", instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{ instance }} - {{ runner }}"
    },
    { "expr": "0.85", "legendFormat": "Soft SLO" },
    { "expr": "0.9", "legendFormat": "Hard SLO" }
   ]
  },
  {
   "title": "CPU usage by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4000 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_utilization:ratio{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4000 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_memory_utilization:ratio{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "File Descriptiors usage by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4000 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\",job=~\"runners-manager|scrapeConfig/monitoring/prometheus-agent-runner\"}\n/\nprocess_max_fds{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\",job=~\"runners-manager|scrapeConfig/monitoring/prometheus-agent-runner\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk available by instance and device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5000 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_filesystem_avail:ratio{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\",fstype=\"ext4\"}\n",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "instance:node_disk_writes_completed:irate1m{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}\n",
     "legendFormat": "{{instance}} - writes"
    },
    {
     "expr": "instance:node_disk_reads_completed:irate1m{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}\n",
     "legendFormat": "{{instance}} - reads"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5000 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(node_network_transmit_bytes_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{instance}} - sent"
    },
    {
     "expr": "sum by (instance) (\n  rate(node_network_receive_bytes_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{instance}} - received"
    }
   ]
  },
  {
   "title": "Failures on GitLab Inc. runners (by instance,failure_reason)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,failure_reason)\n(\n  increase(gitlab_runner_failed_jobs_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\",failure_reason=~\"$runner_job_failure_reason\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{ instance }} - {{ failure_reason }}"
    }
   ]
  },
  {
   "title": "Jobs started on runners (by instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (\n  increase(gitlab_runner_jobs_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "avg (\n  increase(gitlab_runner_jobs_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "Jobs distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7000 } },
  {
   "title": "Jobs running on GitLab Inc. runners (by instance)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4.8, "x": 0, "y": 7001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (\n  gitlab_runner_jobs{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Jobs running on GitLab Inc. runners (by runner)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4.8, "x": 4.8, "y": 7001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(runner) (\n  gitlab_runner_jobs{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{ runner }}"
    }
   ]
  },
  {
   "title": "Jobs running on GitLab Inc. runners (by state)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4.8, "x": 9.6, "y": 7001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(state) (\n  gitlab_runner_jobs{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Jobs running on GitLab Inc. runners (by exported_stage)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4.8, "x": 14.399999999999999, "y": 7001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(exported_stage) (\n  gitlab_runner_jobs{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{ exported_stage }}"
    }
   ]
  },
  {
   "title": "Jobs running on GitLab Inc. runners (by executor_stage)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4.8, "x": 19.2, "y": 7001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(executor_stage) (\n  gitlab_runner_jobs{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{ executor_stage }}"
    }
   ]
  },
  { "title": "Workers & Slots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8000 } },
  {
   "title": "Worker feed rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  increase(\n    gitlab_runner_worker_feeds_total{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Worker slots",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  gitlab_runner_worker_slots_number{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Worker slot operations rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  increase(\n    gitlab_runner_worker_slot_operations_total{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  { "title": "Workers & Slots failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9000 } },
  {
   "title": "Worker feed failures rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  increase(\n    gitlab_runner_worker_feed_failures_total{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Worker processing failures rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(shard, failure_type) (\n  increase(\n    gitlab_runner_worker_processing_failures_total{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}}: {{failure_type}}"
    }
   ]
  },
  {
   "title": "Worker health check failures rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(shard, runner_name) (\n  increase(\n    gitlab_runner_worker_health_check_failures_total{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}}: {{runner_name}}"
    }
   ]
  }
 ]
}