{
 "title": "ci-runners: Incident Support: database",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8397766929 at Mon Nov 18 09:15:48 UTC 2024",
 "tags": [
  "managed",
  "ci-runners",
  "type:ci-runners",
  "managed",
  "ci-runners:incident-support",
  "ci-runners:incident-db"
 ],
 "time": { "from": "now-3h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "type",
    "query": "label_values(gitlab_runner_version_info{job=~\"runners-manager|scrapeConfig/monitoring/prometheus-agent-runner\", environment=\"$environment\"}, type)\n"
   },
   {
    "name": "shard",
    "query": "label_values(gitlab_runner_version_info{environment=~\"$environment\",stage=~\"$stage\",type=~\"$type\",shard!=\"default\"}, shard)\n"
   },
   {
    "name": "runner_manager",
    "query": "query_result(label_replace(gitlab_runner_version_info{environment=~\"$environment\",stage=~\"$stage\",shard=~\"$shard\"}, \"fqdn\", \"$1.*\", \"instance\", \"([^:]*)(:[0-9]+)?$\"))\n"
   },
   {
    "name": "project_jobs_running",
    "query": "label_values(gitlab_runner_job_queue_duration_seconds_sum{environment=~\"$environment\",stage=~\"$stage\"}, project_jobs_running)\n"
   },
   {
    "name": "db_instance",
    "query": "query_result(pg_replication_is_replica{environment=~\"$environment\",stage=~\"$stage\"} == 0)\n"
   },
   {
    "name": "db_instances",
    "query": "label_values(pg_slow_queries{environment=~\"$environment\",stage=~\"$stage\"},fqdn)\n"
   },
   {
    "name": "db_database",
    "query": "label_values(pg_stat_database_tup_deleted{environment=~\"$environment\",stage=~\"$stage\",fqdn=\"$db_instance\"}, datname)\n"
   },
   {
    "name": "db_top_dead_tup",
    "query": "query_result(topk(20, max_over_time(pg_stat_user_tables_n_dead_tup{environment=~\"$environment\",stage=~\"$stage\",fqdn=\"$db_instance\",datname=\"$db_database\"}[${__range_s}s])))\n"
   },
   {
    "name": "runner_type",
    "query": "label_values(gitlab_ci_queue_retrieval_duration_seconds_bucket{environment=\"$environment\"}, runner_type)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  },
  {
   "title": "ci-runners Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n",
     "legendFormat": "ci-runners apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n",
     "legendFormat": "ci-runners apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "ci-runners Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "ci-runners Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "ci-runners error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "ci-runners error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "ci-runners Service | Errors"
    }
   ]
  },
  {
   "title": "ci-runners Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n",
     "legendFormat": "ci-runners RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  {
   "title": "Jobs running on GitLab Inc. runners (by shard)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 0, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  gitlab_runner_jobs{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Jobs started on runners (by shard)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 4.8, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  increase(gitlab_runner_jobs_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{ shard }}"
    },
    {
     "expr": "avg (\n  increase(gitlab_runner_jobs_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Pending job queue duration histogram",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 4.8, "x": 9.6, "y": 1000 },
   "targets": [
    {
     "expr": "sum by (le) (\n  increase(gitlab_runner_job_queue_duration_seconds_bucket{environment=~\"$environment\", stage=~\"$stage\", project_jobs_running=~\"$project_jobs_running\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pending jobs queue size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 14.399999999999999, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(runner_type) (\n  gitlab_ci_current_queue_size{environment=~\"$environment\", stage=~\"$stage\"}\n)\n",
     "legendFormat": "{{runner_type}}"
    }
   ]
  },
  {
   "title": "database caused incident notes",
   "type": "text",
   "gridPos": { "h": 7, "w": 4.8, "x": 19.2, "y": 1000 },
   "content": "In short: scheduling of CI/CD jobs to runners fully depends on DB. Any DB problems may affect our ability\nto pass jobs to runners that are asking for them.\n\nThe scheduling is done by using a special SQL query executed on API requests to `/api/v4/jobs/request`. We name\nthis query \"Big Query\". Depending on the type of the runner that asks for a job (instance, group or project)\nthe query is slightly different. The query for `instance_type` runners is most complicated and execution heavy,\nas it includes resolving the \"fair scheduling algorithm\" problem, respecting Pipeline Minutes quotas and checking\nif `instance_type` runners are even enabled for a project.\n\nThe query does also initial handling of runner tags matching.\n\nThe result is next filtered in Rails to fully resolve tags matching, respect the `protected` setting etc. From the\nfinal list of jobs GitLab tries to schedule the first one to the Runner that asked for a job. In case the same\njob was already assigned to another Runner that asked for a job concurrently, GitLab tries - but only once - to\nschedule the second job from the list. If this also fails on SQL transaction (which mostly means that this job also\nwas already scheduled to a different Runner by a different request) the `409 Conflict` response is sent back.\n\nThe Big Query should be executed only on the read-only replicas.\n\nKnown problem indicators:\n- general Patroni service problems,\n- a high number of dead tuples for tables used in the Big Query,\n- a high percentage of dead tuples for tables used in the Big Query,\n- a high number of slow queries on the replicas (usually >50 opm becomes problematic).\n\nDatabase problems can be caused by many different reasons and it's hard to define \"most known problems\".\nHowever, the most popular ones that we've seen regularly are:\n- A significant increase of jobs in the `pending` queue, which makes executions of queries on `ci_builds` much\n  slower.\n- A significant increase of requests to `/api/v4/jobs/request` which triggers more Big Query executions and may\n  be the source of DB slowness.\n- VACUUM or AUTOVACUUM running on the DB (especially on the tables used in the Big Query).\n- Long running transactions (for example sourced by DB migrations) that are blocking DB and causing slower\n  queries execution.\n"
  },
  {
   "title": "patroni Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"}[$__interval])\n",
     "legendFormat": "patroni apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"db\",type=\"patroni\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"db\",type=\"patroni\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"}[$__interval])\n",
     "legendFormat": "patroni apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"db\",type=\"patroni\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 2006 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"db\",type=\"patroni\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"db\",type=\"patroni\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"db\",type=\"patroni\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"db\",type=\"patroni\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "patroni Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "patroni Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2001 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "patroni error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"db\",type=\"patroni\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"db\",type=\"patroni\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "patroni error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"db\",type=\"patroni\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 2006 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"db\",type=\"patroni\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"db\",type=\"patroni\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"db\",type=\"patroni\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"db\",type=\"patroni\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "patroni Service | Errors"
    }
   ]
  },
  {
   "title": "patroni Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"}[$__interval])\n",
     "legendFormat": "patroni RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"db\",type=\"patroni\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2001 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\",stage=\"$stage\",tier=\"db\",type=\"patroni\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  {
   "title": "Total dead tuples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_dead_tup{environment=~\"$environment\",stage=~\"$stage\",fqdn=\"$db_instance\",datname=\"$db_database\",relname=~\"$db_top_dead_tup\"}\n",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Dead tuples percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3000 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_dead_tup{environment=~\"$environment\",stage=~\"$stage\",fqdn=\"$db_instance\",datname=\"$db_database\",relname=~\"$db_top_dead_tup\"}\n/\n(\n  pg_stat_user_tables_n_live_tup{environment=~\"$environment\",stage=~\"$stage\",fqdn=\"$db_instance\",datname=\"$db_database\",relname=~\"$db_top_dead_tup\"}\n  +\n  pg_stat_user_tables_n_dead_tup{environment=~\"$environment\",stage=~\"$stage\",fqdn=\"$db_instance\",datname=\"$db_database\",relname=~\"$db_top_dead_tup\"}\n)\n",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Slow queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3000 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(pg_slow_queries{environment=~\"$environment\",stage=~\"$stage\",fqdn=~\"$db_instances\"}[$__rate_interval]) * 60\n",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "instance_type - duration of the builds queue retrieval SQL query",
   "type": "heatmap",
   "description": "The \"big query SQL\" is the SQL query GitLab uses to retrieve the jobs queue from the database. That query\nis used to add initial filtering and sorting of the queue. It's the core of jobs scheduling mechanism.\n\nWith more and more of jobs in the ci_pending_builds table it's getting longer. At some level it may start\naffecting the whole system. The direct consequences will be seen as jobs queuing duration getting longer\n(which affects Runner's apdex) and general database slowness for the CI database.\n\nTherefore, observing the trend of our \"big query SQL\" duration is important.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4000 },
   "targets": [
    {
     "expr": "sum by (le) (\n  increase(\n    gitlab_ci_queue_retrieval_duration_seconds_bucket{\n      environment=~\"$environment\",\n      stage=~\"$stage\",\n      runner_type=~\"instance_type\"\n    }[$__rate_interval]\n  )\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "group_type - duration of the builds queue retrieval SQL query",
   "type": "heatmap",
   "description": "The \"big query SQL\" is the SQL query GitLab uses to retrieve the jobs queue from the database. That query\nis used to add initial filtering and sorting of the queue. It's the core of jobs scheduling mechanism.\n\nWith more and more of jobs in the ci_pending_builds table it's getting longer. At some level it may start\naffecting the whole system. The direct consequences will be seen as jobs queuing duration getting longer\n(which affects Runner's apdex) and general database slowness for the CI database.\n\nTherefore, observing the trend of our \"big query SQL\" duration is important.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4000 },
   "targets": [
    {
     "expr": "sum by (le) (\n  increase(\n    gitlab_ci_queue_retrieval_duration_seconds_bucket{\n      environment=~\"$environment\",\n      stage=~\"$stage\",\n      runner_type=~\"group_type\"\n    }[$__rate_interval]\n  )\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "project_type - duration of the builds queue retrieval SQL query",
   "type": "heatmap",
   "description": "The \"big query SQL\" is the SQL query GitLab uses to retrieve the jobs queue from the database. That query\nis used to add initial filtering and sorting of the queue. It's the core of jobs scheduling mechanism.\n\nWith more and more of jobs in the ci_pending_builds table it's getting longer. At some level it may start\naffecting the whole system. The direct consequences will be seen as jobs queuing duration getting longer\n(which affects Runner's apdex) and general database slowness for the CI database.\n\nTherefore, observing the trend of our \"big query SQL\" duration is important.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4000 },
   "targets": [
    {
     "expr": "sum by (le) (\n  increase(\n    gitlab_ci_queue_retrieval_duration_seconds_bucket{\n      environment=~\"$environment\",\n      stage=~\"$stage\",\n      runner_type=~\"project_type\"\n    }[$__rate_interval]\n  )\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}