{
 "title": "sentry: Kube Sentry main",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7867191950 at Thu Sep 19 12:04:26 UTC 2024",
 "tags": [
  "managed",
  "sentry",
  "sentry"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Sentry Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events processed per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sentry_ingest_consumer_process_event_count{cluster=\"ops-gitlab-gke\",env=\"ops\",namespace=\"sentry\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sentry_jobs_duration{cluster=\"ops-gitlab-gke\",env=\"ops\",namespace=\"sentry\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Time to process events",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sentry_ingest_consumer_process_event{cluster=\"ops-gitlab-gke\",env=\"ops\",namespace=\"sentry\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (nginx_ingress_controller_nginx_process_connections{cluster=\"ops-gitlab-gke\",env=\"ops\",namespace=\"sentry\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests in 5 minutes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(exported_service) (rate(nginx_ingress_controller_requests{cluster=\"ops-gitlab-gke\",env=\"ops\",namespace=\"sentry\", exported_service=~\"sentry-relay|sentry-web\"}[5m]))",
     "legendFormat": "{{ exported_service }}"
    }
   ]
  },
  { "title": "Clickhouse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(hostname)(chi_clickhouse_metric_TCPConnection{chi=\"sentry\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replica delay",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 201 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_ReplicasMaxAbsoluteDelay{chi=\"sentry\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Zookeeper requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 211 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(hostname)(chi_clickhouse_metric_ZooKeeperRequest{chi=\"sentry\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 } },
  {
   "title": "Consumer group lag by topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 301 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{cluster=\"ops-gitlab-gke\",env=\"ops\",namespace=\"sentry\"}",
     "legendFormat": "{{ topic }} in group {{ consumergroup }}"
    }
   ]
  }
 ]
}