{
 "title": "frontend: Git Utilization",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8245226639 at Fri Nov  1 04:32:47 UTC 2024",
 "tags": [
  "managed",
  "frontend",
  "managed",
  "type:frontend"
 ],
 "time": { "from": "now-24h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(haproxy_frontend_bytes_in_total{frontend=\"https\"}, env)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTPs Git Traffic as a Percentage of Main HTTPS Frontend Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_backend_bytes_in_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval]) + rate(haproxy_backend_bytes_out_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n/\nsum by(env) (\n  rate(haproxy_frontend_bytes_in_total{frontend=\"https\",env=~\"${environment}\"}[$__rate_interval]) + rate(haproxy_frontend_bytes_out_total{frontend=\"https\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_backend_bytes_in_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n/\nsum by(env) (\n  rate(haproxy_frontend_bytes_in_total{frontend=\"https\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "egress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_backend_bytes_out_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n/\nsum by(env) (\n  rate(haproxy_frontend_bytes_out_total{frontend=\"https\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "HTTPS CI Gateway Traffic as a Percentage of All Git HTTPS Backend Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_in_total{frontend=\"https_git_ci_gateway\",env=~\"${environment}\"}[$__rate_interval]) + rate(haproxy_frontend_bytes_out_total{frontend=\"https_git_ci_gateway\",env=~\"${environment}\"}[$__rate_interval])\n)\n/\nsum by(env) (\n  rate(haproxy_backend_bytes_in_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval]) + rate(haproxy_backend_bytes_out_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_in_total{frontend=\"https_git_ci_gateway\",env=~\"${environment}\"}[$__rate_interval])\n)\n/\nsum by(env) (\n  rate(haproxy_backend_bytes_in_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "egress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_out_total{frontend=\"https_git_ci_gateway\",env=~\"${environment}\"}[$__rate_interval])\n)\n/\nsum by(env) (\n  rate(haproxy_backend_bytes_out_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "HTTPS Traffic - Based on the Main HTTPS HAProxy Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_in_total{frontend=\"https\",env=~\"${environment}\"}[$__rate_interval]) + rate(haproxy_frontend_bytes_out_total{frontend=\"https\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_in_total{frontend=\"https\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "egress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_out_total{frontend=\"https\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "HTTPS Git Traffic - Based on the HAProxy Backend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_backend_bytes_in_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval]) + rate(haproxy_backend_bytes_out_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_backend_bytes_in_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "egress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_backend_bytes_out_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "HTTPS CI Gateway Traffic - Based on the Dedicated HAProxy Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 }
  },
  {
   "title": "total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_in_total{frontend=\"https_git_ci_gateway\",env=~\"${environment}\"}[$__rate_interval]) + rate(haproxy_frontend_bytes_out_total{frontend=\"https_git_ci_gateway\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_in_total{frontend=\"https_git_ci_gateway\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "egress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_out_total{frontend=\"https_git_ci_gateway\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  }
 ]
}