{
 "title": "runway: Runway Load Balancer Metrics",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7867191950 at Thu Sep 19 12:04:17 UTC 2024",
 "tags": [
  "managed",
  "runway",
  "runway",
  "type:runway"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   {
    "name": "loadbalancer",
    "query": "label_values(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_request_count{job=\"runway-exporter\", env=\"$environment\"}, url_map_name)"
   },
   {
    "name": "region",
    "query": "label_values(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_request_count{job=\"runway-exporter\", env=\"$environment\", url_map_name=\"$loadbalancer\"}, backend_scope)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request rate by status",
   "type": "graph",
   "description": "Rate of requests served by the external HTTP(S) load balancer, grouped by HTTP status code.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by(response_code_class) (\n  rate(\n    stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{backend_scope=~\"$region\",env=\"$environment\",job=\"runway-exporter\",url_map_name=\"$loadbalancer\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "HTTP status {{response_code_class}}"
    }
   ]
  },
  {
   "title": "Request rate by region",
   "type": "graph",
   "description": "Rate of requests served by the external HTTP(S) load balancer, grouped by the region of the backend handling the request.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by(backend_scope) (\n  rate(\n    stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{backend_scope=~\"$region\",env=\"$environment\",job=\"runway-exporter\",url_map_name=\"$loadbalancer\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "Region {{backend_scope}}"
    }
   ]
  },
  {
   "title": "Error ratio",
   "type": "graph",
   "description": "Ratio of HTTP 5xx status codes to total number of requests.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Error ratio" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum(\n  stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{response_code_class=\"500\",backend_scope=~\"$region\",env=\"$environment\",job=\"runway-exporter\",url_map_name=\"$loadbalancer\"}\n  OR on()\n  vector(0)\n)\n/\nsum(\n  stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{backend_scope=~\"$region\",env=\"$environment\",job=\"runway-exporter\",url_map_name=\"$loadbalancer\"}\n)\n,1),0)\n",
     "legendFormat": "Total error ratio"
    }
   ]
  },
  {
   "title": "Error rate by region",
   "type": "graph",
   "description": "Rate of requests with status code 500 served by the external HTTP(S) load balancer, grouped by the region of the backend handling the request.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by(backend_scope) (\n  stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{response_code_class=\"500\",backend_scope=~\"$region\",env=\"$environment\",job=\"runway-exporter\",url_map_name=\"$loadbalancer\"}\n) / 60\n",
     "legendFormat": "Region {{backend_scope}}"
    }
   ]
  },
  {
   "title": "Total latency by region",
   "type": "graph",
   "description": "The latency calculated from when the request was received by the external HTTP(S) load balancer proxy until the proxy got ACK from client on last response byte.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by(le, backend_scope) (\n    rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_total_latencies_bucket{backend_scope=~\"$region\",env=\"$environment\",job=\"runway-exporter\",url_map_name=\"$loadbalancer\"}[$__rate_interval])\n  )\n)\n",
     "legendFormat": "Region {{backend_scope}} p99"
    }
   ]
  },
  {
   "title": "Backend latency by region",
   "type": "graph",
   "description": "Distribution of the latency calculated from when the request was sent by the proxy to the backend, in milliseconds.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by(le, backend_scope) (\n    rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies_bucket{backend_scope=~\"$region\",env=\"$environment\",job=\"runway-exporter\",url_map_name=\"$loadbalancer\"}[$__rate_interval])\n  )\n)\n",
     "legendFormat": "Region {{backend_scope}} p99"
    }
   ]
  }
 ]
}