{
 "title": "runway: Runway Service Metrics",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7867191950 at Thu Sep 19 12:04:17 UTC 2024",
 "tags": [
  "managed",
  "runway",
  "runway",
  "type:runway"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   {
    "name": "type",
    "label": "service",
    "query": "label_values(stackdriver_cloud_run_revision_run_googleapis_com_container_instance_count{job=\"runway-exporter\", env=\"$environment\"}, service_name)"
   },
   {
    "name": "region",
    "query": "label_values(stackdriver_cloud_run_revision_run_googleapis_com_container_instance_count{job=\"runway-exporter\", env=\"$environment\", type=\"$type\"}, location)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request count by Status",
   "type": "graph",
   "description": "Number of requests reaching the service, grouped by HTTP response status",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (response_code_class) (\n  stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}\n) / 60\n",
     "legendFormat": "HTTP status {{response_code_class}}"
    }
   ]
  },
  {
   "title": "Request count by Region",
   "type": "graph",
   "description": "Number of requests reaching the service, grouped by region",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (region, location) (\n  stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}\n) / 60\n",
     "legendFormat": "Region {{location}}"
    }
   ]
  },
  {
   "title": "Error ratio",
   "type": "graph",
   "description": "Ratio of errors (HTTP status 5xx) to total requests",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Error ratio" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum (\n  stackdriver_cloud_run_revision_run_googleapis_com_request_count{response_code_class=\"5xx\",env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}\n  OR on() vector(0)\n)\n/\nsum (\n  stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}\n)\n,1),0)\n",
     "legendFormat": "Overall error ratio"
    }
   ]
  },
  {
   "title": "Error ratio by Revision",
   "type": "graph",
   "description": "Ratio of errors (HTTP status 5xx) to total requests, grouped by revision",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Error ratio" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by(revision_name) (\n  stackdriver_cloud_run_revision_run_googleapis_com_request_count{response_code_class=\"5xx\",env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}\n  OR on(revision_name) vector(0)\n)\n/ on(revision_name)\nsum by(revision_name) (\n  stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}\n)\n,1),0)\n",
     "legendFormat": "Revision {{revision_name}}"
    }
   ]
  },
  {
   "title": "Runway Service Request Latency",
   "type": "graph",
   "description": "Distribution of request times reaching the service, in milliseconds.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (revision_name, region, location, le) (\n    rate(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}[$__interval])\n  )\n)\n",
     "legendFormat": "p99 {{revision_name}} {{region}} {{location}}"
    }
   ]
  },
  {
   "title": "Runway Service Container Instance Count",
   "type": "graph",
   "description": "Number of container instances that exist for the service.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Container Instances per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (revision_name, region, location) (\n  max_over_time(\n    stackdriver_cloud_run_revision_run_googleapis_com_container_instance_count{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}[${__interval}]\n  )\n)\n",
     "legendFormat": "{{revision_name}} {{region}} {{location}}"
    }
   ]
  },
  {
   "title": "Runway Service Billable Container Instance Time",
   "type": "graph",
   "description": "Billable time aggregated from all container instances.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Seconds per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name) (\n  stackdriver_cloud_run_revision_run_googleapis_com_container_billable_instance_time{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}\n) / 60\n",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Runway Service CPU Utilization",
   "type": "graph",
   "description": "Container CPU utilization distribution across all container instances.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(histogram_quantile(\n  0.99,\n  sum by (revision_name, region, location, le) (\n    max_over_time(stackdriver_cloud_run_revision_run_googleapis_com_container_cpu_utilizations_bucket{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}[$__interval])\n  )\n)\n,1),0)\n",
     "legendFormat": "p99 {{revision_name}} {{region}} {{location}}"
    }
   ]
  },
  {
   "title": "Runway Service Memory Utilization",
   "type": "graph",
   "description": "Container memory utilization distribution across all container instances.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(histogram_quantile(\n  0.99,\n  sum by (revision_name, region, location, le) (\n    max_over_time(stackdriver_cloud_run_revision_run_googleapis_com_container_memory_utilizations_bucket{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}[$__interval])\n  )\n)\n,1),0)\n",
     "legendFormat": "p99 {{revision_name}} {{region}} {{location}}"
    }
   ]
  },
  {
   "title": "Sent bytes by Kind",
   "type": "graph",
   "description": "Outgoing socket and HTTP response traffic, in bytes.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(kind) (\n  stackdriver_cloud_run_revision_run_googleapis_com_container_network_sent_bytes_count{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}\n) / 60\n",
     "legendFormat": "send {{kind}}"
    },
    { "legendFormat": "receive {{kind}}" }
   ]
  },
  {
   "title": "Received bytes by Kind",
   "type": "graph",
   "description": "Incoming socket and HTTP response traffic, in bytes.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    { "legendFormat": "send {{kind}}" },
    {
     "expr": "sum by(kind) (\n  stackdriver_cloud_run_revision_run_googleapis_com_container_network_received_bytes_count{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}\n) * -1 / 60\n",
     "legendFormat": "receive {{kind}}"
    }
   ]
  },
  {
   "title": "Runway Service Max Concurrent Requests",
   "type": "graph",
   "description": "Distribution of the maximum number number of concurrent requests being served by each container instance over a minute.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(histogram_quantile(\n  0.99,\n  sum by (revision_name, region, location, le) (\n    max_over_time(stackdriver_cloud_run_revision_run_googleapis_com_container_max_request_concurrencies_bucket{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}[$__interval])\n  )\n) / 100\n,1),0)\n",
     "legendFormat": "p99 {{revision_name}} {{region}} {{location}}"
    }
   ]
  },
  {
   "title": "Runway Service Container Startup Latency",
   "type": "graph",
   "description": "Distribution of time spent starting a new container instance, in milliseconds.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ms", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "sum by (revision_name, region, location) (\n  stackdriver_cloud_run_revision_run_googleapis_com_container_startup_latencies_sum{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}\n) / 60\n",
     "legendFormat": "{{revision_name}} {{region}} {{location}}"
    }
   ]
  },
  {
   "title": "Runway Service Container Healthcheck Requests",
   "type": "graph",
   "description": "Request rate of healthcheck attempts for the ingress container",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (revision_name, region, location, probe_type, is_healthy) (\n  stackdriver_cloud_run_revision_run_googleapis_com_container_completed_probe_attempt_count{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\", container_name='ingress'}\n) / 60\n",
     "legendFormat": "{{revision_name}} {{region}} {{location}} {{probe_type}} healthy: {{is_healthy}}"
    }
   ]
  },
  {
   "title": "Runway Service Container Healthcheck Latency",
   "type": "graph",
   "description": "Distribution of time spent probing a container instance, in milliseconds.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ms", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, revision_name, region, location, probe_type, is_healthy) (\n    max_over_time(stackdriver_cloud_run_revision_run_googleapis_com_container_probe_attempt_latencies_bucket{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\", container_name='ingress'}[$__interval])\n  )\n)\n",
     "legendFormat": "{{revision_name}} {{region}} {{location}} {{probe_type}} healthy: {{is_healthy}}"
    }
   ]
  }
 ]
}