# HEADER
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: service-sentry-sentry_events-apdex
spec:
  budgetingMethod: Occurrences
  description: |
    Sentry is an application monitoring platform.
     This SLI monitors the sentry API. 5xx responses are considered failures.
  objectives:
  - ratioMetrics:
      good:
        query: sum(rate(apiserver_request_total{code!~"(5..|429)"}[{{.window}}]))
        queryType: promql
        source: prometheus
      target: 0.999
      total:
        query: sum(rate(apiserver_request_total[{{.window}}]))
        queryType: promql
        source: prometheus
  service: sentry
  timeWindows:
  - count: 30
    unit: Day
