# HEADER
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: service-web-imagescaler-apdex
spec:
  budgetingMethod: Occurrences
  description: |
    The imagescaler rescales images before sending them to clients. This allows faster transmission of
    images and faster rendering of web pages.
  objectives:
  - ratioMetrics:
      good:
        query: sum(rate(apiserver_request_total{code!~"(5..|429)"}[{{.window}}]))
        queryType: promql
        source: prometheus
      target: 0.998
      total:
        query: sum(rate(apiserver_request_total[{{.window}}]))
        queryType: promql
        source: prometheus
  service: web
  timeWindows:
  - count: 30
    unit: Day
