# HEADER
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: service-registry-server-apdex
spec:
  budgetingMethod: Occurrences
  description: |
    Aggregation of all registry requests.
  objectives:
  - ratioMetrics:
      good:
        query: sum(rate(apiserver_request_total{code!~"(5..|429)"}[{{.window}}]))
        queryType: promql
        source: prometheus
      target: 0.997
      total:
        query: sum(rate(apiserver_request_total[{{.window}}]))
        queryType: promql
        source: prometheus
  service: registry
  timeWindows:
  - count: 30
    unit: Day
