# HEADER
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: service-camoproxy-server-apdex
spec:
  budgetingMethod: Occurrences
  description: |
    This SLI monitors the camoproxy server via its HTTP interface.
    5xx responses are considered to be failures. Note that this SLI
    is highly dependent on upstream proxy targets, not under the control
    of GitLab. We are unable to distinguish problems in the proxy from
    upstream problems. This should be taken into account for this SLI.
  objectives:
  - ratioMetrics:
      good:
        query: sum(rate(apiserver_request_total{code!~"(5..|429)"}[{{.window}}]))
        queryType: promql
        source: prometheus
      target: 0.999
      total:
        query: sum(rate(apiserver_request_total[{{.window}}]))
        queryType: promql
        source: prometheus
  service: camoproxy
  timeWindows:
  - count: 30
    unit: Day
