# HEADER
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: service-web-workhorse-apdex
spec:
  budgetingMethod: Occurrences
  description: |
    Aggregation of most web requests that pass through workhorse, monitored via the HTTP interface.
    Excludes health, readiness and liveness requests. Some known slow requests, such as HTTP uploads,
    are excluded from the apdex score.
  objectives:
  - ratioMetrics:
      good:
        query: sum(rate(apiserver_request_total{code!~"(5..|429)"}[{{.window}}]))
        queryType: promql
        source: prometheus
      target: 0.998
      total:
        query: sum(rate(apiserver_request_total[{{.window}}]))
        queryType: promql
        source: prometheus
  service: web
  timeWindows:
  - count: 30
    unit: Day
