# HEADER
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: service-registry-server_route_manifest_reads-apdex
spec:
  budgetingMethod: Occurrences
  description: |
    All read-requests (HEAD or GET) for the manifest endpoints on
    the registry.
    Fetch the manifest identified by name and reference where reference can be
    a tag or digest. A HEAD request can also be issued to this endpoint to
    obtain resource information without receiving all data.
  objectives:
  - ratioMetrics:
      good:
        query: sum(rate(apiserver_request_total{code!~"(5..|429)"}[{{.window}}]))
        queryType: promql
        source: prometheus
      target: 0.997
      total:
        query: sum(rate(apiserver_request_total[{{.window}}]))
        queryType: promql
        source: prometheus
  service: registry
  timeWindows:
  - count: 30
    unit: Day
