# HEADER
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: service-git-puma-apdex
spec:
  budgetingMethod: Occurrences
  description: |
    Monitors Rails endpoints, running in the Git fleet, via the HTTP interface.
  objectives:
  - ratioMetrics:
      good:
        query: sum(rate(apiserver_request_total{code!~"(5..|429)"}[{{.window}}]))
        queryType: promql
        source: prometheus
      target: 0.998
      total:
        query: sum(rate(apiserver_request_total[{{.window}}]))
        queryType: promql
        source: prometheus
  service: git
  timeWindows:
  - count: 30
    unit: Day
