# HEADER
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: service-web-puma-apdex
spec:
  budgetingMethod: Occurrences
  description: |
    Aggregation of most web requests that pass through the puma to the GitLab rails monolith.
    Healthchecks are excluded.
  objectives:
  - ratioMetrics:
      good:
        query: sum(rate(apiserver_request_total{code!~"(5..|429)"}[{{.window}}]))
        queryType: promql
        source: prometheus
      target: 0.998
      total:
        query: sum(rate(apiserver_request_total[{{.window}}]))
        queryType: promql
        source: prometheus
  service: web
  timeWindows:
  - count: 30
    unit: Day
