# HEADER
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: service-pvs-http-apdex
spec:
  budgetingMethod: Occurrences
  description: ""
  objectives:
  - ratioMetrics:
      good:
        query: sum(rate(apiserver_request_total{code!~"(5..|429)"}[{{.window}}]))
        queryType: promql
        source: prometheus
      target: 0.999
      total:
        query: sum(rate(apiserver_request_total[{{.window}}]))
        queryType: promql
        source: prometheus
  service: pvs
  timeWindows:
  - count: 30
    unit: Day
