# HEADER
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: service-monitoring-prometheus-apdex
spec:
  budgetingMethod: Occurrences
  description: |
    This SLI monitors Prometheus instances via the HTTP interface.
    5xx responses are considered errors.
  objectives:
  - ratioMetrics:
      good:
        query: sum(rate(apiserver_request_total{code!~"(5..|429)"}[{{.window}}]))
        queryType: promql
        source: prometheus
      target: 0.999
      total:
        query: sum(rate(apiserver_request_total[{{.window}}]))
        queryType: promql
        source: prometheus
  service: monitoring
  timeWindows:
  - count: 30
    unit: Day
