# HEADER
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: service-git-workhorse_auth_api-apdex
spec:
  budgetingMethod: Occurrences
  description: |
    Monitors Workhorse API endpoints, running in the Git fleet, via the HTTP interface.
    Workhorse API requests have much tigher latency requirements, as these requests originate in GitLab-Shell
    and are on the critical path for authentication of Git SSH commands.
  objectives:
  - ratioMetrics:
      good:
        query: sum(rate(apiserver_request_total{code!~"(5..|429)"}[{{.window}}]))
        queryType: promql
        source: prometheus
      target: 0.998
      total:
        query: sum(rate(apiserver_request_total[{{.window}}]))
        queryType: promql
        source: prometheus
  service: git
  timeWindows:
  - count: 30
    unit: Day
