# HEADER
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: service-sidekiq-shard_low_urgency_cpu_bound-apdex
spec:
  budgetingMethod: Occurrences
  description: |
    Aggregation of all jobs for the low-urgency-cpu-bound Sidekiq shard.
  objectives:
  - ratioMetrics:
      good:
        query: sum(rate(apiserver_request_total{code!~"(5..|429)"}[{{.window}}]))
        queryType: promql
        source: prometheus
      target: 0.995
      total:
        query: sum(rate(apiserver_request_total[{{.window}}]))
        queryType: promql
        source: prometheus
  service: sidekiq
  timeWindows:
  - count: 30
    unit: Day
