# HEADER
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: service-monitoring-thanos_store-apdex
spec:
  budgetingMethod: Occurrences
  description: |
    Thanos store will respond to Thanos Query (and other) requests for historical data. This historical data is kept in
    GCS buckets. This SLI monitors the Thanos StoreAPI GRPC endpoint. GRPC error responses are considered to be service-level failures.
  objectives:
  - ratioMetrics:
      good:
        query: sum(rate(apiserver_request_total{code!~"(5..|429)"}[{{.window}}]))
        queryType: promql
        source: prometheus
      target: 0.999
      total:
        query: sum(rate(apiserver_request_total[{{.window}}]))
        queryType: promql
        source: prometheus
  service: monitoring
  timeWindows:
  - count: 30
    unit: Day
