# HEADER
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: service-gitaly-goserver-apdex
spec:
  budgetingMethod: Occurrences
  description: |
    This SLI monitors all Gitaly GRPC requests in aggregate, excluding the OperationService.
    GRPC failures which are considered to be the "server's fault" are counted as errors.
    The apdex score is based on a subset of GRPC methods which are expected to be fast.
  objectives:
  - ratioMetrics:
      good:
        query: sum(rate(apiserver_request_total{code!~"(5..|429)"}[{{.window}}]))
        queryType: promql
        source: prometheus
      target: 0.999
      total:
        query: sum(rate(apiserver_request_total[{{.window}}]))
        queryType: promql
        source: prometheus
  service: gitaly
  timeWindows:
  - count: 30
    unit: Day
