# HEADER
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: service-gitaly-gitalyruby-apdex
spec:
  budgetingMethod: Occurrences
  description: |
    This SLI monitors requests to Gitaly's Ruby sidecar, known as Gitaly-Ruby. All requests made to
    Gitaly-Ruby are monitored in aggregate, via its GRPC interface.
  objectives:
  - ratioMetrics:
      good:
        query: sum(rate(apiserver_request_total{code!~"(5..|429)"}[{{.window}}]))
        queryType: promql
        source: prometheus
      target: 0.999
      total:
        query: sum(rate(apiserver_request_total[{{.window}}]))
        queryType: promql
        source: prometheus
  service: gitaly
  timeWindows:
  - count: 30
    unit: Day
