{
 "title": "istio: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8245226639 at Fri Nov  1 04:33:07 UTC 2024",
 "tags": [
  "managed",
  "istio",
  "gitlab",
  "type:istio",
  "istio",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "istio Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}[$__interval])\n",
     "legendFormat": "istio apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"istio\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"istio\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}[$__interval])\n",
     "legendFormat": "istio apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"istio\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"istio\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"istio\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"istio\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"istio\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "istio Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "istio Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "istio error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"istio\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"istio\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "istio error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"istio\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"istio\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"istio\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"istio\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"istio\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "istio Service | Errors"
    }
   ]
  },
  {
   "title": "istio Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}[$__interval])\n",
     "legendFormat": "istio RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"istio\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "istio_pilot SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"istio_pilot\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}[$__interval])\n",
     "legendFormat": "istio_pilot apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"istio_pilot\",monitor=\"global\",type=\"istio\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"istio_pilot\",monitor=\"global\",type=\"istio\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"istio_pilot\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}[$__interval])\n",
     "legendFormat": "istio_pilot apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"istio_pilot\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"istio_pilot\",monitor=\"global\",type=\"istio\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"istio_pilot\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"istio_pilot\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"istio_pilot\",monitor=\"global\",type=\"istio\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"istio_pilot\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"istio_pilot\",monitor=\"global\",type=\"istio\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"istio_pilot\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"istio_pilot\",monitor=\"global\",type=\"istio\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"istio_pilot\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"istio_pilot\",monitor=\"global\",type=\"istio\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "istio_pilot SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "istio_pilot SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"istio_pilot\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}[$__interval])\n",
     "legendFormat": "istio_pilot RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"istio_pilot\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "istio_sidecar_injection SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"istio_sidecar_injection\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "istio_sidecar_injection error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"istio_sidecar_injection\",monitor=\"global\",type=\"istio\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"istio_sidecar_injection\",monitor=\"global\",type=\"istio\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"istio_sidecar_injection\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "istio_sidecar_injection error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"istio_sidecar_injection\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"istio_sidecar_injection\",monitor=\"global\",type=\"istio\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"istio_sidecar_injection\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"istio_sidecar_injection\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"istio_sidecar_injection\",monitor=\"global\",type=\"istio\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"istio_sidecar_injection\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"istio_sidecar_injection\",monitor=\"global\",type=\"istio\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"istio_sidecar_injection\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"istio_sidecar_injection\",monitor=\"global\",type=\"istio\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"istio_sidecar_injection\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"istio_sidecar_injection\",monitor=\"global\",type=\"istio\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "istio_sidecar_injection SLI | Errors"
    }
   ]
  },
  {
   "title": "istio_sidecar_injection SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"istio_sidecar_injection\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"}[$__interval])\n",
     "legendFormat": "istio_sidecar_injection RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"istio_sidecar_injection\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"istio\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: istio_pilot",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 istio_pilot Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    sli_aggregations:pilot_proxy_convergence_time_bucket:rate_5m{app=\"istiod\",env=\"$environment\",environment=\"$environment\",job=\"pilot\"}\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "istio_pilot RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:pilot_xds_pushes:rate_5m{app=\"istiod\",env=\"$environment\",environment=\"$environment\",job=\"pilot\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 istio_pilot Latency - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,pod) (\n    sli_aggregations:pilot_proxy_convergence_time_bucket:rate_5m{app=\"istiod\",env=\"$environment\",environment=\"$environment\",job=\"pilot\",pod!=\"\"}\n  )\n)\n > 0",
       "legendFormat": "p95 {{pod}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for istio_pilot Latency - per pod",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (pod) (\n  sli_aggregations:pilot_proxy_convergence_time_bucket:rate_5m{app=\"istiod\",env=\"$environment\",environment=\"$environment\",job=\"pilot\",le=\"+Inf\",pod!=\"\"}\n)\n\n    -\n    (\n      sum by (pod) (\n  sli_aggregations:pilot_proxy_convergence_time_bucket:rate_5m{app=\"istiod\",env=\"$environment\",environment=\"$environment\",job=\"pilot\",le=\"1000\",pod!=\"\"}\n)\n\n    )\n  )\n  / ignoring(pod) group_left()\n  (\n    sum by () (\n  sli_aggregations:pilot_proxy_convergence_time_bucket:rate_5m{app=\"istiod\",env=\"$environment\",environment=\"$environment\",job=\"pilot\",le=\"+Inf\",pod!=\"\"}\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "istio_pilot RPS - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:pilot_xds_pushes:rate_5m{app=\"istiod\",env=\"$environment\",environment=\"$environment\",job=\"pilot\",pod!=\"\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: istio_sidecar_injection",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "istio_sidecar_injection Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:sidecar_injection_failure_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"pilot\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "istio_sidecar_injection RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:sidecar_injection_requests_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"pilot\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "istio_sidecar_injection Errors - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:sidecar_injection_failure_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"pilot\",pod!=\"\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "istio_sidecar_injection RPS - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:sidecar_injection_requests_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"pilot\",pod!=\"\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "☸️ Kubernetes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 },
   "collapsed": true,
   "panels": [
    {
     "title": "istio Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"istio\",env=\"$environment\",environment=\"$environment\",type=\"istio\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "istio Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"istio\",env=\"$environment\",environment=\"$environment\",type=\"istio\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "istio Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"istio\",env=\"$environment\",environment=\"$environment\",type=\"istio\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"istio\",env=\"$environment\",environment=\"$environment\",type=\"istio\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "kube_container_cpu component saturation: Kube Container CPU Utilization",
     "type": "graph",
     "description": "Kubernetes containers are allocated a share of CPU. Configured using resource requests.\n\nThis is the amount of CPU that a container should always have available,\nthough it can briefly utilize more. However, if a lot of pods on the same\nhost exceed their requested CPU the container could be throttled earlier.\n\nThis monitors utilization/allocated requests over a 1 hour period, and takes\nthe 99th quantile of that utilization percentage in that period.\nWe want the worst case to be around 80%-90% utilization,\nmeaning we've sized the container correctly. If utilization is much higher than that\nthe container could already be throttled because the host is overused, if it\nis much lower, then we could be underutilizing a host.\n\nThis saturation point is only used for capacity planning.\nContainers that have a quota specified are excluded here and can be monitored using\nthe `kube_container_throttling` saturation component.\nThe burst utilization of a CPU is monitored and alerted upon using the\n`kube_container_cpu_limit` saturation point.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, pod, container) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      (\n        sum by (environment, tier, type, stage, shard, pod, container) (\n          rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"istio\"}[1h])\n        )\n        unless on(environment, tier, type, stage, shard, pod, container) (\n          last_over_time(container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"istio\"}[1h])\n        )\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        kube_pod_container_resource_requests:labeled{container!=\"\", container!=\"POD\", resource=\"cpu\", env=\"$environment\",environment=\"$environment\",type=\"istio\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_container_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_cpu_limit component saturation: Kube Container CPU over-utilization",
     "type": "graph",
     "description": "Kubernetes containers can have a limit configured on how much CPU they can consume in\na burst. If we are at this limit, exceeding the allocated requested resources, we\nshould consider revisting the container's HPA configuration.\n\nWhen a container is utilizing CPU resources up-to it's configured limit for\nextended periods of time, this could cause it and other running containers to be\nthrottled.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, pod, container) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard, pod, container) (\n        rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"istio\"}[5m])\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"istio\"}\n        /\n        container_spec_cpu_period:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"istio\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_container_cpu_limit\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_memory component saturation: Kube Container Memory Utilization",
     "type": "graph",
     "description": "This uses the working set size from cAdvisor for the cgroup's memory usage. That may\nnot be a good measure as it includes filesystem cache pages that are not necessarily\nattributable to the application inside the cgroup, and are permitted to be evicted\ninstead of being OOM killed.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, deployment) (\n  clamp_min(\n    clamp_max(\n      container_memory_working_set_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"istio\"}\n      /\n      (container_spec_memory_limit_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"istio\"} > 0)\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ deployment }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_container_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_container_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_container_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_throttling component saturation: Kube container throttling",
     "type": "graph",
     "description": "Kube container throttling\n\nA container will be throttled if it reaches the configured cpu limit for the\nhorizontal pod autoscaler. Or when other containers on the node are overutilizing\nthe the CPU.\n\nTo get around this, consider increasing the limit for this workload, taking\ninto consideration the requested resources.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, pod, container) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      avg by (environment, tier, type, stage, shard, pod, container)(\n        rate(container_cpu_cfs_throttled_periods_total:labeled{container!=\"\", env=\"$environment\",environment=\"$environment\",type=\"istio\"}[5m])\n        /\n        rate(container_cpu_cfs_periods_total:labeled{container!=\"\", env=\"$environment\",environment=\"$environment\",type=\"istio\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_container_throttling\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_container_throttling\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_container_throttling\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_throttling\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_throttling\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_go_memory component saturation: Go Memory Utilization per Node",
     "type": "graph",
     "description": "Measures Go memory usage as a percentage of container memory limit\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(env, environment, tier, type, stage, shard, cluster, pod) (\n  clamp_min(\n    clamp_max(\n      go_memstats_alloc_bytes{env=\"$environment\",environment=\"$environment\",type=\"istio\"}\n      / on(env, environment, tier, type, stage, shard, cluster, pod) group_left()\n      topk by(env, environment, tier, type, stage, shard, cluster, pod) (1,\n        container_spec_memory_limit_bytes:labeled{container=~\"gitlab-pages|gitlab-workhorse|kas|registry|thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"istio\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ cluster }} {{ pod }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_go_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_go_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_go_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_go_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_go_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_horizontalpodautoscaler_desired_replicas component saturation: Horizontal Pod Autoscaler Desired Replicas",
     "type": "graph",
     "description": "The [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)\nautomatically scales the number of Pods in a deployment based on metrics.\n\nThe Horizontal Pod Autoscaler has a configured upper maximum. When this\nlimit is reached, the HPA will not increase the number of pods and other\nresource saturation (eg, CPU, memory) may occur.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, horizontalpodautoscaler, shard) (\n  clamp_min(\n    clamp_max(\n      kube_horizontalpodautoscaler_status_desired_replicas:labeled{env=\"$environment\",environment=\"$environment\",type=\"istio\", shard!~\"ai-abstraction-layer|database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects\", namespace!~\"pubsubbeat\"}\n      /\n      kube_horizontalpodautoscaler_spec_max_replicas:labeled{env=\"$environment\",environment=\"$environment\",type=\"istio\", shard!~\"ai-abstraction-layer|database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects\", namespace!~\"pubsubbeat\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ horizontalpodautoscaler }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",type=\"istio\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"istio\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",type=\"istio\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"istio\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"istio\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph inf\n  istio\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph inf\n  istio\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph inf\n  istio[\"istio (Level 2)\"]\nend\n\n\n  \n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}