{
 "title": "spamcheck: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8397766929 at Mon Nov 18 09:15:46 UTC 2024",
 "tags": [
  "managed",
  "spamcheck",
  "gitlab",
  "type:spamcheck",
  "spamcheck",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "spamcheck Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}[$__interval])\n",
     "legendFormat": "spamcheck apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"spamcheck\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"spamcheck\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}[$__interval])\n",
     "legendFormat": "spamcheck apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"spamcheck\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"spamcheck\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"spamcheck\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"spamcheck\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"spamcheck\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "spamcheck Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "spamcheck Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "spamcheck error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"spamcheck\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"spamcheck\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "spamcheck error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"spamcheck\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"spamcheck\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"spamcheck\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"spamcheck\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"spamcheck\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "spamcheck Service | Errors"
    }
   ]
  },
  {
   "title": "spamcheck Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}[$__interval])\n",
     "legendFormat": "spamcheck RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "runway_ingress SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}[$__interval])\n",
     "legendFormat": "runway_ingress apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"spamcheck\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"spamcheck\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}[$__interval])\n",
     "legendFormat": "runway_ingress apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"spamcheck\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"spamcheck\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"spamcheck\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"spamcheck\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"spamcheck\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "runway_ingress SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "runway_ingress SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "runway_ingress error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"spamcheck\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"spamcheck\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "runway_ingress error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"spamcheck\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"spamcheck\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"spamcheck\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"spamcheck\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"spamcheck\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "runway_ingress SLI | Errors"
    }
   ]
  },
  {
   "title": "runway_ingress SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}[$__interval])\n",
     "legendFormat": "runway_ingress RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "content": "### Description\n\nApplication load balancer serving ingress HTTP requests for the Runway service.\n\n\n\n### Observability Tools\n\n* [Google Cloud Run Console](https://console.cloud.google.com/run/detail/us-east1/spamcheck/metrics?project=gitlab-runway-production)\n* [Stackdriver Logs: Cloud Run Access Logs](https://console.cloud.google.com/logs/query;query=resource%2Elabels%2Eservice%5Fname%3D%22spamcheck%22%0Aresource%2Etype%3D%22cloud%5Frun%5Frevision%22;timeRange=PT30M?project=gitlab-runway-production)\n* [Stackdriver Logs: Cloud Run Access 5xx Logs](https://console.cloud.google.com/logs/query;query=httpRequest%2Estatus%3E%3D500%0Aresource%2Elabels%2Eservice%5Fname%3D%22spamcheck%22%0Aresource%2Etype%3D%22cloud%5Frun%5Frevision%22;timeRange=PT30M?project=gitlab-runway-production)\n\n"
  },
  {
   "title": "runway_lb SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"runway_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "runway_lb error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"runway_lb\",monitor=\"global\",type=\"spamcheck\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"runway_lb\",monitor=\"global\",type=\"spamcheck\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"runway_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "runway_lb error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"runway_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"runway_lb\",monitor=\"global\",type=\"spamcheck\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"runway_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"runway_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"runway_lb\",monitor=\"global\",type=\"spamcheck\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"runway_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"runway_lb\",monitor=\"global\",type=\"spamcheck\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"runway_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"runway_lb\",monitor=\"global\",type=\"spamcheck\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"runway_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"runway_lb\",monitor=\"global\",type=\"spamcheck\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "runway_lb SLI | Errors"
    }
   ]
  },
  {
   "title": "runway_lb SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"runway_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"}[$__interval])\n",
     "legendFormat": "runway_lb RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"runway_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"spamcheck\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "content": "### Description\n\nExternal load balancer serving global HTTP requests for the Runway service.\n\n\n\n### Observability Tools\n\n* [Google Load Balancer](https://console.cloud.google.com/net-services/loadbalancing/details/http/spamcheck-url-map?project=gitlab-runway-production)\n* [Stackdriver Logs: Loadbalancer Access Logs](https://console.cloud.google.com/logs/query;query=resource%2Elabels%2Eurl%5Fmap%5Fname%3D%22spamcheck%2Durl%2Dmap%22%0Aresource%2Etype%3D%22http%5Fload%5Fbalancer%22;timeRange=PT30M?project=gitlab-runway-production)\n* [Stackdriver Logs: Loadbalancer Access 5xx Logs](https://console.cloud.google.com/logs/query;query=httpRequest%2Estatus%3E%3D500%0Aresource%2Elabels%2Eurl%5Fmap%5Fname%3D%22spamcheck%2Durl%2Dmap%22%0Aresource%2Etype%3D%22http%5Fload%5Fbalancer%22;timeRange=PT30M?project=gitlab-runway-production)\n\n"
  },
  {
   "title": "🔬 SLI Detail: runway_ingress",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 runway_ingress Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "ms", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",response_code_class!~\"4xx|5xx\",type=\"spamcheck\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "runway_ingress Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",environment=\"$environment\",response_code_class=\"5xx\",type=\"spamcheck\"}[$__interval]) / 60\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "runway_ingress RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\"}[$__interval]) / 60\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 runway_ingress Latency - per revision_name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,revision_name) (\n    avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",response_code_class!~\"4xx|5xx\",revision_name!=\"\",type=\"spamcheck\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{revision_name}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for runway_ingress Latency - per revision_name",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (revision_name) (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",response_code_class!~\"4xx|5xx\",revision_name!=\"\",type=\"spamcheck\"}[$__interval])\n)\n\n    -\n    (\n      sum by (revision_name) (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",le=\"1067.1895716335973\",response_code_class!~\"4xx|5xx\",revision_name!=\"\",type=\"spamcheck\"}[$__interval])\n)\n\n    )\n  )\n  / ignoring(revision_name) group_left()\n  (\n    sum by () (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",response_code_class!~\"4xx|5xx\",revision_name!=\"\",type=\"spamcheck\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{revision_name}}"
      }
     ]
    },
    {
     "title": "runway_ingress Errors - per revision_name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (revision_name) (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",environment=\"$environment\",response_code_class=\"5xx\",revision_name!=\"\",type=\"spamcheck\"}[$__interval]) / 60\n)\n > 0",
       "legendFormat": "{{revision_name}}"
      }
     ]
    },
    {
     "title": "runway_ingress RPS - per revision_name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (revision_name) (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",environment=\"$environment\",revision_name!=\"\",type=\"spamcheck\"}[$__interval]) / 60\n)\n > 0",
       "legendFormat": "{{revision_name}}"
      }
     ]
    },
    {
     "title": "Estimated p95 runway_ingress Latency - per response_code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ms", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,response_code) (\n    avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",response_code!=\"\",response_code_class!~\"4xx|5xx\",type=\"spamcheck\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{response_code}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for runway_ingress Latency - per response_code",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (response_code) (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",response_code!=\"\",response_code_class!~\"4xx|5xx\",type=\"spamcheck\"}[$__interval])\n)\n\n    -\n    (\n      sum by (response_code) (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",le=\"1067.1895716335973\",response_code!=\"\",response_code_class!~\"4xx|5xx\",type=\"spamcheck\"}[$__interval])\n)\n\n    )\n  )\n  / ignoring(response_code) group_left()\n  (\n    sum by () (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",response_code!=\"\",response_code_class!~\"4xx|5xx\",type=\"spamcheck\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{response_code}}"
      }
     ]
    },
    {
     "title": "runway_ingress Errors - per response_code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (response_code) (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",environment=\"$environment\",response_code!=\"\",response_code_class=\"5xx\",type=\"spamcheck\"}[$__interval]) / 60\n)\n > 0",
       "legendFormat": "{{response_code}}"
      }
     ]
    },
    {
     "title": "runway_ingress RPS - per response_code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (response_code) (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",environment=\"$environment\",response_code!=\"\",type=\"spamcheck\"}[$__interval]) / 60\n)\n > 0",
       "legendFormat": "{{response_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: runway_lb",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "runway_lb Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"runway-exporter\",response_code_class=\"500\",url_map_name=\"spamcheck-url-map\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "runway_lb RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"runway-exporter\",url_map_name=\"spamcheck-url-map\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "runway_lb Errors - per proxy_continent",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy_continent) (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"runway-exporter\",proxy_continent!=\"\",response_code_class=\"500\",url_map_name=\"spamcheck-url-map\"}\n)\n > 0",
       "legendFormat": "{{proxy_continent}}"
      }
     ]
    },
    {
     "title": "runway_lb RPS - per proxy_continent",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy_continent) (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"runway-exporter\",proxy_continent!=\"\",url_map_name=\"spamcheck-url-map\"}\n)\n > 0",
       "legendFormat": "{{proxy_continent}}"
      }
     ]
    },
    {
     "title": "runway_lb Errors - per response_code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (response_code) (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"runway-exporter\",response_code!=\"\",response_code_class=\"500\",url_map_name=\"spamcheck-url-map\"}\n)\n > 0",
       "legendFormat": "{{response_code}}"
      }
     ]
    },
    {
     "title": "runway_lb RPS - per response_code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (response_code) (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"runway-exporter\",response_code!=\"\",url_map_name=\"spamcheck-url-map\"}\n)\n > 0",
       "legendFormat": "{{response_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "runway_container_cpu_utilization component saturation: Runway Container CPU Utilization",
     "type": "graph",
     "description": "Container CPU utilization of the Runway service distributed across all container instances.\n\nFor scaling, refer to https://cloud.google.com/run/docs/configuring/services/cpu.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, type, shard, revision_name, region, location) (\n  clamp_min(\n    clamp_max(\n      histogram_quantile(0.9999, sum by(le, environment, type, shard, revision_name, region, location)\n        (\n          avg_over_time(\n            stackdriver_cloud_run_revision_run_googleapis_com_container_cpu_utilizations_bucket{job=\"runway-exporter\",env=\"$environment\",environment=\"$environment\",type=\"spamcheck\"}[30m]\n          )\n        )\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ revision_name }} {{ region }} {{ location }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\", component=\"runway_container_cpu_utilization\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\", component=\"runway_container_cpu_utilization\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\", component=\"runway_container_cpu_utilization\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"runway_container_cpu_utilization\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"runway_container_cpu_utilization\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "runway_container_instance_utilization component saturation: Runway Container Instance Utilization",
     "type": "graph",
     "description": "Container instance utilization of the Runway service.\n\nFor scaling, refer to https://cloud.google.com/run/docs/configuring/max-instances.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, type, shard, revision_name, region, location) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, type, shard, revision_name, region, location) (\n        stackdriver_cloud_run_revision_run_googleapis_com_container_instance_count{job=\"runway-exporter\",state=\"active\",env=\"$environment\",environment=\"$environment\",type=\"spamcheck\"}\n      )\n      /\n      100\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ revision_name }} {{ region }} {{ location }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\", component=\"runway_container_instance_utilization\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\", component=\"runway_container_instance_utilization\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\", component=\"runway_container_instance_utilization\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"runway_container_instance_utilization\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"runway_container_instance_utilization\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "runway_container_max_concurrent_requests component saturation: Runway Max Concurrent Requests",
     "type": "graph",
     "description": "Max number of concurrent requests being served by each container instance of the Runway service.\n\nFor scaling, refer to https://cloud.google.com/run/docs/configuring/concurrency.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, type, shard, revision_name, region, location) (\n  clamp_min(\n    clamp_max(\n      histogram_quantile(0.9999, sum by(le, environment, type, shard, revision_name, region, location)\n        (\n          rate(\n            stackdriver_cloud_run_revision_run_googleapis_com_container_max_request_concurrencies_bucket{job=\"runway-exporter\",state=\"active\",env=\"$environment\",environment=\"$environment\",type=\"spamcheck\"}[30m]\n          )\n        )\n      ) / 100\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ revision_name }} {{ region }} {{ location }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\", component=\"runway_container_max_concurrent_requests\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\", component=\"runway_container_max_concurrent_requests\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\", component=\"runway_container_max_concurrent_requests\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"runway_container_max_concurrent_requests\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"runway_container_max_concurrent_requests\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "runway_container_memory_utilization component saturation: Runway Container Memory Utilization",
     "type": "graph",
     "description": "Container memory utilization of the Runway service distributed across all container instances.\n\nFor scaling, refer to https://cloud.google.com/run/docs/configuring/services/memory-limits.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, type, shard, revision_name, region) (\n  clamp_min(\n    clamp_max(\n      histogram_quantile(0.9999, sum by(le, environment, type, shard, revision_name, region)\n        (\n          avg_over_time(\n            stackdriver_cloud_run_revision_run_googleapis_com_container_memory_utilizations_bucket{job=\"runway-exporter\",env=\"$environment\",environment=\"$environment\",type=\"spamcheck\"}[30m]\n          )\n        )\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ revision_name }} {{ region }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\", component=\"runway_container_memory_utilization\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\", component=\"runway_container_memory_utilization\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"spamcheck\", component=\"runway_container_memory_utilization\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"runway_container_memory_utilization\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"runway_container_memory_utilization\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph sv\n  spamcheck\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph sv\n  spamcheck\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph sv\n  spamcheck[\"spamcheck (Level 2)\"]\nend\n\n\n  \n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}