{
 "title": "ai-gateway: Language",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8245226639 at Fri Nov  1 04:32:44 UTC 2024",
 "tags": [
  "managed",
  "ai-gateway",
  "type:ai-gateway",
  "detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Acceptance Rate / sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "Acceptance Rates per Second" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by(lang) (\n  rate(code_suggestions_accepts_total{env=\"$environment\",environment=\"$environment\",type=\"ai-gateway\",lang=~\".+\"}[$__rate_interval])\n)\n/ on(lang) group_left()\nsum by(lang) (\n  rate(code_suggestions_requests_total{env=\"$environment\",environment=\"$environment\",type=\"ai-gateway\",lang=~\".+\"}[$__rate_interval]) > 0\n)\n,1),0)\n",
     "legendFormat": "{{lang}}"
    }
   ]
  },
  {
   "title": "Acceptance by Language",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  100 *\n    sum by(lang) (\n      increase(code_suggestions_accepts_total{env=\"$environment\",environment=\"$environment\",type=\"ai-gateway\",lang=~\".+\"}[$__range])\n    )\n    / on(lang) group_left()\n    sum by(lang) (\n      increase(code_suggestions_requests_total{env=\"$environment\",environment=\"$environment\",type=\"ai-gateway\",lang=~\".+\"}[$__range]) > 0\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Language / sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ops", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by(lang, symbol) (\n  rate(code_suggestions_prompt_language_total{env=\"$environment\",environment=\"$environment\",type=\"ai-gateway\"}[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage by Language",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  100 *\n    sum by(lang) (\n      increase(code_suggestions_prompt_language_total{env=\"$environment\",environment=\"$environment\",type=\"ai-gateway\",lang=~\".+\"}[$__range])\n    )\n    / on() group_left()\n    sum (\n      increase(code_suggestions_prompt_language_total{env=\"$environment\",environment=\"$environment\",type=\"ai-gateway\",lang=~\".+\"}[$__range])\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Extension / sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ops", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by(extension) (\n  rate(code_suggestions_prompt_language_total{env=\"$environment\",environment=\"$environment\",type=\"ai-gateway\",extension=~\".+\"}[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage by Extension",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  100 *\n    sum by(extension) (\n      increase(code_suggestions_prompt_language_total{env=\"$environment\",environment=\"$environment\",type=\"ai-gateway\",extension=~\".+\"}[$__range])\n    )\n    / on() group_left()\n    sum (\n      increase(code_suggestions_prompt_language_total{env=\"$environment\",environment=\"$environment\",type=\"ai-gateway\",extension=~\".+\"}[$__range])\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Symbol / sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ops", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by(lang) (\n  rate(code_suggestions_prompt_symbols_total{env=\"$environment\",environment=\"$environment\",type=\"ai-gateway\"}[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extensions with Unknown Language",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by(extension) (\n    increase(code_suggestions_prompt_language_total{env=\"$environment\",environment=\"$environment\",type=\"ai-gateway\",lang=\"None\",extension=~\".+\"}[$__range])\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}