{
 "title": "ai-gateway: Regional Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7867191950 at Thu Sep 19 12:04:24 UTC 2024",
 "tags": [
  "managed",
  "ai-gateway",
  "type:ai-gateway",
  "regional"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "Regional Service Aggregated  Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_regional_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"ai-gateway\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"ai-gateway\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "Regional Service Aggregated  Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_regional_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "Regional Service Aggregated  RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_regional_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  { "title": "🔬 Regional SLIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "inference SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"inference\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"inference\",monitor=\"global\",type=\"ai-gateway\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"inference\",monitor=\"global\",type=\"ai-gateway\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "inference SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1001 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"inference\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"inference\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"inference\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "inference SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"inference\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1001 },
   "content": "### Description\n\nInferences to the different model engines used by the AI-gateway.\n\nApdex applies to non-streaming inferences, they are considered fast enough\nwhen the request took less than 30s. Errors don't count toward apdex\n\nA failure means an inference threw an error, for example when the model is\nnot available.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Model Inference logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:exists,type:json.jsonPayload.model_engine,value:exists),query:(exists:(field:json.jsonPayload.model_engine)))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Model Inference failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:exists,type:json.jsonPayload.model_engine,value:exists),query:(exists:(field:json.jsonPayload.model_engine))),(meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Model Inference requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:exists,type:json.jsonPayload.model_engine,value:exists),query:(exists:(field:json.jsonPayload.model_engine)))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Model Inference failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:exists,type:json.jsonPayload.model_engine,value:exists),query:(exists:(field:json.jsonPayload.model_engine))),(meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Model Inference sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:exists,type:json.jsonPayload.model_engine,value:exists),query:(exists:(field:json.jsonPayload.model_engine)))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Model Inference sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:exists,type:json.jsonPayload.model_engine,value:exists),query:(exists:(field:json.jsonPayload.model_engine)))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Model Inference percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:exists,type:json.jsonPayload.model_engine,value:exists),query:(exists:(field:json.jsonPayload.model_engine)))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Model Inference percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:exists,type:json.jsonPayload.model_engine,value:exists),query:(exists:(field:json.jsonPayload.model_engine)))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.jsonPayload.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "runway_ingress SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1011 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ai-gateway\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ai-gateway\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "runway_ingress SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1011 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "runway_ingress SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1011 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1011 },
   "content": "### Description\n\nApplication load balancer serving ingress HTTP requests for the Runway service.\n\n\n\n### Observability Tools\n\n* [Google Cloud Run Console](https://console.cloud.google.com/run/detail/us-east1/ai-gateway/metrics?project=gitlab-runway-production)\n* [Stackdriver Logs: Cloud Run Access Logs](https://console.cloud.google.com/logs/query;query=resource%2Elabels%2Eservice%5Fname%3D%22ai%2Dgateway%22%0Aresource%2Etype%3D%22cloud%5Frun%5Frevision%22;timeRange=PT30M?project=gitlab-runway-production)\n* [Stackdriver Logs: Cloud Run Access 5xx Logs](https://console.cloud.google.com/logs/query;query=httpRequest%2Estatus%3E%3D500%0Aresource%2Elabels%2Eservice%5Fname%3D%22ai%2Dgateway%22%0Aresource%2Etype%3D%22cloud%5Frun%5Frevision%22;timeRange=PT30M?project=gitlab-runway-production)\n* [📖 Kibana: MLOps logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.project_id,params:'gitlab-runway-production',type:phrase),query:(match:(json.jsonPayload.project_id:(query:'gitlab-runway-production',type:phrase))))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: MLOps failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.project_id,params:'gitlab-runway-production',type:phrase),query:(match:(json.jsonPayload.project_id:(query:'gitlab-runway-production',type:phrase)))),(meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: MLOps requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.project_id,params:'gitlab-runway-production',type:phrase),query:(match:(json.jsonPayload.project_id:(query:'gitlab-runway-production',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: MLOps failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.project_id,params:'gitlab-runway-production',type:phrase),query:(match:(json.jsonPayload.project_id:(query:'gitlab-runway-production',type:phrase)))),(meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: MLOps sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.project_id,params:'gitlab-runway-production',type:phrase),query:(match:(json.jsonPayload.project_id:(query:'gitlab-runway-production',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: MLOps sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.project_id,params:'gitlab-runway-production',type:phrase),query:(match:(json.jsonPayload.project_id:(query:'gitlab-runway-production',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: MLOps percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.project_id,params:'gitlab-runway-production',type:phrase),query:(match:(json.jsonPayload.project_id:(query:'gitlab-runway-production',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: MLOps percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.project_id,params:'gitlab-runway-production',type:phrase),query:(match:(json.jsonPayload.project_id:(query:'gitlab-runway-production',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.jsonPayload.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "runway_lb SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1021 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"runway_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"runway_lb\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"runway_lb\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "runway_lb SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1021 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"runway_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1021 },
   "content": "### Description\n\nExternal load balancer serving global HTTP requests for the Runway service.\n\n\n\n### Observability Tools\n\n* [Google Load Balancer](https://console.cloud.google.com/net-services/loadbalancing/details/http/ai-gateway-url-map?project=gitlab-runway-production)\n* [Stackdriver Logs: Loadbalancer Access Logs](https://console.cloud.google.com/logs/query;query=resource%2Elabels%2Eurl%5Fmap%5Fname%3D%22ai%2Dgateway%2Durl%2Dmap%22%0Aresource%2Etype%3D%22http%5Fload%5Fbalancer%22;timeRange=PT30M?project=gitlab-runway-production)\n* [Stackdriver Logs: Loadbalancer Access 5xx Logs](https://console.cloud.google.com/logs/query;query=httpRequest%2Estatus%3E%3D500%0Aresource%2Elabels%2Eurl%5Fmap%5Fname%3D%22ai%2Dgateway%2Durl%2Dmap%22%0Aresource%2Etype%3D%22http%5Fload%5Fbalancer%22;timeRange=PT30M?project=gitlab-runway-production)\n\n"
  },
  {
   "title": "server SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1031 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server\",monitor=\"global\",type=\"ai-gateway\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server\",monitor=\"global\",type=\"ai-gateway\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "server SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1031 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"server\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"server\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "server SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1031 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1031 },
   "content": "### Description\n\nFastAPI server for AI Gateway.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: FastAPI Server logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase))))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: FastAPI Server failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.jsonPayload.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "server_chat SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1041 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"server_chat\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_chat\",monitor=\"global\",type=\"ai-gateway\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_chat\",monitor=\"global\",type=\"ai-gateway\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "server_chat SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1041 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"server_chat\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"server_chat\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"server_chat\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "server_chat SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1041 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"server_chat\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1041 },
   "content": "### Description\n\nFastAPI server for AI Gateway - chat.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: FastAPI Server - chat logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v1/chat/agent',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v1/chat/agent',type:phrase))))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: FastAPI Server - chat failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v1/chat/agent',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v1/chat/agent',type:phrase)))),(meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - chat requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v1/chat/agent',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v1/chat/agent',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - chat failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v1/chat/agent',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v1/chat/agent',type:phrase)))),(meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - chat sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v1/chat/agent',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v1/chat/agent',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - chat sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v1/chat/agent',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v1/chat/agent',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - chat percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v1/chat/agent',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v1/chat/agent',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - chat percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v1/chat/agent',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v1/chat/agent',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.jsonPayload.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "server_code_completions SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1051 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"server_code_completions\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_code_completions\",monitor=\"global\",type=\"ai-gateway\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_code_completions\",monitor=\"global\",type=\"ai-gateway\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "server_code_completions SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1051 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"server_code_completions\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"server_code_completions\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"server_code_completions\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "server_code_completions SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1051 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"server_code_completions\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1051 },
   "content": "### Description\n\nFastAPI server for AI Gateway - code completions.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: FastAPI Server - code completions logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v2/code/completions',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v2/code/completions',type:phrase))))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: FastAPI Server - code completions failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v2/code/completions',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v2/code/completions',type:phrase)))),(meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - code completions requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v2/code/completions',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v2/code/completions',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - code completions failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v2/code/completions',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v2/code/completions',type:phrase)))),(meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - code completions sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v2/code/completions',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v2/code/completions',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - code completions sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v2/code/completions',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v2/code/completions',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - code completions percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v2/code/completions',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v2/code/completions',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - code completions percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v2/code/completions',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v2/code/completions',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.jsonPayload.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "server_code_generations SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1061 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"server_code_generations\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_code_generations\",monitor=\"global\",type=\"ai-gateway\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_code_generations\",monitor=\"global\",type=\"ai-gateway\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "server_code_generations SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1061 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"server_code_generations\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"server_code_generations\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"server_code_generations\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "server_code_generations SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1061 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"server_code_generations\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1061 },
   "content": "### Description\n\nFastAPI server for AI Gateway - code generations.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: FastAPI Server - code generations logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v2/code/generations',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v2/code/generations',type:phrase))))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: FastAPI Server - code generations failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v2/code/generations',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v2/code/generations',type:phrase)))),(meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - code generations requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v2/code/generations',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v2/code/generations',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - code generations failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v2/code/generations',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v2/code/generations',type:phrase)))),(meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - code generations sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v2/code/generations',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v2/code/generations',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - code generations sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v2/code/generations',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v2/code/generations',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - code generations percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v2/code/generations',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v2/code/generations',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - code generations percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v2/code/generations',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v2/code/generations',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.jsonPayload.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "server_x_ray SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1071 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"server_x_ray\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_x_ray\",monitor=\"global\",type=\"ai-gateway\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_x_ray\",monitor=\"global\",type=\"ai-gateway\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "server_x_ray SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1071 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"server_x_ray\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"server_x_ray\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"server_x_ray\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "server_x_ray SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1071 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"server_x_ray\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1071 },
   "content": "### Description\n\nFastAPI server for AI Gateway - X-Ray.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: FastAPI Server - X-Ray logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v1/x-ray/libraries',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v1/x-ray/libraries',type:phrase))))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: FastAPI Server - X-Ray failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v1/x-ray/libraries',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v1/x-ray/libraries',type:phrase)))),(meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - X-Ray requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v1/x-ray/libraries',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v1/x-ray/libraries',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - X-Ray failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v1/x-ray/libraries',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v1/x-ray/libraries',type:phrase)))),(meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - X-Ray sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v1/x-ray/libraries',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v1/x-ray/libraries',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - X-Ray sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v1/x-ray/libraries',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v1/x-ray/libraries',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - X-Ray percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v1/x-ray/libraries',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v1/x-ray/libraries',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: FastAPI Server - X-Ray percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.logger,params:api.access,type:phrase),query:(match:(json.jsonPayload.logger:(query:api.access,type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.path,params:'/v1/x-ray/libraries',type:phrase),query:(match:(json.jsonPayload.path:(query:'/v1/x-ray/libraries',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.jsonPayload.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "waf SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1081 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"waf\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"waf\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"waf\",monitor=\"global\",type=\"ai-gateway\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "waf SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1081 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"waf\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"ai-gateway\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1081 },
   "content": "### Description\n\nCloudflare WAF and rate limit rules for codesuggestions.gitlab.com host.\n\n\n\n### Observability Tools\n\n* [Cloudflare: codesuggestions.gitlab.com](https://dash.cloudflare.com/852e9d53d0f8adbd9205389356f2303d/gitlab.com/analytics/traffic?host=codesuggestions.gitlab.com&time-window=30)\n* [Grafana: CloudFlare Overview](/d/cloudflare-main/cloudflare-overview?)\n\n"
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}