{
 "title": "packagecloud: Kube Containers Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8397766929 at Mon Nov 18 09:15:12 UTC 2024",
 "tags": [
  "managed",
  "packagecloud",
  "packagecloud",
  "type:packagecloud",
  "kube",
  "kube detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   }
  ]
 },
 "panels": [
  { "title": "rainbows deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "packagecloud container/rainbows deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 packagecloud Container CPU"
    }
   ]
  },
  {
   "title": "packagecloud container/rainbows deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p99 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p95 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p75 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p50 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p25 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p10 packagecloud Container Memory"
    }
   ]
  },
  {
   "title": "packagecloud container/rainbows deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"packagecloud\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "packagecloud container/rainbows deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"packagecloud\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "memorystore-tls container/rainbows deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 memorystore-tls Container CPU"
    }
   ]
  },
  {
   "title": "memorystore-tls container/rainbows deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p99 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p95 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p75 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p50 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p25 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p10 memorystore-tls Container Memory"
    }
   ]
  },
  {
   "title": "memorystore-tls container/rainbows deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"memorystore-tls\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "memorystore-tls container/rainbows deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"memorystore-tls\",deployment=\"rainbows\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "resque deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "packagecloud container/resque deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 packagecloud Container CPU"
    }
   ]
  },
  {
   "title": "packagecloud container/resque deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p99 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p95 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p75 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p50 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p25 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p10 packagecloud Container Memory"
    }
   ]
  },
  {
   "title": "packagecloud container/resque deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"packagecloud\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "packagecloud container/resque deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"packagecloud\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "memorystore-tls container/resque deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 memorystore-tls Container CPU"
    }
   ]
  },
  {
   "title": "memorystore-tls container/resque deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p99 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p95 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p75 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p50 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p25 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p10 memorystore-tls Container Memory"
    }
   ]
  },
  {
   "title": "memorystore-tls container/resque deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"memorystore-tls\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "memorystore-tls container/resque deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"memorystore-tls\",deployment=\"resque\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "sql-proxy deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "sqlproxy container/sql-proxy deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sqlproxy\",deployment=\"sql-proxy\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 sqlproxy Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sqlproxy\",deployment=\"sql-proxy\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 sqlproxy Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sqlproxy\",deployment=\"sql-proxy\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 sqlproxy Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sqlproxy\",deployment=\"sql-proxy\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 sqlproxy Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sqlproxy\",deployment=\"sql-proxy\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 sqlproxy Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sqlproxy\",deployment=\"sql-proxy\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 sqlproxy Container CPU"
    }
   ]
  },
  {
   "title": "sqlproxy container/sql-proxy deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"sqlproxy\",deployment=\"sql-proxy\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p99 sqlproxy Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"sqlproxy\",deployment=\"sql-proxy\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p95 sqlproxy Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"sqlproxy\",deployment=\"sql-proxy\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p75 sqlproxy Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"sqlproxy\",deployment=\"sql-proxy\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p50 sqlproxy Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"sqlproxy\",deployment=\"sql-proxy\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p25 sqlproxy Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"sqlproxy\",deployment=\"sql-proxy\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p10 sqlproxy Container Memory"
    }
   ]
  },
  {
   "title": "sqlproxy container/sql-proxy deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"sqlproxy\",deployment=\"sql-proxy\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sqlproxy container/sql-proxy deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"sqlproxy\",deployment=\"sql-proxy\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "toolbox deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "packagecloud container/toolbox deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 packagecloud Container CPU"
    }
   ]
  },
  {
   "title": "packagecloud container/toolbox deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p99 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p95 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p75 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p50 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p25 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p10 packagecloud Container Memory"
    }
   ]
  },
  {
   "title": "packagecloud container/toolbox deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"packagecloud\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "packagecloud container/toolbox deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"packagecloud\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "memorystore-tls container/toolbox deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 memorystore-tls Container CPU"
    }
   ]
  },
  {
   "title": "memorystore-tls container/toolbox deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p99 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p95 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p75 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p50 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p25 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p10 memorystore-tls Container Memory"
    }
   ]
  },
  {
   "title": "memorystore-tls container/toolbox deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"memorystore-tls\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "memorystore-tls container/toolbox deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"memorystore-tls\",deployment=\"toolbox\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "web deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "packagecloud container/web deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 packagecloud Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"packagecloud\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 packagecloud Container CPU"
    }
   ]
  },
  {
   "title": "packagecloud container/web deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p99 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p95 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p75 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p50 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p25 packagecloud Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"packagecloud\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p10 packagecloud Container Memory"
    }
   ]
  },
  {
   "title": "packagecloud container/web deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"packagecloud\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "packagecloud container/web deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"packagecloud\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "memorystore-tls container/web deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 memorystore-tls Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memorystore-tls\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 memorystore-tls Container CPU"
    }
   ]
  },
  {
   "title": "memorystore-tls container/web deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p99 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p95 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p75 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p50 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p25 memorystore-tls Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"memorystore-tls\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n }\n)\n",
     "legendFormat": "p10 memorystore-tls Container Memory"
    }
   ]
  },
  {
   "title": "memorystore-tls container/web deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"memorystore-tls\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "memorystore-tls container/web deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"memorystore-tls\",deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"packagecloud\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}