{
 "title": "delivery: Percentage of Auto deploy environment states",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8397766929 at Mon Nov 18 09:15:52 UTC 2024",
 "tags": [
  "managed",
  "delivery",
  "release"
 ],
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Deployment state explainer",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "- Awaiting promotion - State where production or staging was idle and waiting for a package to be promoted. This only counts the time where there was a package available for promotion.\n- Ready - State where the environment was idle.\n- Baking time - State where there was a package baking on gprd-cny.\n- Locked - State where there was a deployment ongoing on the environment, or QA, or post-deploy migrations being executed.\n"
  },
  {
   "title": "gprd-main environment states",
   "type": "piechart",
   "description": "Pie chart representation of the percentage of time gprd-main spent in different states",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without (pod,instance) (delivery_auto_deploy_environment_state{target_env=\"gprd\", target_stage=\"main\"}) * $__range_s",
     "legendFormat": "{{env_state}}"
    }
   ]
  },
  {
   "title": "gprd-main environment states",
   "type": "graph",
   "description": "Time series representation of the percentage of time gprd-main spent in different states",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (pod,instance) (delivery_auto_deploy_environment_state{target_env=\"gprd\", target_stage=\"main\"})",
     "legendFormat": "{{env_state}}"
    }
   ]
  },
  {
   "title": "gprd-cny environment states",
   "type": "piechart",
   "description": "Pie chart representation of the percentage of time gprd-cny spent in different states",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without (pod,instance) (delivery_auto_deploy_environment_state{target_env=\"gprd\", target_stage=\"cny\"}) * $__range_s",
     "legendFormat": "{{env_state}}"
    }
   ]
  },
  {
   "title": "gprd-cny environment states",
   "type": "graph",
   "description": "Time series representation of the percentage of time gprd-cny spent in different states",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (pod,instance) (delivery_auto_deploy_environment_state{target_env=\"gprd\", target_stage=\"cny\"})",
     "legendFormat": "{{env_state}}"
    }
   ]
  },
  {
   "title": "gstg-main environment states",
   "type": "piechart",
   "description": "Pie chart representation of the percentage of time gstg-main spent in different states",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without (pod,instance) (delivery_auto_deploy_environment_state{target_env=\"gstg\", target_stage=\"main\"}) * $__range_s",
     "legendFormat": "{{env_state}}"
    }
   ]
  },
  {
   "title": "gstg-main environment states",
   "type": "graph",
   "description": "Time series representation of the percentage of time gstg-main spent in different states",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (pod,instance) (delivery_auto_deploy_environment_state{target_env=\"gstg\", target_stage=\"main\"})",
     "legendFormat": "{{env_state}}"
    }
   ]
  },
  {
   "title": "gstg-cny environment states",
   "type": "piechart",
   "description": "Pie chart representation of the percentage of time gstg-cny spent in different states",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without (pod,instance) (delivery_auto_deploy_environment_state{target_env=\"gstg\", target_stage=\"cny\"}) * $__range_s",
     "legendFormat": "{{env_state}}"
    }
   ]
  },
  {
   "title": "gstg-cny environment states",
   "type": "graph",
   "description": "Time series representation of the percentage of time gstg-cny spent in different states",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (pod,instance) (delivery_auto_deploy_environment_state{target_env=\"gstg\", target_stage=\"cny\"})",
     "legendFormat": "{{env_state}}"
    }
   ]
  },
  {
   "title": "Package status when gstg-cny is idle",
   "type": "bargauge",
   "description": "Amount of time where gstg-cny was idle and packages were in varying states of being built. There can be overlap in the numbers.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(max by (pkg_state) (delivery_auto_deploy_building_package_state)) * on() group_left max(delivery_auto_deploy_environment_state{target_env=\"gstg\",target_stage=\"cny\",env_state=\"ready\"}) * $__range_s",
     "legendFormat": "Package build {{pkg_state}}"
    },
    {
     "expr": "max(delivery_auto_deploy_environment_state{target_env=\"gstg\",target_stage=\"cny\",env_state=\"ready\"}) * $__range_s",
     "legendFormat": "gstg-cny idle"
    }
   ]
  },
  {
   "title": "Package build status when gstg-cny is idle",
   "type": "graph",
   "description": "Time series representation of amount of time where gstg-cny was idle and packages were in varying states of being built.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(max by (pkg_state) (delivery_auto_deploy_building_package_state)) * on() group_left max(delivery_auto_deploy_environment_state{target_env=\"gstg\",target_stage=\"cny\",env_state=\"ready\"})",
     "legendFormat": "Package build {{pkg_state}}"
    },
    {
     "expr": "max(delivery_auto_deploy_environment_state{target_env=\"gstg\",target_stage=\"cny\",env_state=\"ready\"})",
     "legendFormat": "gstg-cny idle"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}