{
 "title": "delivery: Deployment Blockers",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7927277014 at Thu Sep 26 12:04:17 UTC 2024",
 "tags": [
  "managed",
  "delivery",
  "release"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "root_cause",
    "query": "query_result(max by (root_cause) (last_over_time(delivery_deployment_blocker_count{root_cause!=\"RootCause::FlakyTest\"}[$__range]) > 0))"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Deployment Blockers\n\nDeployment failures are currently automatically captured under [release/tasks issues](https://gitlab.com/gitlab-org/release/tasks/-/issues).\nEach week a report is generated to keep track of the deployment blockers of the GitLab.com environments, release managers are responsible for labeling these failures with appropriate `RootCause::*` labels\n\nThis dashboard tracks the trend of recurring root causes for deployment blockers. Each root cause is displayed in separate rows with three panels: one for the count of blockers, one for `gprd` hours blocked, and one for `gstg` hours blocked. At the top, there is an overview of the failure types, including the total calculations for the entire specified time window.\n\nLinks:\n- [List of root causes](https://gitlab.com/gitlab-org/release/tasks/-/labels?subscribed=&sort=relevance&search=RootCause)\n- [Deployments metrics review](https://gitlab.com/groups/gitlab-com/gl-infra/-/epics/1192)\n"
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Blockers Count per Root Cause",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_blocker_count{root_cause=~\".+\", root_cause!=\"RootCause::FlakyTest\"}[1d])) != 0",
     "legendFormat": "{{root_cause}}"
    }
   ]
  },
  {
   "title": "Total gprd Hours Blocked per Root Cause",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_hours_blocked{root_cause=~\".+\", root_cause!=\"RootCause::FlakyTest\", target_env=\"gprd\"}[1d])) != 0",
     "legendFormat": "{{root_cause}}"
    }
   ]
  },
  {
   "title": "Total gstg Hours Blocked per Root Cause",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_hours_blocked{root_cause=~\".+\", root_cause!=\"RootCause::FlakyTest\", target_env=\"gstg\"}[1d])) != 0",
     "legendFormat": "{{root_cause}}"
    }
   ]
  },
  { "title": "$root_cause", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "root_cause" },
  {
   "title": "Blockers Count for $root_cause",
   "type": "trend",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_blocker_count{root_cause=\"$root_cause\"}[1d]))"
    }
   ]
  },
  {
   "title": "gprd Hours Blocked for $root_cause",
   "type": "trend",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_hours_blocked{root_cause=\"$root_cause\", target_env=\"gprd\"}[1d]))"
    }
   ]
  },
  {
   "title": "gstg Hours Blocked for $root_cause",
   "type": "trend",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_hours_blocked{root_cause=\"$root_cause\", target_env=\"gstg\"}[1d]))"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_blocker_count{root_cause=\"$root_cause\"}[1d]))"
    },
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_hours_blocked{root_cause=\"$root_cause\", target_env=\"gprd\"}[1d]))"
    },
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_hours_blocked{root_cause=\"$root_cause\", target_env=\"gstg\"}[1d]))"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100000 } },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}