{
 "title": "delivery: Rollback information",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8245226639 at Fri Nov  1 04:32:47 UTC 2024",
 "tags": [
  "managed",
  "delivery",
  "release"
 ],
 "time": { "from": "now-30d", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Percentage of rollbackable packages",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "🚀 gprd",
   "type": "stat",
   "description": "Percentage of packages deployed to Production over the selected time range that could have been rolled back.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    delivery_deployment_can_rollback_total{target_env=\"gprd\"}[$__range]\n  )\n) /\nsum(\n  increase(\n    delivery_deployment_started_total{target_env=\"gprd\"}[$__range]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "🏗 gstg",
   "type": "stat",
   "description": "Percentage of packages deployed to Staging over the selected time range that could have been rolled back.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    delivery_deployment_can_rollback_total{target_env=\"gstg\"}[$__range]\n  )\n) /\nsum(\n  increase(\n    delivery_deployment_started_total{target_env=\"gstg\"}[$__range]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Percentage of deployments that could be rolled back per day",
   "type": "graph",
   "description": "Percentage of deployments that could have been rolled back per day.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum(\n  increase(\n    delivery_deployment_can_rollback_total{target_env=~\"gprd|gstg\"}[1d]\n  )\n) by (target_env)\n/\nsum(\n  increase(\n    delivery_deployment_started_total{target_env=~\"gprd|gstg\"}[1d]\n  )\n) by (target_env)\n",
     "legendFormat": "{{target_env}}"
    }
   ]
  },
  { "title": "Number of rollbacks performed", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "🚀 gprd",
   "type": "stat",
   "description": "Number of rollbacks performed in Production over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1000 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    delivery_deployment_rollbacks_started_total{target_env=\"gprd\"}[$__range]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "🏗 gstg",
   "type": "stat",
   "description": "Number of rollbacks performed in Staging over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1004 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    delivery_deployment_rollbacks_started_total{target_env=\"gstg\"}[$__range]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Number of rollbacks",
   "type": "graph",
   "description": "Number of rollbacks performed per day.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  increase(\n    delivery_deployment_rollbacks_started_total{target_env=~\"gprd|gstg\"}[$__range]\n  )\n) by (target_env)\n",
     "legendFormat": "{{target_env}}"
    }
   ]
  }
 ]
}