{
 "title": "http-router: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8245226639 at Fri Nov  1 04:32:42 UTC 2024",
 "tags": [
  "managed",
  "http-router",
  "gitlab",
  "type:http-router",
  "http-router",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "http-router Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "http-router error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"http-router\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"http-router\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "http-router error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"http-router\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"http-router\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"http-router\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"http-router\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"http-router\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "http-router Service | Errors"
    }
   ]
  },
  {
   "title": "http-router Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"}[$__interval])\n",
     "legendFormat": "http-router RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "worker_requests SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"worker_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "worker_requests error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"worker_requests\",monitor=\"global\",type=\"http-router\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"worker_requests\",monitor=\"global\",type=\"http-router\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"worker_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "worker_requests error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"worker_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"worker_requests\",monitor=\"global\",type=\"http-router\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"worker_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"worker_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"worker_requests\",monitor=\"global\",type=\"http-router\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"worker_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"worker_requests\",monitor=\"global\",type=\"http-router\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"worker_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"worker_requests\",monitor=\"global\",type=\"http-router\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"worker_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"worker_requests\",monitor=\"global\",type=\"http-router\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "worker_requests SLI | Errors"
    }
   ]
  },
  {
   "title": "worker_requests SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"worker_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"}[$__interval])\n",
     "legendFormat": "worker_requests RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"worker_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"http-router\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "content": "### Description\n\nAggregation of request that are flowing through the `http-router`.\n\nErrors on this SLI may indicate issues within the deployed `http-router`\ncodebase as errors are limited to those originating inside of the worker.\n\nSee: https://gitlab.com/gitlab-com/runbooks/-/blob/master/docs/http-router/logging.md?ref_type=heads\n\n"
  },
  {
   "title": "🔬 SLI Detail: worker_requests",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "worker_requests Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cloudflare_worker_errors_count:rate_5m{env=\"$environment\",environment=\"$environment\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "worker_requests RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cloudflare_worker_requests_count:rate_5m{env=\"$environment\",environment=\"$environment\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "worker_requests Errors - per script_name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (script_name) (\n  sli_aggregations:cloudflare_worker_errors_count:rate_5m{env=\"$environment\",environment=\"$environment\",script_name!=\"\"}\n)\n > 0",
       "legendFormat": "{{script_name}}"
      }
     ]
    },
    {
     "title": "worker_requests RPS - per script_name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (script_name) (\n  sli_aggregations:cloudflare_worker_requests_count:rate_5m{env=\"$environment\",environment=\"$environment\",script_name!=\"\"}\n)\n > 0",
       "legendFormat": "{{script_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni\n  pgbouncer\n  redis\n  redis-cluster-cache\n  redis-cluster-chat-cache\n  redis-cluster-feature-flag\n  redis-cluster-queues-meta\n  redis-cluster-ratelimiting\n  redis-cluster-repo-cache\n  redis-cluster-shared-state\n  redis-db-load-balancing\n  redis-pubsub\n  redis-registry-cache\n  redis-sessions\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph inf\n  nat\n  search\n  zoekt\nend\n\nsubgraph lb\n  frontend\n  http-router\nend\n\nsubgraph stor\n  gitaly\n  google-cloud-storage\nend\n\nsubgraph sv\n  api\n  consul\n  ext-pvs\n  git\n  kas\n  registry\n  web\nend\n\n\n  api --> consul\napi --> ext-pvs\napi --> gitaly\napi --> google-cloud-storage\napi --> kas\napi --> patroni\napi --> pgbouncer\napi --> redis\napi --> redis-cluster-cache\napi --> redis-cluster-chat-cache\napi --> redis-cluster-feature-flag\napi --> redis-cluster-queues-meta\napi --> redis-cluster-ratelimiting\napi --> redis-cluster-repo-cache\napi --> redis-cluster-shared-state\napi --> redis-pubsub\napi --> redis-sessions\napi --> redis-sidekiq\napi --> redis-tracechunks\napi --> search\napi --> zoekt\nfrontend --> api\nfrontend --> git\nfrontend --> registry\nfrontend --> web\ngit --> consul\ngit --> ext-pvs\ngit --> gitaly\ngit --> google-cloud-storage\ngit --> patroni\ngit --> pgbouncer\ngit --> redis\ngit --> redis-cluster-cache\ngit --> redis-sidekiq\ngitaly --> gitaly\nhttp-router --> frontend\nhttp-router --> nat\nkas --> api\nkas --> gitaly\nkas --> kas\nkas --> redis\nnat --> frontend\npgbouncer --> patroni\nregistry --> api\nregistry --> redis-registry-cache\nweb --> consul\nweb --> ext-pvs\nweb --> gitaly\nweb --> google-cloud-storage\nweb --> patroni\nweb --> pgbouncer\nweb --> redis\nweb --> redis-cluster-cache\nweb --> redis-cluster-chat-cache\nweb --> redis-cluster-feature-flag\nweb --> redis-cluster-queues-meta\nweb --> redis-cluster-ratelimiting\nweb --> redis-cluster-repo-cache\nweb --> redis-cluster-shared-state\nweb --> redis-db-load-balancing\nweb --> redis-pubsub\nweb --> redis-sessions\nweb --> redis-sidekiq\nweb --> search\nweb --> zoekt\n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni\n  pgbouncer\n  redis\n  redis-cluster-cache\n  redis-cluster-chat-cache\n  redis-cluster-feature-flag\n  redis-cluster-queues-meta\n  redis-cluster-ratelimiting\n  redis-cluster-repo-cache\n  redis-cluster-shared-state\n  redis-db-load-balancing\n  redis-pubsub\n  redis-registry-cache\n  redis-sessions\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph inf\n  nat\n  search\n  zoekt\nend\n\nsubgraph lb\n  frontend\n  http-router\nend\n\nsubgraph stor\n  gitaly\n  google-cloud-storage\nend\n\nsubgraph sv\n  api\n  consul\n  ext-pvs\n  git\n  kas\n  registry\n  web\nend\n\n\n  api --> consul\napi --> ext-pvs\napi --> gitaly\napi --> google-cloud-storage\napi --> kas\napi --> patroni\napi --> pgbouncer\napi --> redis\napi --> redis-cluster-cache\napi --> redis-cluster-chat-cache\napi --> redis-cluster-feature-flag\napi --> redis-cluster-queues-meta\napi --> redis-cluster-ratelimiting\napi --> redis-cluster-repo-cache\napi --> redis-cluster-shared-state\napi --> redis-pubsub\napi --> redis-sessions\napi --> redis-sidekiq\napi --> redis-tracechunks\napi --> search\napi --> zoekt\nfrontend --> api\nfrontend --> git\nfrontend --> registry\nfrontend --> web\ngit --> consul\ngit --> ext-pvs\ngit --> gitaly\ngit --> google-cloud-storage\ngit --> patroni\ngit --> pgbouncer\ngit --> redis\ngit --> redis-cluster-cache\ngit --> redis-sidekiq\ngitaly --> gitaly\nhttp-router --> frontend\nhttp-router --> nat\nkas --> api\nkas --> gitaly\nkas --> kas\nkas --> redis\nnat --> frontend\npgbouncer --> patroni\nregistry --> api\nregistry --> redis-registry-cache\nweb --> consul\nweb --> ext-pvs\nweb --> gitaly\nweb --> google-cloud-storage\nweb --> patroni\nweb --> pgbouncer\nweb --> redis\nweb --> redis-cluster-cache\nweb --> redis-cluster-chat-cache\nweb --> redis-cluster-feature-flag\nweb --> redis-cluster-queues-meta\nweb --> redis-cluster-ratelimiting\nweb --> redis-cluster-repo-cache\nweb --> redis-cluster-shared-state\nweb --> redis-db-load-balancing\nweb --> redis-pubsub\nweb --> redis-sessions\nweb --> redis-sidekiq\nweb --> search\nweb --> zoekt\n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni[\"patroni (Level 2)\"]\n  pgbouncer[\"pgbouncer (Level 1)\"]\n  redis-cluster-cache[\"redis-cluster-cache (Level 2)\"]\n  redis-cluster-chat-cache[\"redis-cluster-chat-cache (Level 2)\"]\n  redis-cluster-feature-flag[\"redis-cluster-feature-flag (Level 2)\"]\n  redis-cluster-queues-meta[\"redis-cluster-queues-meta (Level 2)\"]\n  redis-cluster-ratelimiting[\"redis-cluster-ratelimiting (Level 2)\"]\n  redis-cluster-repo-cache[\"redis-cluster-repo-cache (Level 2)\"]\n  redis-cluster-shared-state[\"redis-cluster-shared-state (Level 2)\"]\n  redis-db-load-balancing[\"redis-db-load-balancing (Level 2)\"]\n  redis-pubsub[\"redis-pubsub (Level 2)\"]\n  redis-registry-cache[\"redis-registry-cache (Level 2)\"]\n  redis-sessions[\"redis-sessions (Level 3)\"]\n  redis-sidekiq[\"redis-sidekiq (Level 3)\"]\n  redis-tracechunks[\"redis-tracechunks (Level 3)\"]\n  redis[\"redis (Level 3)\"]\nend\n\nsubgraph inf\n  nat[\"nat (Level 1)\"]\n  search[\"search (Level 1)\"]\n  zoekt[\"zoekt (Level 1)\"]\nend\n\nsubgraph lb\n  frontend[\"frontend (Level 1)\"]\n  http-router[\"http-router (Level 1)\"]\nend\n\nsubgraph stor\n  gitaly[\"gitaly (Level 3)\"]\n  google-cloud-storage[\"google-cloud-storage (Level 2)\"]\nend\n\nsubgraph sv\n  api[\"api (Level 2)\"]\n  consul[\"consul (Level 1)\"]\n  ext-pvs[\"ext-pvs (Level 2)\"]\n  git[\"git (Level 2)\"]\n  kas[\"kas (Level 3)\"]\n  registry[\"registry (Level 2)\"]\n  web[\"web (Level 2)\"]\nend\n\n\n  api[\"api (Level 2)\"] --> consul\napi[\"api (Level 2)\"] --> ext-pvs\napi[\"api (Level 2)\"] --> gitaly\napi[\"api (Level 2)\"] --> google-cloud-storage\napi[\"api (Level 2)\"] --> kas\napi[\"api (Level 2)\"] --> patroni\napi[\"api (Level 2)\"] --> pgbouncer\napi[\"api (Level 2)\"] --> redis\napi[\"api (Level 2)\"] --> redis-cluster-cache\napi[\"api (Level 2)\"] --> redis-cluster-chat-cache\napi[\"api (Level 2)\"] --> redis-cluster-feature-flag\napi[\"api (Level 2)\"] --> redis-cluster-queues-meta\napi[\"api (Level 2)\"] --> redis-cluster-ratelimiting\napi[\"api (Level 2)\"] --> redis-cluster-repo-cache\napi[\"api (Level 2)\"] --> redis-cluster-shared-state\napi[\"api (Level 2)\"] --> redis-pubsub\napi[\"api (Level 2)\"] --> redis-sessions\napi[\"api (Level 2)\"] --> redis-sidekiq\napi[\"api (Level 2)\"] --> redis-tracechunks\napi[\"api (Level 2)\"] --> search\napi[\"api (Level 2)\"] --> zoekt\nfrontend[\"frontend (Level 1)\"] --> api\nfrontend[\"frontend (Level 1)\"] --> git\nfrontend[\"frontend (Level 1)\"] --> registry\nfrontend[\"frontend (Level 1)\"] --> web\ngit[\"git (Level 2)\"] --> consul\ngit[\"git (Level 2)\"] --> ext-pvs\ngit[\"git (Level 2)\"] --> gitaly\ngit[\"git (Level 2)\"] --> google-cloud-storage\ngit[\"git (Level 2)\"] --> patroni\ngit[\"git (Level 2)\"] --> pgbouncer\ngit[\"git (Level 2)\"] --> redis\ngit[\"git (Level 2)\"] --> redis-cluster-cache\ngit[\"git (Level 2)\"] --> redis-sidekiq\ngitaly[\"gitaly (Level 3)\"] --> gitaly\nhttp-router[\"http-router (Level 1)\"] --> frontend\nhttp-router[\"http-router (Level 1)\"] --> nat\nkas[\"kas (Level 3)\"] --> api\nkas[\"kas (Level 3)\"] --> gitaly\nkas[\"kas (Level 3)\"] --> kas\nkas[\"kas (Level 3)\"] --> redis\nnat[\"nat (Level 1)\"] --> frontend\npgbouncer[\"pgbouncer (Level 1)\"] --> patroni\nregistry[\"registry (Level 2)\"] --> api\nregistry[\"registry (Level 2)\"] --> redis-registry-cache\nweb[\"web (Level 2)\"] --> consul\nweb[\"web (Level 2)\"] --> ext-pvs\nweb[\"web (Level 2)\"] --> gitaly\nweb[\"web (Level 2)\"] --> google-cloud-storage\nweb[\"web (Level 2)\"] --> patroni\nweb[\"web (Level 2)\"] --> pgbouncer\nweb[\"web (Level 2)\"] --> redis\nweb[\"web (Level 2)\"] --> redis-cluster-cache\nweb[\"web (Level 2)\"] --> redis-cluster-chat-cache\nweb[\"web (Level 2)\"] --> redis-cluster-feature-flag\nweb[\"web (Level 2)\"] --> redis-cluster-queues-meta\nweb[\"web (Level 2)\"] --> redis-cluster-ratelimiting\nweb[\"web (Level 2)\"] --> redis-cluster-repo-cache\nweb[\"web (Level 2)\"] --> redis-cluster-shared-state\nweb[\"web (Level 2)\"] --> redis-db-load-balancing\nweb[\"web (Level 2)\"] --> redis-pubsub\nweb[\"web (Level 2)\"] --> redis-sessions\nweb[\"web (Level 2)\"] --> redis-sidekiq\nweb[\"web (Level 2)\"] --> search\nweb[\"web (Level 2)\"] --> zoekt\n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}