groups:
  - name: prometheus_alerts
    rules:
      - alert: PrometheusInstanceMissing
        annotations:
          title: Prometheus Instance {{ $labels.pod }} from {{ $labels.cluster }} hasn't been seen in the last 1.5hours.
          # TODO: Update this discription to be meaningful
          description: |
            asdasd
          runbook: docs/
          grafana_datasource_id: mimir-gitlab-gprd
        expr: |
          time() - max_over_time(prometheus_remote_storage_queue_highest_sent_timestamp_seconds{job=~".*prometheus.*"}[5m]) > 5400
        for: 5m
        labels:
          env: ops
          alert_class: traffic_cessation
          severity: s3
          team: scalability:observability
          slo_alert: "no"
      - alert: PrometheusHAGroupDown
        annotations:
          title: Prometheus HA Group {{ $labels.cluster }} hasn't sent metrics in the last few minutes.
          # TODO: Update this discription to be meaningful
          description: |
            Both instance in a Prometheus HA group are not sending data
          runbook: docs/
          grafana_datasource_id: mimir-gitlab-gprd
        expr: |
          min by (cluster, env, namespace, job) (time() - max_over_time(prometheus_remote_storage_queue_highest_sent_timestamp_seconds{job=~".*prometheus.*"}[5m])) > 180
        for: 2m
        labels:
          env: ops
          alert_class: traffic_cessation
          severity: s2
          slo_alert: "no"
