{
 "title": "stage-groups: Product Analytics: Group dashboard",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7927277014 at Thu Sep 26 12:04:29 UTC 2024",
 "tags": [
  "managed",
  "stage-groups",
  "feature_category",
  "stage_group:Product Analytics"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "controller",
    "query": "label_values(controller_action:gitlab_transaction_duration_seconds_count:rate1m{environment='$environment', feature_category=~'(product_analytics_visualization|product_analytics_data_management)'}, controller)"
   },
   {
    "name": "action",
    "query": "label_values(controller_action:gitlab_transaction_duration_seconds_count:rate1m{environment='$environment', controller=~'$controller', feature_category=~'(product_analytics_visualization|product_analytics_data_management)'}, action)"
   }
  ]
 },
 "panels": [
  { "title": "Error Budget (past 28 days)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n",
     "legendFormat": "%"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 0, "y": 105.5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.9995 * 100.0" }
   ]
  },
  {
   "title": "Budget remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in 28d\n1209.5999999998667\n-\n(\n  (\n     1 - clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n\n  ) * 2419200\n)\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 6, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 6, "y": 105.5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in 28d\n1209.5999999998667\n"
    }
   ]
  },
  {
   "title": "Budget spent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (\n     1 - clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n\n  ) * 2419200\n)\n"
    },
    {
     "expr": "# The number of seconds allowed to be spent in 28d\n1209.5999999998667\n",
     "legendFormat": "budget"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 12, "y": 105.5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in 28d\n1209.5999999998667\n"
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 100 },
   "content": "### [Error budget](https://about.gitlab.com/handbook/engineering/error-budgets/)\n\nThese error budget panels show an aggregate of SLIs across all components.\nHowever, not all components have been implemented yet.\n\nThe [handbook](https://about.gitlab.com/handbook/engineering/error-budgets/)\nexplains how these budgets are used.\n\nRead more about how the error budgets are calculated in the\n[stage group dashboard documentation](https://docs.gitlab.com/ee/development/stage_group_observability/dashboards/stage_group_dashboard.html#error-budget-panels).\n\nThe error budget is compared to our SLO of 99.95% and is always in\na range of 28 days from the selected end date in Grafana.\n\n### Availability\n\nThe availability shows the percentage of operations labeled with one of the\ncategories owned by Product Analytics with satisfactory completion.\n\n### Budget remaining\n\nThe error budget in minutes is calculated based on the 99.95%.\nThere are 40320 minutes in 28 days, we allow 0.05% of failures, which\nmeans the budget in minutes is 20.159999999997776 minutes.\n\nThe budget remaining shows how many minutes have not been spent in the\npast 28 days.\n\n### Minutes spent\n\nThis shows the total minutes spent over the past 28 days.\n\nFor example, if there were 403200 (28 * 24 * 60) operations in 28 days.\nThis would be 1 every minute. If 10 of those were unsatisfactory, that\nwould mean 10 minutes of the budget were spent.\n"
  },
  {
   "title": "Budget spend attribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 },
   "collapsed": true,
   "panels": [
    {
     "title": "Budget failures",
     "type": "table",
     "description": "Number of failures contributing to the budget send per component and type ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 151 },
     "targets": [
      {
       "expr": "ceil(\n  (\n    sum by (component,type,violation_type) (\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n            ) -\n            # Request with satisfactory apdex\n            sum_over_time(\n              gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n            )\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'apdex' , '', ''\n      )\n      or\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n            )\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'error' , '', ''\n      )\n    ) > 0\n  ) * 60\n)\n"
      },
      {
       "expr": "ceil(\n  (\n    sum by (component,type,violation_type) (\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n            )\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'apdex' , '', ''\n      )\n      or\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d]\n            )\n            and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"product_analytics\"}[28d])\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'error' , '', ''\n      )\n    ) > 0\n  ) * 60\n)\n"
      }
     ]
    },
    {
     "title": "Info",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 151 },
     "content": "This table shows the failures that contribute to the spend of the error budget.\nFixing the top item in this table will have the biggest impact on the\nbudget spend.\n\nA failure is one of 2 types:\n\n- **error**: An operation that failed: 500 response, failed background job.\n- **apdex**: This means an operation that succeeded, but did not perform within the set threshold.\n\nSee the [developer documentation](https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/development/stage_group_dashboards.md#error-budget)\nto learn more about this.\n\nThe component refers to the component in our stack where the violation occurred.\nThe most common ones are:\n\n- **puma**: This component signifies requests handled by rails\n- **sidekiq_execution**: This component signifies background jobs executed by Sidekiq\n\nTo find the endpoint that is attributing to the budget spend and a violation type\nwe can use the logs over a 7 day range. Links for puma and sidekiq are available on the right.\nThese logs list the endpoints that had the most violations over the past 7 days.\n\nThe \"Other\" row is the sum of all the other violations excluding the top ones\nthat are listed.\n"
    },
    {
     "title": "Failure log links",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 151 },
     "content": "##### [Rails Requests Apdex](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management)))))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:exists,type:json.duration_s,value:exists),query:(exists:(field:json.duration_s))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:exists,type:json.target_duration_s,value:exists),query:(exists:(field:json.target_duration_s)))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'3',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,params:(field:json.request_urgency.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'3',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,params:(field:json.target_duration_s,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'3',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,id:'3',params:(customLabel:'Operations+over+specified+threshold+(apdex)',field:json.duration_s,json:'{\"script\":+\"doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value+?+1+:+0\"}'),schema:metric,type:sum))))&_g=(time:(from:'now-7d',to:'now'))): slow requests\n\nThis shows the number of requests exceeding the request duration thresholds\nconfigured per endpoint over the past 7 days.\n\nThe threshold depends on the [configurable request urgency](https://docs.gitlab.com/ee/development/application_slis/rails_request.html#adjusting-request-urgency).\n\n##### [Puma Errors](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management)))))),(meta:(field:json.status,index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,params:(field:json.request_urgency.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,params:(field:json.target_duration_s,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms))))&_g=(time:(from:'now-7d',to:'now'))): failing requests\n\nThis shows the number of Rails requests that failed per endpoint over\nthe past 7 days.\n\n##### <a href=\"https://dashboards.gitlab.net/d/general-application-sli-violations/general-application-sli-violations?orgId=1&var-component=rails_request&from=${__from}&to=${__to}&var-stage_group=product_analytics\" target=\"_blank\">All request violations</a>: slow requests + failing requests\n\nThis dashboard shows the endpoints that are violating the apdex.\n\n##### [Sidekiq Execution Apdex](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management)))))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.job_status,params:done,type:phrase),query:(match:(json.job_status:(query:done,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(filters:!((input:(language:kuery,query:'json.shard:+\"urgent\"+AND+json.duration_s+>+10'),label:'Jobs+exceeding+10s'),(input:(language:kuery,query:'not+json.shard:+\"urgent\"+AND+json.duration_s+>+300'),label:'Jobs+exceeding+300s'))),schema:split,type:filters),(enabled:!t,params:(field:json.class.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms))))&_g=(time:(from:'now-7d',to:'now'))): slow jobs\n\nThis shows the number of jobs per worker that took longer than their threshold to\nexecute over the past 7 days.\n\nThe threshold depends on the [configurable job urgency](https://docs.gitlab.com/ee/development/application_slis/sidekiq_execution.html#adjusting-job-urgency).\n\n##### [Sidekiq Execution Errors](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management)))))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.job_status,params:fail,type:phrase),query:(match:(json.job_status:(query:fail,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.class.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms))))&_g=(time:(from:'now-7d',to:'now'))): failing jobs\n\nThis shows the number of jobs per worker that failed over the past 7 days.\nThis includes retries: if a job with a was retried 3 times, before exhausting\nits retries, this counts as 3 failures towards the budget.\n\n##### <a href=\"https://dashboards.gitlab.net/d/general-application-sli-violations/general-application-sli-violations?orgId=1&var-component=sidekiq_execution&from=${__from}&to=${__to}&var-stage_group=product_analytics\" target=\"_blank\">All Sidekiq job violations</a>: slow jobs + failing jobs\n\nThis dashboard shows the jobs that are violating the apdex.\n"
    }
   ]
  },
  { "title": "Rails Request Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 201 } },
  {
   "title": "API Request Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (\n  rate(gitlab_transaction_duration_seconds_count{\n    environment='$environment',\n    stage='$stage',\n    feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n    type='api',\n    controller=~'$controller',\n    action=~'$action'\n  }[$__interval])\n)\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "WEB Request Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 202 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (\n  rate(gitlab_transaction_duration_seconds_count{\n    environment='$environment',\n    stage='$stage',\n    feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n    type='web',\n    controller=~'$controller',\n    action=~'$action'\n  }[$__interval])\n)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Extra links",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 202 },
   "content": "* [📖 Kibana: Kibana Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management))))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Kibana Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management)))))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:exists,type:json.target_duration_s,value:exists),query:(exists:(field:json.target_duration_s))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:exists,type:json.duration_s,value:exists),query:(exists:(field:json.duration_s))),!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"script\":+{\"script\":+{\"source\":+\"doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value\"}}}]}}'),query:(bool:(minimum_should_match:1,should:!((script:(script:(source:'doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value'))))))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Kibana Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management)))))),(meta:(field:json.status,index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management)))))),(meta:(field:json.status,index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [🐞 Sentry Releases](https://new-sentry.gitlab.net/organizations/gitlab/releases/?project=3&environment=${environment})\n* [🐞 Sentry issues: product_analytics_visualization](https://new-sentry.gitlab.net/organizations/gitlab/issues/?project=3&environment=${environment}&query=feature_category%3Aproduct_analytics_visualization+stage%3A${stage})\n* [🐞 Sentry issues: product_analytics_data_management](https://new-sentry.gitlab.net/organizations/gitlab/issues/?project=3&environment=${environment}&query=feature_category%3Aproduct_analytics_data_management+stage%3A${stage})\n"
  },
  {
   "title": "Rails 95th Percentile Request Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 301 }
  },
  {
   "title": "API 95th Percentile Request Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 302 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(\n    controller_action:gitlab_transaction_duration_seconds:p95{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n      type='api'\n    }[$__interval]\n  )\n) by (controller, action)\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "WEB 95th Percentile Request Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 302 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(\n    controller_action:gitlab_transaction_duration_seconds:p95{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n      type='web'\n    }[$__interval]\n  )\n) by (controller, action)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Rails Error Rates (accumulated by components)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 401 }
  },
  {
   "title": "API Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 402 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (component) (\n  gitlab:component:feature_category:execution:error:rate_5m{\n    environment='$environment',\n    stage='$stage',\n    feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n    type='api'\n  }\n)\n",
     "legendFormat": "api error rate"
    }
   ]
  },
  {
   "title": "WEB Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 402 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (component) (\n  gitlab:component:feature_category:execution:error:rate_5m{\n    environment='$environment',\n    stage='$stage',\n    feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n    type='web'\n  }\n)\n",
     "legendFormat": "web error rate"
    }
   ]
  },
  { "title": "SQL Queries Per Action", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 501 } },
  {
   "title": "API SQL Queries per Action",
   "type": "graph",
   "description": "Average amount of SQL queries performed by a controller action.\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 502 },
   "yaxes": [
    { "format": "short", "label": "Queries" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (\n  controller_action:gitlab_sql_duration_seconds_count:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n    type='api'\n  }\n)\n/\nsum by (controller, action) (\n  controller_action:gitlab_transaction_duration_seconds_count:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n    type='api'\n  }\n)\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "WEB SQL Queries per Action",
   "type": "graph",
   "description": "Average amount of SQL queries performed by a controller action.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 502 },
   "yaxes": [
    { "format": "short", "label": "Queries" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (\n  controller_action:gitlab_sql_duration_seconds_count:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n    type='web'\n  }\n)\n/\nsum by (controller, action) (\n  controller_action:gitlab_transaction_duration_seconds_count:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n    type='web'\n  }\n)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  { "title": "SQL Latency Per Action", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 601 } },
  {
   "title": "API SQL Latency per Action",
   "type": "graph",
   "description": "Average sum of all SQL query latency accumulated by a controller action.\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 602 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(\n  controller_action:gitlab_sql_duration_seconds_sum:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n    type='api'\n  }[$__interval]\n)\n/\navg_over_time(\n  controller_action:gitlab_transaction_duration_seconds_count:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n    type='api'\n  }[$__interval]\n)\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "WEB SQL Latency per Action",
   "type": "graph",
   "description": "Average sum of all SQL query latency accumulated by a controller action.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 602 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(\n  controller_action:gitlab_sql_duration_seconds_sum:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n    type='web'\n  }[$__interval]\n)\n/\navg_over_time(\n  controller_action:gitlab_transaction_duration_seconds_count:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n    type='web'\n  }[$__interval]\n)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  { "title": "SQL Latency Per Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 701 } },
  {
   "title": "API SQL Latency per Query",
   "type": "graph",
   "description": "Average latency of individual SQL queries\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 702 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (\n  rate(\n    gitlab_sql_duration_seconds_sum{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n      type='api'\n    }[$__interval]\n  )\n)\n/\nsum by (controller, action) (\n  rate(\n    gitlab_sql_duration_seconds_count{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n      type='api'\n    }[$__interval]\n  )\n)\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "WEB SQL Latency per Query",
   "type": "graph",
   "description": "Average latency of individual SQL queries\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 702 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (\n  rate(\n    gitlab_sql_duration_seconds_sum{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n      type='web'\n    }[$__interval]\n  )\n)\n/\nsum by (controller, action) (\n  rate(\n    gitlab_sql_duration_seconds_count{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n      type='web'\n    }[$__interval]\n  )\n)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  { "title": "Caches per Action", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 801 } },
  {
   "title": "API Caches per Action",
   "type": "graph",
   "description": "Average total number of caching operations (Read & Write) per action.\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 802 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action, operation) (\n  rate(\n    gitlab_cache_operations_total{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n      type='api'\n    }[$__interval]\n  )\n)\n",
     "legendFormat": "{{operation}} - {{action}}"
    }
   ]
  },
  {
   "title": "WEB Caches per Action",
   "type": "graph",
   "description": "Average total number of caching operations (Read & Write) per action.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 802 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action, operation) (\n  rate(\n    gitlab_cache_operations_total{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(product_analytics_visualization|product_analytics_data_management)',\n      type='web'\n    }[$__interval]\n  )\n)\n",
     "legendFormat": "{{operation}} - {{controller}}#{{action}}"
    }
   ]
  },
  { "title": "Sidekiq", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 901 } },
  {
   "title": "Sidekiq Completion Rate",
   "type": "graph",
   "description": "The rate (Jobs per Second) at which jobs are completed after dequeue",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 902 },
   "yaxes": [
    { "format": "short", "label": "Jobs per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (\n  application_sli_aggregation:sidekiq_execution:ops:rate_5m{\n    environment=\"$environment\",\n    stage='$stage',\n    feature_category=~'(product_analytics_visualization|product_analytics_data_management)'\n  }\n)\n",
     "legendFormat": "{{worker]}}"
    }
   ]
  },
  {
   "title": "Sidekiq Error Rate",
   "type": "graph",
   "description": "The rate (Jobs per Second) at which jobs fail after dequeue",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 902 },
   "yaxes": [
    { "format": "short", "label": "Jobs per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (\n  application_sli_aggregation:sidekiq_execution:error:rate_5m{\n    environment=\"$environment\",\n    stage='$stage',\n    feature_category=~'(product_analytics_visualization|product_analytics_data_management)'\n  }\n)\n",
     "legendFormat": "{{worker]}}"
    }
   ]
  },
  {
   "title": "Extra links",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 902 },
   "content": "* [📖 Kibana: Kibana Sidekiq logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.class,json.queue,json.meta.project,json.job_status,json.scheduling_latency_s,json.duration_s),filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management))))))),index:'AWNABDRwNDuQHTm2tH6l')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Kibana Sidekiq failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.class,json.queue,json.meta.project,json.job_status,json.scheduling_latency_s,json.duration_s),filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management)))))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.job_status,params:fail,type:phrase),query:(match:(json.job_status:(query:fail,type:phrase))))),index:'AWNABDRwNDuQHTm2tH6l')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management)))))),(meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.job_status,params:fail,type:phrase),query:(match:(json.job_status:(query:fail,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.project.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(index:'AWNABDRwNDuQHTm2tH6l',key:json.meta.feature_category,params:!(product_analytics_visualization,product_analytics_data_management),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:product_analytics_visualization)),(match_phrase:(json.meta.feature_category:product_analytics_data_management))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.project.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [🐞 Sentry Releases](https://new-sentry.gitlab.net/organizations/gitlab/releases/?project=3&environment=${environment})\n* [🐞 Sentry sidekiq issues: product_analytics_visualization](https://new-sentry.gitlab.net/organizations/gitlab/issues/?project=3&environment=${environment}&query=feature_category%3Aproduct_analytics_visualization+stage%3A${stage}+type%3Asidekiq)\n* [🐞 Sentry sidekiq issues: product_analytics_data_management](https://new-sentry.gitlab.net/organizations/gitlab/issues/?project=3&environment=${environment}&query=feature_category%3Aproduct_analytics_data_management+stage%3A${stage}+type%3Asidekiq)\n"
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}