{
 "title": "registry Service Overview",
 "tags": [
  "gitlab",
  "type:registry",
  "registry",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "registry Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{type=\"registry\"}[$__interval])\n",
     "legendFormat": "registry apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{type=\"registry\"}[$__interval])\n",
     "legendFormat": "registry apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{type=\"registry\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"registry\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"registry\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"registry\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"registry\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"registry\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "registry Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "registry Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "registry error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"registry\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"registry\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "registry error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{type=\"registry\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"registry\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{type=\"registry\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"registry\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{type=\"registry\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"registry\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{type=\"registry\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"registry\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{type=\"registry\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"registry\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "registry Service | Errors"
    }
   ]
  },
  {
   "title": "registry Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{type=\"registry\"}[$__interval])\n",
     "legendFormat": "registry RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{type=\"registry\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{type=\"registry\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{type=\"registry\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{type=\"registry\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{type=\"registry\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{type=\"registry\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "server SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"server\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"server\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"server\",type=\"registry\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server\",type=\"registry\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:confidence:ratio_5m{component=\"server\",confidence=\"98%\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "Apdex SLI (upper 98% confidence boundary)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:confidence:ratio_1h{component=\"server\",confidence=\"98%\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:confidence:ratio_5m{component=\"server\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server\",type=\"registry\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:confidence:ratio_1h{component=\"server\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server\",type=\"registry\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:confidence:ratio_30m{component=\"server\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server\",type=\"registry\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:confidence:ratio_6h{component=\"server\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server\",type=\"registry\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "server SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "server SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"server\",type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "server error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"server\",type=\"registry\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"server\",type=\"registry\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"server\",type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "server error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"server\",type=\"registry\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"server\",type=\"registry\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:confidence:ratio_5m{component=\"server\",confidence=\"98%\",type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "Error SLI (lower 98% confidence boundary)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:confidence:ratio_1h{component=\"server\",confidence=\"98%\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:confidence:ratio_5m{component=\"server\",confidence=\"98%\",type=\"registry\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"server\",type=\"registry\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:confidence:ratio_1h{component=\"server\",confidence=\"98%\",type=\"registry\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"server\",type=\"registry\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:confidence:ratio_30m{component=\"server\",confidence=\"98%\",type=\"registry\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"server\",type=\"registry\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:confidence:ratio_6h{component=\"server\",confidence=\"98%\",type=\"registry\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"server\",type=\"registry\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "server SLI | Errors"
    }
   ]
  },
  {
   "title": "server SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"server\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"server\",type=\"registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "content": "### Description\n\nAggregation of all registry HTTP requests.\n\n\n\n### Observability Tools\n\n\n"
  },
  {
   "title": "server_route_blob_digest_deletes SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"server_route_blob_digest_deletes\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_digest_deletes apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_deletes\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_deletes\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"server_route_blob_digest_deletes\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_digest_deletes apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"server_route_blob_digest_deletes\",type=\"registry\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_deletes\",type=\"registry\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:confidence:ratio_5m{component=\"server_route_blob_digest_deletes\",confidence=\"98%\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "Apdex SLI (upper 98% confidence boundary)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:confidence:ratio_1h{component=\"server_route_blob_digest_deletes\",confidence=\"98%\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:confidence:ratio_5m{component=\"server_route_blob_digest_deletes\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_deletes\",type=\"registry\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:confidence:ratio_1h{component=\"server_route_blob_digest_deletes\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_deletes\",type=\"registry\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:confidence:ratio_30m{component=\"server_route_blob_digest_deletes\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_deletes\",type=\"registry\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:confidence:ratio_6h{component=\"server_route_blob_digest_deletes\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_deletes\",type=\"registry\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "server_route_blob_digest_deletes SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "server_route_blob_digest_deletes SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"server_route_blob_digest_deletes\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_digest_deletes RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"server_route_blob_digest_deletes\",type=\"registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "content": "### Description\n\nDelete requests for the blob digest endpoints on\nthe registry.\n\nUsed to delete blobs identified by name and digest.\n\n"
  },
  {
   "title": "server_route_blob_digest_reads SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"server_route_blob_digest_reads\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_digest_reads apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_reads\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_reads\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"server_route_blob_digest_reads\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_digest_reads apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"server_route_blob_digest_reads\",type=\"registry\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_reads\",type=\"registry\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:confidence:ratio_5m{component=\"server_route_blob_digest_reads\",confidence=\"98%\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "Apdex SLI (upper 98% confidence boundary)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:confidence:ratio_1h{component=\"server_route_blob_digest_reads\",confidence=\"98%\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:confidence:ratio_5m{component=\"server_route_blob_digest_reads\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_reads\",type=\"registry\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:confidence:ratio_1h{component=\"server_route_blob_digest_reads\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_reads\",type=\"registry\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:confidence:ratio_30m{component=\"server_route_blob_digest_reads\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_reads\",type=\"registry\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:confidence:ratio_6h{component=\"server_route_blob_digest_reads\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_reads\",type=\"registry\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "server_route_blob_digest_reads SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "server_route_blob_digest_reads SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"server_route_blob_digest_reads\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_digest_reads RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"server_route_blob_digest_reads\",type=\"registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "content": "### Description\n\nAll read-requests (GET or HEAD) for the blob endpoints on\nthe registry.\n\nGET is used to pull a layer gated by the name of repository\nand uniquely identified by the digest in the registry.\n\nHEAD is used to check the existence of a layer.\n\n"
  },
  {
   "title": "server_route_blob_digest_writes SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"server_route_blob_digest_writes\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_digest_writes apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_writes\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_writes\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"server_route_blob_digest_writes\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_digest_writes apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"server_route_blob_digest_writes\",type=\"registry\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_writes\",type=\"registry\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:confidence:ratio_5m{component=\"server_route_blob_digest_writes\",confidence=\"98%\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "Apdex SLI (upper 98% confidence boundary)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:confidence:ratio_1h{component=\"server_route_blob_digest_writes\",confidence=\"98%\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:confidence:ratio_5m{component=\"server_route_blob_digest_writes\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_writes\",type=\"registry\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:confidence:ratio_1h{component=\"server_route_blob_digest_writes\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_writes\",type=\"registry\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:confidence:ratio_30m{component=\"server_route_blob_digest_writes\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_writes\",type=\"registry\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:confidence:ratio_6h{component=\"server_route_blob_digest_writes\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_digest_writes\",type=\"registry\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "server_route_blob_digest_writes SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "server_route_blob_digest_writes SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"server_route_blob_digest_writes\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_digest_writes RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"server_route_blob_digest_writes\",type=\"registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "content": "### Description\n\nWrite requests (PUT or PATCH or POST) for the registry blob digest endpoints.\n\nCurrently not part of the spec.\n\n"
  },
  {
   "title": "server_route_blob_upload_uuid_deletes SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"server_route_blob_upload_uuid_deletes\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_upload_uuid_deletes apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_deletes\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_deletes\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"server_route_blob_upload_uuid_deletes\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_upload_uuid_deletes apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"server_route_blob_upload_uuid_deletes\",type=\"registry\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_deletes\",type=\"registry\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:confidence:ratio_5m{component=\"server_route_blob_upload_uuid_deletes\",confidence=\"98%\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "Apdex SLI (upper 98% confidence boundary)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:confidence:ratio_1h{component=\"server_route_blob_upload_uuid_deletes\",confidence=\"98%\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:confidence:ratio_5m{component=\"server_route_blob_upload_uuid_deletes\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_deletes\",type=\"registry\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:confidence:ratio_1h{component=\"server_route_blob_upload_uuid_deletes\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_deletes\",type=\"registry\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:confidence:ratio_30m{component=\"server_route_blob_upload_uuid_deletes\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_deletes\",type=\"registry\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:confidence:ratio_6h{component=\"server_route_blob_upload_uuid_deletes\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_deletes\",type=\"registry\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "server_route_blob_upload_uuid_deletes SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "server_route_blob_upload_uuid_deletes SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"server_route_blob_upload_uuid_deletes\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_upload_uuid_deletes RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"server_route_blob_upload_uuid_deletes\",type=\"registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "content": "### Description\n\nDelete requests for the registry blob upload endpoints.\n\nUsed to cancel outstanding upload processes, releasing associated\nresources.\n\n"
  },
  {
   "title": "server_route_blob_upload_uuid_reads SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"server_route_blob_upload_uuid_reads\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_upload_uuid_reads apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_reads\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_reads\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"server_route_blob_upload_uuid_reads\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_upload_uuid_reads apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"server_route_blob_upload_uuid_reads\",type=\"registry\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_reads\",type=\"registry\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:confidence:ratio_5m{component=\"server_route_blob_upload_uuid_reads\",confidence=\"98%\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "Apdex SLI (upper 98% confidence boundary)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:confidence:ratio_1h{component=\"server_route_blob_upload_uuid_reads\",confidence=\"98%\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:confidence:ratio_5m{component=\"server_route_blob_upload_uuid_reads\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_reads\",type=\"registry\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:confidence:ratio_1h{component=\"server_route_blob_upload_uuid_reads\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_reads\",type=\"registry\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:confidence:ratio_30m{component=\"server_route_blob_upload_uuid_reads\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_reads\",type=\"registry\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:confidence:ratio_6h{component=\"server_route_blob_upload_uuid_reads\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_reads\",type=\"registry\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "server_route_blob_upload_uuid_reads SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "server_route_blob_upload_uuid_reads SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"server_route_blob_upload_uuid_reads\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_upload_uuid_reads RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"server_route_blob_upload_uuid_reads\",type=\"registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
   "content": "### Description\n\nRead requests (GET) for the registry blob upload endpoints.\n\nGET is used to retrieve the current status of a resumable upload.\n\n"
  },
  {
   "title": "server_route_blob_upload_uuid_writes SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"server_route_blob_upload_uuid_writes\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_upload_uuid_writes apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_writes\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_writes\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"server_route_blob_upload_uuid_writes\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_upload_uuid_writes apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"server_route_blob_upload_uuid_writes\",type=\"registry\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_writes\",type=\"registry\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:confidence:ratio_5m{component=\"server_route_blob_upload_uuid_writes\",confidence=\"98%\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "Apdex SLI (upper 98% confidence boundary)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:confidence:ratio_1h{component=\"server_route_blob_upload_uuid_writes\",confidence=\"98%\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:confidence:ratio_5m{component=\"server_route_blob_upload_uuid_writes\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_writes\",type=\"registry\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:confidence:ratio_1h{component=\"server_route_blob_upload_uuid_writes\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_writes\",type=\"registry\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:confidence:ratio_30m{component=\"server_route_blob_upload_uuid_writes\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_writes\",type=\"registry\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:confidence:ratio_6h{component=\"server_route_blob_upload_uuid_writes\",confidence=\"98%\",type=\"registry\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_writes\",type=\"registry\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "server_route_blob_upload_uuid_writes SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "server_route_blob_upload_uuid_writes SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"server_route_blob_upload_uuid_writes\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_blob_upload_uuid_writes RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"server_route_blob_upload_uuid_writes\",type=\"registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 81 },
   "content": "### Description\n\nWrite requests (PUT or PATCH) for the registry blob upload endpoints.\n\nPUT is used to complete the upload specified by uuid, optionally appending\nthe body as the final chunk.\n\nPATCH is used to upload a chunk of data for the specified upload.\n\n"
  },
  {
   "title": "🔬 SLI Detail: server",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 server Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{route!~\"/v2/{name}/blobs/uploads/{uuid}|/v2/{name}/blobs/{digest}\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "server Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_requests_total{code=~\"5..\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "server RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_requests_total{}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 server Latency - per route",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,route) (\n    rate(registry_http_request_duration_seconds_bucket{route!=\"\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{route}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server Latency - per route",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (route) (\n  rate(registry_http_request_duration_seconds_bucket{le=\"+Inf\",route!=\"\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (route) (\n    rate(registry_http_request_duration_seconds_bucket{le=\"2.5\",route!=\"\"}[$__interval])\n  )\n  +\n  sum by (route) (\n    rate(registry_http_request_duration_seconds_bucket{le=\"25\",route!=\"\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(route) group_left()\n  (\n    sum by () (\n  rate(registry_http_request_duration_seconds_bucket{le=\"+Inf\",route!=\"\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "server Errors - per route",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (route) (\n  rate(registry_http_requests_total{code=~\"5..\",route!=\"\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "server RPS - per route",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (route) (\n  rate(registry_http_requests_total{route!=\"\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Estimated p95 server Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,method) (\n    rate(registry_http_request_duration_seconds_bucket{method!=\"\",route!~\"/v2/{name}/blobs/uploads/{uuid}|/v2/{name}/blobs/{digest}\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{le=\"+Inf\",method!=\"\",route!~\"/v2/{name}/blobs/uploads/{uuid}|/v2/{name}/blobs/{digest}\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{le=\"2.5\",method!=\"\",route!~\"/v2/{name}/blobs/uploads/{uuid}|/v2/{name}/blobs/{digest}\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{le=\"25\",method!=\"\",route!~\"/v2/{name}/blobs/uploads/{uuid}|/v2/{name}/blobs/{digest}\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(method) group_left()\n  (\n    sum by () (\n  rate(registry_http_request_duration_seconds_bucket{le=\"+Inf\",method!=\"\",route!~\"/v2/{name}/blobs/uploads/{uuid}|/v2/{name}/blobs/{digest}\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "server Errors - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_requests_total{code=~\"5..\",method!=\"\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "server RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_requests_total{method!=\"\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: server_route_blob_digest_deletes",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 server_route_blob_digest_deletes Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{method=~\"delete\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "server_route_blob_digest_deletes RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_request_duration_seconds_count{method=~\"delete\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 server_route_blob_digest_deletes Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,method) (\n    rate(registry_http_request_duration_seconds_bucket{method!=\"\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server_route_blob_digest_deletes Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{le=\"+Inf\",method!=\"\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{le=\"0.5\",method!=\"\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{le=\"2.5\",method!=\"\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(method) group_left()\n  (\n    sum by () (\n  rate(registry_http_request_duration_seconds_bucket{le=\"+Inf\",method!=\"\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "server_route_blob_digest_deletes RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_request_duration_seconds_count{method=~\"delete\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: server_route_blob_digest_reads",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 220 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 server_route_blob_digest_reads Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{method=~\"get|head\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "server_route_blob_digest_reads RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_request_duration_seconds_count{method=~\"get|head\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 server_route_blob_digest_reads Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,method) (\n    rate(registry_http_request_duration_seconds_bucket{method!=\"\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server_route_blob_digest_reads Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{le=\"+Inf\",method!=\"\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{le=\"10\",method!=\"\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{le=\"60\",method!=\"\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(method) group_left()\n  (\n    sum by () (\n  rate(registry_http_request_duration_seconds_bucket{le=\"+Inf\",method!=\"\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "server_route_blob_digest_reads RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_request_duration_seconds_count{method=~\"get|head\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: server_route_blob_digest_writes",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 230 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 server_route_blob_digest_writes Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{method=~\"patch|post|put\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "server_route_blob_digest_writes RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_request_duration_seconds_count{method=~\"patch|post|put\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 server_route_blob_digest_writes Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,method) (\n    rate(registry_http_request_duration_seconds_bucket{method!=\"\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server_route_blob_digest_writes Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{le=\"+Inf\",method!=\"\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{le=\"2.5\",method!=\"\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{le=\"25\",method!=\"\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(method) group_left()\n  (\n    sum by () (\n  rate(registry_http_request_duration_seconds_bucket{le=\"+Inf\",method!=\"\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "server_route_blob_digest_writes RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_request_duration_seconds_count{method=~\"patch|post|put\",route=\"/v2/{name}/blobs/{digest}\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: server_route_blob_upload_uuid_deletes",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 240 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 server_route_blob_upload_uuid_deletes Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{method=~\"delete\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "server_route_blob_upload_uuid_deletes RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_request_duration_seconds_count{method=~\"delete\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 server_route_blob_upload_uuid_deletes Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,method) (\n    rate(registry_http_request_duration_seconds_bucket{method!=\"\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server_route_blob_upload_uuid_deletes Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{le=\"+Inf\",method!=\"\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{le=\"2.5\",method!=\"\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{le=\"5\",method!=\"\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(method) group_left()\n  (\n    sum by () (\n  rate(registry_http_request_duration_seconds_bucket{le=\"+Inf\",method!=\"\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "server_route_blob_upload_uuid_deletes RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_request_duration_seconds_count{method=~\"delete\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: server_route_blob_upload_uuid_reads",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 250 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 server_route_blob_upload_uuid_reads Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{method=~\"get|head\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "server_route_blob_upload_uuid_reads RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_request_duration_seconds_count{method=~\"get|head\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 server_route_blob_upload_uuid_reads Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,method) (\n    rate(registry_http_request_duration_seconds_bucket{method!=\"\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server_route_blob_upload_uuid_reads Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{le=\"+Inf\",method!=\"\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{le=\"1\",method!=\"\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{le=\"2.5\",method!=\"\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(method) group_left()\n  (\n    sum by () (\n  rate(registry_http_request_duration_seconds_bucket{le=\"+Inf\",method!=\"\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "server_route_blob_upload_uuid_reads RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_request_duration_seconds_count{method=~\"get|head\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: server_route_blob_upload_uuid_writes",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 260 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 server_route_blob_upload_uuid_writes Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{method=~\"patch|post|put\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "server_route_blob_upload_uuid_writes RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_request_duration_seconds_count{method=~\"patch|post|put\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 server_route_blob_upload_uuid_writes Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,method) (\n    rate(registry_http_request_duration_seconds_bucket{method!=\"\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server_route_blob_upload_uuid_writes Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{le=\"+Inf\",method!=\"\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{le=\"25\",method!=\"\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{le=\"60\",method!=\"\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(method) group_left()\n  (\n    sum by () (\n  rate(registry_http_request_duration_seconds_bucket{le=\"+Inf\",method!=\"\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "server_route_blob_upload_uuid_writes RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_request_duration_seconds_count{method=~\"patch|post|put\",route=\"/v2/{name}/blobs/uploads/{uuid}\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "kube_container_cpu_limit component saturation: Kube Container CPU over-utilization",
     "type": "graph",
     "description": "Kubernetes containers can have a limit configured on how much CPU they can consume in\na burst. If we are at this limit, exceeding the allocated requested resources, we\nshould consider revisting the container's HPA configuration.\n\nWhen a container is utilizing CPU resources up-to it's configured limit for\nextended periods of time, this could cause it and other running containers to be\nthrottled.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(container,pod,type) (\n  clamp_min(\n    clamp_max(\n      sum by (container,pod,type) (\n        rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", type=\"registry\"}[5m])\n      )\n      /\n      sum by(container,pod,type) (\n        container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", type=\"registry\"}\n        /\n        container_spec_cpu_period:labeled{container!=\"\", container!=\"POD\", type=\"registry\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{type=\"registry\", component=\"kube_container_cpu_limit\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{type=\"registry\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{type=\"registry\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_memory component saturation: Kube Container Memory Utilization",
     "type": "graph",
     "description": "This uses the working set size from cAdvisor for the cgroup's memory usage. That may\nnot be a good measure as it includes filesystem cache pages that are not necessarily\nattributable to the application inside the cgroup, and are permitted to be evicted\ninstead of being OOM killed.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(deployment,type) (\n  clamp_min(\n    clamp_max(\n      container_memory_working_set_bytes:labeled{container!=\"\", container!=\"POD\", type=\"registry\"}\n      /\n      (container_spec_memory_limit_bytes:labeled{container!=\"\", container!=\"POD\", type=\"registry\"} > 0)\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ deployment }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{type=\"registry\", component=\"kube_container_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{type=\"registry\", component=\"kube_container_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{type=\"registry\", component=\"kube_container_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}