{
 "title": "rate-limiting: Rate Limiting: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8397766929 at Mon Nov 18 09:15:29 UTC 2024",
 "tags": [
  "managed",
  "rate-limiting",
  "protected"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Rate Limiting Overview\n\nThis dashboard shows the rate limiting metrics at each layer of GitLab, beginning with the edge and working it's way down to the application.\n\nEach section contains links to logs to do further investigation.\n\n- 📑 Read more: [Rate Limiting Handbook Page](https://handbook.gitlab.com/handbook/engineering/infrastructure/rate-limiting/)"
   }
  },
  { "title": "Cloudflare", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 6 },
   "options": {
    "content": "# Cloudflare\n\nThe edge of our network - applies IP based rate limits and other high level blocks.\n\n## Links\n\n- 📊 [Cloudflare Dashboard: Rate Limit configuration](https://dash.cloudflare.com/852e9d53d0f8adbd9205389356f2303d/gitlab.com/security/waf/rate-limiting-rules)\n- 📊 [Cloudflare Dashboard: Custom Rules configuration](https://dash.cloudflare.com/852e9d53d0f8adbd9205389356f2303d/gitlab.com/security/waf/custom-rules)\n- 📊 [Cloudflare Dashboard: Firewall Events](https://dash.cloudflare.com/852e9d53d0f8adbd9205389356f2303d/gitlab.com/security/events)\n\nRules are managed in [config-mgmt](https://ops.gitlab.net/gitlab-com/gl-infra/config-mgmt/-/blob/main/environments/gprd/cloudflare-rate-limits-waf-and-rules.tf)\n\n"
   }
  },
  {
   "title": "Cloudflare rate limited response rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum by (status) (rate(cloudflare_zone_requests_status{zone=\"gitlab.com\", status=\"429\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloudflare percentage of rate limited requests",
   "type": "timeseries",
   "description": "What percentage of requests were rate limited in this period of time?",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "($B / $A) * 100", "type": "math" }
   ]
  },
  {
   "title": "Cloudflare ratelimit block events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum by (action) (rate(cloudflare_zone_firewall_events_count{zone=\"gitlab.com\", source=\"ratelimit\",action=\"block\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloudflare events by source",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "sum by (source,action) (rate(cloudflare_zone_firewall_events_count{zone=\"gitlab.com\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HAProxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "options": {
    "content": "# HAProxy\n\nProvides rate limiting for GitLab Pages and Registry.\n\n- These metrics are only by `4xx` which could mean rate limited responses, or any other client side error status, such as unauthenticated. It doesn't provide the most value. \n\n## Links\n\n- 📊 [HAProxy BigQuery](https://console.cloud.google.com/bigquery?project=gitlab-production&pli=1&ws=!1m4!1m3!3m2!1sgitlab-production!2shaproxy_logs) "
   }
  },
  {
   "title": "HAProxy 4xx response rate by backend",
   "type": "timeseries",
   "description": "We don't have the granularity to differentiate between 4xx client errors with HAProxy.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "sum by (backend)(rate(haproxy_backend_http_responses_total{code=\"4xx\",env=\"gprd\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HAProxy 4xx response rate: pages_http, registry",
   "type": "timeseries",
   "description": "We know Pages and Registry use HAProxy for rate limiting, so specifically filter on this.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "sum by (backend) (rate(haproxy_backend_http_responses_total{code=\"4xx\",env=\"gprd\", backend=~\"pages_http|registry\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application::Workhorse Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "options": {
    "content": "# Workhorse\n\nHTTP Request Metrics from Workhorse by status.\n\nDoesn't show which rate limiter applied the throttle, but does give a signal if the application was doing the throttling.\n\n## Links\n\n- 📊 [Workhorse: Rate Limited](https://log.gprd.gitlab.net/app/discover#/view/7b6dc396-5b27-4e86-b150-72b476255faf?_g=())"
   }
  },
  {
   "title": "Workhorse rate limited response rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "sum by (code)(rate(gitlab_workhorse_http_requests_total{code=\"429\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workhorse response rate by status",
   "type": "timeseries",
   "description": "The overall response statuses being returned by the application.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "sum by (code)(rate(gitlab_workhorse_http_requests_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application::Rack Attack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "options": {
    "content": "# RackAttack\n\nThese metrics show the RackAttack throttles that have been triggered during the selected timeframe.\n## Links\n\n- 📊 [RackAttack: Kibana logs](https://log.gprd.gitlab.net/app/discover#/view/0026cc97-6b9a-445a-a364-7197e04053a2?_g=())\n  - Use the `json.matched` field to filter by throttle.\n- 📊 [Support Rate Limit Kibana Dashboard](https://log.gprd.gitlab.net/app/r/s/AJDZC)"
   }
  },
  {
   "title": "RackAttack rate limited response rate ",
   "type": "timeseries",
   "description": "by event name and type",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(gitlab_rack_attack_events_total{env='gprd'}[1m])) by (event_name, event_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RackAttack throttle limits",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gitlab_rack_attack_throttle_limit) by (event_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RackAttack throttle period (seconds)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gitlab_rack_attack_throttle_period_seconds) by (event_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application::ApplicationRateLimiter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 }
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "options": {
    "content": "# ApplicationRateLimiter\n\nIntelligent application rate limits.\n\n## Links\n\n- 📊 [ApplicationRateLimiter: Kibana Logs](https://log.gprd.gitlab.net/app/discover#/view/2d2cf10e-b22a-4c07-bbda-45bb665c31ee?_g=())\n  - Use the `json.env` field to filter by throttle."
   }
  },
  {
   "title": "ApplicationRateLimiter rate of throttled requests by key",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 50 },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  }
 ]
}