{
 "title": "registry: Webhook Notifications Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8397766929 at Mon Nov 18 09:15:41 UTC 2024",
 "tags": [
  "managed",
  "registry",
  "container registry",
  "docker",
  "registry",
  "webhook",
  "notifications"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, cluster)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, namespace)"
   },
   { "name": "Deployment", "query": "gitlab-registry," },
   {
    "name": "cluster",
    "query": "label_values(registry_notifications_events_total{environment=\"$environment\"}, cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events per second",
   "type": "stat",
   "description": "The per-second rate of all event notifications sent by the registry.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (\n  rate(\n    registry_notifications_events_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_type=\"Events\"}[$__interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Events queued",
   "type": "stat",
   "description": "The total number of events generated by the registry per interval.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    registry_notifications_events_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_type=\"Events\"}[$__interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Events delivered",
   "type": "stat",
   "description": "The total number of events sent by the registry per interval.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    registry_notifications_events_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_type=\"Successes\"}[$__interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Pending events",
   "type": "stat",
   "description": "The number of pending events that need to be sent.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n  max_over_time(\n    registry_notifications_pending_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Event delivery success rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    registry_notifications_events_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_type=\"Successes\"}[$__interval]\n  )\n)\n/\nsum(\n  rate(\n    registry_notifications_events_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_type=\"Events\"}[$__interval]\n  )\n)\n"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Events queued per second",
   "type": "graph",
   "description": "The per-second rate of all events generated by the registry.",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    registry_notifications_events_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_type=\"Events\"}[$__interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Event delivery failure rate",
   "type": "graph",
   "description": "The per-second rate of events that failed to be delivered due to response status code >= 400",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 1001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    registry_notifications_events_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_type=\"Failures\"}[$__interval]\n  )\n)\n/\nsum(\n  rate(\n    registry_notifications_events_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_type=\"Events\"}[$__interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Event delivery error rate",
   "type": "graph",
   "description": "The per-second rate of events that were not sent due to registry internal errors or timeouts",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 1001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    registry_notifications_events_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_type=\"Errors\"}[$__interval]\n  )\n)\n/\nsum(\n  rate(\n    registry_notifications_events_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_type=\"Events\"}[$__interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Pending events",
   "type": "graph",
   "description": "The number of events pending to be sent.",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 1014 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max_over_time(\n    registry_notifications_pending_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]\n  )\n)\n",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  {
   "title": "Events per second (by Status Code)",
   "type": "graph",
   "description": "The per-second rate of response status codes for all events.",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 1014 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (\n  rate(\n    registry_notifications_status_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]\n  )\n)\n"
    }
   ]
  }
 ]
}