{
 "title": "registry: Regional Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7927277014 at Thu Sep 26 12:04:06 UTC 2024",
 "tags": [
  "managed",
  "registry",
  "type:registry",
  "regional"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "Regional Service Aggregated  Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_regional_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "Regional Service Aggregated  Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_regional_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"registry\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"registry\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "Regional Service Aggregated  RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_regional_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  { "title": "🔬 Regional SLIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "database SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"database\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"database\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"database\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "database SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1001 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"database\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1001 },
   "content": "### Description\n\nAggregation of all container registry database operations.\n\n"
  },
  {
   "title": "garbagecollector SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1011 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"garbagecollector\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"garbagecollector\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"garbagecollector\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "garbagecollector SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1011 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"garbagecollector\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"garbagecollector\",monitor=\"global\",type=\"registry\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"garbagecollector\",monitor=\"global\",type=\"registry\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "garbagecollector SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1011 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"garbagecollector\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1011 },
   "content": "### Description\n\nAggregation of all container registry online garbage collection operations.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Garbage Collector logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.correlation_id,json.component,json.worker,json.msg,json.error,json.duration_s),filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.component,params:!(registry.gc.Agent,registry.gc.worker.ManifestWorker,registry.gc.worker.BlobWorker),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.component:registry.gc.Agent)),(match_phrase:(json.component:registry.gc.worker.ManifestWorker)),(match_phrase:(json.component:registry.gc.worker.BlobWorker)))))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase))))),index:'97ce8e90-63ad-11ea-8617-2347010d3aab')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Garbage Collector failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.correlation_id,json.component,json.worker,json.msg,json.error,json.duration_s),filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.component,params:!(registry.gc.Agent,registry.gc.worker.ManifestWorker,registry.gc.worker.BlobWorker),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.component:registry.gc.Agent)),(match_phrase:(json.component:registry.gc.worker.ManifestWorker)),(match_phrase:(json.component:registry.gc.worker.BlobWorker)))))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.level,params:error,type:phrase),query:(match:(json.level:(query:error,type:phrase))))),index:'97ce8e90-63ad-11ea-8617-2347010d3aab')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Garbage Collector requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.component,params:!(registry.gc.Agent,registry.gc.worker.ManifestWorker,registry.gc.worker.BlobWorker),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.component:registry.gc.Agent)),(match_phrase:(json.component:registry.gc.worker.ManifestWorker)),(match_phrase:(json.component:registry.gc.worker.BlobWorker)))))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Garbage Collector failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.component,params:!(registry.gc.Agent,registry.gc.worker.ManifestWorker,registry.gc.worker.BlobWorker),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.component:registry.gc.Agent)),(match_phrase:(json.component:registry.gc.worker.ManifestWorker)),(match_phrase:(json.component:registry.gc.worker.BlobWorker)))))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.level,params:error,type:phrase),query:(match:(json.level:(query:error,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Garbage Collector sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.component,params:!(registry.gc.Agent,registry.gc.worker.ManifestWorker,registry.gc.worker.BlobWorker),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.component:registry.gc.Agent)),(match_phrase:(json.component:registry.gc.worker.ManifestWorker)),(match_phrase:(json.component:registry.gc.worker.BlobWorker)))))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Garbage Collector sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.component,params:!(registry.gc.Agent,registry.gc.worker.ManifestWorker,registry.gc.worker.BlobWorker),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.component:registry.gc.Agent)),(match_phrase:(json.component:registry.gc.worker.ManifestWorker)),(match_phrase:(json.component:registry.gc.worker.BlobWorker)))))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.worker,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Garbage Collector percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.component,params:!(registry.gc.Agent,registry.gc.worker.ManifestWorker,registry.gc.worker.BlobWorker),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.component:registry.gc.Agent)),(match_phrase:(json.component:registry.gc.worker.ManifestWorker)),(match_phrase:(json.component:registry.gc.worker.BlobWorker)))))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Garbage Collector percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.component,params:!(registry.gc.Agent,registry.gc.worker.ManifestWorker,registry.gc.worker.BlobWorker),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.component:registry.gc.Agent)),(match_phrase:(json.component:registry.gc.worker.ManifestWorker)),(match_phrase:(json.component:registry.gc.worker.BlobWorker)))))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.worker,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "loadbalancer SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1021 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"registry\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"registry\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "loadbalancer SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1021 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1021 },
   "content": "### Description\n\nMeasures aggregated HTTP request traffic through the HAProxy.\n5xx responses are considered to be failures.\n\n"
  },
  {
   "title": "redis SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1031 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"redis\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"redis\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"redis\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "redis SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1031 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"redis\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"redis\",monitor=\"global\",type=\"registry\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"redis\",monitor=\"global\",type=\"registry\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "redis SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1031 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"redis\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1031 },
   "content": "### Description\n\nAggregation of all container registry Redis operations.\n\n"
  },
  {
   "title": "registry_cdn SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1041 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"registry_cdn\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"registry_cdn\",monitor=\"global\",type=\"registry\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"registry_cdn\",monitor=\"global\",type=\"registry\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "registry_cdn SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1041 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"registry_cdn\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1041 },
   "content": "### Observability Tools\n\n* [Google Load Balancer](https://console.cloud.google.com/net-services/loadbalancing/details/http/gprd-registry-cdn?project=gitlab-production)\n* [Stackdriver Logs: Loadbalancer Access Logs](https://console.cloud.google.com/logs/query;query=resource%2Elabels%2Eurl%5Fmap%5Fname%3D%22gprd%2Dregistry%2Dcdn%22%0Aresource%2Etype%3D%22http%5Fload%5Fbalancer%22;timeRange=PT30M?project=gitlab-production)\n* [Stackdriver Logs: Loadbalancer Access 5xx Logs](https://console.cloud.google.com/logs/query;query=httpRequest%2Estatus%3E%3D500%0Aresource%2Elabels%2Eurl%5Fmap%5Fname%3D%22gprd%2Dregistry%2Dcdn%22%0Aresource%2Etype%3D%22http%5Fload%5Fbalancer%22;timeRange=PT30M?project=gitlab-production)\n\n"
  },
  {
   "title": "registry_server SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1051 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"registry_server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"registry_server\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"registry_server\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "registry_server SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1051 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_regional_sli_errors:ratio_5m{component=\"registry_server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{ region }} {{ location }} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"registry_server\",monitor=\"global\",type=\"registry\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"registry_server\",monitor=\"global\",type=\"registry\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "registry_server SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1051 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"registry_server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1051 },
   "content": "### Description\n\nAggregation of all registry HTTP requests.\n\n\n\n### Observability Tools\n\n* [GKE Deployment: gitlab-registry](https://console.cloud.google.com/kubernetes/deployment/us-east1/gprd-gitlab-gke/gitlab/gitlab-registry/overview?project=gitlab-production)\n* [Stackdriver Logs: GKE Container Logs](https://console.cloud.google.com/logs/query;query=labels%2E%22k8s%2Dpod%2Ftype%22%3D%22registry%22%0Aresource%2Elabels%2Ecluster%5Fname%3D%22gprd%2Dgitlab%2Dgke%22%0Aresource%2Elabels%2Econtainer%5Fname%3D%22registry%22%0Aresource%2Elabels%2Enamespace%5Fname%3D%22gitlab%22%0Aresource%2Elabels%2Eproject%5Fid%3D%22gitlab%2Dproduction%22%0Aresource%2Etype%3D%22k8s%5Fcontainer%22;timeRange=PT30M?project=gitlab-production)\n* [📖 Kibana: Registry logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.remote_ip,json.duration_ms,json.code,json.msg,json.status,json.error,json.method,json.uri),filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase))))),index:'97ce8e90-63ad-11ea-8617-2347010d3aab')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Registry slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.remote_ip,json.duration_ms,json.code,json.msg,json.status,json.error,json.method,json.uri),filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase)))),(meta:(field:json.duration_ms,index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.duration_ms,params:(gte:10000,lte:!n),type:range),query:(range:(json.duration_ms:(gte:10000,lte:!n))))),index:'97ce8e90-63ad-11ea-8617-2347010d3aab',sort:!(!(json.duration_ms,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Registry failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.remote_ip,json.duration_ms,json.code,json.msg,json.status,json.error,json.method,json.uri),filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase)))),(meta:(field:json.status,index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),index:'97ce8e90-63ad-11ea-8617-2347010d3aab')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase)))),(meta:(field:json.status,index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type.keyword,params:registry,type:phrase),query:(match:(json.type.keyword:(query:registry,type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'97ce8e90-63ad-11ea-8617-2347010d3aab',key:json.type,params:registry,type:phrase),query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_ms),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [Google Stackdriver Continuous Profiling](https://console.cloud.google.com/profiler;timespan=4h/gitlab-registry;type=CPU/cpu?project=gitlab-production)\n\n"
  },
  {
   "title": "server_route_blob_upload_uuid_deletes SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1061 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"server_route_blob_upload_uuid_deletes\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_deletes\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_deletes\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "server_route_blob_upload_uuid_deletes SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1061 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"server_route_blob_upload_uuid_deletes\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1061 },
   "content": "### Description\n\nDelete requests for the registry blob upload endpoints.\n\nUsed to cancel outstanding upload processes, releasing associated\nresources.\n\n"
  },
  {
   "title": "server_route_blob_upload_uuid_reads SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1071 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"server_route_blob_upload_uuid_reads\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_reads\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_reads\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "server_route_blob_upload_uuid_reads SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1071 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"server_route_blob_upload_uuid_reads\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1071 },
   "content": "### Description\n\nRead requests (GET) for the registry blob upload endpoints.\n\nGET is used to retrieve the current status of a resumable upload.\n\nThis is currently not used on GitLab.com.\n\n"
  },
  {
   "title": "server_route_blob_upload_uuid_writes SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1081 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"server_route_blob_upload_uuid_writes\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_writes\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_blob_upload_uuid_writes\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "server_route_blob_upload_uuid_writes SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1081 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"server_route_blob_upload_uuid_writes\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1081 },
   "content": "### Description\n\nWrite requests (PUT or PATCH) for the registry blob upload endpoints.\n\nPUT is used to complete the upload specified by uuid, optionally appending\nthe body as the final chunk.\n\nPATCH is used to upload a chunk of data for the specified upload.\n\n"
  },
  {
   "title": "server_route_manifest_reads SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1091 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"server_route_manifest_reads\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_manifest_reads\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_manifest_reads\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "server_route_manifest_reads SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1091 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"server_route_manifest_reads\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1091 },
   "content": "### Description\n\nAll read-requests (HEAD or GET) for the manifest endpoints on\nthe registry.\nFetch the manifest identified by name and reference where reference can be\na tag or digest. A HEAD request can also be issued to this endpoint to\nobtain resource information without receiving all data.\n\n"
  },
  {
   "title": "server_route_manifest_writes SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1101 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_regional_sli_apdex:ratio_5m{component=\"server_route_manifest_writes\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_manifest_writes\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"server_route_manifest_writes\",monitor=\"global\",type=\"registry\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    }
   ]
  },
  {
   "title": "server_route_manifest_writes SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1101 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_regional_sli_ops:rate_5m{component=\"server_route_manifest_writes\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "{{ region }} {{ location }} RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1101 },
   "content": "### Description\n\nAll write-requests (put, delete) for the manifest endpoints on\nthe registry.\n\nPut the manifest identified by name and reference where reference can be\na tag or digest.\n\nDelete the manifest identified by name and reference. Note that a manifest\ncan only be deleted by digest.\n\n"
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}