{
 "title": "mimir: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7867191950 at Thu Sep 19 12:03:49 UTC 2024",
 "tags": [
  "managed",
  "mimir",
  "gitlab",
  "type:mimir",
  "mimir",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "mimir Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"mimir\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"mimir\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"mimir\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "mimir Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "mimir Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"mimir\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "mimir Service | Errors"
    }
   ]
  },
  {
   "title": "mimir Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"mimir\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "mimir_compactor SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"mimir_compactor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir_compactor error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_compactor\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_compactor\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"mimir_compactor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir_compactor error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"mimir_compactor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_compactor\",monitor=\"global\",type=\"mimir\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"mimir_compactor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"mimir_compactor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_compactor\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"mimir_compactor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_compactor\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"mimir_compactor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_compactor\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"mimir_compactor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_compactor\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "mimir_compactor SLI | Errors"
    }
   ]
  },
  {
   "title": "mimir_compactor SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"mimir_compactor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_compactor RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"mimir_compactor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "content": "### Description\n\nThe compactor increases query performance and reduces long-term storage usage by combining blocks.\nThis SLI monitors the compactor operations for failures.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Mimir Compactor logs](https://nonprod-log.gitlab.net/app/kibana#/discover?_a=(columns:!(json.message,json.err),filters:!((meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:kubernetes.container_name,params:compactor,type:phrase),query:(match:(kubernetes.container_name:(query:compactor,type:phrase)))),(meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:json.type,params:mimir,type:phrase),query:(match:(json.type:(query:mimir,type:phrase))))),index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Mimir Compactor requests](https://nonprod-log.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=69713556-cfad-4fcd-a7f6-7e1ac0f90313&_a=(filters:!((meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:kubernetes.container_name,params:compactor,type:phrase),query:(match:(kubernetes.container_name:(query:compactor,type:phrase)))),(meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:json.type,params:mimir,type:phrase),query:(match:(json.type:(query:mimir,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "mimir_distributor SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_distributor apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_distributor\",monitor=\"global\",type=\"mimir\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_distributor\",monitor=\"global\",type=\"mimir\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_distributor apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_distributor\",monitor=\"global\",type=\"mimir\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_distributor\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_distributor\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_distributor\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_distributor\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "mimir_distributor SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "mimir_distributor SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir_distributor error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_distributor\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_distributor\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir_distributor error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_distributor\",monitor=\"global\",type=\"mimir\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_distributor\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_distributor\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_distributor\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_distributor\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "mimir_distributor SLI | Errors"
    }
   ]
  },
  {
   "title": "mimir_distributor SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_distributor RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"mimir_distributor\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "content": "### Description\n\nThe distributor is a stateless component that receives time-series data from remote-write requests via Prometheus or the Grafana agent.\nIt validates the data for correctness and ensures that it is within the configured limits for a given tenant.\nThe distributor then divides the data into batches and sends it to multiple ingesters in parallel, shards the series among ingesters, and replicates each series by the configured replication factor.\nBy default, the configured replication factor is three.\nThis SLI monitors the distributor requests. 5xx responses are considered failures.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Mimir Distributor logs](https://nonprod-log.gitlab.net/app/kibana#/discover?_a=(columns:!(json.message,json.err),filters:!((meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:kubernetes.container_name,params:distributor,type:phrase),query:(match:(kubernetes.container_name:(query:distributor,type:phrase)))),(meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:json.type,params:mimir,type:phrase),query:(match:(json.type:(query:mimir,type:phrase))))),index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Mimir Distributor requests](https://nonprod-log.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=69713556-cfad-4fcd-a7f6-7e1ac0f90313&_a=(filters:!((meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:kubernetes.container_name,params:distributor,type:phrase),query:(match:(kubernetes.container_name:(query:distributor,type:phrase)))),(meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:json.type,params:mimir,type:phrase),query:(match:(json.type:(query:mimir,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "mimir_ingester SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_ingester apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_ingester\",monitor=\"global\",type=\"mimir\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_ingester\",monitor=\"global\",type=\"mimir\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_ingester apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_ingester\",monitor=\"global\",type=\"mimir\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_ingester\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_ingester\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_ingester\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_ingester\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "mimir_ingester SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "mimir_ingester SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir_ingester error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_ingester\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_ingester\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir_ingester error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_ingester\",monitor=\"global\",type=\"mimir\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_ingester\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_ingester\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_ingester\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_ingester\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "mimir_ingester SLI | Errors"
    }
   ]
  },
  {
   "title": "mimir_ingester SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_ingester RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"mimir_ingester\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "content": "### Description\n\nThe ingester is a stateful component that writes incoming series to long-term storage on the write path and returns series samples for queries on the read path.\nIncoming time series data from distributors are temporarily stored in the ingester’s memory or offloaded to disk before being written to long-term storage.\nEventually, all series are written to disk and periodically uploaded (by default every two hours) to the long-term storage.\nThis SLI monitors the distributor requests. 5xx responses are considered failures.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Mimir Ingester logs](https://nonprod-log.gitlab.net/app/kibana#/discover?_a=(columns:!(json.message,json.err),filters:!((meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:kubernetes.container_name,params:ingester,type:phrase),query:(match:(kubernetes.container_name:(query:ingester,type:phrase)))),(meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:json.type,params:mimir,type:phrase),query:(match:(json.type:(query:mimir,type:phrase))))),index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Mimir Ingester requests](https://nonprod-log.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=69713556-cfad-4fcd-a7f6-7e1ac0f90313&_a=(filters:!((meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:kubernetes.container_name,params:ingester,type:phrase),query:(match:(kubernetes.container_name:(query:ingester,type:phrase)))),(meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:json.type,params:mimir,type:phrase),query:(match:(json.type:(query:mimir,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "mimir_querier SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_querier apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_querier\",monitor=\"global\",type=\"mimir\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_querier\",monitor=\"global\",type=\"mimir\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_querier apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_querier\",monitor=\"global\",type=\"mimir\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_querier\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_querier\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_querier\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_querier\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "mimir_querier SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "mimir_querier SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir_querier error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_querier\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_querier\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir_querier error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_querier\",monitor=\"global\",type=\"mimir\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_querier\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_querier\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_querier\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_querier\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "mimir_querier SLI | Errors"
    }
   ]
  },
  {
   "title": "mimir_querier SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_querier RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"mimir_querier\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
   "content": "### Description\n\nThe querier is a stateless component that evaluates PromQL expressions by fetching time series and labels on the read path.\nThe querier uses the store-gateway component to query the long-term storage and the ingester component to query recently written data.\nThis SLI monitors the querier requests. 5xx responses are considered failures.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Mimir Querier logs](https://nonprod-log.gitlab.net/app/kibana#/discover?_a=(columns:!(json.message,json.err),filters:!((meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:kubernetes.container_name,params:querier,type:phrase),query:(match:(kubernetes.container_name:(query:querier,type:phrase)))),(meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:json.type,params:mimir,type:phrase),query:(match:(json.type:(query:mimir,type:phrase))))),index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Mimir Querier requests](https://nonprod-log.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=69713556-cfad-4fcd-a7f6-7e1ac0f90313&_a=(filters:!((meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:kubernetes.container_name,params:querier,type:phrase),query:(match:(kubernetes.container_name:(query:querier,type:phrase)))),(meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:json.type,params:mimir,type:phrase),query:(match:(json.type:(query:mimir,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "mimir_query_frontend SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_query_frontend apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_query_frontend\",monitor=\"global\",type=\"mimir\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_query_frontend\",monitor=\"global\",type=\"mimir\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_query_frontend apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_query_frontend\",monitor=\"global\",type=\"mimir\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_query_frontend\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_query_frontend\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_query_frontend\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_query_frontend\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "mimir_query_frontend SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "mimir_query_frontend SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 61 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir_query_frontend error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_query_frontend\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_query_frontend\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir_query_frontend error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_query_frontend\",monitor=\"global\",type=\"mimir\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_query_frontend\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_query_frontend\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_query_frontend\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_query_frontend\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "mimir_query_frontend SLI | Errors"
    }
   ]
  },
  {
   "title": "mimir_query_frontend SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_query_frontend RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"mimir_query_frontend\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 61 },
   "content": "### Description\n\nThe query-frontend is a stateless component that provides the same API as the querier and can be used to accelerate the read path via caching.\nThis SLI monitors the query-frontend requests. 5xx responses are considered failures.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Mimir Query Frontend logs](https://nonprod-log.gitlab.net/app/kibana#/discover?_a=(columns:!(json.message,json.err),filters:!((meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:kubernetes.container_name,params:'query-frontend',type:phrase),query:(match:(kubernetes.container_name:(query:'query-frontend',type:phrase)))),(meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:json.type,params:mimir,type:phrase),query:(match:(json.type:(query:mimir,type:phrase))))),index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Mimir Query Frontend requests](https://nonprod-log.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=69713556-cfad-4fcd-a7f6-7e1ac0f90313&_a=(filters:!((meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:kubernetes.container_name,params:'query-frontend',type:phrase),query:(match:(kubernetes.container_name:(query:'query-frontend',type:phrase)))),(meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:json.type,params:mimir,type:phrase),query:(match:(json.type:(query:mimir,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "mimir_query_scheduler SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_query_scheduler apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_query_scheduler\",monitor=\"global\",type=\"mimir\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_query_scheduler\",monitor=\"global\",type=\"mimir\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_query_scheduler apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_query_scheduler\",monitor=\"global\",type=\"mimir\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_query_scheduler\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_query_scheduler\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_query_scheduler\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_query_scheduler\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "mimir_query_scheduler SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "mimir_query_scheduler SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 71 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir_query_scheduler error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_query_scheduler\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_query_scheduler\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir_query_scheduler error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_query_scheduler\",monitor=\"global\",type=\"mimir\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_query_scheduler\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_query_scheduler\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_query_scheduler\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_query_scheduler\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "mimir_query_scheduler SLI | Errors"
    }
   ]
  },
  {
   "title": "mimir_query_scheduler SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_query_scheduler RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"mimir_query_scheduler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 71 },
   "content": "### Description\n\nThe query-scheduler is an optional, stateless component that retains a queue of queries to execute, and distributes the workload to available queriers.\nThis enabled easier scaling of the query-frontends\nThis SLI monitors the query-scheduler requests. 5xx responses are considered failures.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Mimir Query Scheduler logs](https://nonprod-log.gitlab.net/app/kibana#/discover?_a=(columns:!(json.message,json.err),filters:!((meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:kubernetes.container_name,params:'query-scheduler',type:phrase),query:(match:(kubernetes.container_name:(query:'query-scheduler',type:phrase)))),(meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:json.type,params:mimir,type:phrase),query:(match:(json.type:(query:mimir,type:phrase))))),index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Mimir Query Scheduler requests](https://nonprod-log.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=69713556-cfad-4fcd-a7f6-7e1ac0f90313&_a=(filters:!((meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:kubernetes.container_name,params:'query-scheduler',type:phrase),query:(match:(kubernetes.container_name:(query:'query-scheduler',type:phrase)))),(meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:json.type,params:mimir,type:phrase),query:(match:(json.type:(query:mimir,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "mimir_ruler SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"mimir_ruler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir_ruler error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_ruler\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_ruler\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"mimir_ruler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir_ruler error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"mimir_ruler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_ruler\",monitor=\"global\",type=\"mimir\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"mimir_ruler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"mimir_ruler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_ruler\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"mimir_ruler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_ruler\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"mimir_ruler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_ruler\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"mimir_ruler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_ruler\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "mimir_ruler SLI | Errors"
    }
   ]
  },
  {
   "title": "mimir_ruler SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"mimir_ruler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_ruler RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"mimir_ruler\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 81 },
   "content": "### Description\n\nThe ruler component evaluates PromQL expressions defined in recording and alerting rules. Each tenant has a set of recording and alerting rules and can group those rules into namespaces.\nThis SLI monitors the rulers evaluation failures.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Mimir Ruler logs](https://nonprod-log.gitlab.net/app/kibana#/discover?_a=(columns:!(json.message,json.err),filters:!((meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:kubernetes.container_name,params:ruler,type:phrase),query:(match:(kubernetes.container_name:(query:ruler,type:phrase)))),(meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:json.type,params:mimir,type:phrase),query:(match:(json.type:(query:mimir,type:phrase))))),index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Mimir Ruler requests](https://nonprod-log.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=69713556-cfad-4fcd-a7f6-7e1ac0f90313&_a=(filters:!((meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:kubernetes.container_name,params:ruler,type:phrase),query:(match:(kubernetes.container_name:(query:ruler,type:phrase)))),(meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:json.type,params:mimir,type:phrase),query:(match:(json.type:(query:mimir,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "mimir_store_gateway SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_store_gateway apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_store_gateway\",monitor=\"global\",type=\"mimir\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_store_gateway\",monitor=\"global\",type=\"mimir\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_store_gateway apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_store_gateway\",monitor=\"global\",type=\"mimir\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_store_gateway\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_store_gateway\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_store_gateway\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"mimir_store_gateway\",monitor=\"global\",type=\"mimir\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "mimir_store_gateway SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "mimir_store_gateway SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 91 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir_store_gateway error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_store_gateway\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_store_gateway\",monitor=\"global\",type=\"mimir\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "mimir_store_gateway error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"mimir_store_gateway\",monitor=\"global\",type=\"mimir\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_store_gateway\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_store_gateway\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_store_gateway\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"mimir_store_gateway\",monitor=\"global\",type=\"mimir\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "mimir_store_gateway SLI | Errors"
    }
   ]
  },
  {
   "title": "mimir_store_gateway SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"}[$__interval])\n",
     "legendFormat": "mimir_store_gateway RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"mimir_store_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"mimir\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 91 },
   "content": "### Description\n\nThe store-gateway component, which is stateful, queries blocks from long-term storage.\nOn the read path, the querier and the ruler use the store-gateway when handling the query, whether the query comes from a user or from when a rule is being evaluated.\nThis SLI monitors the store-gatewau requests. 5xx responses are considered failures.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Mimir Store Gateway logs](https://nonprod-log.gitlab.net/app/kibana#/discover?_a=(columns:!(json.message,json.err),filters:!((meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:kubernetes.container_name,params:'store-gateway',type:phrase),query:(match:(kubernetes.container_name:(query:'store-gateway',type:phrase)))),(meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:json.type,params:mimir,type:phrase),query:(match:(json.type:(query:mimir,type:phrase))))),index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Mimir Store Gateway requests](https://nonprod-log.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=69713556-cfad-4fcd-a7f6-7e1ac0f90313&_a=(filters:!((meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:kubernetes.container_name,params:'store-gateway',type:phrase),query:(match:(kubernetes.container_name:(query:'store-gateway',type:phrase)))),(meta:(index:'69713556-cfad-4fcd-a7f6-7e1ac0f90313',key:json.type,params:mimir,type:phrase),query:(match:(json.type:(query:mimir,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "🔬 SLI Detail: mimir_compactor",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "mimir_compactor Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cortex_compactor_group_compactions_failures_total:rate_5m{job=\"mimir/compactor\",namespace=\"mimir\",type=\"mimir\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "mimir_compactor RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cortex_compactor_group_compaction_runs_started_total:rate_5m{job=\"mimir/compactor\",namespace=\"mimir\",type=\"mimir\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: mimir_distributor",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 mimir_distributor Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    sli_aggregations:cortex_request_duration_seconds_bucket:rate_5m{job=\"mimir/distributor\",namespace=\"mimir\",route=~\"/distributor\\\\.Distributor/Push|/httpgrpc.*|(api_(v1|prom)_push)|otlp_v1_metrics\",type=\"mimir\"}\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "mimir_distributor Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cortex_request_duration_seconds_count:rate_5m{job=\"mimir/distributor\",namespace=\"mimir\",route=~\"/distributor\\\\.Distributor/Push|/httpgrpc.*|(api_(v1|prom)_push)|otlp_v1_metrics\",status_code=~\"^5.*\",type=\"mimir\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "mimir_distributor RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cortex_request_duration_seconds_count:rate_5m{job=\"mimir/distributor\",namespace=\"mimir\",route=~\"/distributor\\\\.Distributor/Push|/httpgrpc.*|(api_(v1|prom)_push)|otlp_v1_metrics\",type=\"mimir\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: mimir_ingester",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 220 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 mimir_ingester Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    sli_aggregations:cortex_request_duration_seconds_bucket:rate_5m{job=\"mimir/ingester\",namespace=\"mimir\",route=\"/cortex.Ingester/Push\",type=\"mimir\"}\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "mimir_ingester Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cortex_request_duration_seconds_count:rate_5m{job=\"mimir/ingester\",namespace=\"mimir\",route=\"/cortex.Ingester/Push\",status_code=~\"^5.*\",type=\"mimir\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "mimir_ingester RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cortex_request_duration_seconds_count:rate_5m{job=\"mimir/ingester\",namespace=\"mimir\",route=\"/cortex.Ingester/Push\",type=\"mimir\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: mimir_querier",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 230 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 mimir_querier Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    sli_aggregations:cortex_querier_request_duration_seconds_bucket:rate_5m{job=\"mimir/querier\",namespace=\"mimir\",route=~\"prometheus_(api|prom)_v1_.+\",type=\"mimir\"}\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "mimir_querier Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cortex_querier_request_duration_seconds_count:rate_5m{job=\"mimir/querier\",namespace=\"mimir\",route=~\"prometheus_(api|prom)_v1_.+\",status_code=~\"^5.*\",type=\"mimir\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "mimir_querier RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cortex_querier_request_duration_seconds_count:rate_5m{job=\"mimir/querier\",namespace=\"mimir\",route=~\"prometheus_(api|prom)_v1_.+\",type=\"mimir\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: mimir_query_frontend",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 240 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 mimir_query_frontend Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    sli_aggregations:cortex_request_duration_seconds_bucket:rate_5m{job=\"mimir/query-frontend\",namespace=\"mimir\",route=~\"prometheus_(api|prom)_v1_.+\",type=\"mimir\"}\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "mimir_query_frontend Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cortex_request_duration_seconds_count:rate_5m{job=\"mimir/query-frontend\",namespace=\"mimir\",route=~\"prometheus_(api|prom)_v1_.+\",status_code=~\"^5.*\",type=\"mimir\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "mimir_query_frontend RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cortex_request_duration_seconds_count:rate_5m{job=\"mimir/query-frontend\",namespace=\"mimir\",route=~\"prometheus_(api|prom)_v1_.+\",type=\"mimir\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: mimir_query_scheduler",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 250 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 mimir_query_scheduler Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    sli_aggregations:cortex_query_scheduler_queue_duration_seconds_bucket:rate_5m{job=\"mimir/query-scheduler\",namespace=\"mimir\",type=\"mimir\"}\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "mimir_query_scheduler Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cortex_query_scheduler_queue_duration_seconds_count:rate_5m{job=\"mimir/query-scheduler\",namespace=\"mimir\",status_code=~\"^5.*\",type=\"mimir\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "mimir_query_scheduler RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cortex_query_scheduler_queue_duration_seconds_count:rate_5m{job=\"mimir/query-scheduler\",namespace=\"mimir\",type=\"mimir\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: mimir_ruler",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 260 },
   "collapsed": true,
   "panels": [
    {
     "title": "mimir_ruler Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cortex_prometheus_rule_evaluation_failures_total:rate_5m{job=\"mimir/ruler\",namespace=\"mimir\",type=\"mimir\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "mimir_ruler RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cortex_prometheus_rule_evaluations_total:rate_5m{job=\"mimir/ruler\",namespace=\"mimir\",type=\"mimir\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: mimir_store_gateway",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 270 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 mimir_store_gateway Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    sli_aggregations:cortex_request_duration_seconds_bucket:rate_5m{job=\"mimir/store-gateway\",namespace=\"mimir\",route=~\"/gatewaypb\\\\.StoreGateway/.*\",type=\"mimir\"}\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "mimir_store_gateway Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cortex_request_duration_seconds_count:rate_5m{job=\"mimir/store-gateway\",namespace=\"mimir\",route=~\"/gatewaypb\\\\.StoreGateway/.*\",status_code=~\"^5.*\",type=\"mimir\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "mimir_store_gateway RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:cortex_request_duration_seconds_count:rate_5m{job=\"mimir/store-gateway\",namespace=\"mimir\",route=~\"/gatewaypb\\\\.StoreGateway/.*\",type=\"mimir\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "☸️ Kubernetes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 },
   "collapsed": true,
   "panels": [
    {
     "title": "mimir-alertmanager Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"mimir-alertmanager\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-alertmanager Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"mimir-alertmanager\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-alertmanager Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"mimir-alertmanager\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"mimir-alertmanager\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-chunks-cache Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"mimir-chunks-cache\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-chunks-cache Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"mimir-chunks-cache\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-chunks-cache Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"mimir-chunks-cache\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"mimir-chunks-cache\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-compactor Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"mimir-compactor\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-compactor Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"mimir-compactor\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-compactor Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"mimir-compactor\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"mimir-compactor\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-consul Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"mimir-consul\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-consul Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"mimir-consul\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-consul Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"mimir-consul\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"mimir-consul\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-distributor Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"mimir-distributor\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-distributor Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"mimir-distributor\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-distributor Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"mimir-distributor\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"mimir-distributor\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-gateway Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"mimir-gateway\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-gateway Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"mimir-gateway\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-gateway Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"mimir-gateway\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"mimir-gateway\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-index-cache Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"mimir-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-index-cache Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"mimir-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-index-cache Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"mimir-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"mimir-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-ingester Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"mimir-ingester\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-ingester Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"mimir-ingester\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-ingester Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"mimir-ingester\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"mimir-ingester\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-metadata-cache Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"mimir-metadata-cache\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-metadata-cache Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 65 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"mimir-metadata-cache\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-metadata-cache Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 65 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"mimir-metadata-cache\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"mimir-metadata-cache\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-querier Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"mimir-querier\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-querier Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"mimir-querier\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-querier Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"mimir-querier\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"mimir-querier\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-query-frontend Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"mimir-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-query-frontend Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 81 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"mimir-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-query-frontend Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 81 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"mimir-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"mimir-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-query-scheduler Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"mimir-query-scheduler\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-query-scheduler Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 89 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"mimir-query-scheduler\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-query-scheduler Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 89 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"mimir-query-scheduler\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"mimir-query-scheduler\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-results-cache Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"mimir-results-cache\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-results-cache Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 97 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"mimir-results-cache\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-results-cache Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 97 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"mimir-results-cache\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"mimir-results-cache\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-ruler Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 105 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"mimir-ruler\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-ruler Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 105 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"mimir-ruler\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-ruler Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 105 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"mimir-ruler\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"mimir-ruler\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-store-gateway Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 113 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"mimir-store-gateway\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-store-gateway Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 113 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"mimir-store-gateway\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "mimir-store-gateway Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 113 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"mimir-store-gateway\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"mimir-store-gateway\",env=\"$environment\",environment=\"$environment\",type=\"mimir\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "kube_container_cpu component saturation: Kube Container CPU Utilization",
     "type": "graph",
     "description": "Kubernetes containers are allocated a share of CPU. Configured using resource requests.\n\nThis is the amount of CPU that a container should always have available,\nthough it can briefly utilize more. However, if a lot of pods on the same\nhost exceed their requested CPU the container could be throttled earlier.\n\nThis monitors utilization/allocated requests over a 1 hour period, and takes\nthe 99th quantile of that utilization percentage in that period.\nWe want the worst case to be around 80%-90% utilization,\nmeaning we've sized the container correctly. If utilization is much higher than that\nthe container could already be throttled because the host is overused, if it\nis much lower, then we could be underutilizing a host.\n\nThis saturation point is only used for capacity planning.\nContainers that have a quota specified are excluded here and can be monitored using\nthe `kube_container_throttling` saturation component.\nThe burst utilization of a CPU is monitored and alerted upon using the\n`kube_container_cpu_limit` saturation point.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, pod, container) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      (\n        sum by (environment, tier, type, stage, shard, pod, container) (\n          rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"mimir\"}[1h])\n        )\n        unless on(environment, tier, type, stage, shard, pod, container) (\n          last_over_time(container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"mimir\"}[1h])\n        )\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        kube_pod_container_resource_requests:labeled{container!=\"\", container!=\"POD\", resource=\"cpu\", env=\"$environment\",environment=\"$environment\",type=\"mimir\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"kube_container_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_cpu_limit component saturation: Kube Container CPU over-utilization",
     "type": "graph",
     "description": "Kubernetes containers can have a limit configured on how much CPU they can consume in\na burst. If we are at this limit, exceeding the allocated requested resources, we\nshould consider revisting the container's HPA configuration.\n\nWhen a container is utilizing CPU resources up-to it's configured limit for\nextended periods of time, this could cause it and other running containers to be\nthrottled.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, pod, container) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard, pod, container) (\n        rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"mimir\"}[5m])\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"mimir\"}\n        /\n        container_spec_cpu_period:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"mimir\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"kube_container_cpu_limit\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_memory component saturation: Kube Container Memory Utilization",
     "type": "graph",
     "description": "This uses the working set size from cAdvisor for the cgroup's memory usage. That may\nnot be a good measure as it includes filesystem cache pages that are not necessarily\nattributable to the application inside the cgroup, and are permitted to be evicted\ninstead of being OOM killed.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      container_memory_working_set_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"mimir\"}\n      /\n      (container_spec_memory_limit_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"mimir\"} > 0)\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"kube_container_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"kube_container_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"kube_container_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_throttling component saturation: Kube container throttling",
     "type": "graph",
     "description": "Kube container throttling\n\nA container will be throttled if it reaches the configured cpu limit for the\nhorizontal pod autoscaler. Or when other containers on the node are overutilizing\nthe the CPU.\n\nTo get around this, consider increasing the limit for this workload, taking\ninto consideration the requested resources.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, pod, container) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      avg by (environment, tier, type, stage, shard, pod, container)(\n        rate(container_cpu_cfs_throttled_periods_total:labeled{container!=\"\", env=\"$environment\",environment=\"$environment\",type=\"mimir\"}[5m])\n        /\n        rate(container_cpu_cfs_periods_total:labeled{container!=\"\", env=\"$environment\",environment=\"$environment\",type=\"mimir\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"kube_container_throttling\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"kube_container_throttling\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"kube_container_throttling\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_throttling\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_throttling\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_horizontalpodautoscaler_desired_replicas component saturation: Horizontal Pod Autoscaler Desired Replicas",
     "type": "graph",
     "description": "The [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)\nautomatically scales the number of Pods in a deployment based on metrics.\n\nThe Horizontal Pod Autoscaler has a configured upper maximum. When this\nlimit is reached, the HPA will not increase the number of pods and other\nresource saturation (eg, CPU, memory) may occur.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, horizontalpodautoscaler, shard) (\n  clamp_min(\n    clamp_max(\n      kube_horizontalpodautoscaler_status_desired_replicas:labeled{env=\"$environment\",environment=\"$environment\",type=\"mimir\", shard!~\"database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects\", namespace!~\"pubsubbeat\"}\n      /\n      kube_horizontalpodautoscaler_spec_max_replicas:labeled{env=\"$environment\",environment=\"$environment\",type=\"mimir\", shard!~\"database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects\", namespace!~\"pubsubbeat\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ horizontalpodautoscaler }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",type=\"mimir\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"mimir\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",type=\"mimir\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"mimir\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"mimir\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql\nend\n\nsubgraph inf\n  mimir\n  monitoring\nend\n\n\n  mimir --> monitoring\nmonitoring --> cloud-sql\n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql\nend\n\nsubgraph inf\n  mimir\n  monitoring\nend\n\n\n  mimir --> monitoring\nmonitoring --> cloud-sql\n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql[\"cloud-sql (Level 1)\"]\nend\n\nsubgraph inf\n  mimir[\"mimir (Level 2)\"]\n  monitoring[\"monitoring (Level 2)\"]\nend\n\n\n  mimir[\"mimir (Level 2)\"] --> monitoring\nmonitoring[\"monitoring (Level 2)\"] --> cloud-sql\n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}