{
 "title": "cloud-sql: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7927277014 at Thu Sep 26 12:03:40 UTC 2024",
 "tags": [
  "managed",
  "cloud-sql",
  "gitlab",
  "type:cloud-sql",
  "cloud-sql",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"cloud-sql\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "cloudsql_cpu component saturation: CloudSQL CPU Utilization",
     "type": "graph",
     "description": "CloudSQL CPU utilization.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, shard, database_id) (\n  clamp_min(\n    clamp_max(\n      avg_over_time(stackdriver_cloudsql_database_cloudsql_googleapis_com_database_cpu_utilization{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"cloud-sql\"}[5m])\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ database_id }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"cloud-sql\", component=\"cloudsql_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"cloud-sql\", component=\"cloudsql_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"cloud-sql\", component=\"cloudsql_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cloudsql_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cloudsql_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "cloudsql_disk component saturation: CloudSQL Disk Utilization",
     "type": "graph",
     "description": "CloudSQL Disk utilization.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, shard, database_id) (\n  clamp_min(\n    clamp_max(\n      avg_over_time(stackdriver_cloudsql_database_cloudsql_googleapis_com_database_disk_utilization{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"cloud-sql\"}[5m])\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ database_id }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"cloud-sql\", component=\"cloudsql_disk\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"cloud-sql\", component=\"cloudsql_disk\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"cloud-sql\", component=\"cloudsql_disk\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cloudsql_disk\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cloudsql_disk\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "cloudsql_memory component saturation: CloudSQL Memory Utilization",
     "type": "graph",
     "description": "CloudSQL Memory utilization.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, shard, database_id) (\n  clamp_min(\n    clamp_max(\n      avg_over_time(stackdriver_cloudsql_database_cloudsql_googleapis_com_database_memory_utilization{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"cloud-sql\"}[5m])\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ database_id }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"cloud-sql\", component=\"cloudsql_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"cloud-sql\", component=\"cloudsql_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"cloud-sql\", component=\"cloudsql_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cloudsql_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cloudsql_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql[\"cloud-sql (Level 1)\"]\nend\n\n\n  \n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}