{
 "title": "monitoring: Prometheus Cardinality Metrics",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7867191950 at Thu Sep 19 12:04:04 UTC 2024",
 "tags": [
  "managed",
  "monitoring",
  "monitoring"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "The total number of samples scraped",
   "type": "graph",
   "description": "Number of samples scraped",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped{env=\"$environment\"})",
     "legendFormat": "Number of samples scraped"
    },
    {
     "expr": "(sum(scrape_samples_scraped{env=\"$environment\"} offset 1w))",
     "legendFormat": "Number of samples scraped last week"
    }
   ]
  },
  {
   "title": "Samples scraped in k8s",
   "type": "graph",
   "description": "The number of samples the target exposed by type and job.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (job, type, deployment, app) (scrape_samples_scraped{env=\"$environment\", deployment!=\"\"})",
     "legendFormat": "Type: {{type}} - Job: {{job}}"
    }
   ]
  },
  {
   "title": "Samples scraped in chef-managed VMs",
   "type": "graph",
   "description": "The number of samples the target exposed by type and job.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (job, type, deployment, app) (scrape_samples_scraped{env=\"$environment\", deployment=\"\", type!=\"\"})",
     "legendFormat": "Type: {{type}} - Job: {{job}}"
    }
   ]
  },
  {
   "title": "Scrape series added in k8s",
   "type": "graph",
   "description": "The number of samples the target exposed by type and job.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (job, type, deployment, app) (scrape_series_added{env=\"$environment\", deployment!=\"\"})",
     "legendFormat": "Type: {{type}} - Job: {{job}}"
    }
   ]
  },
  {
   "title": "Scrape series added in chef-managed VMs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (job, type, deployment, app) (scrape_series_added{env=\"$environment\", deployment=\"\", type!=\"\"})",
     "legendFormat": "Type: {{type}} - Job: {{job}}"
    }
   ]
  }
 ]
}