{
 "title": "monitoring: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8245226639 at Fri Nov  1 04:32:25 UTC 2024",
 "tags": [
  "managed",
  "monitoring",
  "gitlab",
  "type:monitoring",
  "monitoring",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "monitoring Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "monitoring apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"monitoring\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"monitoring\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "monitoring apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"monitoring\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "monitoring Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "monitoring Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "monitoring error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"monitoring\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"monitoring\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "monitoring error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"monitoring\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "monitoring Service | Errors"
    }
   ]
  },
  {
   "title": "monitoring Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "monitoring RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "grafana SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "grafana apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"grafana\",monitor=\"global\",type=\"monitoring\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"grafana\",monitor=\"global\",type=\"monitoring\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "grafana apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"grafana\",monitor=\"global\",type=\"monitoring\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"grafana\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"grafana\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"grafana\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"grafana\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "grafana SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "grafana SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "grafana error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"grafana\",monitor=\"global\",type=\"monitoring\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"grafana\",monitor=\"global\",type=\"monitoring\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "grafana error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"grafana\",monitor=\"global\",type=\"monitoring\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"grafana\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"grafana\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"grafana\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"grafana\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "grafana SLI | Errors"
    }
   ]
  },
  {
   "title": "grafana SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "grafana RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"grafana\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "content": "### Description\n\nGrafana builds and displays dashboards querying Thanos, Elasticsearch and other datasources.\nThis SLI monitors the Grafana HTTP interface.\n\n"
  },
  {
   "title": "grafana_datasources SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"grafana_datasources\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "grafana_datasources error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"grafana_datasources\",monitor=\"global\",type=\"monitoring\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"grafana_datasources\",monitor=\"global\",type=\"monitoring\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"grafana_datasources\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "grafana_datasources error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"grafana_datasources\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"grafana_datasources\",monitor=\"global\",type=\"monitoring\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"grafana_datasources\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"grafana_datasources\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"grafana_datasources\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"grafana_datasources\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"grafana_datasources\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"grafana_datasources\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"grafana_datasources\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"grafana_datasources\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"grafana_datasources\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "grafana_datasources SLI | Errors"
    }
   ]
  },
  {
   "title": "grafana_datasources SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"grafana_datasources\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "grafana_datasources RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"grafana_datasources\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "content": "### Description\n\nGrafana builds and displays dashboards querying Thanos, Elasticsearch and other datasources.\nThis SLI monitors the requests from Grafana to its datasources.\n\n"
  },
  {
   "title": "grafana_google_lb SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"grafana_google_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "grafana_google_lb error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"grafana_google_lb\",monitor=\"global\",type=\"monitoring\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"grafana_google_lb\",monitor=\"global\",type=\"monitoring\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"grafana_google_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "grafana_google_lb error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"grafana_google_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"grafana_google_lb\",monitor=\"global\",type=\"monitoring\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"grafana_google_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"grafana_google_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"grafana_google_lb\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"grafana_google_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"grafana_google_lb\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"grafana_google_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"grafana_google_lb\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"grafana_google_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"grafana_google_lb\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "grafana_google_lb SLI | Errors"
    }
   ]
  },
  {
   "title": "grafana_google_lb SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"grafana_google_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "grafana_google_lb RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"grafana_google_lb\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "content": "### Observability Tools\n\n* [Google Load Balancer](https://console.cloud.google.com/net-services/loadbalancing/details/http/k8s2-um-4zodnh0s-grafana-grafana-cfagrqyu?project=gitlab-ops)\n* [Stackdriver Logs: Loadbalancer Access Logs](https://console.cloud.google.com/logs/query;query=resource%2Elabels%2Eurl%5Fmap%5Fname%3D%22k8s2%2Dum%2D4zodnh0s%2Dgrafana%2Dgrafana%2Dcfagrqyu%22%0Aresource%2Etype%3D%22http%5Fload%5Fbalancer%22;timeRange=PT30M?project=gitlab-ops)\n* [Stackdriver Logs: Loadbalancer Access 5xx Logs](https://console.cloud.google.com/logs/query;query=httpRequest%2Estatus%3E%3D500%0Aresource%2Elabels%2Eurl%5Fmap%5Fname%3D%22k8s2%2Dum%2D4zodnh0s%2Dgrafana%2Dgrafana%2Dcfagrqyu%22%0Aresource%2Etype%3D%22http%5Fload%5Fbalancer%22;timeRange=PT30M?project=gitlab-ops)\n\n"
  },
  {
   "title": "grafana_image_renderer SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "grafana_image_renderer apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"grafana_image_renderer\",monitor=\"global\",type=\"monitoring\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"grafana_image_renderer\",monitor=\"global\",type=\"monitoring\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "grafana_image_renderer apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"grafana_image_renderer\",monitor=\"global\",type=\"monitoring\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"grafana_image_renderer\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"grafana_image_renderer\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"grafana_image_renderer\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"grafana_image_renderer\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "grafana_image_renderer SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "grafana_image_renderer SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "grafana_image_renderer error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"grafana_image_renderer\",monitor=\"global\",type=\"monitoring\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"grafana_image_renderer\",monitor=\"global\",type=\"monitoring\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "grafana_image_renderer error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"grafana_image_renderer\",monitor=\"global\",type=\"monitoring\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"grafana_image_renderer\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"grafana_image_renderer\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"grafana_image_renderer\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"grafana_image_renderer\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "grafana_image_renderer SLI | Errors"
    }
   ]
  },
  {
   "title": "grafana_image_renderer SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "grafana_image_renderer RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"grafana_image_renderer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
   "content": "### Description\n\nThe Grafana Image Renderer exports Grafana dashboards or panels to PNG for external use.\nThis SLI monitors the Grafana Image Renderer HTTP interface.\n\n"
  },
  {
   "title": "prometheus SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "prometheus apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"prometheus\",monitor=\"global\",type=\"monitoring\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"prometheus\",monitor=\"global\",type=\"monitoring\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "prometheus apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"prometheus\",monitor=\"global\",type=\"monitoring\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"prometheus\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"prometheus\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"prometheus\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"prometheus\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "prometheus SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "prometheus SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 61 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "prometheus error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"prometheus\",monitor=\"global\",type=\"monitoring\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"prometheus\",monitor=\"global\",type=\"monitoring\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "prometheus error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"prometheus\",monitor=\"global\",type=\"monitoring\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"prometheus\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"prometheus\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"prometheus\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"prometheus\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "prometheus SLI | Errors"
    }
   ]
  },
  {
   "title": "prometheus SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "prometheus RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"prometheus\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 61 },
   "content": "### Description\n\nThis SLI monitors Prometheus instances via the HTTP interface.\n5xx responses are considered errors.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Prometheus (gprd) logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.msg,json.level),filters:!((meta:(index:'AW5ZoH2ddtvLTaJbch2P',key:json.tag.keyword,params:monitoring.prometheus,type:phrase),query:(match:(json.tag.keyword:(query:monitoring.prometheus,type:phrase)))),(meta:(index:'AW5ZoH2ddtvLTaJbch2P',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AW5ZoH2ddtvLTaJbch2P',key:json.type,params:monitoring,type:phrase),query:(match:(json.type:(query:monitoring,type:phrase))))),index:'AW5ZoH2ddtvLTaJbch2P')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Prometheus (gprd) failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.msg,json.level),filters:!((meta:(index:'AW5ZoH2ddtvLTaJbch2P',key:json.tag.keyword,params:monitoring.prometheus,type:phrase),query:(match:(json.tag.keyword:(query:monitoring.prometheus,type:phrase)))),(meta:(index:'AW5ZoH2ddtvLTaJbch2P',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AW5ZoH2ddtvLTaJbch2P',key:json.type,params:monitoring,type:phrase),query:(match:(json.type:(query:monitoring,type:phrase)))),(meta:(index:'AW5ZoH2ddtvLTaJbch2P',key:json.level,params:error,type:phrase),query:(match:(json.level:(query:error,type:phrase))))),index:'AW5ZoH2ddtvLTaJbch2P')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Prometheus (gprd) requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5ZoH2ddtvLTaJbch2P&_a=(filters:!((meta:(index:'AW5ZoH2ddtvLTaJbch2P',key:json.tag.keyword,params:monitoring.prometheus,type:phrase),query:(match:(json.tag.keyword:(query:monitoring.prometheus,type:phrase)))),(meta:(index:'AW5ZoH2ddtvLTaJbch2P',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AW5ZoH2ddtvLTaJbch2P',key:json.type,params:monitoring,type:phrase),query:(match:(json.type:(query:monitoring,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Prometheus (gprd) failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5ZoH2ddtvLTaJbch2P&_a=(filters:!((meta:(index:'AW5ZoH2ddtvLTaJbch2P',key:json.tag.keyword,params:monitoring.prometheus,type:phrase),query:(match:(json.tag.keyword:(query:monitoring.prometheus,type:phrase)))),(meta:(index:'AW5ZoH2ddtvLTaJbch2P',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'AW5ZoH2ddtvLTaJbch2P',key:json.type,params:monitoring,type:phrase),query:(match:(json.type:(query:monitoring,type:phrase)))),(meta:(index:'AW5ZoH2ddtvLTaJbch2P',key:json.level,params:error,type:phrase),query:(match:(json.level:(query:error,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Prometheus (ops) logs](https://nonprod-log.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.msg,json.level),filters:!((meta:(index:'0931f630-582b-11ec-87e2-4f63f28291d2',key:json.tag.keyword,params:monitoring.prometheus,type:phrase),query:(match:(json.tag.keyword:(query:monitoring.prometheus,type:phrase)))),(meta:(index:'0931f630-582b-11ec-87e2-4f63f28291d2',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'0931f630-582b-11ec-87e2-4f63f28291d2',key:json.type,params:monitoring,type:phrase),query:(match:(json.type:(query:monitoring,type:phrase))))),index:'0931f630-582b-11ec-87e2-4f63f28291d2')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Prometheus (ops) failed request logs](https://nonprod-log.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.msg,json.level),filters:!((meta:(index:'0931f630-582b-11ec-87e2-4f63f28291d2',key:json.tag.keyword,params:monitoring.prometheus,type:phrase),query:(match:(json.tag.keyword:(query:monitoring.prometheus,type:phrase)))),(meta:(index:'0931f630-582b-11ec-87e2-4f63f28291d2',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'0931f630-582b-11ec-87e2-4f63f28291d2',key:json.type,params:monitoring,type:phrase),query:(match:(json.type:(query:monitoring,type:phrase)))),(meta:(index:'0931f630-582b-11ec-87e2-4f63f28291d2',key:json.level,params:error,type:phrase),query:(match:(json.level:(query:error,type:phrase))))),index:'0931f630-582b-11ec-87e2-4f63f28291d2')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Prometheus (ops) requests](https://nonprod-log.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=0931f630-582b-11ec-87e2-4f63f28291d2&_a=(filters:!((meta:(index:'0931f630-582b-11ec-87e2-4f63f28291d2',key:json.tag.keyword,params:monitoring.prometheus,type:phrase),query:(match:(json.tag.keyword:(query:monitoring.prometheus,type:phrase)))),(meta:(index:'0931f630-582b-11ec-87e2-4f63f28291d2',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'0931f630-582b-11ec-87e2-4f63f28291d2',key:json.type,params:monitoring,type:phrase),query:(match:(json.type:(query:monitoring,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Prometheus (ops) failed requests](https://nonprod-log.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=0931f630-582b-11ec-87e2-4f63f28291d2&_a=(filters:!((meta:(index:'0931f630-582b-11ec-87e2-4f63f28291d2',key:json.tag.keyword,params:monitoring.prometheus,type:phrase),query:(match:(json.tag.keyword:(query:monitoring.prometheus,type:phrase)))),(meta:(index:'0931f630-582b-11ec-87e2-4f63f28291d2',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'0931f630-582b-11ec-87e2-4f63f28291d2',key:json.type,params:monitoring,type:phrase),query:(match:(json.type:(query:monitoring,type:phrase)))),(meta:(index:'0931f630-582b-11ec-87e2-4f63f28291d2',key:json.level,params:error,type:phrase),query:(match:(json.level:(query:error,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "prometheus_alert_sender SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"prometheus_alert_sender\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "prometheus_alert_sender error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"prometheus_alert_sender\",monitor=\"global\",type=\"monitoring\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"prometheus_alert_sender\",monitor=\"global\",type=\"monitoring\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"prometheus_alert_sender\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "prometheus_alert_sender error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"prometheus_alert_sender\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"prometheus_alert_sender\",monitor=\"global\",type=\"monitoring\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"prometheus_alert_sender\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"prometheus_alert_sender\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"prometheus_alert_sender\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"prometheus_alert_sender\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"prometheus_alert_sender\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"prometheus_alert_sender\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"prometheus_alert_sender\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"prometheus_alert_sender\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"prometheus_alert_sender\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "prometheus_alert_sender SLI | Errors"
    }
   ]
  },
  {
   "title": "prometheus_alert_sender SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"prometheus_alert_sender\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "prometheus_alert_sender RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"prometheus_alert_sender\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
   "content": "### Description\n\nThis SLI monitors all prometheus alert notifications that are generated by AlertManager.\nAlert delivery failure is considered a service-level failure.\n\n"
  },
  {
   "title": "rule_evaluation SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "rule_evaluation apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rule_evaluation\",monitor=\"global\",type=\"monitoring\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rule_evaluation\",monitor=\"global\",type=\"monitoring\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "rule_evaluation apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rule_evaluation\",monitor=\"global\",type=\"monitoring\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rule_evaluation\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rule_evaluation\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rule_evaluation\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rule_evaluation\",monitor=\"global\",type=\"monitoring\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "rule_evaluation SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "rule_evaluation SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 81 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "rule_evaluation error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rule_evaluation\",monitor=\"global\",type=\"monitoring\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rule_evaluation\",monitor=\"global\",type=\"monitoring\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "rule_evaluation error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rule_evaluation\",monitor=\"global\",type=\"monitoring\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"rule_evaluation\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"rule_evaluation\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"rule_evaluation\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"rule_evaluation\",monitor=\"global\",type=\"monitoring\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "rule_evaluation SLI | Errors"
    }
   ]
  },
  {
   "title": "rule_evaluation SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n",
     "legendFormat": "rule_evaluation RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"rule_evaluation\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"monitoring\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 81 },
   "content": "### Description\n\nThis SLI monitors Prometheus recording rule evaluations. Recording rule evalution failures are considered to be\nservice failures.\n\nPrometheus rule groups are evaluating recording rules in a group in sequence at an interval.\nIf the recording of all rules in a groups exceeds the interval for the group, we could be\nmissing data points in the group.\n\nIf a group fails often, we should split it up or improve query performance.\n\nTo see which rules are often not meeting their target. Look at the SLI-details. The `rule_group` label will contain\ninformation about the slow group.\n\n"
  },
  {
   "title": "🔬 SLI Detail: grafana",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 grafana Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    sli_aggregations:grafana_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "grafana Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:grafana_http_request_duration_seconds_bucket:rate_5m{code=~\"^5.*\",env=\"$environment\",environment=\"$environment\",job=\"grafana\",le=\"+Inf\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "grafana RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:grafana_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana\",le=\"+Inf\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 grafana Latency - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,pod) (\n    sli_aggregations:grafana_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana\",pod!=\"\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n  )\n)\n > 0",
       "legendFormat": "p95 {{pod}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for grafana Latency - per pod",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (pod) (\n  sli_aggregations:grafana_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana\",le=\"+Inf\",pod!=\"\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n\n    -\n    (\n      sum by (pod) (\n  sli_aggregations:grafana_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana\",le=\"5.0\",pod!=\"\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n\n    )\n  )\n  / ignoring(pod) group_left()\n  (\n    sum by () (\n  sli_aggregations:grafana_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana\",le=\"+Inf\",pod!=\"\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "grafana Errors - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:grafana_http_request_duration_seconds_bucket:rate_5m{code=~\"^5.*\",env=\"$environment\",environment=\"$environment\",job=\"grafana\",le=\"+Inf\",pod!=\"\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "grafana RPS - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:grafana_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana\",le=\"+Inf\",pod!=\"\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: grafana_datasources",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "grafana_datasources Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:grafana_datasource_request_total:rate_5m{code=~\"^5.*\",env=\"$environment\",environment=\"$environment\",job=\"grafana\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "grafana_datasources RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:grafana_datasource_request_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "grafana_datasources Errors - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:grafana_datasource_request_total:rate_5m{code=~\"^5.*\",env=\"$environment\",environment=\"$environment\",job=\"grafana\",pod!=\"\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "grafana_datasources RPS - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:grafana_datasource_request_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana\",pod!=\"\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "grafana_datasources Errors - per datasource",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (datasource) (\n  sli_aggregations:grafana_datasource_request_total:rate_5m{code=~\"^5.*\",datasource!=\"\",env=\"$environment\",environment=\"$environment\",job=\"grafana\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{datasource}}"
      }
     ]
    },
    {
     "title": "grafana_datasources RPS - per datasource",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (datasource) (\n  sli_aggregations:grafana_datasource_request_total:rate_5m{datasource!=\"\",env=\"$environment\",environment=\"$environment\",job=\"grafana\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{datasource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: grafana_google_lb",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 220 },
   "collapsed": true,
   "panels": [
    {
     "title": "grafana_google_lb Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-ops\",response_code_class=\"500\",url_map_name=\"k8s2-um-4zodnh0s-grafana-grafana-cfagrqyu\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "grafana_google_lb RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-ops\",url_map_name=\"k8s2-um-4zodnh0s-grafana-grafana-cfagrqyu\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "grafana_google_lb Errors - per proxy_continent",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy_continent) (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-ops\",proxy_continent!=\"\",response_code_class=\"500\",url_map_name=\"k8s2-um-4zodnh0s-grafana-grafana-cfagrqyu\"}\n)\n > 0",
       "legendFormat": "{{proxy_continent}}"
      }
     ]
    },
    {
     "title": "grafana_google_lb RPS - per proxy_continent",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy_continent) (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-ops\",proxy_continent!=\"\",url_map_name=\"k8s2-um-4zodnh0s-grafana-grafana-cfagrqyu\"}\n)\n > 0",
       "legendFormat": "{{proxy_continent}}"
      }
     ]
    },
    {
     "title": "grafana_google_lb Errors - per response_code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (response_code) (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-ops\",response_code!=\"\",response_code_class=\"500\",url_map_name=\"k8s2-um-4zodnh0s-grafana-grafana-cfagrqyu\"}\n)\n > 0",
       "legendFormat": "{{response_code}}"
      }
     ]
    },
    {
     "title": "grafana_google_lb RPS - per response_code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (response_code) (\n  sli_aggregations:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count:rate_5m{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-ops\",response_code!=\"\",url_map_name=\"k8s2-um-4zodnh0s-grafana-grafana-cfagrqyu\"}\n)\n > 0",
       "legendFormat": "{{response_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: grafana_image_renderer",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 230 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 grafana_image_renderer Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    sli_aggregations:grafana_image_renderer_service_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana-image-renderer\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "grafana_image_renderer Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:grafana_image_renderer_service_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana-image-renderer\",le=\"+Inf\",shard=\"default\",stage=\"$stage\",status_code=~\"^5.*\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "grafana_image_renderer RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:grafana_image_renderer_service_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana-image-renderer\",le=\"+Inf\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 grafana_image_renderer Latency - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,pod) (\n    sli_aggregations:grafana_image_renderer_service_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana-image-renderer\",pod!=\"\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n  )\n)\n > 0",
       "legendFormat": "p95 {{pod}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for grafana_image_renderer Latency - per pod",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (pod) (\n  sli_aggregations:grafana_image_renderer_service_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana-image-renderer\",le=\"+Inf\",pod!=\"\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n\n    -\n    (\n      sum by (pod) (\n  sli_aggregations:grafana_image_renderer_service_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana-image-renderer\",le=\"30\",pod!=\"\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n\n    )\n  )\n  / ignoring(pod) group_left()\n  (\n    sum by () (\n  sli_aggregations:grafana_image_renderer_service_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana-image-renderer\",le=\"+Inf\",pod!=\"\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "grafana_image_renderer Errors - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:grafana_image_renderer_service_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana-image-renderer\",le=\"+Inf\",pod!=\"\",shard=\"default\",stage=\"$stage\",status_code=~\"^5.*\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "grafana_image_renderer RPS - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:grafana_image_renderer_service_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"grafana-image-renderer\",le=\"+Inf\",pod!=\"\",shard=\"default\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: prometheus",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 240 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 prometheus Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    sli_aggregations:prometheus_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",stage=\"$stage\",type=\"monitoring\"}\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "prometheus Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:prometheus_http_requests_total:rate_5m{code=~\"^5.*\",env=\"$environment\",environment=\"$environment\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "prometheus RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:prometheus_http_requests_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 prometheus Latency - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (fqdn,le) (\n    sli_aggregations:prometheus_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",stage=\"$stage\",type=\"monitoring\"}\n  )\n)\n > 0",
       "legendFormat": "p95 {{fqdn}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for prometheus Latency - per fqdn",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (fqdn) (\n  sli_aggregations:prometheus_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",le=\"+Inf\",stage=\"$stage\",type=\"monitoring\"}\n)\n\n    -\n    (\n      (\n  sum by (fqdn) (\n    sli_aggregations:prometheus_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",le=\"1\",stage=\"$stage\",type=\"monitoring\"}\n  )\n  +\n  sum by (fqdn) (\n    sli_aggregations:prometheus_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",le=\"3\",stage=\"$stage\",type=\"monitoring\"}\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(fqdn) group_left()\n  (\n    sum by () (\n  sli_aggregations:prometheus_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",le=\"+Inf\",stage=\"$stage\",type=\"monitoring\"}\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "prometheus Errors - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  sli_aggregations:prometheus_http_requests_total:rate_5m{code=~\"^5.*\",env=\"$environment\",environment=\"$environment\",fqdn!=\"\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "prometheus RPS - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  sli_aggregations:prometheus_http_requests_total:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "Estimated p95 prometheus Latency - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,pod) (\n    sli_aggregations:prometheus_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",pod!=\"\",stage=\"$stage\",type=\"monitoring\"}\n  )\n)\n > 0",
       "legendFormat": "p95 {{pod}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for prometheus Latency - per pod",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (pod) (\n  sli_aggregations:prometheus_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",le=\"+Inf\",pod!=\"\",stage=\"$stage\",type=\"monitoring\"}\n)\n\n    -\n    (\n      (\n  sum by (pod) (\n    sli_aggregations:prometheus_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",le=\"1\",pod!=\"\",stage=\"$stage\",type=\"monitoring\"}\n  )\n  +\n  sum by (pod) (\n    sli_aggregations:prometheus_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",le=\"3\",pod!=\"\",stage=\"$stage\",type=\"monitoring\"}\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(pod) group_left()\n  (\n    sum by () (\n  sli_aggregations:prometheus_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",le=\"+Inf\",pod!=\"\",stage=\"$stage\",type=\"monitoring\"}\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "prometheus Errors - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:prometheus_http_requests_total:rate_5m{code=~\"^5.*\",env=\"$environment\",environment=\"$environment\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",pod!=\"\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "prometheus RPS - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:prometheus_http_requests_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",pod!=\"\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Estimated p95 prometheus Latency - per handler",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (handler,le) (\n    sli_aggregations:prometheus_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",handler!=\"\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",stage=\"$stage\",type=\"monitoring\"}\n  )\n)\n > 0",
       "legendFormat": "p95 {{handler}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for prometheus Latency - per handler",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (handler) (\n  sli_aggregations:prometheus_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",handler!=\"\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",le=\"+Inf\",stage=\"$stage\",type=\"monitoring\"}\n)\n\n    -\n    (\n      (\n  sum by (handler) (\n    sli_aggregations:prometheus_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",handler!=\"\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",le=\"1\",stage=\"$stage\",type=\"monitoring\"}\n  )\n  +\n  sum by (handler) (\n    sli_aggregations:prometheus_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",handler!=\"\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",le=\"3\",stage=\"$stage\",type=\"monitoring\"}\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(handler) group_left()\n  (\n    sum by () (\n  sli_aggregations:prometheus_http_request_duration_seconds_bucket:rate_5m{env=\"$environment\",environment=\"$environment\",handler!=\"\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",le=\"+Inf\",stage=\"$stage\",type=\"monitoring\"}\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "prometheus Errors - per handler",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (handler) (\n  sli_aggregations:prometheus_http_requests_total:rate_5m{code=~\"^5.*\",env=\"$environment\",environment=\"$environment\",handler!=\"\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "prometheus RPS - per handler",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (handler) (\n  sli_aggregations:prometheus_http_requests_total:rate_5m{env=\"$environment\",environment=\"$environment\",handler!=\"\",job!=\"prometheus-metamon\",job=~\"prometheus.*\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: prometheus_alert_sender",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 250 },
   "collapsed": true,
   "panels": [
    {
     "title": "prometheus_alert_sender Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:prometheus_notifications_errors_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"prometheus\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "prometheus_alert_sender RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:prometheus_notifications_sent_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"prometheus\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "prometheus_alert_sender Errors - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  sli_aggregations:prometheus_notifications_errors_total:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",job=\"prometheus\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "prometheus_alert_sender RPS - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  sli_aggregations:prometheus_notifications_sent_total:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",job=\"prometheus\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "prometheus_alert_sender Errors - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:prometheus_notifications_errors_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"prometheus\",pod!=\"\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "prometheus_alert_sender RPS - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:prometheus_notifications_sent_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"prometheus\",pod!=\"\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "prometheus_alert_sender Errors - per alertmanager",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (alertmanager) (\n  sli_aggregations:prometheus_notifications_errors_total:rate_5m{alertmanager!=\"\",env=\"$environment\",environment=\"$environment\",job=\"prometheus\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{alertmanager}}"
      }
     ]
    },
    {
     "title": "prometheus_alert_sender RPS - per alertmanager",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (alertmanager) (\n  sli_aggregations:prometheus_notifications_sent_total:rate_5m{alertmanager!=\"\",env=\"$environment\",environment=\"$environment\",job=\"prometheus\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{alertmanager}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: rule_evaluation",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 260 },
   "collapsed": true,
   "panels": [
    {
     "title": "rule_evaluation Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:prometheus_rule_evaluation_failures_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!~\"^thanos.*\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "rule_evaluation RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:prometheus_rule_evaluations_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!~\"^thanos.*\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for rule_evaluation Latency - per fqdn",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (fqdn) (\n      sli_aggregations:prometheus_rule_group_iterations_total:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",job!~\"^thanos.*\",stage=\"$stage\",type=\"monitoring\"}\n    )\n    -\n    sum by (fqdn) (\n      sli_aggregations:prometheus_rule_group_iterations_total:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",job!~\"^thanos.*\",stage=\"$stage\",type=\"monitoring\"}\n    ) - (\n      sum by (fqdn) (\n        sli_aggregations:prometheus_rule_group_iterations_missed_total:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",job!~\"^thanos.*\",stage=\"$stage\",type=\"monitoring\"}\n      ) or\n      0 * sum by (fqdn) (\n        sli_aggregations:prometheus_rule_group_iterations_total:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",job!~\"^thanos.*\",stage=\"$stage\",type=\"monitoring\"}\n      )\n    )\n  )\n  / ignoring (fqdn) group_left()\n  (\n    sum by () (\n      sli_aggregations:prometheus_rule_group_iterations_total:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",job!~\"^thanos.*\",stage=\"$stage\",type=\"monitoring\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "rule_evaluation Errors - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  sli_aggregations:prometheus_rule_evaluation_failures_total:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",job!~\"^thanos.*\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "rule_evaluation RPS - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  sli_aggregations:prometheus_rule_evaluations_total:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",job!~\"^thanos.*\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for rule_evaluation Latency - per pod",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (pod) (\n      sli_aggregations:prometheus_rule_group_iterations_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!~\"^thanos.*\",pod!=\"\",stage=\"$stage\",type=\"monitoring\"}\n    )\n    -\n    sum by (pod) (\n      sli_aggregations:prometheus_rule_group_iterations_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!~\"^thanos.*\",pod!=\"\",stage=\"$stage\",type=\"monitoring\"}\n    ) - (\n      sum by (pod) (\n        sli_aggregations:prometheus_rule_group_iterations_missed_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!~\"^thanos.*\",pod!=\"\",stage=\"$stage\",type=\"monitoring\"}\n      ) or\n      0 * sum by (pod) (\n        sli_aggregations:prometheus_rule_group_iterations_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!~\"^thanos.*\",pod!=\"\",stage=\"$stage\",type=\"monitoring\"}\n      )\n    )\n  )\n  / ignoring (pod) group_left()\n  (\n    sum by () (\n      sli_aggregations:prometheus_rule_group_iterations_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!~\"^thanos.*\",pod!=\"\",stage=\"$stage\",type=\"monitoring\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "rule_evaluation Errors - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:prometheus_rule_evaluation_failures_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!~\"^thanos.*\",pod!=\"\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "rule_evaluation RPS - per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  sli_aggregations:prometheus_rule_evaluations_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!~\"^thanos.*\",pod!=\"\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for rule_evaluation Latency - per rule_group",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (rule_group) (\n      sli_aggregations:prometheus_rule_group_iterations_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!~\"^thanos.*\",rule_group!=\"\",stage=\"$stage\",type=\"monitoring\"}\n    )\n    -\n    sum by (rule_group) (\n      sli_aggregations:prometheus_rule_group_iterations_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!~\"^thanos.*\",rule_group!=\"\",stage=\"$stage\",type=\"monitoring\"}\n    ) - (\n      sum by (rule_group) (\n        sli_aggregations:prometheus_rule_group_iterations_missed_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!~\"^thanos.*\",rule_group!=\"\",stage=\"$stage\",type=\"monitoring\"}\n      ) or\n      0 * sum by (rule_group) (\n        sli_aggregations:prometheus_rule_group_iterations_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!~\"^thanos.*\",rule_group!=\"\",stage=\"$stage\",type=\"monitoring\"}\n      )\n    )\n  )\n  / ignoring (rule_group) group_left()\n  (\n    sum by () (\n      sli_aggregations:prometheus_rule_group_iterations_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!~\"^thanos.*\",rule_group!=\"\",stage=\"$stage\",type=\"monitoring\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{rule_group}}"
      }
     ]
    },
    {
     "title": "rule_evaluation Errors - per rule_group",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (rule_group) (\n  sli_aggregations:prometheus_rule_evaluation_failures_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!~\"^thanos.*\",rule_group!=\"\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{rule_group}}"
      }
     ]
    },
    {
     "title": "rule_evaluation RPS - per rule_group",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (rule_group) (\n  sli_aggregations:prometheus_rule_evaluations_total:rate_5m{env=\"$environment\",environment=\"$environment\",job!~\"^thanos.*\",rule_group!=\"\",stage=\"$stage\",type=\"monitoring\"}\n)\n > 0",
       "legendFormat": "{{rule_group}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🖥️ Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU",
     "type": "graph",
     "description": "The amount of non-idle time consumed by nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Average CPU Utilization" }
     ],
     "targets": [
      {
       "expr": "avg(instance:node_cpu_utilization:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Maximum Single Core Utilization",
     "type": "graph",
     "description": "The maximum utilization of a single core on each node. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(max(1 - rate(node_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", mode=\"idle\"}[$__interval])) by (fqdn)\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Network Utilization",
     "type": "graph",
     "description": "Network utilization for nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "send {{ fqdn }}"
      },
      {
       "expr": "sum(rate(node_network_receive_bytes_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "receive {{ fqdn }}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "description": "Memory utilization. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(instance:node_memory_utilization:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read IOPs",
     "type": "graph",
     "description": "Disk Read IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_reads_completed_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write IOPs",
     "type": "graph",
     "description": "Disk Write IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_writes_completed_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Throughput",
     "type": "graph",
     "description": "Disk Read throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_read_bytes_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Throughput",
     "type": "graph",
     "description": "Disk Write throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_written_bytes_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Total Time",
     "type": "graph",
     "description": "Total time spent in read operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_read_time_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Total Time",
     "type": "graph",
     "description": "Total time spent in write operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_write_time_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "CPU Scheduling Waiting",
     "type": "graph",
     "description": "CPU scheduling waiting on the run queue, as a percentage of time. Aggregated to worst CPU per node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "max by (fqdn) (\n  rate(node_schedstat_waiting_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[5m])\n)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg1 per core",
     "type": "graph",
     "description": "Loadavg (1 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "loadavg1" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load1{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg5 per core",
     "type": "graph",
     "description": "Loadavg (5 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg5" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load5{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg15 per core",
     "type": "graph",
     "description": "Loadavg (15 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg15" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load15{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    }
   ]
  },
  {
   "title": "☸️ Kubernetes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 },
   "collapsed": true,
   "panels": [
    {
     "title": "grafana Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"grafana\",env=\"$environment\",environment=\"$environment\",type=\"monitoring\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "grafana Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"grafana\",env=\"$environment\",environment=\"$environment\",type=\"monitoring\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "grafana Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"grafana\",env=\"$environment\",environment=\"$environment\",type=\"monitoring\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"grafana\",env=\"$environment\",environment=\"$environment\",type=\"monitoring\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "grafana-image-renderer Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"grafana-image-renderer\",env=\"$environment\",environment=\"$environment\",type=\"monitoring\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "grafana-image-renderer Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"grafana-image-renderer\",env=\"$environment\",environment=\"$environment\",type=\"monitoring\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "grafana-image-renderer Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"grafana-image-renderer\",env=\"$environment\",environment=\"$environment\",type=\"monitoring\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"grafana-image-renderer\",env=\"$environment\",environment=\"$environment\",type=\"monitoring\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "cloudsql_cpu component saturation: CloudSQL CPU Utilization",
     "type": "graph",
     "description": "CloudSQL CPU utilization.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, shard, database_id) (\n  clamp_min(\n    clamp_max(\n      avg_over_time(stackdriver_cloudsql_database_cloudsql_googleapis_com_database_cpu_utilization{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[5m])\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ database_id }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"cloudsql_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"cloudsql_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"cloudsql_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cloudsql_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cloudsql_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "cloudsql_disk component saturation: CloudSQL Disk Utilization",
     "type": "graph",
     "description": "CloudSQL Disk utilization.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, shard, database_id) (\n  clamp_min(\n    clamp_max(\n      avg_over_time(stackdriver_cloudsql_database_cloudsql_googleapis_com_database_disk_utilization{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[5m])\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ database_id }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"cloudsql_disk\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"cloudsql_disk\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"cloudsql_disk\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cloudsql_disk\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cloudsql_disk\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "cloudsql_memory component saturation: CloudSQL Memory Utilization",
     "type": "graph",
     "description": "CloudSQL Memory utilization.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, shard, database_id) (\n  clamp_min(\n    clamp_max(\n      avg_over_time(stackdriver_cloudsql_database_cloudsql_googleapis_com_database_memory_utilization{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[5m])\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ database_id }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"cloudsql_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"cloudsql_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"cloudsql_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cloudsql_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cloudsql_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "cpu component saturation: Average Service CPU Utilization",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in a service fleet.\nIf it is becoming saturated, it may indicate that the fleet needs\nhorizontal or vertical scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage, shard) (\n        rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_inodes component saturation: Disk inode Utilization per Device per Node",
     "type": "graph",
     "description": "Disk inode utilization per device per node.\n\nIf this is too high, its possible that a directory is filling up with\nfiles. Consider logging in an checking temp directories for large numbers\nof files\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      1 - (\n        node_filesystem_files_free{fstype=~\"(ext.|xfs)\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n        /\n        node_filesystem_files{fstype=~\"(ext.|xfs)\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"disk_inodes\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"disk_inodes\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"disk_inodes\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_inodes\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_inodes\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_maximum_capacity component saturation: Maximum per-disk capacity",
     "type": "graph",
     "description": "The maximum capacity for a single disk can be limited by the cloud provider.\nThis tracks the saturation as a ratio of the storage utilization to the maximum size limit enforced per disk.\n\nIn order to resolve a saturation alert, storage needed on a single disk needs to be reduced.\nPossible ways of doing this include reducing utilization overall or partitioning data across multiple disks.\n\n(64*2^40) = 64TiB is the maximum value for many types of GCP disks, see https://cloud.google.com/compute/docs/disks#introduction.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      max by (environment, tier, type, stage, shard, fqdn, device) (\n        node_filesystem_size_bytes{fstype=~\"ext.|xfs\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"} - node_filesystem_avail_bytes{fstype=~\"ext.|xfs\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      ) / (64*2^40)\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"disk_maximum_capacity\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"disk_maximum_capacity\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"disk_maximum_capacity\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_maximum_capacity\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_maximum_capacity\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_space component saturation: Disk Space Utilization per Device per Node",
     "type": "graph",
     "description": "Disk space utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      (\n        1 - node_filesystem_avail_bytes{fstype=~\"ext.|xfs\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"} / node_filesystem_size_bytes{fstype=~\"ext.|xfs\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"disk_space\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"disk_space\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"disk_space\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "gcp_quota_limit component saturation: GCP Quota utilization per environment",
     "type": "graph",
     "description": "GCP Quota utilization / limit ratio\n\nSaturation on a quota may cause problems with creating infrastructure resources on GCP.\n\nTo fix, we can request a quota increase for the specific resource to the GCP support team.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, project, metric, quotaregion, region) (\n  clamp_min(\n    clamp_max(\n      (\n        gcp_quota_usage{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      /\n        gcp_quota_limit{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      ) > 0\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ project }} {{ metric }} {{ quotaregion }} {{ region }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"gcp_quota_limit\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"gcp_quota_limit\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"gcp_quota_limit\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"gcp_quota_limit\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"gcp_quota_limit\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "go_goroutines component saturation: Go goroutines Utilization per Node",
     "type": "graph",
     "description": "Go goroutines utilization per node.\n\nGoroutines leaks can cause memory saturation which can cause service degradation.\n\nA limit of 250k goroutines is very generous, so if a service exceeds this limit,\nit's a sign of a leak and it should be dealt with.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(env, environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      sum by (env, environment, tier, type, stage, shard, fqdn) (\n        go_goroutines{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      )\n      /\n      250000\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"go_goroutines\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"go_goroutines\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"go_goroutines\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"go_goroutines\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"go_goroutines\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "go_memory component saturation: Go Memory Utilization per Node",
     "type": "graph",
     "description": "Go's memory allocation strategy can make it look like a Go process is saturating memory when measured using RSS, when in fact\nthe process is not at risk of memory saturation. For this reason, we measure Go processes using the `go_memstat_alloc_bytes`\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(env, environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      max by (env, environment, tier, type, stage, shard, fqdn) (\n        go_memstats_alloc_bytes{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      )\n      /\n      sum by (env, environment, tier, type, stage, shard, fqdn) (\n        node_memory_MemTotal_bytes{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"go_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"go_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"go_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"go_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"go_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_cpu component saturation: Kube Container CPU Utilization",
     "type": "graph",
     "description": "Kubernetes containers are allocated a share of CPU. Configured using resource requests.\n\nThis is the amount of CPU that a container should always have available,\nthough it can briefly utilize more. However, if a lot of pods on the same\nhost exceed their requested CPU the container could be throttled earlier.\n\nThis monitors utilization/allocated requests over a 1 hour period, and takes\nthe 99th quantile of that utilization percentage in that period.\nWe want the worst case to be around 80%-90% utilization,\nmeaning we've sized the container correctly. If utilization is much higher than that\nthe container could already be throttled because the host is overused, if it\nis much lower, then we could be underutilizing a host.\n\nThis saturation point is only used for capacity planning.\nContainers that have a quota specified are excluded here and can be monitored using\nthe `kube_container_throttling` saturation component.\nThe burst utilization of a CPU is monitored and alerted upon using the\n`kube_container_cpu_limit` saturation point.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, pod, container) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      (\n        sum by (environment, tier, type, stage, shard, pod, container) (\n          rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[1h])\n        )\n        unless on(environment, tier, type, stage, shard, pod, container) (\n          last_over_time(container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[1h])\n        )\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        kube_pod_container_resource_requests:labeled{container!=\"\", container!=\"POD\", resource=\"cpu\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_container_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_cpu_limit component saturation: Kube Container CPU over-utilization",
     "type": "graph",
     "description": "Kubernetes containers can have a limit configured on how much CPU they can consume in\na burst. If we are at this limit, exceeding the allocated requested resources, we\nshould consider revisting the container's HPA configuration.\n\nWhen a container is utilizing CPU resources up-to it's configured limit for\nextended periods of time, this could cause it and other running containers to be\nthrottled.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, pod, container) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard, pod, container) (\n        rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[5m])\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n        /\n        container_spec_cpu_period:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_container_cpu_limit\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_memory component saturation: Kube Container Memory Utilization",
     "type": "graph",
     "description": "This uses the working set size from cAdvisor for the cgroup's memory usage. That may\nnot be a good measure as it includes filesystem cache pages that are not necessarily\nattributable to the application inside the cgroup, and are permitted to be evicted\ninstead of being OOM killed.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, deployment) (\n  clamp_min(\n    clamp_max(\n      container_memory_working_set_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      /\n      (container_spec_memory_limit_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"} > 0)\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ deployment }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_container_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_container_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_container_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_throttling component saturation: Kube container throttling",
     "type": "graph",
     "description": "Kube container throttling\n\nA container will be throttled if it reaches the configured cpu limit for the\nhorizontal pod autoscaler. Or when other containers on the node are overutilizing\nthe the CPU.\n\nTo get around this, consider increasing the limit for this workload, taking\ninto consideration the requested resources.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, pod, container) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      avg by (environment, tier, type, stage, shard, pod, container)(\n        rate(container_cpu_cfs_throttled_periods_total:labeled{container!=\"\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[5m])\n        /\n        rate(container_cpu_cfs_periods_total:labeled{container!=\"\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_container_throttling\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_container_throttling\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_container_throttling\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_throttling\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_throttling\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_go_memory component saturation: Go Memory Utilization per Node",
     "type": "graph",
     "description": "Measures Go memory usage as a percentage of container memory limit\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(env, environment, tier, type, stage, shard, cluster, pod) (\n  clamp_min(\n    clamp_max(\n      go_memstats_alloc_bytes{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      / on(env, environment, tier, type, stage, shard, cluster, pod) group_left()\n      topk by(env, environment, tier, type, stage, shard, cluster, pod) (1,\n        container_spec_memory_limit_bytes:labeled{container=~\"gitlab-pages|gitlab-workhorse|kas|registry|thanos-store\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ cluster }} {{ pod }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_go_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_go_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_go_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_go_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_go_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_horizontalpodautoscaler_desired_replicas component saturation: Horizontal Pod Autoscaler Desired Replicas",
     "type": "graph",
     "description": "The [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)\nautomatically scales the number of Pods in a deployment based on metrics.\n\nThe Horizontal Pod Autoscaler has a configured upper maximum. When this\nlimit is reached, the HPA will not increase the number of pods and other\nresource saturation (eg, CPU, memory) may occur.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, horizontalpodautoscaler, shard) (\n  clamp_min(\n    clamp_max(\n      kube_horizontalpodautoscaler_status_desired_replicas:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", shard!~\"ai-abstraction-layer|database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects\", namespace!~\"pubsubbeat\"}\n      /\n      kube_horizontalpodautoscaler_spec_max_replicas:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", shard!~\"ai-abstraction-layer|database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects\", namespace!~\"pubsubbeat\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ horizontalpodautoscaler }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "memory component saturation: Memory Utilization per Node",
     "type": "graph",
     "description": "Memory utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      instance:node_memory_utilization:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"} or instance:node_memory_utilisation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "nf_conntrack_entries component saturation: conntrack Entries per Node",
     "type": "graph",
     "description": "Netfilter connection tracking table utilization per node.\n\nWhen saturated, new connection attempts (incoming SYN packets) are dropped with no reply, leaving clients to slowly retry (and typically fail again) over the next several seconds.  When packets are being dropped due to this condition, kernel will log the event as: \"nf_conntrack: table full, dropping packet\".\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, instance) (\n  clamp_min(\n    clamp_max(\n      max_over_time(node_nf_conntrack_entries{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[1m])\n      /\n      node_nf_conntrack_entries_limit{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"nf_conntrack_entries\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"nf_conntrack_entries\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"nf_conntrack_entries\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"nf_conntrack_entries\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"nf_conntrack_entries\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "node_schedstat_waiting component saturation: Node Scheduler Waiting Time",
     "type": "graph",
     "description": "Measures the amount of scheduler waiting time that processes are waiting\nto be scheduled, according to [`CPU Scheduling Metrics`](https://www.robustperception.io/cpu-scheduling-metrics-from-the-node-exporter).\n\nA high value indicates that a node has more processes to be run than CPU time available\nto handle them, and may lead to degraded responsiveness and performance from the application.\n\nAdditionally, it may indicate that the fleet is under-provisioned.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, shard) (\n  clamp_min(\n    clamp_max(\n      avg without (cpu) (rate(node_schedstat_waiting_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[1h]))\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"node_schedstat_waiting\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"node_schedstat_waiting\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"node_schedstat_waiting\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"node_schedstat_waiting\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"node_schedstat_waiting\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "shard_cpu component saturation: Average CPU Utilization per Shard",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in a shard of a\nservice fleet. If it is becoming saturated, it may indicate that the\nshard needs horizontal or vertical scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, shard) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage, shard, shard) (\n        rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"shard_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"shard_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"shard_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"shard_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"shard_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "single_node_cpu component saturation: Average CPU Utilization per Node",
     "type": "graph",
     "description": "Average CPU utilization per Node.\n\nIf average CPU is saturated, it may indicate that a fleet is in need to horizontal or vertical scaling. It may also indicate\nimbalances in load in a fleet.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      avg without(cpu, mode) (1 - rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\"}[5m]))\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"single_node_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"single_node_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"monitoring\", component=\"single_node_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Grafana CloudSQL Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "graph",
     "description": "CPU utilization.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details.\n",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1000 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_cpu_utilization{database_id=~\".+:grafana-(pre|internal)-.+\", environment=\"$environment\"}",
       "legendFormat": "{{ database_id }}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "description": "Memory utilization.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details.\n",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1000 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_memory_utilization{database_id=~\".+:grafana-(pre|internal)-.+\", environment=\"$environment\"}",
       "legendFormat": "{{ database_id }}"
      }
     ]
    },
    {
     "title": "Disk Utilization",
     "type": "graph",
     "description": "Data utilization in bytes.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details.\n",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1000 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_disk_bytes_used{database_id=~\".+:grafana-(pre|internal)-.+\", environment=\"$environment\"}",
       "legendFormat": "{{ database_id }}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "graph",
     "description": "Delta count of number of transactions. Sampled every 60 seconds.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details.\n",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1000 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (database_id) (\n  avg_over_time(stackdriver_cloudsql_database_cloudsql_googleapis_com_database_postgresql_transaction_count{database_id=~\".+:grafana-(pre|internal)-.+\", environment=\"$environment\"}[$__interval])\n)\n",
       "legendFormat": "{{ database_id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Grafana Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Grafana API Dataproxy Request Duration (logn scale)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1000 },
     "yaxes": [
      { "format": "ms", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "grafana_api_dataproxy_request_all_milliseconds{environment=\"$environment\", quantile=\"0.5\"}\n",
       "legendFormat": "p50 {{ pod }}"
      },
      {
       "expr": "grafana_api_dataproxy_request_all_milliseconds{environment=\"$environment\", quantile=\"0.9\"}\n",
       "legendFormat": "p90 {{ pod }}"
      },
      {
       "expr": "grafana_api_dataproxy_request_all_milliseconds{environment=\"$environment\", quantile=\"0.99\"}\n",
       "legendFormat": "p99 {{ pod }}"
      }
     ]
    },
    {
     "title": "Grafana Datasource RPS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1000 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grafana_datasource_request_total{environment=\"$environment\"}[$__interval])) by (datasource)\n",
       "legendFormat": "{{ datasource }}"
      }
     ]
    },
    {
     "title": "Grafana Datasource Request Duration (logn scale)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1000 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "avg(grafana_datasource_request_duration_seconds{environment=\"$environment\"} >= 0) by (datasource)\n",
       "legendFormat": "{{ datasource }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql\nend\n\nsubgraph inf\n  monitoring\nend\n\n\n  monitoring --> cloud-sql\n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql\nend\n\nsubgraph inf\n  monitoring\nend\n\n\n  monitoring --> cloud-sql\n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql[\"cloud-sql (Level 1)\"]\nend\n\nsubgraph inf\n  monitoring[\"monitoring (Level 2)\"]\nend\n\n\n  monitoring[\"monitoring (Level 2)\"] --> cloud-sql\n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}