{
 "title": "ops-gitlab-net: Kube Deployment Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7867191950 at Thu Sep 19 12:03:51 UTC 2024",
 "tags": [
  "managed",
  "ops-gitlab-net",
  "ops-gitlab-net",
  "type:ops-gitlab-net",
  "kube",
  "kube detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "gitaly deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gitaly Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"gitaly\",type=\"ops-gitlab-net\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "gitaly Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"gitaly\",type=\"ops-gitlab-net\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "gitaly Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"gitaly\",type=\"ops-gitlab-net\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"gitaly\",type=\"ops-gitlab-net\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  { "title": "kas deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "kas Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"kas\",type=\"ops-gitlab-net\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "kas Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"kas\",type=\"ops-gitlab-net\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "kas Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"kas\",type=\"ops-gitlab-net\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"kas\",type=\"ops-gitlab-net\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  { "title": "registry deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "registry Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"registry\",type=\"ops-gitlab-net\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "registry Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"registry\",type=\"ops-gitlab-net\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "registry Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"registry\",type=\"ops-gitlab-net\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"registry\",type=\"ops-gitlab-net\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  { "title": "sidekiq deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "sidekiq Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  { "title": "webservice deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "webservice Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "webservice Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "webservice Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"webservice\",type=\"ops-gitlab-net\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"webservice\",type=\"ops-gitlab-net\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}