groups:
- name: alertmanager.rules
  rules:
  - alert: AlertmanagerNotificationsFailing
    expr: >
      sum by (integration) (
        rate(alertmanager_notifications_failed_total[2m])
      ) > 0
    for: 20m
    labels:
      pager: pagerduty
      page: 'true'
      service: alertmanager
      severity: s1
      alert_type: cause
    annotations:
      title: Alertmanager is failing sending notifications
      runbook: docs/monitoring/alertmanager-notification-failures.md
      description: Alertmanager is seeing errors for the {{$labels.integration}} integration.
