groups:
- name: alertmanager.rules
  rules:
  - alert: AlertmanagerNotificationsFailing
    expr: rate(alertmanager_notifications_failed_total[1m]) > 0
    for: 1m
    labels:
      pager: pagerduty
      service: alertmanager
      severity: s1
      alert_type: cause
    annotations:
      title: Alertmanager is failing sending notifications
      runbook: docs/monitoring/alertmanager-notification-failures.md
      description: Alertmanager is seeing errors for integration {{$labels.integration}}
