groups:
- name: logging.rules
  rules:
  - alert: DroppedLogs
    expr: >
      (rate(pubsubbeat_libbeat_output_events{type="dropped"}[5m]))
      / ignoring (type) group_left
      sum without (type) (rate(pubsubbeat_libbeat_output_events[5m]))
      > 0.005
    for: 1m
    labels:
      severity: s4
      alert_type: cause
    annotations:
      title: Cluster is refusing to process logs sent to it by pubsubbeat
      description: >
        pubsubbeat internal metric is reporting logs being dropped by the cluster.
        Consider checking /var/log/pubsubbeat/current on the affected
        host and see what's the cause of the errors. One potential source of the problem are conflicting mappings in the index.

  - alert: PubSubSendRateFalling
    expr: |
      deriv(
        sum without (fqdn,instance,plugin_id,stage) (
          rate(fluentd_output_status_emit_count{type="cloud_pubsub"}[15m])
        )[15m:]
      ) < -2
    for: 5m
    labels:
      severity: s3
      alert_type: cause
    annotations:
      description: >
        Logs send rate is lower than usual.
      runbook: docs/logging/troubleshooting/README.md
      title: Logs send rate is unusually low

  - alert: LoggingVisibilityDiminished
    expr: |
      avg_over_time(stackdriver_pubsub_subscription_pubsub_googleapis_com_subscription_oldest_unacked_message_age[30m]) > 300
    for: 5m
    labels:
      severity: s2
      pager: 'pagerduty'
      alert_type: symptom
    annotations:
      description: >
        PubSub messages are queuing up.  Messages in {{ $labels.subscription_id }} have been
        un-acked for {{ $value | humanizeDuration }} in the queue for the last 5 minutes.
        This will lead to Elastic lagging behind with the log data.
      runbook: docs/logging/troubleshooting/README.md
      title: PubSub queuing high
