{
 "title": "errortracking: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/8397766929 at Mon Nov 18 09:15:42 UTC 2024",
 "tags": [
  "managed",
  "errortracking",
  "gitlab",
  "type:errortracking",
  "errortracking",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "errortracking Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}[$__interval])\n",
     "legendFormat": "errortracking apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"errortracking\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"errortracking\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}[$__interval])\n",
     "legendFormat": "errortracking apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"errortracking\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"errortracking\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"errortracking\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"errortracking\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"errortracking\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "errortracking Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "errortracking Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "errortracking error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"errortracking\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"errortracking\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "errortracking error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"errortracking\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"errortracking\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"errortracking\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"errortracking\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"errortracking\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "errortracking Service | Errors"
    }
   ]
  },
  {
   "title": "errortracking Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}[$__interval])\n",
     "legendFormat": "errortracking RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"errortracking\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "loadbalancer SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}[$__interval])\n",
     "legendFormat": "loadbalancer apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"errortracking\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"errortracking\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}[$__interval])\n",
     "legendFormat": "loadbalancer apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"errortracking\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"errortracking\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"errortracking\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"errortracking\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"errortracking\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "loadbalancer SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "loadbalancer SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "loadbalancer error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"errortracking\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"errortracking\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "loadbalancer error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"errortracking\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"errortracking\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:ratio_1h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"errortracking\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:ratio_30m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"errortracking\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:ratio_6h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"errortracking\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "loadbalancer SLI | Errors"
    }
   ]
  },
  {
   "title": "loadbalancer SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"}[$__interval])\n",
     "legendFormat": "loadbalancer RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"errortracking\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "content": "### Description\n\nError Tracking allows developers to discover and view errors generated by their application\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Observability logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.severity,json.textPayload),filters:!((meta:(index:'2b3f598d-cf5a-4186-99f0-0075d9235c57',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'2b3f598d-cf5a-4186-99f0-0075d9235c57',key:json.type,params:errortracking,type:phrase),query:(match:(json.type:(query:errortracking,type:phrase))))),index:'2b3f598d-cf5a-4186-99f0-0075d9235c57')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Observability requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=2b3f598d-cf5a-4186-99f0-0075d9235c57&_a=(filters:!((meta:(index:'2b3f598d-cf5a-4186-99f0-0075d9235c57',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'2b3f598d-cf5a-4186-99f0-0075d9235c57',key:json.type,params:errortracking,type:phrase),query:(match:(json.type:(query:errortracking,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "🔬 SLI Detail: loadbalancer",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 loadbalancer Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    sli_aggregations:traefik_service_request_duration_seconds_bucket:rate_5m{code!~\"4xx|5xx\",env=\"$environment\",environment=\"$environment\",job=\"default/traefik\",service=~\".*errortracking-api.*\",stage=\"$stage\",team=\"platform_insights\"}\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "loadbalancer Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:traefik_service_requests_total:rate_5m{code=~\"^5.*\",env=\"$environment\",environment=\"$environment\",job=\"default/traefik\",service=~\".*errortracking-api.*\",stage=\"$stage\",team=\"platform_insights\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "loadbalancer RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:traefik_service_requests_total:rate_5m{env=\"$environment\",environment=\"$environment\",job=\"default/traefik\",service=~\".*errortracking-api.*\",stage=\"$stage\",team=\"platform_insights\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"errortracking\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"errortracking\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"errortracking\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"errortracking\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"errortracking\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"errortracking\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"errortracking\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni\n  pgbouncer\n  redis\n  redis-cluster-cache\n  redis-cluster-chat-cache\n  redis-cluster-feature-flag\n  redis-cluster-queues-meta\n  redis-cluster-ratelimiting\n  redis-cluster-repo-cache\n  redis-cluster-shared-state\n  redis-pubsub\n  redis-sessions\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph inf\n  search\n  zoekt\nend\n\nsubgraph stor\n  gitaly\n  google-cloud-storage\nend\n\nsubgraph sv\n  api\n  consul\n  errortracking\n  ext-pvs\n  kas\nend\n\n\n  api --> consul\napi --> ext-pvs\napi --> gitaly\napi --> google-cloud-storage\napi --> kas\napi --> patroni\napi --> pgbouncer\napi --> redis\napi --> redis-cluster-cache\napi --> redis-cluster-chat-cache\napi --> redis-cluster-feature-flag\napi --> redis-cluster-queues-meta\napi --> redis-cluster-ratelimiting\napi --> redis-cluster-repo-cache\napi --> redis-cluster-shared-state\napi --> redis-pubsub\napi --> redis-sessions\napi --> redis-sidekiq\napi --> redis-tracechunks\napi --> search\napi --> zoekt\nerrortracking --> api\ngitaly --> gitaly\nkas --> api\nkas --> gitaly\nkas --> kas\nkas --> redis\npgbouncer --> patroni\n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni\n  pgbouncer\n  redis\n  redis-cluster-cache\n  redis-cluster-chat-cache\n  redis-cluster-feature-flag\n  redis-cluster-queues-meta\n  redis-cluster-ratelimiting\n  redis-cluster-repo-cache\n  redis-cluster-shared-state\n  redis-pubsub\n  redis-sessions\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph inf\n  search\n  zoekt\nend\n\nsubgraph stor\n  gitaly\n  google-cloud-storage\nend\n\nsubgraph sv\n  api\n  consul\n  errortracking\n  ext-pvs\n  kas\nend\n\n\n  api --> consul\napi --> ext-pvs\napi --> gitaly\napi --> google-cloud-storage\napi --> kas\napi --> patroni\napi --> pgbouncer\napi --> redis\napi --> redis-cluster-cache\napi --> redis-cluster-chat-cache\napi --> redis-cluster-feature-flag\napi --> redis-cluster-queues-meta\napi --> redis-cluster-ratelimiting\napi --> redis-cluster-repo-cache\napi --> redis-cluster-shared-state\napi --> redis-pubsub\napi --> redis-sessions\napi --> redis-sidekiq\napi --> redis-tracechunks\napi --> search\napi --> zoekt\nerrortracking --> api\ngitaly --> gitaly\nkas --> api\nkas --> gitaly\nkas --> kas\nkas --> redis\npgbouncer --> patroni\n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni[\"patroni (Level 2)\"]\n  pgbouncer[\"pgbouncer (Level 1)\"]\n  redis-cluster-cache[\"redis-cluster-cache (Level 2)\"]\n  redis-cluster-chat-cache[\"redis-cluster-chat-cache (Level 2)\"]\n  redis-cluster-feature-flag[\"redis-cluster-feature-flag (Level 2)\"]\n  redis-cluster-queues-meta[\"redis-cluster-queues-meta (Level 2)\"]\n  redis-cluster-ratelimiting[\"redis-cluster-ratelimiting (Level 2)\"]\n  redis-cluster-repo-cache[\"redis-cluster-repo-cache (Level 2)\"]\n  redis-cluster-shared-state[\"redis-cluster-shared-state (Level 2)\"]\n  redis-pubsub[\"redis-pubsub (Level 2)\"]\n  redis-sessions[\"redis-sessions (Level 3)\"]\n  redis-sidekiq[\"redis-sidekiq (Level 3)\"]\n  redis-tracechunks[\"redis-tracechunks (Level 3)\"]\n  redis[\"redis (Level 3)\"]\nend\n\nsubgraph inf\n  search[\"search (Level 1)\"]\n  zoekt[\"zoekt (Level 1)\"]\nend\n\nsubgraph stor\n  gitaly[\"gitaly (Level 3)\"]\n  google-cloud-storage[\"google-cloud-storage (Level 2)\"]\nend\n\nsubgraph sv\n  api[\"api (Level 2)\"]\n  consul[\"consul (Level 1)\"]\n  errortracking[\"errortracking (Level 2)\"]\n  ext-pvs[\"ext-pvs (Level 2)\"]\n  kas[\"kas (Level 3)\"]\nend\n\n\n  api[\"api (Level 2)\"] --> consul\napi[\"api (Level 2)\"] --> ext-pvs\napi[\"api (Level 2)\"] --> gitaly\napi[\"api (Level 2)\"] --> google-cloud-storage\napi[\"api (Level 2)\"] --> kas\napi[\"api (Level 2)\"] --> patroni\napi[\"api (Level 2)\"] --> pgbouncer\napi[\"api (Level 2)\"] --> redis\napi[\"api (Level 2)\"] --> redis-cluster-cache\napi[\"api (Level 2)\"] --> redis-cluster-chat-cache\napi[\"api (Level 2)\"] --> redis-cluster-feature-flag\napi[\"api (Level 2)\"] --> redis-cluster-queues-meta\napi[\"api (Level 2)\"] --> redis-cluster-ratelimiting\napi[\"api (Level 2)\"] --> redis-cluster-repo-cache\napi[\"api (Level 2)\"] --> redis-cluster-shared-state\napi[\"api (Level 2)\"] --> redis-pubsub\napi[\"api (Level 2)\"] --> redis-sessions\napi[\"api (Level 2)\"] --> redis-sidekiq\napi[\"api (Level 2)\"] --> redis-tracechunks\napi[\"api (Level 2)\"] --> search\napi[\"api (Level 2)\"] --> zoekt\nerrortracking[\"errortracking (Level 2)\"] --> api\ngitaly[\"gitaly (Level 3)\"] --> gitaly\nkas[\"kas (Level 3)\"] --> api\nkas[\"kas (Level 3)\"] --> gitaly\nkas[\"kas (Level 3)\"] --> kas\nkas[\"kas (Level 3)\"] --> redis\npgbouncer[\"pgbouncer (Level 1)\"] --> patroni\n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}